### PR TITLE
Fix incomplete data in generated tasks.json

### LINKED ISSUE #8950: Incomplete creation of a typescript build task
### Bug Description:
When creating a first build task for a typescript project, 
the generated tasks.json is incomplete.

### Steps to Reproduce:

1. From a hello world project as shown.
image

2.Create a default build configuration by selecting the typescript file and then select
Main menu -> Terminal -> Configure Tasks... -> "tsc: build - tsconfig.json"

3.The created configuration will look like:
image

The created task entry may some times be more complete, i.e. the created entry is not consistent.

4.The expected input on the created tasks.json
image

### Additional Information

- Operating System:
- Theia Version: master branch, commit: 1c84263a7

### LINKED ISSUE #8980: The task 'label' attribute given by Task providers is not included in generated tasks.json
### Bug Description:
When configuring tasks, tasks providers may include a label for it e.g. 'build - tsconfig.json',
however the resulting entry in the tasks.json file does not include it.

The following example is produced after PR:  https://github.com/eclipse-theia/theia/pull/8971
```ts
{
    "tasks": [
        {
            "type": "typescript",
            "tsconfig": "tsconfig.json",
            "problemMatcher": [
                "$tsc"
            ],
            "group": "build"
        }
    ]
}
```

### Steps to Reproduce:

1. in a typescript project, select a *.ts file
2.Main menu -> Terminal -> Configure -> "tsc: build - tsconfig.json"
3.The resulting file under .theia/tasks.json will be missing the label

### Additional Information

- Operating System: Linux debian
- Theia Version: master (47be972b4) + https://github.com/eclipse-theia/theia/pull/8971

### PR DESCRIPTION
**Pull request by alvsan09**
#### What it does

Fixes #8950
Fixes #8980

- Added missing 'group' property to the TaskDto interface
- Added group when converting between TaskDto and TaskConfiguration
- Added group when converting between TaskDto and Task
- Removes clearing of problem matchers (error) to pass the received ones from a given extension
- Aligns TaskCustomization.group with task schema (i.e. remove 'none' when 'isDefault').
- Include provided task 'label' in the generated task.json

#### How to test

The steps to reproduce the issue are indicated in issues: 
- https://github.com/eclipse-theia/theia/issues/8950
- https://github.com/eclipse-theia/theia/issues/8980

the same steps can be used to notice the difference after applying the fix.

The following unit test were updated and pass locally:
 - `npx run test @theia/plugin-ext`
 - `npx run test @theia/task`

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: Alvaro Sanchez-Leon <alvaro.sanchez-leon@ericsson.com>

### CODE REVIEW

File: packages/plugin-ext/src/common/plugin-api-rpc.ts [hunk 1]
```diff
@@ -1255,6 +1255,8 @@ export interface TaskDto {
     // Provide a more specific type when necessary (see ProblemMatcherContribution)
     // eslint-disable-next-line @typescript-eslint/no-explicit-any
     problemMatcher?: any;
+    group?: string,
```
Comment (vince-fugnitto) [inline packages/plugin-ext/src/common/plugin-api-rpc.ts:1258]: minor:

```suggestion
    group?: string;
```

File: packages/plugin-ext/src/main/browser/tasks-main.ts [hunk 2]
```diff
@@ -175,16 +175,38 @@ export class TasksMainImpl implements TasksMain, Disposable {
...
     }
 
     protected fromTaskConfiguration(task: TaskConfiguration): TaskDto {
-        return Object.assign(task, {
-            source: task._source,
-            scope: task._scope
+        const { group, ...taskDto } = task;
+        if (group) {
+            if (TaskCustomization.isBuildTask(task)) {
+                taskDto.group = 'build'
```
Comment (vince-fugnitto) [inline packages/plugin-ext/src/main/browser/tasks-main.ts:197]: The following is failing the build:

```suggestion
                taskDto.group = 'build';
```

File: packages/plugin-ext/src/common/plugin-api-rpc.ts (hunk 1 above)
Comment (alvsan09) [reply packages/plugin-ext/src/common/plugin-api-rpc.ts]: Hi Vince !, 
I missed running lint to detect those errors.

A new patch set was submitted addressing your comments and a fix that was braking tests.
Thanks !
/Alvaro

File: packages/plugin-ext/src/main/browser/tasks-main.ts (hunk 2 above)
Comment (alvsan09) [reply packages/plugin-ext/src/main/browser/tasks-main.ts]: Done on new commit !

File: packages/plugin-ext/src/common/plugin-api-rpc.ts [hunk 3]
```diff
@@ -1255,6 +1255,7 @@ export interface TaskDto {
     // Provide a more specific type when necessary (see ProblemMatcherContribution)
     // eslint-disable-next-line @typescript-eslint/no-explicit-any
     problemMatcher?: any;
+    group?: string;
```
Comment (colin-grant-work) [inline packages/plugin-ext/src/common/plugin-api-rpc.ts:1258]: Should the `TaskDto` support all the options available in the task schema (i.e. strings or `{kind: string}`)? Or is there reason to believe that we won't receive data in that form?

File: packages/task/src/browser/task-configurations.ts [hunk 4]
```diff
@@ -317,7 +317,7 @@ export class TaskConfigurations implements Disposable {
 
         const configuredAndCustomizedTasks = await this.getTasks(token);
         if (!configuredAndCustomizedTasks.some(t => this.taskDefinitionRegistry.compareTasks(t, task))) {
-            await this.saveTask(scope, { ...task, problemMatcher: [] });
+            await this.saveTask(scope, task);
```
Comment (colin-grant-work) [inline packages/task/src/browser/task-configurations.ts:320]: Is there any risk associated with accepting any problem matchers coming into this call? Was the `problemMatcher: []` just always a bad idea?

File: packages/task/src/browser/task-service.ts [hunk 5]
```diff
@@ -1105,7 +1105,11 @@ export class TaskService implements TaskConfigurationClient {
      * @param task The task to configure
      */
     async configure(token: number, task: TaskConfiguration): Promise<void> {
-        await this.taskConfigurations.configure(token, task);
+        const taskConfiguration = Object.freeze({
```
Comment (colin-grant-work) [inline packages/task/src/browser/task-service.ts:1108]: This looks like it's trying to fix the bug where labels were not preserved through this process, but it could have unintended consequences. Were you able to track down the code where the label was being modified or deleted? It might be better to fix the problem there rather than trying to freeze the object at a moment we think we're happy with it.

File: packages/plugin-ext/src/common/plugin-api-rpc.ts (hunk 3 above)
Comment (alvsan09) [reply packages/plugin-ext/src/common/plugin-api-rpc.ts:1258]: hmm!, it's a good question but I am not sure about that, it goes outside the scope of the current fix

File: packages/task/src/browser/task-configurations.ts (hunk 4 above)
Comment (alvsan09) [reply packages/task/src/browser/task-configurations.ts:320]: I don't see any risks with it, it just seem to have been left as an initial default. 
Please let me know if you see any issues with it.

File: packages/task/src/browser/task-service.ts (hunk 5 above)
Comment (alvsan09) [reply packages/task/src/browser/task-service.ts:1108]: The added lines are not displayed correctly by github, please see the image below for the set of lines added.

if we ignore freeze for a moment, the intention is simply to populate a label under the task configuration, before this fix, the label does not get preserved in the tasks.json file.  The freeze could be replaced by Object.assign.
Although freeze is chosen to make it explicit that the configuration shall then be complete.

image

Comment (colin-grant-work) [reply packages/task/src/browser/task-service.ts:1108]: If freezing isn't critical to the intended functionality, I'd suggest removing it and just adding the label here, since `freeze` could produce hard-to-diagnose runtime errors for anyone who works on this code later.

File: packages/plugin-ext/src/main/browser/tasks-main.ts [hunk 6]
```diff
@@ -175,16 +175,30 @@ export class TasksMainImpl implements TasksMain, Disposable {
     }
 
     protected toTaskConfiguration(taskDto: TaskDto): TaskConfiguration {
-        return Object.assign(taskDto, {
-            _source: taskDto.source,
-            _scope: taskDto.scope
+        const { group, ...taskConfiguration } = taskDto;
+        if (group === 'build' || group === 'test') {
```
Comment (colin-grant-work) [inline packages/plugin-ext/src/main/browser/tasks-main.ts:179]: A propos my comment regarding the possibility of accommodating the more elaborate `{kind: string}` form, if you use `TaskCustomization.isBuildTask` and `TaskCustomization.isTestTask` here as you do below, it will catch both the `string`s and any instances of the `object` type automatically.

File: packages/task/src/browser/task-service.ts (hunk 5 above)
Comment (alvsan09) [reply packages/task/src/browser/task-service.ts:1108]: Since the access associated to TaskConfiguration.label is 'readonly' we do have the options to add it with Object.create, Object.assign, Object.freeze, if we don't use Object.freeze, I am fine with using assign or create, please let me know if you have a preference.

Comment (colin-grant-work) [reply packages/task/src/browser/task-service.ts:1108]: It seems as though the problem is just that the label was being omitted previously - is that correct? If so I believe this should be fine:
```
const taskConfiguration = { ...task, label: this.taskNameResolver.resolve(task) };
```
If there's a deeper problem with labels being manipulated inappropriately downstream of this code, or if they're being omitted inappropriately upstream of this code, then it might be best to find those locations and address the bug there. If the label just wasn't included at this stage of the task construction, then we just need to add it here.

Comment (alvsan09) [reply packages/task/src/browser/task-service.ts:1108]: The label was not actually omitted at this point, but it was not prefixed with the source, so we call taskNameResolver to apply the prefix, then the actual storing of the label in the tasks.json was missing and it's fixed under task-configuration.ts.

I think your suggestion may work although I think it's best to use Object.assign or Object.create in order to preserve the prototype.

Comment (colin-grant-work) [reply packages/task/src/browser/task-service.ts:1108]: I believe that `TaskConfiguration` is just an interface, not a class, so the prototype of the object we're dealing with is just the global object type, so destructuring and assigning the label won't change the prototype, but if you prefer one of the `Object` methods, by all means `Object.assign(task, {label: this.taskNameResolver.resolve(task)}`.

File: packages/plugin-ext/src/main/browser/tasks-main.ts (hunk 6 above)
Comment (alvsan09) [reply packages/plugin-ext/src/main/browser/tasks-main.ts:179]: I am not sure if I understand the proposal, although the definition of group is actually aligned with vscode as follows, as a string, see: 
https://github.com/microsoft/vscode/blob/b37252c18238fffcebdc9fd7680f1dabea3a50a0/src/vs/workbench/api/common/shared/tasks.ts#L84-L97

Comment (colin-grant-work) [reply packages/plugin-ext/src/main/browser/tasks-main.ts:179]: If we're confident that we'll never see anything but the string form, then you can ignore my suggestion; however, the `TaskCustomization.isBuildTask` and `TaskCustomization.isTestTask` checks are more general, and more likely to keep up with any future schema changes, so it's likely good to use them as widely as possible.

Comment (alvsan09) [reply packages/plugin-ext/src/main/browser/tasks-main.ts:179]: The TaskCustomization.isBuildTask and TaskCustomization.isTestTask expect a TaskConfiguration as input, which is in the process to be converted to, that's why we are handling the conversion of group as a string separately so the Object.assign can apply.
Let me know if you see an alternative.

Comment (colin-grant-work) [reply packages/plugin-ext/src/main/browser/tasks-main.ts:179]: That's true - though the code could work, the type check would be unhappy. Leave the code as is.

File: packages/task/src/browser/task-service.ts (hunk 5 above)
Comment (alvsan09) [reply packages/task/src/browser/task-service.ts]: Done, on a new version of the commit. Thanks !

File: packages/plugin-ext/src/plugin/type-converters.ts [hunk 7]
```diff
@@ -717,6 +720,15 @@ export function fromTask(task: theia.Task): TaskDto | undefined {
         taskDto.scope = task.scope;
     }
 
+    const group = task.group;
+    if (group) {
```
Comment (colin-grant-work) [inline packages/plugin-ext/src/plugin/type-converters.ts:724]: minor: here and below you check `if (group)` before checking `if (group === something)`. I think you could skip the outer check, since `if (!group)`, definitely `!(group === something)`. Otherwise, this PR looks good to me

Comment (alvsan09) [reply packages/plugin-ext/src/plugin/type-converters.ts]: Thanks for pointing it out Colin, 
It's now fixed in a new version of the commit.

**Comment by colin-grant-work** [comment]
I've confirmed the bad behavior described in the bug reports on `master` and that the current code fixes it. @alvsan09, please squash your commits, and then I'll approve.

File: packages/task/src/browser/task-service.ts [hunk 8]
```diff
@@ -1105,6 +1105,7 @@ export class TaskService implements TaskConfigurationClient {
      * @param task The task to configure
      */
     async configure(token: number, task: TaskConfiguration): Promise<void> {
+        Object.assign(task, {label: this.taskNameResolver.resolve(task)});
```
Comment (RomanNikitenko) [inline packages/task/src/browser/task-service.ts:1108]: Minor: looks like here you have a formatting issue, could you check it please

**Review by RomanNikitenko — APPROVED** [review]
I tested `typescript` tasks according to the `Steps to reproduce` section of https://github.com/eclipse-theia/theia/issues/8950 and https://github.com/eclipse-theia/theia/issues/8980

It works well for me, I didn't notice any regression.
thanks!

File: packages/task/src/browser/task-service.ts (hunk 8 above)
Comment (alvsan09) [reply packages/task/src/browser/task-service.ts]: Fixed in a new commit !
Thanks Roman !

**Review by colin-grant-work — APPROVED** [review]

**Comment by vince-fugnitto** [comment]
Merging :) Thank you for your contribution @alvsan09 👍
