### PR TITLE
Keep closable state through pin/unpin

### LINKED ISSUE #14370: Unpinning an unclosable widget makes it closable
### Bug Description:

By pinning and unpinning a tab containing an unclosable widget, it becomes closable. The reason lies in the unpin function making the widget closable no matter what in https://github.com/eclipse-theia/theia/blob/f29c3d04241b32791462c7027938abeb887f8140/packages/core/src/browser/widgets/widget.ts#L373

### PR DESCRIPTION
**Pull request by tsmaeder**
#### What it does
Fixes #14370

Contributed on behalf of STMicroelectronics

#### How to test
Use the "Sample Unclosable View" and the File explorer to make sure views that are pinned/unpinned return to the same "closable" state after pinning/unpinning.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/core/src/browser/widgets/widget.ts [hunk 1]
```diff
@@ -364,23 +365,37 @@ function waitForVisible(widget: Widget, visible: boolean, attached?: boolean): P
     });
 }
 
+const pinnedTitles = new Map<Title<Widget>, [boolean, Slot<Widget, void>]>();
```
Comment (sgraband) [inline packages/core/src/browser/widgets/widget.ts:368]:
```suggestion
const pinnedTitles = new Map<Title<Widget>, PinnedProperties>();
```

Can we maybe create a type for the values of the map? This way the values in the array are better described and the code in the unpin method becomes more readable imho. I am not sure about the name, but something along the lines of `PinnedProperties` could be a good fit.
WDYT?

Comment (tsmaeder) [reply packages/core/src/browser/widgets/widget.ts:368]: There already is a type for the values in the map, it's a tuple of boolean and a Slot. Explicitly naming that type might make sense if the type was used elsewhere for documentatoin, but it's all private and happening in a couple of lines, so I don't think it adds any value.
