### PR TITLE
core: Command `Save All` only formats the file if it is dirty

### LINKED ISSUE #8548: Command `Save All` should not format and save the code on non-dirty editors
### Bug Description:
+ Running `Save All` should only format/save the files if it's dirty. The current behavior of `Save All` is formatting the file even when there's no new change.

### Steps to Reproduce:
1. Make the file in a wrong format (ie: wrong indentation, ...) 
2. Save without formatting
3. Turn on setting `formatOnSave` in settings
4. Make sure there's no new change in the current file
5. Run `Save All` from command palette or by using shortcut

### Additional Information

- Operating System: Windows 10, MacOS
- Theia Version: Master

### PR DESCRIPTION
**Pull request by DukeNgn**
#### What it does

Fixes #8548 
+ This PR is based on #8551 and #8543 
+ Command `Save All` now only formats the file if it is dirty

#### How to test

+ Turn on `formatOnSave`
+ Make the file in a wrong format (ie: wrong indentation, ...)
+ Save without formatting
+ Make sure there's no new change in the current file
+ Run `Save All` from command palette or by using shortcut

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: Duc Nguyen <duc.a.nguyen@ericsson.com>

### CODE REVIEW

File: packages/core/src/browser/saveable.ts [hunk 1]
```diff
@@ -87,10 +87,16 @@ export namespace Saveable {
...
     }
     // eslint-disable-next-line @typescript-eslint/no-explicit-any
-    export async function save(arg: any): Promise<void> {
+    export async function save(arg: any, options?: SaveOptions): Promise<void> {
         const saveable = get(arg);
+        /**
+         * skipFormatting is true if:
+         * - The function receives skipFormattingOnSave flag from 'options' object (ie: from command `saveWithoutFormatting`).
+         * - The file is not dirty and performing save in multiple files (saveAll command).
+         */
```
Comment (vince-fugnitto) [inline packages/core/src/browser/saveable.ts:96]: I think the documentation can be simplified, if not removed as the use-case is straightforward.

```
// Formatting should be skipped when explicitly requested, or when performing multiple saves (ex: `Save All`).
```

File: packages/core/src/browser/saveable.ts [hunk 2]
```diff
@@ -87,10 +87,16 @@ export namespace Saveable {
...
+        const skipFormatting = options?.skipFormattingOnSave || (!saveable?.dirty && options?.savingMultiple);
```
Comment (vince-fugnitto) [inline packages/core/src/browser/saveable.ts:97]: This check can be performed in the `if (saveable)` block:

```ts
const skipFormatting = options?.skipFormattingOnSave || (!saveable.dirty && options?.savingMultiple);
```

It can save us computation when `saveable` is `undefined`, as `skipFormatting` is only used when actually saving.

File: packages/core/src/browser/saveable.ts [hunk 3]
```diff
@@ -179,6 +185,14 @@ export namespace SaveableWidget {
     }
 }
 
+export interface SaveOptions {
+    readonly skipFormattingOnSave?: boolean;
```
Comment (vince-fugnitto) [inline packages/core/src/browser/saveable.ts:189]: I believe it comes from https://github.com/eclipse-theia/theia/pull/8543, but I think the naming can be simplified to:

```ts
/**
* Controls whether formatting should be applied upon saving.
*/
readonly skipFormatting? boolean;
```

It is clear that these are `saving` options by the naming of the `SaveOptions` interface.

File: packages/core/src/browser/saveable.ts [hunk 4]
```diff
@@ -179,6 +185,14 @@ export namespace SaveableWidget {
...
+    /**
+     * true if performing multiple saving operations
+     */
+    readonly savingMultiple?: boolean;
```
Comment (vince-fugnitto) [inline packages/core/src/browser/saveable.ts:193]: I think the name and documentation can be improved:

```ts
/**
* Represents if multiple saving operations will be performed.
* Ex: when performing a `Save All` operation.
*/
readonly multiple?: boolean;
```

**Review by vince-fugnitto — COMMENTED** [review]
I have a few comments about the code itself, I have yet to perform a review but overall it looks good!

File: packages/core/src/browser/saveable.ts (hunk 3 above)
Comment (DukeNgn) [reply packages/core/src/browser/saveable.ts:189]: Thank you for your feedback. I've updated #8543

**Comment by DukeNgn** [comment]
@vince-fugnitto Thanks for the feedbacks. I've updated this PR according to your review.

**Review by marechal-p — COMMENTED** [review]
I just had a few nitpick, LGTM otherwise!

File: packages/core/src/browser/saveable.ts [hunk 5]
```diff
@@ -90,7 +90,8 @@ export namespace Saveable {
     export async function save(arg: any, options?: SaveOptions): Promise<void> {
         const saveable = get(arg);
         if (saveable) {
-            await saveable.save(options);
+            const skipFormatting = options?.skipFormatting || (!saveable?.dirty && options?.multiple);
+            await saveable.save({ skipFormatting: skipFormatting });
```
[the remark this answers is not in the document]
Comment (DukeNgn) [reply packages/core/src/browser/saveable.ts]: I updated this recently to `saveable.save(options)`, passing the `SaveOptions` object directly to `save()`.

File: packages/core/src/browser/saveable.ts [hunk 6]
```diff
@@ -179,11 +179,29 @@ export namespace SaveableWidget {
...
+    DIRTY = 3
+};
+
 export interface SaveOptions {
     /**
-     * Controls whether formatting should be applied upon saving
+     * Scenario in which formatting is applied.
      */
-    readonly skipFormatting?: boolean;
+    readonly formatOptions?: FormatType;
```
[the remark this answers is not in the document]
Comment (DukeNgn) [reply packages/core/src/browser/saveable.ts:204]: Thanks for your review! I updated the PR according to it.

File: packages/monaco/src/browser/monaco-editor-provider.ts [hunk 7]
```diff
@@ -289,11 +289,22 @@ export class MonacoEditorProvider {
...
+    protected shouldSkipFormatting(editor: MonacoEditor, event: WillSaveMonacoModelEvent): boolean {
         if (event.reason !== TextDocumentSaveReason.Manual) {
-            return [];
+            return true;
+        }
+        if (event.options?.formatOptions) {
+            switch (event.options.formatOptions) {
+                case FormatType.ON: return false;
+                case FormatType.OFF: return true;
+                case FormatType.DIRTY: return (editor.document.dirty ? false : true);
```
[the remark this answers is not in the document]
Comment (DukeNgn) [reply packages/monaco/src/browser/monaco-editor-provider.ts]: Updated this. I was too overthinking when writing this 🤣

**Review by vince-fugnitto — APPROVED** [review]
The changes work well for me :+1: 

| Use Case | Result |
|:---|:---|
| `Save` | saves and formats the given document |
| `Save` (preference off) | saves but does not format the given document |
| `Save All` (with dirty) | saves the dirty documents and formats them |
| `Save All` (without dirty) | does not format the documents |
| `Save without Formattting` | saves the document without formatting |

**Comment by vince-fugnitto** [comment]
I'll merge tomorrow if there are no objections :+1:
