### PR TITLE
Empty VSCode plugin webview editor windows #13258

### LINKED ISSUE #13258: Empty VSCode plugin webview editor windows
### Bug Description:

VSCode plugin webview editor windows are not displayed correctly. See this screenshot:

image

Left is a hello world vsce webview as loaded by current `master`. Right is the same webview after reverting this commit https://github.com/eclipse-theia/theia/commit/72421be24d0461f811a39324579913e91056d7c4

Upon opening the webview this error is logged:
```
2024-01-10T17:16:06.195Z root ERROR [hosted-plugin: 586850] Promise rejection not handled in one second: Error: Unknown Webview: 0917c540-d516-4f59-ace9-bb9fff13c70c , reason: Error: Unknown Webview: 0917c540-d516-4f59-ace9-bb9fff13c70c
With stack trace: Error: Unknown Webview: 0917c540-d516-4f59-ace9-bb9fff13c70c
    at WebviewsMainImpl.getWebview (http://localhost:3000/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:13987:19)
    at async WebviewsMainImpl.$setHtml (http://localhost:3000/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:13917:25)
    at async RpcProtocol.handleRequest (http://localhost:3000/bundle.js:147209:28)
```

### Steps to Reproduce:

This can be reproduced on the Theia browser example. You will also need a sample VSCode extension, I pushed the source code for the one used above [here](https://github.com/bvenreply/helloworld-vsce-webview/tree/master). You can build it with `npm install && npx --yes --package @vscode/vsce vsce package --skip-license --allow-missing-repository`.

- Open Theia
- Install the sample vsce
- Open the command palette and select *Open HelloWorld webview*
- Observe the empty window and error logged in the backend

### Additional Information

- Operating System: `6.1.0-17-amd64 GNU/Linux`
- Theia Version: `master` (https://github.com/eclipse-theia/theia/commit/6a7bd87126e435a84deeda154838f8698ce9f723)
- Browser: Chromium version 119

### PR DESCRIPTION
**Pull request by jfaltermeier**
#### What it does

* introduce widget manager method to find a widget based on testing its options
* use this in webviews-main to also check pending widgets

Fixes #13258

#### How to test

See the reproducers on https://github.com/eclipse-theia/theia/issues/13258 and https://github.com/eclipse-theia/theia/issues/13092

#### Follow-ups

/

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/core/src/common/uuid.ts [hunk 1]
```diff
@@ -97,3 +99,13 @@ export const generateUuid = (function (): () => string {
...
 })();
+
+const NAMESPACE = '4c90ee4f-d952-44b1-83ca-f04121ab8e05';
+/**
+ * This function will hash the given value using SHA1. The result will be a uuid.
+ * @param value the string to hash
+ * @returns a uuid
+ */
+export function hashValue(value: string): string {
+    return v5(value, NAMESPACE);
```
Comment (martin-fleck-at) [inline packages/core/src/common/uuid.ts:110]: Since we are using `v5` as opposed to `v4` here, I assume that we made this choice on purpose to always get the same UUID given the specified value, right? If so I think it would be great to make that even more explicit in the comment. Or is that explicit enough in your opinion, just asking from a very novice point of view.

**Review by martin-fleck-at — COMMENTED** [review]
Looks good to me! I just would like a little bit of clarification on the `v5` stuff so it is very obvious why we use it.

File: packages/core/src/common/uuid.ts (hunk 1 above)
Comment (jfaltermeier) [reply packages/core/src/common/uuid.ts:111]: Thanks, I've added a comment

**Review by martin-fleck-at — APPROVED** [review]
LGTM!
