### PR TITLE
search-in-workspace: Perform workspace search in dirty file content

### LINKED ISSUE #5609: [search-in-workspace] search does not respect dirty changes
**Description**

The `search-in-workspace` widget does not respect dirty changes.
If an editor `A` has dirty changes and the `search-in-workspace` is used to search such changes, no results are found from `A`.

<div align='center'>

a (2)

</div>

**How to Reproduce**
1. open an editor and make changes (do not save and use a unique string ex: `vincent`).
2. open the `search-in-workspace` widget.
3. search for the unique string, the `search-in-workspace` widget will not show the result.

### PR DESCRIPTION
**Pull request by DukeNgn**
#### What it does
Fixes: #5609
Closes: #5651

+ `Search In Workspace` can now search content in dirty files and display the results in search view.
+ Utilizes `findMatches` function from `monaco editor` to get the search matches.
+ The message alert in search view now only shows up when neither workspace nor editor present.

**Note:** PR #5651 can be safely closed if this PR get merged since this PR is an enhancement. 

#### How to test
+ Open editor files in a workspace
+ Make changes in the editors without saving (make sure `auto save` is off)
+ Open `Search-in-Workspace` (`ctrl/cmd` + `shift` + `f`) and search for a certain keyword.
   - The results should correctly reflect the current state of the dirty editors.
   - The unsaved content in the editors should be shown in the search results, and properly highlighted in the editors.

searchInDirty2

#### Checklist when testing with search options

- [x] `Match Case`
- [x] `Match Whole Word`
- [x] `Use Regular Expression`
- [x] `Include Ignored Files`

- [x] `files to include`
- [x] `files to exclude`

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Co-authored-by: fangnx <naxin.fang@ericsson.com>
Co-authored-by: vince-fugnitto <vincent.fugnitto@ericsson.com>
Signed-off-by: DukeNgn <duc.a.nguyen@ericsson.com>

### CODE REVIEW

File: packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx [hunk 1]
```diff
@@ -199,13 +203,148 @@ export class SearchInWorkspaceResultTreeWidget extends TreeWidget {
...
+     * If a file belongs to more than one root folder, return the root folder closest to the file.
+     * If the file is not from the current workspace, return an empty URI.
+     */
+    getRoot(filePath: string, rootUris: string[]): URI {
+        const roots = rootUris.filter(root => new URI(root).withScheme('file').isEqualOrParent(new URI(filePath).withScheme('file')));
+        if (roots.length > 0) {
+            return new URI(roots.sort((r1, r2) => r2.length - r1.length)[0]);
+        }
+        return new URI();
+    }
```
Comment (vince-fugnitto) [inline packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx:219]: We can replace this method with the following method from the `WorkspaceService`:

https://github.com/eclipse-theia/theia/blob/137840a63cb3a250d11a575fee65a294ef6a4e0b/packages/workspace/src/browser/workspace-service.ts#L599-L604

File: packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx [hunk 2]
```diff
@@ -199,13 +203,148 @@ export class SearchInWorkspaceResultTreeWidget extends TreeWidget {
...
+    /**
+     * Find matches in a single widget.
+     * @param searchTerm  The search keyword.
+     * @param widget The widget that is being searched.
+     * @param fileContent The content of the widget.
+     * @param searchOptions The options for search operation.
+     */
+    findMatches(searchTerm: string, widget: EditorWidget, fileContent: string, searchOptions: SearchInWorkspaceOptions): SearchMatch[] {
+        let matches: SearchMatch[] = [];
+        const allLines: string[] = fileContent.split(/[\n\u0085\u2028\u2029]|\r\n?/);
```
Comment (vince-fugnitto) [inline packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx:230]: We can replace this method with the API from `monaco`:

- [getLineContent](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.itextmodel.html#getlinecontent)
- [getLinesContent](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.itextmodel.html#getlinescontent)

File: packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx [hunk 3]
```diff
@@ -199,13 +203,148 @@ export class SearchInWorkspaceResultTreeWidget extends TreeWidget {
...
+            const model = widget.editor.getControl().getModel();
+            const results: monaco.editor.FindMatch[] | undefined = model?.findMatches(
+                searchTerm,
+                true,
+                !!searchOptions.useRegExp,
+                !!searchOptions.matchCase,
+                // eslint-disable-next-line no-null/no-null
+                searchOptions.matchWholeWord ? searchTerm : null,
+                true,
+                searchOptions.maxResults);
```
Comment (vince-fugnitto) [inline packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx:244]: I'm not sure about limiting with `maxResults`, this number is used to get limit the search results obtained by `ripgrep`.
If dirty editors consume results, we should make sure to sum their result count and limit the overall results after.

The other problem is that `ripgrep` will produce duplicate results (for the same dirty editor URI), and the `maxResults` will also be affected.

File: packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx [hunk 4]
```diff
@@ -199,13 +203,148 @@ export class SearchInWorkspaceResultTreeWidget extends TreeWidget {
...
+        return matches;
+    }
+
+    filterEditorWidgets(widgets: EditorWidget[], searchOptions: SearchInWorkspaceOptions): EditorWidget[] {
+        // Exclude dirty widgets that should be ignored in glob.
+        if (!searchOptions.includeIgnored) {
+            const ignoredPatterns = this.filesystemPreferences.get('files.exclude');
+            widgets = widgets.filter(widget => {
+                for (const pattern in ignoredPatterns) {
+                    if (ignoredPatterns[pattern] && minimatch(widget.title.label, pattern)) {
```
Comment (vince-fugnitto) [inline packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx:264]: I believe we should minimatch on the editor's URI instead:

```ts
widget.editor.uri
```

File: packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx [hunk 5]
```diff
@@ -199,13 +203,148 @@ export class SearchInWorkspaceResultTreeWidget extends TreeWidget {
...
+     * Perform searching in all dirty editors.
+     * @param searchTerm The search keyword.
+     * @param searchOptions The options for search operation.
+     * @returns The number of matches in dirty editors.
+     */
+    searchInDirtyEditors(searchTerm: string, searchOptions: SearchInWorkspaceOptions): number {
+        let dirtyWidgets: EditorWidget[] = this.editorManager.all.filter(widget => widget.saveable.dirty);
+        dirtyWidgets = this.filterEditorWidgets(dirtyWidgets, searchOptions);
+        let numberOfResults = 0;
+        if (dirtyWidgets && dirtyWidgets.length > 0) {
```
Comment (vince-fugnitto) [inline packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx:294]: The following check is unnecessary and can be removed.

File: packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx (hunk 3 above)
Comment (DukeNgn) [reply packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx]: For this issue, currently I'm having a workaround by substracting `maxResults` directly in `monaco find matches` (results from monaco should be prioritized). In addition, I added a check for duplicate results from `ripgrep`, and increment `maxResults` by 1 to reimburse the unwanted loss of result counter.

File: packages/editor/src/browser/editor.ts [hunk 6]
```diff
@@ -150,6 +150,54 @@ export const enum EncodingMode {
...
+     */
+    isRegex: boolean;
+    /**
+     * Force the matching to match lower/upper case exactly.
+     */
+    matchCase: boolean;
+    /**
+     * Force the matching to match entire words only. Pass null otherwise.
+     */
+    wordSeparators: string | null;
```
Comment (vince-fugnitto) [inline packages/editor/src/browser/editor.ts:176]: We should use `undefined` instead.

Comment (DukeNgn) [reply packages/editor/src/browser/editor.ts]: Updated `wordSeparator` => boolean `matchWholeWord`

**Comment by DukeNgn** [comment]
@vince-fugnitto Thanks for the reviews. I updated the PR 👍

File: packages/editor/src/browser/editor.ts [hunk 7]
```diff
@@ -237,6 +277,22 @@ export interface TextEditor extends Disposable, TextEditorSelection, Navigatable
...
+     */
+    findMatches?(options: FindMatchesOptions): FindMatch[];
+
+    /**
+     * Get the text for a certain line.
+     * @param lineNumber the line number.
+     *
+     * @returns the text at the given line.
+     */
+    getLineContent?(lineNumber: number): string;
```
Comment (marechal-p) [inline packages/editor/src/browser/editor.ts:295]: I think we can do without this by using [`TextEditor.document.getLineContent(line)`](https://github.com/eclipse-theia/theia/blob/9e46acb5f9a0da7988832df395e2d5d166bd8cd6/packages/editor/src/browser/editor.ts#L31-L34)

File: packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx [hunk 8]
```diff
@@ -117,10 +121,10 @@ export class SearchInWorkspaceResultTreeWidget extends TreeWidget {
     @inject(ApplicationShell) protected readonly shell: ApplicationShell;
     @inject(WorkspaceService) protected readonly workspaceService: WorkspaceService;
     @inject(TreeExpansionService) protected readonly expansionService: TreeExpansionService;
+    @inject(FileSystemPreferences) protected readonly fileSystemPreferences: FileSystemPreferences;
```
Comment (marechal-p) [inline packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx:124]: This is a breaking change, please revert.

File: packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx [hunk 9]
```diff
@@ -199,9 +203,133 @@ export class SearchInWorkspaceResultTreeWidget extends TreeWidget {
...
+        matches: SearchInWorkspaceResult[]
+    } {
+        // Track the number of results found.
+        let numberOfResults = 0;
+
+        const searchResults: SearchInWorkspaceResult[] = [];
+        const editors = this.findMatchedEditors(this.editorManager.all, searchOptions);
+        editors.forEach(async widget => {
+            const matches = this.findMatches(searchTerm, widget, searchOptions);
+            if (matches?.length) {
```
Comment (marechal-p) [inline packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx:290]: Can `matches` really be nullish?

File: packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx [hunk 10]
```diff
@@ -199,9 +203,133 @@ export class SearchInWorkspaceResultTreeWidget extends TreeWidget {
...
+                numberOfResults += matches.length;
+                const fileUri: string = widget.editor.uri.toString();
+                const root: string = this.workspaceService.getWorkspaceRootUri(widget.editor.uri)?.toString()!;
```
Comment (marechal-p) [inline packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx:293]: Checking for nullish and finally forcing the value to not be interpreted as not nullish is a bit weird.

Either do a proper check or move the ending `!` to replace the first `?`.

**Comment by DukeNgn** [comment]
@marechal-p I updated the PR to fix the issues you mentioned. Please review again when you have time, thanks :)

File: packages/monaco/src/browser/monaco-editor.ts [hunk 11]
```diff
@@ -121,6 +121,33 @@ export class MonacoEditor extends MonacoEditorServices implements TextEditor {
...
+        if (!model) {
+            return [];
+        }
+        const results: monaco.editor.FindMatch[] = model.findMatches(
+            options.searchString,
+            false,
+            options.isRegex,
+            options.matchCase,
+            // eslint-disable-next-line no-null/no-null
+            options.matchWholeWord ? options.searchString : null,
```
Comment (marechal-p) [inline packages/monaco/src/browser/monaco-editor.ts:135]: The parameter name is `wordSeparators` here, I don't think passing `options.searchString` is the way to go.

**Review by marechal-p — COMMENTED** [review]
Tested most button combinations, and only "Match Whole Words" didn't work.

**Comment by marechal-p** [comment]
@akosyakov Would you move the `findMatches` function into the `TextEditorDocument` interface or keep it in the `TextEditor` one? Right now it is defined in the latter, but we're wondering if we should move it to `TextEditorDocument`? I don't see precisely which component should be responsible for what.

File: packages/monaco/src/browser/monaco-editor.ts (hunk 11 above)
Comment (DukeNgn) [reply packages/monaco/src/browser/monaco-editor.ts]: Updated the PR to address this :) Thanks for the catch.

File: packages/monaco/src/browser/monaco-editor-model.ts [hunk 12]
```diff
@@ -79,6 +81,8 @@ export class MonacoEditorModel implements ITextEditorModel, TextEditorDocument {
 
     protected resourceVersion: ResourceVersion | undefined;
 
+    protected EditorOptions = monaco.editor.EditorOption;
```
Comment (marechal-p) [inline packages/monaco/src/browser/monaco-editor-model.ts:84]: Please move this to the top, below imports.

Comment (marechal-p) [reply packages/monaco/src/browser/monaco-editor-model.ts:84]: `import EditorOptions = monaco.editor.EditorOption;`

Comment (DukeNgn) [reply packages/monaco/src/browser/monaco-editor-model.ts:84]: Got it. Thanks!

File: packages/monaco/src/browser/monaco-editor-model.ts [hunk 13]
```diff
@@ -83,6 +84,7 @@ export class MonacoEditorModel implements ITextEditorModel, TextEditorDocument {
         protected readonly resource: Resource,
         protected readonly m2p: MonacoToProtocolConverter,
         protected readonly p2m: ProtocolToMonacoConverter,
+        protected readonly editorPreference: EditorPreferences,
```
Comment (marechal-p) [inline packages/monaco/src/browser/monaco-editor-model.ts:87]: Changing the signature of a function is a breaking change. In this case, the function is the constructor but the rule still applies. Moving this parameter last and making it optional would not break api. This mean you'd also need a fallback in the logic trying to use it.

Comment (marechal-p) [reply packages/monaco/src/browser/monaco-editor-model.ts:87]: Typo: missing `s` at the end of the parameter name.

File: packages/editor/src/browser/editor.ts [hunk 14]
```diff
@@ -29,6 +29,7 @@ export const TextEditorProvider = Symbol('TextEditorProvider');
 export type TextEditorProvider = (uri: URI) => Promise<TextEditor>;
 
 export interface TextEditorDocument extends lsp.TextDocument, Saveable, Disposable {
+    findMatches(options: FindMatchesOptions): FindMatch[];
```
Comment (marechal-p) [inline packages/editor/src/browser/editor.ts:32]: Mark this as optional, with a jsdoc as `@since 1.7.0` and add an entry in the changelog to mention that a new method was added to this interface. This way we should be able to make it a required method sometime later.

File: packages/monaco/src/browser/monaco-editor-model.ts [hunk 15]
```diff
@@ -279,6 +281,35 @@ export class MonacoEditorModel implements ITextEditorModel, TextEditorDocument {
...
+     * @returns the list of matches.
+     */
+    findMatches(options: FindMatchesOptions): FindMatch[] {
+        const results: monaco.editor.FindMatch[] = this.model.findMatches(
+            options.searchString,
+            false,
+            options.isRegex,
+            options.matchCase,
+            // eslint-disable-next-line no-null/no-null
+            options.matchWholeWord ? this.editorPreference['editor.wordSeparators'] : null,
```
Comment (marechal-p) [inline packages/monaco/src/browser/monaco-editor-model.ts:297]: For the fallback value, you'd have to move the `editor.wordSeparators` default out of the schema into an exported const, so that we can import it in this file and use it here.

File: packages/editor/src/browser/editor-preferences.ts [hunk 16]
```diff
@@ -58,6 +58,8 @@ export const EDITOR_MODEL_DEFAULTS = {
     largeFileOptimizations: true
 };
 
+export const USUAL_WORD_SEPARATORS = '`~!@#$%^&*()-=+[{]}\\|;:\'",.<>/?';
```
Comment (marechal-p) [inline packages/editor/src/browser/editor-preferences.ts:61]: Just name it `DEFAULT_WORD_SEPARATORS` to match the value usage.

**Review by marechal-p — COMMENTED** [review]
The feature works correctly and code LGTM. Please squash your commits.

File: packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx [hunk 17]
```diff
@@ -199,9 +203,146 @@ export class SearchInWorkspaceResultTreeWidget extends TreeWidget {
...
+     */
+    protected convertPatternToGlob(pattern: string): string {
+        // The leading to make the pattern matches in all directories.
+        const globalPrefix = '**/';
+        if (pattern.startsWith(globalPrefix)) {
+            return pattern;
+        }
+        if (pattern.startsWith('./')) {
+            return pattern.replace('./', globalPrefix);
+        }
```
Comment (marechal-p) [inline packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx:252]: This looks odd. Should we replace `./` by the possible workspace roots rather?

Comment (DukeNgn) [reply packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx]: Yes, I updated the PR. Now it's appending the workspace root URI before the pattern in case of a leading `./`

**Review by vince-fugnitto — APPROVED** [review]
The changes very well for me and the code looks good as well :+1: 
Thank you for the hard work on the pull-request!
