### PR TITLE
Preserve cursor and selection when reopening editors

### LINKED ISSUE #6016: [editor] preserve cursor (selection) in previously opened editor
**Description**

The location of the cursor or selection is lost when an editor is closed.
As an enhancement, the location should be preserved so that users can easily navigate back to their previous context.

**Steps to Reproduce**
1. open a workspace in the application
1. open an editor, preferably a long file and navigate to the bottom
2. close the editor using the command `Close All Tabs`
3. re-open the closed editor using <kbd>ctrlcmd</kbd>+<kbd>p</kdb>
4. the cursor location is lost, the cursor now appears at the beginning of the file

**Additional Info**
- the cursor location is maintained in VSCode and I believe it is a nice enhancement

### PR DESCRIPTION
**Pull request by OmarSdt-EC**
#### What it does

Fixes #6016
Fixes https://github.com/eclipse-theia/theia/issues/8782

The pull-request attempts to restore the previous editor state when re-opening a closed editor through the `quick-file-open`.
The editor-view state should preserve folding, selection, cursor location.

#### How to test

_Selection_:

1. open a workspace in the application.
2. open an editor at a specific line and selection.
3. close the editor.
4. re-open the closed editor using <kbd>ctrlcmd</kbd>+<kbd>p</kbd>.
5. the editor should re-open with the previous state (cursor and selection).

selection

_Folding_:

1. open a workspace in the application.
2. open an editor.
3. execute the command `fold all` (the folding regions of the editor should be collapsed).
4. close the editor.
5. re-open the closed editor using <kbd>ctrlcmd</kbd>+<kbd>p</kbd>.
6. the editor should re-open with the previous folding state.

test-editor-state

_Line and Column_:

Thanks to https://github.com/eclipse-theia/theia/pull/9478, it is now possible to open files with a pre-defined line number and column. If the line number, or line number and column are provided this should take precedence over restoring the editor.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/file-search/src/browser/quick-file-open.ts [hunk 1]
```diff
@@ -361,9 +363,15 @@ export class QuickFileOpenService implements QuickOpenModel, QuickOpenHandler {
 
     openFile(uri: URI): void {
         const options = this.buildOpenerOptions();
-        const resolvedOpener = this.openerService.getOpener(uri, options);
-        resolvedOpener
+        const closedEditor = this.navigationLocationService.closedEditorsStack.find(editor => editor.uri === uri);
```
Comment (paul-marechal) [inline packages/file-search/src/browser/quick-file-open.ts:366]: I'd move this query into the `then(widget =>` callback.

Comment (paul-marechal) [reply packages/file-search/src/browser/quick-file-open.ts:366]: So we can't move the callback there, because opening the given `uri` and opening the editor will remove it from the `closedEditorsStack`.

**Review by alvsan09 — APPROVED** [review]
I tested the behavior and it works nicely! :+1: 
No additional comments on the implementation, well done! :-)

My approval is just symbolic as I am not yet a commiter!

File: packages/file-search/src/browser/quick-file-open.ts [hunk 2]
```diff
@@ -67,6 +67,8 @@ export class QuickFileOpenService implements QuickOpenModel, QuickOpenHandler {
     protected readonly messageService: MessageService;
     @inject(FileSystemPreferences)
     protected readonly fsPreferences: FileSystemPreferences;
+    @inject(EditorManager)
+    protected readonly editorManager: EditorManager;
```
Comment (vince-fugnitto) [inline packages/file-search/src/browser/quick-file-open.ts:71]: @OmarSdt-EC can you remove `EditorManager`, it is unused.

**Review by vince-fugnitto — APPROVED** [review]
I confirmed that the changes work as intended:
- [x] the editor state is restored if available when performing `quick-file-open`.
- [x] the editor state is not preserved if an explicit selection (line number or line number + column) is explicitly requested when opening.
- [x] the editor state is restored if the `editor.history.persistClosedEditors` is set to `true` and we attempt to re-open a previously stored editor.
