### PR TITLE
[vscode] allow installation of extension packs

### LINKED ISSUE #6611: Installing a vscode extension **pack** is not working
### Description

Installing a vscode 'extension pack' does not install the extensions in the pack

### Reproduction Steps

1. Create theia instance with this package.json

```
{
  "private": true,
  "dependencies": {
    "typescript": "latest",
    "@theia/typescript": "next",
    "@theia/navigator": "next",
    "@theia/terminal": "next",
    "@theia/outline-view": "next",
    "@theia/preferences": "next",
    "@theia/messages": "next",
    "@theia/git": "next",
    "@theia/file-search": "next",
    "@theia/markers": "next",
    "@theia/preview": "next",
    "@theia/callhierarchy": "next",
    "@theia/merge-conflicts": "next",
    "@theia/search-in-workspace": "next",
    "@theia/json": "next",
    "@theia/textmate-grammars": "next",
    "@theia/mini-browser": "next",
    "@theia/plugin-ext": "next",
    "@theia/plugin-ext-vscode": "next"
  },
  "devDependencies": {
    "@theia/cli": "next"
  }
}
```

2. Use 'Plugin:  Deploy plugin by id' to install this: `vscode:extension/Pivotal.vscode-boot-dev-pack`

3. Observe that the dev pack is indeed installed, but nothing else is. 

This is wrong, since the devpack contains several vscode extensions which should have been installed.

See: https://github.com/spring-projects/sts4/blob/master/vscode-extensions/boot-dev-pack/package.json

Which has this:

```
 "extensionPack": [
    "Pivotal.vscode-spring-boot",
    "Pivotal.vscode-concourse",
    "Pivotal.vscode-manifest-yaml",
    "vscjava.vscode-spring-initializr",
    "vscjava.vscode-spring-boot-dashboard"
  ]
```

**OS and Theia version:**

Theia version: 0.13.0-next.0860ab1b
Ubuntu 18.04 (running inside ubuntu docker container).

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

Fixes #6611

- added `extensionPack` property to `PluginPackage` interface.
- when getting dependencies, ensure that `extensionPack` dependencies are also loaded. Extensions packs can now be unloaded and their bundled extensions installed.

#### How to test

1. start the application
    - for test purposes a minimal application was used:
        - no `@theia/java`, `@theia/java-debug`, `@theia/textmate-grammars`
        - added `@theia/vscode-builtin-java`
2. install the `java extension pack`: https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack
3. should notice the extensions present in the pack unloaded

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: Vincent Fugnitto <vincent.fugnitto@ericsson.com>

cc @eclipse-theia/plugin-system

### CODE REVIEW

File: packages/plugin-ext-vscode/src/node/scanner-vscode.ts [hunk 1]
```diff
@@ -52,11 +52,23 @@ export class VsCodePluginScanner extends TheiaPluginScanner implements PluginSca
...
+        if (plugin.extensionPack && plugin.extensionPack.length) {
+            deps.push(...plugin.extensionPack);
+        }
+        // Exit early if no dependencies are present.
+        if (!deps.length) {
             return undefined;
         }
-        const dependencies = new Map<string, string>();
-        for (const dependency of plugin.extensionDependencies) {
+        for (const dependency of deps) {
```
Comment (akosyakov) [inline packages/plugin-ext-vscode/src/node/scanner-vscode.ts]: Can we add another loop around instead of going over everything again?

i.e.
```ts
for (const extensionDependencies of [plugin.extendionDependencies, plugin.extensionPack]) {
...
}
```

Comment (vince-fugnitto) [reply packages/plugin-ext-vscode/src/node/scanner-vscode.ts]: Thanks! It's much better that way :)

**Comment by vince-fugnitto** [comment]
I've verified with the **latest changes** that:
- extensions which describe `extensionPacks` successfully work:
   - using [python](https://marketplace.visualstudio.com/items?itemName=donjayamanne.python-extension-pack) extension pack
   - using [java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack) extension pack
- extensions which describe `extensionDependencies` successfully work:
   - using small [markdown julia](https://marketplace.visualstudio.com/items?itemName=colinfang.markdown-julia) extension which pulls [language-julia](https://marketplace.visualstudio.com/items?itemName=julialang.language-julia)

**Comment by vince-fugnitto** [comment]
@lmcbout did you get a chance to try it out for yourself?

**Comment by marcdumais-work** [comment]
> * no `@theia/java`, `@theia/textmate-grammars`

As well one should remove `@theia/java-debug`, else it pulls `@theia/java` as dependency

> * added `@theia/vscode-builtin-java`

BTW, testing a bit with @lmcbout , it looks like adding the built-in as a npm dependency is not enough to have it be discovered/used: we had no syntax highlighting until we copied it under `<workspace>/plugins/`, restarted the BE and reset the FE layout.

About the need to restart the BE / reset the FE, so that plugins work correctly: I think this is probably the problem that @akosyakov was referring-to in a recent dev-meeting?

**Comment by vince-fugnitto** [comment]
> As well one should remove `@theia/java-debug`, else it pulls `@theia/java` as dependency

Correct, to be fair I removed whatever was not necessary. 
Same thing when testing the `python` pack, the `@theia/python` extension was removed.

> BTW, testing a bit with @lmcbout , it looks like adding the built-in as a npm dependency is not enough to have it be discovered/used: we had no syntax highlighting until we copied it under `<workspace>/plugins/`, restarted the BE and reset the FE layout.

The builtins cannot be consumed as `npm` dependencies, they must be added as plugins. 
Is this what you meant?

> About the need to restart the BE / reset the FE, so that plugins work correctly: I think this is probably the problem that @akosyakov was referring-to in a recent dev-meeting?

I'm not sure if hot reload works at the moment (the fact that the FE had to be restarted).
