### PR TITLE
Handle the case where the editor model is set to null

### LINKED ISSUE #14996: Errors in the browser log
### Bug Description:
Recently, I've been getting messages like this in the browser log: 
```
logger-protocol.ts:117 2025-02-19T17:04:51.426Z root ERROR TypeError: Cannot read properties of null (reading 'uri')
    at n.isEditorFrame (file:///C:/Users/thomas/AppData/Local/Programs/TheiaIDE/resources/app/lib/frontend/bundle.js:2:3259788)
    at file:///C:/Users/thomas/AppData/Local/Programs/TheiaIDE/resources/app/lib/frontend/bundle.js:2:3257040
    at file:///C:/Users/thomas/AppData/Local/Programs/TheiaIDE/resources/app/lib/frontend/bundle.js:2:2902111
    at s.invoke (file:///C:/Users/thomas/AppData/Local/Programs/TheiaIDE/resources/app/lib/frontend/bundle.js:2:2902201)
    at a.fire (file:///C:/Users/thomas/AppData/Local/Programs/TheiaIDE/resources/app/lib/frontend/bundle.js:2:2904004)
    at C.fireDidChange (file:///C:/Users/thomas/AppData/Local/Programs/TheiaIDE/resources/app/lib/frontend/bundle.js:2:3170813)
    at set currentSession (file:///C:/Users/thomas/AppData/Local/Programs/TheiaIDE/resources/app/lib/frontend/bundle.js:2:3178849)
    at C.updateCurrentSession (file:///C:/Users/thomas/AppData/Local/Programs/TheiaIDE/resources/app/lib/frontend/bundle.js:2:3179154)
    at file:///C:/Users/thomas/AppData/Local/Programs/TheiaIDE/resources/app/lib/frontend/bundle.js:2:3176295
    at file:///C:/Users/thomas/AppData/Local/Programs/TheiaIDE/resources/app/lib/frontend/bundle.js:2:2902111
e.log	@	logger-protocol.ts:117
```

### Additional Information

- Operating System: Windows
- Theia Version: Theia 1.58.300

### PR DESCRIPTION
**Pull request by tsmaeder**
#### What it does
Because the monaco editor does not work correctly when hidden with `display: none` we are removing the editor model from the editor when hidden. Unfortunately, some of our code relied on the model being non-null, despite the API saying otherwise. This PR introduces code handling the case.

Fixes #14996

#### How to test
Makes sure the changed code still works, mostly the cases are in the debugger like breakpoints or editing launch configurations.

#### Breaking changes

- [ ] This PR introduces breaking changes and requires careful review. If yes, the breaking changes section in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) has been updated.

#### Attribution
Contributed on behalf of STMicroelectronics

#### Review checklist

- [ ] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by tsmaeder** [comment]
@colin-grant-work this one should be in the relase. Let me know if you have no time to review.

File: packages/debug/src/browser/editor/debug-breakpoint-widget.tsx [hunk 1]
```diff
@@ -130,13 +130,14 @@ export class DebugBreakpointWidget implements Disposable {
...
+                    const editorModel = editor.getModel() as unknown as TextModel | undefined;
                     const suggestions: monaco.languages.CompletionItem[] = [];
-                    if ((this.context === 'condition' || this.context === 'logMessage')
+                    if (editorModel && (this.context === 'condition' || this.context === 'logMessage')
                         && input.uri.toString() === model.uri.toString()) {
-                        const editor = this.editor.getControl();
                         const completions = await provideSuggestionItems(
                             StandaloneServices.get(ILanguageFeaturesService).completionProvider,
-                            editor.getModel()! as unknown as TextModel,
+                            editorModel,
```
Comment (colin-grant-work) [inline packages/debug/src/browser/editor/debug-breakpoint-widget.tsx:140]: In most of the places affected by this PR, we're immediately using a model to derive data. This looks like one of the only places where we're passing the model off to another consumer. It looks like that consumer's job should be done in relatively short order, so the reference is safe, but I just want to confirm that that's the case.

Comment (tsmaeder) [reply packages/debug/src/browser/editor/debug-breakpoint-widget.tsx:140]: Since we're passing the model as a parameter to the `provideCompletionItems()` function, the evaluation there is no asynchronicity between the place where we get the model and where we use it. Whether passing this model to function is right or not, I don't know, but at least it's no worse than before.

**Review by colin-grant-work — APPROVED** [review]

**Review by colin-grant-work — APPROVED** [review]
No issues in my tests. 👍
