### PR TITLE
[output] add severity/color to appendLine method

### LINKED ISSUE #7504: Support colors for logs in OutputChannel
### Description
Suggesting an enhancement for the logs in OutputChannel to display colors for different log levels.

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

### PR DESCRIPTION
**Pull request by amiramw**
Signed-off-by: Amiram Wingarten <amiram.wingarten@sap.com>

Fixes #7504 

#### What it does
Add severity to append methods of output channel. This allow to color output lines for errors and warnings.

#### How to test
For some output channel call `appendLine` with severities info, warning and error.
The output lines should color accordingly, warning in yellow and error in red.

Call `append` method - it should behave as info.

See example examples/api-samples/src/browser/output/sample-output-channel-with-severity.ts

Also test application can be found in https://github.com/eclipse-theia/theia/pull/7600

https://github.com/eclipse-theia/theia/blob/d26c403391d05d1bfb59c59c3dd9de154d034b9f/packages/output/src/browser/test-app.ts#L26-L32

The expected output channel "my test channel" should look like this after theia start:

image

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/output/src/browser/output-widget.tsx [hunk 1]
```diff
@@ -117,10 +117,16 @@ export class OutputWidget extends ReactWidget {
         };
 
         if (this.outputChannelManager.selectedChannel) {
-            for (const text of this.outputChannelManager.selectedChannel.getLines()) {
-                const lines = text.split(/[\n\r]+/);
+            for (const outputChannelLine of this.outputChannelManager.selectedChannel.getLines()) {
+                const lines = outputChannelLine.text.split(/[\n\r]+/);
+                let className;
+                if (outputChannelLine.severity === OutputChannelSeverity.Error) {
+                    className = 'theia-console-error';
```
Comment (vince-fugnitto) [inline packages/output/src/browser/output-widget.tsx:124]: I'm not sure these are the correct classes to use as they are contributed by `console`.
It is possible to build an application without `console`, and in this scenario, coloring present in the output view will not work.

**Comment by akosyakov** [comment]
Would it be possible to keep it after we switch to use Monaco editor for the output to align with VS Code and get features like search and so on?

**Comment by amiramw** [comment]
@akosyakov sure. But will colors be possible after the move? VS code doesn't have this feature as far as I know.

**Comment by akosyakov** [comment]
@amiramw It was my question :) But thinking now, Monaco editor has decorators API to color text. So it should be.

Please address @vince-fugnitto comment: https://github.com/eclipse-theia/theia/pull/7549#discussion_r407495763

The output extension should not have implicit dependencies on the console extension via css classes.

**Comment by amiramw** [comment]
@akosyakov i wasn't aware that vscode uses monaco editor component also for the output. 

Anyway for now I'm addressing CR comments...

File: packages/output/src/browser/output-widget.tsx (hunk 1 above)
Comment (amiramw) [reply packages/output/src/browser/output-widget.tsx]: I created new classes in output package styles

**Comment by amiramw** [comment]
@vince-fugnitto I updated the how to test section. There is another PR with test example.

File: packages/output/src/common/output-channel.ts [hunk 2]
```diff
@@ -105,12 +105,20 @@ export class OutputChannelManager implements Disposable {
     }
 }
 
+export enum OutputChannelSeverity {
+    info, Warning, Error
```
Comment (kittaakos) [inline packages/output/src/common/output-channel.ts:109]: `info` -> `Info`?

Comment (kittaakos) [reply packages/output/src/common/output-channel.ts:109]: `packages/core/src/common/severity.ts` defines another `Severity`; can we kind of follow its enum order.
```ts
export enum Severity {
    Ignore = 0,
    Error = 1,
    Warning = 2,
    Info = 3,
    Log = 4
}
``` 
So the new `OutputChannelSeverity` would become:
```ts
export enum OutputChannelSeverity {
    Error = 1,
    Warning = 2,
    Info = 3
}
```

Comment (amiramw) [reply packages/output/src/common/output-channel.ts]: fixed both

**Comment by amiramw** [comment]
Any clue why the build is failing now?

**Comment by akosyakov** [comment]
@amiramw I'm looking into the build failure.

**Comment by kittaakos** [comment]
Adding a new dependency to `@theia/api-sampl` should update the `examples/api-samples/compile.tsconfig.json` with the path too `@theia/output` when you run the build. Did you commit all the file changes?

**Comment by amiramw** [comment]
i didn't, thought it was generated wrongly. I'll chec again.

File: packages/output/src/common/output-channel.ts [hunk 3]
```diff
@@ -105,12 +105,22 @@ export class OutputChannelManager implements Disposable {
...
 }
 
+export enum OutputChannelSeverity {
+    Error = 1,
+    Warning = 2,
+    Info = 3
+}
+export interface OutputChannelLine {
+    text: string;
+    severity: OutputChannelSeverity;
```
Comment (kittaakos) [inline packages/output/src/common/output-channel.ts:115]: Just one remark; let's make this optional. 99% of the cases it will be `Info`, so we do not have to repeat it again. Thoughts? Or make `lines` property `Array<OutputChannelLine  | string>` type.

Comment (amiramw) [reply packages/output/src/common/output-channel.ts:115]: I will make it optional but for clients there won't be any differennce as in the API is optional already.

**Comment by amiramw** [comment]
@kittaakos Seems that build is fine now and i fixed your comment.

**Comment by kittaakos** [comment]
@amiramw, ping me if you cannot do the merge.

File: packages/output/src/common/output-channel.ts (hunk 3 above)
Comment (kittaakos) [reply packages/output/src/common/output-channel.ts]: > there won't be any differennce as in the API is optional already

Thanks for the heads-up; yes I have noticed it.

**Comment by amiramw** [comment]
Thansks @kittaakos! Merging.
