### PR TITLE
workspace: normalize paths of workspace roots

### LINKED ISSUE #7597: [multi-root] Relative paths in multi-root setting are not resolved when opening a Terminal
### Description
When you define a multi-root workspace with relative paths like `../../workspace/` the path is not resolved when you open a terminal. You can see it in the following screenshot in the menu as well as in the terminal view.

image

### Reproduction Steps
- Start Theia
- Create a muli-root workspace like this:
```json
{
   "folders": [
      {
         "path": ""
      },
      {
         "path": "../../workspace"
      }
   ],
   "settings": {}
}
```
- Select `Open New Terminal` in Command Palette
- See that the URI is not resolved, e.g. `../..` is not resolved

**OS and Theia version:**

- Version: ebf7b78
- Started in Gitpod

### PR DESCRIPTION
**Pull request by corneliusludmann**
#### What it does

This is my proposal to fix #7597 .

If you have configured a workspace folder like
```
"path": "../../workspace"
```
you get a Terminal for URI `/workspace/theia/../../workspace` instead of `/workspace`. This commit fixes this by using a normalized path in the terminal cwd selector.

An alternative would be to fix the roots in the workspace service directly so that it benefits everywhere.

#### How to test
see #7597

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/terminal/src/browser/terminal-frontend-contribution.ts [hunk 1]
```diff
@@ -564,7 +564,14 @@ export class TerminalFrontendContribution implements TerminalService, CommandCon
     protected async selectTerminalCwd(): Promise<string | undefined> {
         const roots = this.workspaceService.tryGetRoots();
         return this.quickPick.show(roots.map(
-            ({ uri }) => ({ label: this.labelProvider.getName(new URI(uri)), description: this.labelProvider.getLongName(new URI(uri)), value: uri })
+            ({ uri }) => {
+                const normalizedUri = new URI(uri).normalizePath();
```
Comment (akosyakov) [inline packages/terminal/src/browser/terminal-frontend-contribution.ts:568]: Maybe we should move into `DefaultLabelProvider` that it is applied for other clients as well?

**Comment by vince-fugnitto** [comment]
@corneliusludmann thank you, I hadn't thought of the use case when I initially authored the changes. Would the suggestion you had of updating the `WorkspaceService` be better which would likely fix other similar issues?

**Comment by akosyakov** [comment]
@vince-fugnitto Do you mean that we normalize all root URIs in `WorkspaceService`? It sounds even better.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Do you mean that we normalize all root URIs in `WorkspaceService`? It sounds even better.

Yes exactly, it is what @corneliusludmann mentioned in his pull-request description:
> An alternative would be to fix the roots in the workspace service directly so that it benefits everywhere.

**Comment by akosyakov** [comment]
@corneliusludmann Can you do alternative solution? It sounds great.

**Comment by corneliusludmann** [comment]
Sure. I'll do this.

**Comment by corneliusludmann** [comment]
I'm not sure which is the best place to put this. The call chain is:

- [computeRoots()](https://github.com/eclipse-theia/theia/blob/751a3d7e7c8b23f6101ccf8f03ceefe11d0e33ed/packages/workspace/src/browser/workspace-service.ts#L200)
- [toValidRoot()](https://github.com/eclipse-theia/theia/blob/751a3d7e7c8b23f6101ccf8f03ceefe11d0e33ed/packages/workspace/src/browser/workspace-service.ts#L410)
- [toFileStat()](https://github.com/corneliusludmann/theia/blob/ebf7b78923feb28b2068ec28fd47e3e817873307/packages/workspace/src/browser/workspace-service.ts#L421)

Is normalizing the path in `toFileStat()` too aggressive? I think it fits very well in this method. However, it is called from 4 other places in `workspace-service.ts`. I think, they all benefit form this change but if you afraid of side effects I would add this to `toValidRoot()` instead. WDYT @akosyakov?

https://github.com/eclipse-theia/theia/blob/751a3d7e7c8b23f6101ccf8f03ceefe11d0e33ed/packages/workspace/src/browser/workspace-service.ts#L418-L438

**Comment by akosyakov** [comment]
It seems to be fine. @vince-fugnitto Could you verify it please?

**Comment by vince-fugnitto** [comment]
> It seems to be fine. @vince-fugnitto Could you verify it please?

Sure, I'll test it! 
@corneliusludmann would you mind adding tests to the `workspace-service` to verify if we now correctly handle normalizing? If not I can definitely do so :)


@corneliusludmann do you mind updating the workspace-service tests for `toFileStat` to verify if we are correctly normalizing uris?

**Comment by corneliusludmann** [comment]
@vince-fugnitto I updated the PR with a test. I hope that's of some use. Feel free to modify or to propose changes.
