### PR TITLE
fix reconnection of native language servers

### LINKED ISSUE #6200: `Add Configuration` of debug panel shows wrong suggestions when a new websocket is created
### Description
After the websocket connection is recreated  for network problems, clicking `Add Configuration` of debug panel will only show some useless suggestions. 
This problem appears frequently because of my bad network and is very annoying.

**right suggestions**
image

**wrong suggestions after a new websocket is created**
image

### Reproduction Steps

This issue may be difficult to reproduce in reliable networks, so I use `iptables` to cut the network connection between the server and client as follows:
```
#/bin/bash
iptables -I INPUT -p tcp -s {client ip} --dport {connection port} -j DROP
sleep 20
iptables -D INPUT 1
```
The `sleep time` should be long enough, otherwise the old websocket connection will be reused and the problem will not be reproduced.
**OS and Theia version:**
os: centos 7
theia commit id: https://github.com/eclipse-theia/theia/commit/1808d782a947a52fbeeb900bb83b190cd578420c
**Diagnostics:**

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

fix #6200:
- Force restart language client contribution on reconnect: Since restart skips if a server is not running, on reconnection a server has to be restarted forcefully if it was running before.
- Don't wait when a stopped json language server is ready: Timing of resolving `LanguageClient.onReady` promise is changed in never version of `vscode-languageclient`. It could lead to a situation that clients still use `onReady` of a language client before reconnection.

#### How to test

- cause connection issues either with system proxy or by stopping a server
- make sure that json language server is running after reconnection and proper configuration snippets are available in launch.json
- make sure that other native language servers are restarted on reconnect as well, for example for typescript

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
@tom-shan Could you try whether it resolves #6200?

File: packages/json/src/browser/json-client-contribution.ts [hunk 1]
```diff
@@ -95,15 +84,21 @@ export class JsonClientContribution extends BaseLanguageClientContribution {
...
+        super.onReady(languageClient);
         // handle content request
         languageClient.onRequest('vscode/content', async (uriPath: string) => {
             const uri = new URI(uriPath);
             const resource = await this.resourceProvider(uri);
             const text = await resource.readContents();
             return text;
         });
-        super.onReady(languageClient);
-        setTimeout(() => this.initializeJsonSchemaAssociations());
```
Comment (akosyakov) [inline packages/json/src/browser/json-client-contribution.ts]: @svenefftinge I've removed it because it adds a lot of duplicate schemas on each connection. Calling it once from the constructor should be enough?

**Comment by tom-shan** [comment]
> @tom-shan Could you try whether it resolves #6200?

I'm veryfying it

File: packages/json/src/browser/json-client-contribution.ts [hunk 2]
```diff
@@ -46,18 +46,9 @@ export class JsonClientContribution extends BaseLanguageClientContribution {
     ) {
         super(workspace, languages, languageClientFactory);
         this.initializeJsonSchemaAssociations();
```
Comment (svenefftinge) [inline packages/json/src/browser/json-client-contribution.ts]: How would the language server learn about new `json.schemas` entries?

**Comment by tom-shan** [comment]
When follow the reproduction steps in #6200, the suggestions are always right. So I think #6200 is resolved. I will pay attention to this problem in my bad network and check whether the problem is gone.
