### PR TITLE
Fixed race condition on monaco editor initialization

### LINKED ISSUE #8562: Some files are unexpectedly created when Theia (browser version, run on Linux) is accessed by a Windows machine if a slow frontend contribution is present
### Bug Description:
When Theia (browser version) is run on Linux, if there is a frontend contribution with a long starting time and Theia is accessed by a Windows machine some files (`.theia/tasks.json`, `.theia/launch.json`, `.theia/settings.json`, `.vscode/tasks.json`, `.vscode/launch.json`, `.vscode/settings.json`) might be created.

### Steps to Reproduce:

1. Add a frontend application contribution to Theia with a long starting time. Ideally a `FrontendApplicationContribution` with a configure method taking a few (>3) seconds to be completed.
2. Start Theia (browser version) on a Linux machine.
3. Access Theia from a Windows machine.
4. The files mentioned above are created.

### Additional Information

- Operating System: Observed on Ubuntu 18, but any Linux version should work.
- Theia Version: Tested with Theia 1.2.0 and 1.5.0

### PR DESCRIPTION
**Pull request by federicobozzini**
#### What it does

This PR fixes #8562. I think it was caused by a race condition in the Monaco Editor inizialization and this is one possible way to fix it.

#### How to test

To test try to run the browser version of Theia on windows, with a slow frontend contribution, and access Theia with a windows machine.

This fix prevents `MonacoTextModelService` to run until `MonacoEditorProvider` is properly initialized, preventing the issue from happening.

#### Review checklist

- [X] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by vince-fugnitto — COMMENTED** [review]
Thank you for the fix, there are [build errors](https://travis-ci.com/github/eclipse-theia/theia/jobs/391050731#L1238-L1276).

**Comment by federicobozzini** [comment]
> Thank you for the fix, there are [build errors](https://travis-ci.com/github/eclipse-theia/theia/jobs/391050731#L1238-L1276).

Thanks, I've fixed it. It seems there is still some issue with the dependencies but I don't think it's related to this PR.

**Comment by marcdumais-work** [comment]
> It seems there is still some issue with the dependencies but I don't think it's related to this PR.

Indeed - it's because of  `vscode-ripgrep` and not related to the PR.

**Comment by marechal-p** [comment]
@federicobozzini For the sake of verification, could you provide us with some pseudo stack trace illustrating the race condition?

I'd like to understand the chain of events that lead to the issue, and I am having trouble finding it on my end.

**Comment by federicobozzini** [comment]
The stacktrace of the files creation on the frontend side is:
```
(anonymous) (user-storage-service-filesystem.ts:96)
step (user-storage-service-filesystem.ts:15)
(anonymous) (user-storage-service-filesystem.ts:15)
fulfilled (user-storage-service-filesystem.ts:15)
Promise.then (async)
step (user-storage-service-filesystem.ts:15)
fulfilled (user-storage-service-filesystem.ts:15)
Promise.then (async)
step (user-storage-service-filesystem.ts:15)
(anonymous) (user-storage-service-filesystem.ts:15)
push.../../node_modules/@theia/userstorage/lib/browser/user-storage-service-filesystem.js.__awaiter (user-storage-service-filesystem.ts:15)
push.../../node_modules/@theia/userstorage/lib/browser/user-storage-service-filesystem.js.UserStorageServiceFilesystemImpl.saveContents (user-storage-service-filesystem.ts:87)
push.../../node_modules/@theia/userstorage/lib/browser/user-storage-resource.js.UserStorageResource.saveContents (user-storage-resource.ts:51)
(anonymous) (resource.ts:98)
step (resource.ts:15)
(anonymous) (resource.ts:15)
fulfilled (resource.ts:15)
Promise.then (async)
step (resource.ts:15)
(anonymous) (resource.ts:15)
../../theia/packages/core/lib/common/resource.js.__awaiter (resource.ts:15)
save (resource.ts:88)
(anonymous) (monaco-editor-model.js:520)
step (monaco-editor-model.js:59)
(anonymous) (monaco-editor-model.js:40)
fulfilled (monaco-editor-model.js:31)
Promise.then (async)
step (monaco-editor-model.js:33)
(anonymous) (monaco-editor-model.js:34)
push.../../node_modules/@theia/monaco/lib/browser/monaco-editor-model.js.__awaiter (monaco-editor-model.js:30)
push.../../node_modules/@theia/monaco/lib/browser/monaco-editor-model.js.MonacoEditorModel.doSave (monaco-editor-model.js:496)
(anonymous) (monaco-editor-model.js:452)
(anonymous) (monaco-editor-model.js:339)
step (monaco-editor-model.js:59)
(anonymous) (monaco-editor-model.js:40)
(anonymous) (monaco-editor-model.js:34)
push.../../node_modules/@theia/monaco/lib/browser/monaco-editor-model.js.__awaiter (monaco-editor-model.js:30)
(anonymous) (monaco-editor-model.js:333)
Promise.then (async)
(anonymous) (monaco-editor-model.js:333)
step (monaco-editor-model.js:59)
(anonymous) (monaco-editor-model.js:40)
(anonymous) (monaco-editor-model.js:34)
push.../../node_modules/@theia/monaco/lib/browser/monaco-editor-model.js.__awaiter (monaco-editor-model.js:30)
push.../../node_modules/@theia/monaco/lib/browser/monaco-editor-model.js.MonacoEditorModel.run (monaco-editor-model.js:327)
push.../../node_modules/@theia/monaco/lib/browser/monaco-editor-model.js.MonacoEditorModel.scheduleSave (monaco-editor-model.js:452)
(anonymous) (monaco-editor-model.js:437)
setTimeout (async)
push.../../node_modules/@theia/monaco/lib/browser/monaco-editor-model.js.MonacoEditorModel.doAutoSave (monaco-editor-model.js:436)
push.../../node_modules/@theia/monaco/lib/browser/monaco-editor-model.js.MonacoEditorModel.markAsDirty (monaco-editor-model.js:429)
push.../../node_modules/@theia/monaco/lib/browser/monaco-editor-model.js.MonacoEditorModel.fireDidChangeContent (monaco-editor-model.js:465)
(anonymous) (monaco-editor-model.js:179)
(anonymous) (textModel.ts:237)
Emitter.fire (event.ts:581)
DidChangeContentEmitter.fire (textModel.ts:3100)
TextModel._emitContentChangedEvent (textModel.ts:374)
TextModel.setEOL (textModel.ts:461)
ModelServiceImpl._setModelOptionsForModel (modelServiceImpl.ts:230)
ModelServiceImpl._updateModelOptions (modelServiceImpl.ts:224)
(anonymous) (modelServiceImpl.ts:131)
Emitter.fire (event.ts:581)
(anonymous) (monaco-frontend-module.ts:179)
(anonymous) (event.ts:117)
../../theia/packages/core/lib/common/event.js.CallbackList.invoke (event.ts:125)
../../theia/packages/core/lib/common/event.js.Emitter.fire (event.ts:267)
push.../../node_modules/@theia/monaco/lib/browser/monaco-configurations.js.MonacoConfigurations.reconcileData (monaco-configurations.ts:48)
(anonymous) (monaco-configurations.ts:44)
(anonymous) (event.ts:117)
../../theia/packages/core/lib/common/event.js.CallbackList.invoke (event.ts:125)
../../theia/packages/core/lib/common/event.js.Emitter.fire (event.ts:267)
../../theia/packages/core/lib/browser/preferences/preference-service.js.PreferenceServiceImpl.reconcilePreferences (preference-service.ts:206)
(anonymous) (preference-service.ts:128)
(anonymous) (event.ts:117)
../../theia/packages/core/lib/common/event.js.CallbackList.invoke (event.ts:125)
../../theia/packages/core/lib/common/event.js.Emitter.fire (event.ts:267)
(anonymous) (preference-provider.ts:115)
(anonymous) (index.js:21)
setTimeout (async)
(anonymous) (index.js:18)
(anonymous) (index.js:13)
../../theia/packages/core/lib/browser/preferences/preference-provider.js.PreferenceProvider.emitPreferencesChangedEvent (preference-provider.ts:90)
../../theia/packages/core/lib/browser/preferences/preference-contribution.js.PreferenceSchemaProvider.setSchema (preference-contribution.ts:258)
push.../../node_modules/@theia/languages/lib/browser/languages-frontend-contribution.js.LanguagesFrontendContribution.onStart (languages-frontend-contribution.ts:54)
(anonymous) (frontend-application.ts:346)
(anonymous) (frontend-application.ts:376)
step (frontend-application.ts:15)
(anonymous) (frontend-application.ts:15)
(anonymous) (frontend-application.ts:15)
../../theia/packages/core/lib/browser/frontend-application.js.__awaiter (frontend-application.ts:15)
../../theia/packages/core/lib/browser/frontend-application.js.FrontendApplication.measure (frontend-application.ts:372)
(anonymous) (frontend-application.ts:345)
step (frontend-application.ts:15)
(anonymous) (frontend-application.ts:15)
step (frontend-application.ts:15)
(anonymous) (frontend-application.ts:15)
fulfilled (frontend-application.ts:15)
Promise.then (async)
step (frontend-application.ts:15)
fulfilled (frontend-application.ts:15)
Promise.then (async)
step (frontend-application.ts:15)
fulfilled (frontend-application.ts:15)
Promise.then (async)
step (frontend-application.ts:15)
fulfilled (frontend-application.ts:15)
Promise.then (async)
step (frontend-application.ts:15)
fulfilled (frontend-application.ts:15)
Promise.then (async)
step (frontend-application.ts:15)
fulfilled (frontend-application.ts:15)
Promise.then (async)
step (frontend-application.ts:15)
fulfilled (frontend-application.ts:15)
Promise.then (async)
step (frontend-application.ts:15)
fulfilled (frontend-application.ts:15)
Promise.then (async)
step (frontend-application.ts:15)
fulfilled (frontend-application.ts:15)
Promise.then (async)
step (frontend-application.ts:15)
fulfilled (frontend-application.ts:15)
Promise.then (async)
step (frontend-application.ts:15)
fulfilled (frontend-application.ts:15)
Promise.then (async)
step (frontend-application.ts:15)
fulfilled (frontend-application.ts:15)
Promise.then (async)
step (frontend-application.ts:15)
fulfilled (frontend-application.ts:15)
Promise.then (async)
step (frontend-application.ts:15)
fulfilled (frontend-application.ts:15)
Promise.then (async)
step (frontend-application.ts:15)
fulfilled (frontend-application.ts:15)
Promise.then (async)
step (frontend-application.ts:15)
fulfilled (frontend-application.ts:15)
Promise.then (async)
step (frontend-application.ts:15)
fulfilled (frontend-application.ts:15)
Promise.then (async)
step (frontend-application.ts:15)
fulfilled (frontend-application.ts:15)
Promise.then (async)
step (frontend-application.ts:15)
fulfilled (frontend-application.ts:15)
Promise.then (async)
step (frontend-application.ts:15)
fulfilled (frontend-application.ts:15)
Promise.then (async)
step (frontend-application.ts:15)
fulfilled (frontend-application.ts:15)
Promise.then (async)
step (frontend-application.ts:15)
fulfilled (frontend-application.ts:15)
Promise.then (async)
step (frontend-application.ts:15)
fulfilled (frontend-application.ts:15)
Promise.then (async)
step (frontend-application.ts:15)
fulfilled (frontend-application.ts:15)
Promise.then (async)
step (frontend-application.ts:15)
fulfilled (frontend-application.ts:15)
Promise.then (async)
step (frontend-application.ts:15)
fulfilled (frontend-application.ts:15)
```

This is not too easy to debug because as far as I understand most of this process is not started explicitly but by a chain of object creations and inizialitazions managed by `inversify`.

The source of this error seems to come from the fact that the [`MonacoEditorProvider` redefines the default `EOL` for the new resource models](https://github.com/eclipse-theia/theia/blob/ff354d6d19a9f4a2c2dddb7aea63ca192a964a8b/packages/monaco/src/browser/monaco-editor-provider.ts#L105) but if this initialization happens too late (because of a slow frontend contribution), [when the resource models are initialized](https://github.com/microsoft/vscode/blob/master/src/vs/editor/common/services/modelServiceImpl.ts#L290) the [incorrect default 'EOL`](https://github.com/microsoft/vscode/blob/master/src/vs/editor/standalone/browser/simpleServices.ts#L546) is used and this mismatch causes the files to get created (as if the file had changed).

**Comment by marechal-p** [comment]
I think I get a general sense of the issue thanks to your explanation.

I don't like this lock (deferred) to be exposed and waiting for some other component to release. It works, but I was looking for a different way to address the issue:

Is it possible to move the code on which the `MonacoTextModelService` depends upon into its own `postConstruct` method?

**Comment by federicobozzini** [comment]
@marechal-p I agree with you. I've changed the code to move the `EOL` overriding to the `MonacoTextModelService` as you suggest.

**Review by marechal-p — COMMENTED** [review]
LGTM.

@akosyakov you have more experience with the monaco integration, are we missing anything?

File: packages/monaco/src/browser/monaco-text-model-service.ts [hunk 1]
```diff
@@ -62,6 +63,34 @@ export class MonacoTextModelService implements monaco.editor.ITextModelService {
...
 
+    @inject(ApplicationServer)
+    protected readonly applicationServer!: ApplicationServer;
+
+    @postConstruct()
+    public init(): void {
+        let isWindowsBackend = false;
+
+        this.applicationServer.getBackendOS().then(os => {
+            isWindowsBackend = os === OS.Type.Windows;
```
Comment (marechal-p) [inline packages/monaco/src/browser/monaco-text-model-service.ts:74]: Is `false` a good default or is it better to use the same mechanism you did with the deferred value on the last iteration of your changes? This time the deferred would stay protected and only used within this class, and it would make sure that we use the right value for the given backend?

File: packages/monaco/src/browser/monaco-editor-provider.ts [hunk 2]
```diff
@@ -90,28 +87,11 @@ export class MonacoEditorProvider {
         @inject(EditorPreferences) protected readonly editorPreferences: EditorPreferences,
         @inject(MonacoQuickOpenService) protected readonly quickOpenService: MonacoQuickOpenService,
         @inject(MonacoDiffNavigatorFactory) protected readonly diffNavigatorFactory: MonacoDiffNavigatorFactory,
-        @inject(ApplicationServer) protected readonly applicationServer: ApplicationServer,
```
Comment (marechal-p) [inline packages/monaco/src/browser/monaco-editor-provider.ts:93]: We usually don't change constructor signatures, even when something is unused. Maybe mark the field as deprecated? `/** @deprecated since 1.6.0 */`

**Review by marechal-p — COMMENTED** [review]
Took a second look and had a few remarks.

File: packages/monaco/src/browser/monaco-text-model-service.ts (hunk 1 above)
Comment (marechal-p) [reply packages/monaco/src/browser/monaco-text-model-service.ts:81]: @federicobozzini I just pushed what I suggested to your branch 👍

**Review by marechal-p — APPROVED** [review]
LGTM, thanks for the fix!

File: packages/monaco/src/browser/monaco-text-model-service.ts (hunk 1 above)
Comment (federicobozzini) [reply packages/monaco/src/browser/monaco-text-model-service.ts:81]: @marechal-p  Sorry for the late reply. I did some investigation about adding a deferred barrier to the object initialization, but what I've noticed is that with that a long `configure` step might create some issues with the Theia plugins initialization. It's something that I was still investigating so it might be unrelated to this change.

Comment (marechal-p) [reply packages/monaco/src/browser/monaco-text-model-service.ts:81]: I'll wait for your feedback then, thank you for the info!

**Comment by marechal-p** [comment]
Please squash your commits, we can merge multi-commit PRs but the history has to stay clean from merge commits :)

**Comment by federicobozzini** [comment]
@marechal-p It should now be ready.
