### PR TITLE
12570 Localized quick file open labels

### LINKED ISSUE #12570: Quick file open labels are not localized
### Steps to Reproduce:

1. Press "Ctrl + P" , find some file, open it
2. Press "Ctrl + P" again and you see label "recently opened"
3. This label is not localized
4. The same situation with label "file results"

https://github.com/eclipse-theia/theia/blob/c1a2b7b021cb67db4cc05a57cd3561bcba023ab9/packages/file-search/src/browser/quick-file-open.ts#L171

https://github.com/eclipse-theia/theia/blob/c1a2b7b021cb67db4cc05a57cd3561bcba023ab9/packages/file-search/src/browser/quick-file-open.ts#L201

### Additional Information

- Operating System: Any
- Theia Version: Latest

### PR DESCRIPTION
**Pull request by Zebsterpasha**
#### What it does

Fixes #12570 
Localized labels "recently opened" "file results"

#### How to test

Just check the keys of licalized strings

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/file-search/src/browser/quick-file-open.ts [hunk 1]
```diff
@@ -168,7 +168,10 @@ export class QuickFileOpenService implements QuickAccessProvider {
 
             if (location.uri.scheme === 'file' && !alreadyCollected.has(uriString) && fuzzy.test(fileFilter, uriString)) {
                 if (recentlyUsedItems.length === 0) {
-                    recentlyUsedItems.push({ type: 'separator', label: 'recently opened' });
+                    recentlyUsedItems.push({
+                        type: 'separator',
+                        label: nls.localizeByDefault('recently opened')
+                    });
```
Comment (vince-fugnitto) [inline packages/file-search/src/browser/quick-file-open.ts:174]: minor: splitting the lines are unnecessary
```suggestion
                    recentlyUsedItems.push({ type: 'separator', label: nls.localizeByDefault('recently opened') });
```

The same is true below.

**Review by vince-fugnitto — APPROVED** [review]
LGTM, I confirmed it is properly localized.
