### PR TITLE
Ensure 'All Files' key present in File Dialog Filters

### LINKED ISSUE #8072: `All Files` filter option throws error
### Bug Description:

When a file dialog is open that includes a filter field, selecting `All Files` will throw an error in the console.

### Steps to Reproduce:

1. Start Theia on `master` in a browser.
1. Select File menu -> Open Workspace
2. At the bottom of the file picker, select one of the filter options
3. Then select the `All Files` filter option
4. Observe that an error about `.slice` of `undefined` is thrown.

I'll create a PR to fix this in a moment.

### Additional Information

- Operating System: REL7
- Theia Version: Current master

### PR DESCRIPTION
**Pull request by colin-grant-work**
Signed-off-by: Colin Grant <colin.grant@ericsson.com>

#### What it does

Fixes #8072 by ensuring that a properly formatted 'All Files' key will be present in the filter object. Formerly, 'All Files' was added to an array containing the keys of the filter object, but there was no guarantee that the filter object itself would have an entry corresponding to that value.

#### How to test

1. Build with this code and start Theia in a browser
1. Open the File menu -> Open Workspace file dialog.
1. At the bottom of the file dialog, select various filter options.
1. Observe that none of them throw an error.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/filesystem/src/browser/file-dialog/file-dialog-tree-filters-renderer.tsx [hunk 1]
```diff
@@ -50,12 +53,7 @@ export class FileDialogTreeFiltersRenderer extends ReactRenderer {
             return undefined;
         }
 
-        const fileTypes = ['All Files'];
```
Comment (colin-grant-work) [inline packages/filesystem/src/browser/file-dialog/file-dialog-tree-filters-renderer.tsx:53]: This starting point - adding 'All Files' to an array that otherwise contains only keys from the `filters` object - causes the error, since a later lookup of `this.filters['All Files']` will fail unless the creator of the dialog happens to have supplied that field.

**Comment by vince-fugnitto** [comment]
> @colin-grant-work just a few general comments:

I don't think the 2nd comment is necessarily part of this pull-request, the bug exists in `master`, we should not show `all files` for open workspace. I'll open a bug for it.

**Comment by colin-grant-work** [comment]
@vince-fugnitto, do you think it's a problem in general to include a default 'All Files' option? If you think that it shouldn't be included by default in any filtered file dialog, it can easily be removed as part of this PR - it makes it even simpler :) - but if you think it should be included in some file dialogues but not that particular one, then it's a bit more complicated.

**Comment by colin-grant-work** [comment]
> @colin-grant-work just a few general comments:
> 
> 1. I was unable to reproduce the issue on `master` with the steps provided, is there something I might be missing (I used `open workspace`).
> 2. I think that including `all files` is a bug we currently have, for example for `open workspace` only the two other filters should be applied, we cannot open any arbitrary file (all file) as a workspace anyways

Re: reproduction, it may only occur in the browser. Electron seems to use the native file dialogues at least some of the time, and I don't see the error in that case, but I see it consistently in the browser, which uses the Theia renderer.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto, do you think it's a problem in general to include a default 'All Files' option? If you think that it shouldn't be included by default in any filtered file dialog, it can easily be removed as part of this PR - it makes it even simpler :) - but if you think it should be included in some file dialogues but not that particular one, then it's a bit more complicated.

I think the best thing would be to update the `props` to be able to include control the behavior since it's likely that only the `open workspace` and `save workspace as` dialog will need to be updated (so the prop can be on by default).

**Comment by colin-grant-work** [comment]
It seems to me almost all file dialogues have an 'All Files' option, even when you almost certainly have a specific subset of files in mind - certainly in Windows, there's almost always an 'All Files' option. To me, that suggests that it may not be worth much to add a separate configuration prop to enable or disable it. With the object spread in this PR, for example, application developers can customize the position of the 'All Files' by including it in the filter object they pass in, allowing them to control what the default filter is by simply having it as the first key of the filter object.

**Comment by colin-grant-work** [comment]
@vince-fugnitto, yes, it seems like changing that behavior of the file dialogue would go beyond just fixing the present error. Let me know if you're still unable to reproduce the error on `master` even in the browser.

File: packages/filesystem/src/browser/file-dialog/file-dialog-tree-filters-renderer.tsx [hunk 2]
```diff
@@ -36,11 +36,14 @@ export class FileDialogTreeFilters {
 
 export class FileDialogTreeFiltersRenderer extends ReactRenderer {
 
+    readonly filters: FileDialogTreeFilters;
+
     constructor(
-        readonly filters: FileDialogTreeFilters,
```
Comment (vince-fugnitto) [inline packages/filesystem/src/browser/file-dialog/file-dialog-tree-filters-renderer.tsx:40]: I think we can keep the readonly and update it to:

```ts
protected readonly filters: FileDialogTreeFilters;

constructor(
  readonly _filters: FileDialogTreeFilters,
  readonly fileDialogTree: FileDialogTree
) {
  super();
  this.filters = { 'All Files': [], ..._filters, };
}
```

Comment (colin-grant-work) [reply packages/filesystem/src/browser/file-dialog/file-dialog-tree-filters-renderer.tsx:40]: @vince-fugnitto, 👍 I like the idea of keeping both around, since it may aid with future customization. I have pushed a change that distinguishes between `suppliedFilters` and `appliedFilters`.

**Comment by vince-fugnitto** [comment]
I'll merge tomorrow if there no objections :)
