### PR TITLE
handles invalid task configurations

### LINKED ISSUE #6482: task config parsing errors are not handled properly
### Description

In the current version of Theia, the invalid task configs from `tasks.json`, although not successfully parsed, are still added to the list of tasks.
  
Theia should handle those errors properly.

### Reproduction Steps

Peek 2019-11-01 23-09

- add an invalid task config to `tasks.json` - it could be as simple as an empty object `{ }`
- pull out the task list from the top menu bar "Terminal" -> "Run Task"

Expected: the invalid task should be hidden from the user
What happened: `undefined: undefined` shows up in the list of tasks

**OS and Theia version:**

Ubuntu 18.04. Example browser
Version 05f2e07bb77637723e6720231342b9acce01a159

### PR DESCRIPTION
**Pull request by elaihau**
- not display the invalid task configurations in the list of tasks.
- displays a warning message to inform users if Theia finds invalid task
configuration(s) in tasks.json.
- fixes #6482

Signed-off-by: Liang Huang <liang.huang@ericsson.com>

#### How to test

As the GIF shows,

- enter an invalid task configuration into tasks.json. 
  FYI, it would be helpful to keep the Problem View open, as it would display the schema errors Theia finds from task configuration. With the information from the Problems View, we know if we are truely entering an invalid config.

- Open the list of tasks from the top menu bar "Termimal -> Run Tasks"
  At this point of time, the list of tasks should NOT have the task config that was entered most recently, because it's invalid. Also, there should be a warning populated that reminds us to open the Problems view to get what the errors are.

- Go back to tasks.json and fix the invalid configuration
  After the config is fixed, it should show up as one item in the list of tasks.

Peek 2019-11-07 22-56

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

### CODE REVIEW

**Comment by akosyakov** [comment]
What VS Code does? Usually it is more tolerant and will ignore unnecessary or bogus properties. Please check.

**Comment by elaihau** [comment]
> What VS Code does? Usually it is more tolerant and will ignore unnecessary or bogus properties. Please check.

vs code does something similar ...
The part I am missing in this PR is "directing the validation errors into the Output View", and I am trying to improve it in that aspect.

Peek 2019-11-08 07-04

**Comment by lmcbout** [comment]
I think it is a good start to show a dialog with some info, but it goes away. I find what VSCode do is better by having the dialog, but also with a button to open the "Output" view with more details about the invalid task. If the end-user doesn't have the "problem " view open in Theia, it is harder to see the reason why the task is not showing in he quick-open menu.  The "Problem" view is not always visible when you modify the task.json file.

**Comment by elaihau** [comment]
> If the end-user doesn't have the "problem " view open in Theia, it is harder to see the reason why the task is not showing in he quick-open menu. The "Problem" view is not always visible when you modify the task.json file.

Thank you for the feedback ! @lmcbout 
Would it be good to add an action button to the dialog, once users click it we 
1) Open tasks.json, and 
2) Open the Problems View (if they are not opened) ?

**Comment by lmcbout** [comment]
Would be nice to open task.json and the problem view, but we also need to point to the faulty task (at least for the first faulty task) if there are more than one.
I think we should open all "tasks.json" having faulty tasks. It is a personnel choice here :)

**Comment by lmcbout** [comment]
What about opening the output view with all the faulty tasks if there are more than one and open the tasks.json with the first error in it with the problem view ?

**Comment by vince-fugnitto** [comment]
> I think it is a good start to show a dialog with some info, but it goes away. I find what VSCode do is better by having the dialog, but also with a button to open the "Output" view with more details about the invalid task. If the end-user doesn't have the "problem " view open in Theia, it is harder to see the reason why the task is not showing in he quick-open menu. The "Problem" view is not always visible when you modify the task.json file.

If the `problems-view` is closed, there are still multiple indications that the task has errors.
1. the statusbar contribution shows the number of markers.
2. the editor itself has the marker where the incorrect task(s) are.
3. the editor itself has a decoration on the right-hand side for the marker.
4. the task does not display in the `run task` menu, which tells users something may be wrong.

I'm not sure we need to over-engineer the solution, I think properly handling invalid task configs like @elaihau has been doing is great. If you'd like @lmcbout because you find it hard to distinguish when invalid tasks are present, using a notifications message which states there may be invalid tasks might be helpful.

**Comment by elaihau** [comment]
> What about opening the output view with all the faulty tasks if there are more than one and open the tasks.json with the first error in it with the problem view ?

hmm, i can work on the part that opens the `tasks.json` what has the 1st invalid task, and the Problems View. 

Once that's implemented I can upload a GIF to demo what it looks like, and we could discuss if opening the Output View makes the solution more user friendly. 
My only concern is: If both Problems view and Output view are open, which view should stay on top of the other?

**Comment by vince-fugnitto** [comment]
> > What about opening the output view with all the faulty tasks if there are more than one and open the tasks.json with the first error in it with the problem view ?
> 
> hmm, i can work on the part that opens the `tasks.json` that has the 1st invalid task, and the Problems View.
> 
> Once that's implemented I can upload a GIF to demo what it looks like, and we could discuss if opening the Output View makes the solution more user friendly.
> My only concern is: If both Problems view and Output view are open, which view should stay on top of the other?

@elaihau I don't think it needs to be overcomplicated for the moment. Informing users that they may have one or more task configs which are invalid due to missing properties is sufficient. An end user knows where the `tasks.json` is and how to display the `problems-view` if required.

**Comment by vince-fugnitto** [comment]
In the future we can have a new channel for the `output-view` to display task errors and prompt users to open the `output-view` when tasks have errors, but I don't believe it necessarily needs to be addressed in this PR. For most cases, the current implementation you have is sufficient while anything more would be an enhancement.

File: packages/task/src/browser/task-service.ts [hunk 1]
```diff
@@ -233,9 +234,26 @@ export class TaskService implements TaskConfigurationClient {
...
+
+    /**
+     * Returns `true` if the given task configuration is valid as per the task schema defined in Theia
+     * or contributed by Theia extensions and plugins, `false` otherwise.
+     */
+    isTaskConfigValid(task: TaskConfiguration): boolean {
+        const schema = this.taskSchemaUpdater.getTaskSchema();
+        const ajv = new Ajv();
+        const validateSchema = ajv.compile(schema);
+        const isValid = !!validateSchema({ tasks: [task] });
```
Comment (vince-fugnitto) [inline packages/task/src/browser/task-service.ts]: [minor] I believe we can simply
```ts
return !!validateSchema({ tasks: [task] });
```

**Comment by elaihau** [comment]
@lmcbout 
I made a change as per our discussion earlier today: the `tasks.json` and problems view are opened by clicking the action button in the message dialog. 

if the `tasks.json` and problems view are both already open, the action button is not displayed.

Peek 2019-11-11 22-26

File: packages/task/src/browser/task-service.ts (hunk 1 above)
Comment (elaihau) [reply packages/task/src/browser/task-service.ts]: resolved. Thank you for your review !

**Comment by elaihau** [comment]
> btw: should we remove warning for `version` property?

Yes you are right. I will update the schema. Thank you for the review !
