### PR TITLE
terminal: Windows .exe compatibility for VSCode

### LINKED ISSUE #12734: Terminal profile contribution from VS Code extension throws exception if vscode.TerminalOptions.shellPath lacks ".exe" extension on Windows
### Bug Description:
I'm trying to contribute a terminal profile from a VS Code extension. If in the provider I fail to specify the ".exe" executable in `vscode.TerminalOptions.shellPath`, a "File not found" exception is thrown. In VS Code, it works fine without specifying the extension.

```
2023-07-19T22:04:58.500Z terminal ERROR Error: File not found: 
    at WindowsPtyAgent (C:\j.cortell\git\theiasandbox\node_modules\node-pty\src\windowsPtyAgent.ts:103:49)
    at WindowsTerminal (C:\j.cortell\git\theiasandbox\node_modules\node-pty\src\windowsTerminal.ts:51:19)
    at spawn (C:\j.cortell\git\theiasandbox\node_modules\node-pty\src\index.ts:30:10)
    at TerminalProcess (C:\j.cortell\git\theiasandbox\node_modules\@theia\process\src\node\terminal-process.ts:83:34)
    at ShellProcess (C:\j.cortell\git\theiasandbox\node_modules\@theia\terminal\src\node\shell-process.ts:64:9)
    at createInstanceWithInjections (C:\j.cortell\git\theiasandbox\node_modules\inversify\src\resolution\instantiation.ts:67:17)
    at _createInstance (C:\j.cortell\git\theiasandbox\node_modules\inversify\src\resolution\instantiation.ts:55:16)
    at resolveInstance (C:\j.cortell\git\theiasandbox\node_modules\inversify\src\resolution\instantiation.ts:145:18)
    at _getResolvedFromBinding (C:\j.cortell\git\theiasandbox\node_modules\inversify\src\resolution\resolver.ts:77:31)
    at <anonymous> (C:\j.cortell\git\theiasandbox\node_modules\inversify\src\resolution\resolver.ts:111:18)
```

Note that working around this bug by specifying the extension unfortunately leads you into the more general bug that opening a terminal in Theia hangs the app: https://github.com/eclipse-theia/theia/issues/12733

### Additional Information

- Operating System: Windows
- Theia Version: 1.39

### PR DESCRIPTION
**Pull request by cdamus**
#### What it does

On Windows platform, support implicit file '.exe' extension on the shell command in terminal profiles as in VS Code.

VS Code allows a terminal profile to omit the `'.exe'` extension of the executable file and will find and run it anyways. So this PR enhances the `TerminalProcess` initialization, in the case that the program launch fails by reason of not being found and the host platform is Windows and the command did not end with `'.exe'`, to try again with `'.exe'` appended to the program.

Fixes #12734

#### How to test

Per the description of #12734:

1. Clone the OP's referenced sample repository
2. Check out the `terminal` branch. This provides a `myext` VS Code extension that you can link into your `plugins/` directory to obtain a "Profile from my extension" terminal profile. This is configured simply with `'cmd'` as the command to run, not `'cmd.exe'`.
3. Launch Theia and start a new terminal using the "Profile from my extension" profile in the Terminal menu.
4. See that the terminal starts (you may observe other unrelated issues as described in other bugs filed by the OP).

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by cdamus** [comment]
Yeah, I can see why the test failed and what I did wrong. Easy to fix.

**Comment by cdamus** [comment]
Commit e0e2b2e84392dfe4ea19a550f9e0e86a02fe7675 fixes the problem that broke the test and adds a new test case for this PR's Windows-specific behaviour.

File: packages/process/src/node/terminal-process.ts [hunk 1]
```diff
@@ -79,72 +79,100 @@ export class TerminalProcess extends Process {
...
+            } catch (error) {
+                // Normalize the error to make it as close as possible as what
+                // node's child_process.spawn would generate in the same
+                // situation.
+                const message: string = error.message;
+
+                if (message.startsWith('File not found: ') || message.endsWith(NodePtyErrors.ENOENT)) {
+                    if (isWindows && command && !command.toLowerCase().endsWith('.exe')) {
+                        const commandExe = command + '.exe';
+                        this.logger.warn(`Trying terminal command '${commandExe}' because '${command}' was not found.`);
```
Comment (jfaltermeier) [inline packages/process/src/node/terminal-process.ts:94]: I don't have a strong opinion here, but imo this could be an info message as well. 
I guess it depends on whether we see this more as a feature or more as a fallback for a misconfiguration

**Review by jfaltermeier — APPROVED** [review]
LGTM. I've tested with the instructions from the ticket. 
Besides the refactoring with the introduction of the `createPseudoTerminal` method, the only code change is the addition of the `if (isWindows && command && !command.toLowerCase().endsWith('.exe'))` clause, which looks good to me.

File: packages/process/src/node/terminal-process.ts (hunk 1 above)
Comment (cdamus) [reply packages/process/src/node/terminal-process.ts:94]: Actually, that's a good point. I might rather lean to `'debug'` as this is supposed to be unsurprising and totally supported behaviour, but should still be recorded in case some flow doesn't happen as expect. For example, in the — decidedly inadvisable — case where a `.exe` file exists but the developer doesn't want it to be used in the case that the unsuffixed file doesn't exist?

Comment (cdamus) [reply packages/process/src/node/terminal-process.ts]: Changed in commit b5d02c6fba7400b3ee358601891d713af8225569 to debug level.

**Comment by cdamus** [comment]
I should mention also that this PR fixes deprecation warnings in the listener API usage of the `IPty` terminal object. Good opportunity while the file was being changed anyways and the terminal set-up factored out into a helper method.
