### PR TITLE
fix: various debug fixes and VS Code compatibility enhancements

### LINKED ISSUE #11871: vscode: add support for `debug/toolbar`, `debug/variables/context` menus contribution and `debugState` `when` clause context
### Feature Description:

Add support for the following in Theia to improve the VS Code compatibility:
 - [`debug/toolbar`](https://code.visualstudio.com/api/references/contribution-points#contributes.menus), (See https://github.com/eclipse-theia/theia/issues/9389)
 - [`debug/variables/context`](https://code.visualstudio.com/api/references/contribution-points#contributes.menus), and
 - [`debugState`](https://code.visualstudio.com/api/references/when-clause-contexts) `when` context.

----

Steps to reproduce:
 - Check out the [`vscode-mock-debug--theia`](https://github.com/kittaakos/theia/tree/vscode-mock-debug--theia) branch in my fork,
 - Build and start Theia from the sources (make sure to run `yarn download:plugins` to make the mock debugger VS Code extension available before Theia start),
 - Open the `sampleWorkspace` folder from [Microsoft/vscode-mock-debug](https://github.com/Microsoft/vscode-mock-debug) repo as a workspace in Theia,
 - Open the _Debug_ view and start `Debug readme.md`,

Screen Shot 2022-11-16 at 17 05 57

```
2022-11-16T15:08:02.683Z root WARN Failed to register a menu item for plugin kittaakos.mock-debug contributed to debug/toolBar {
  command: 'extension.mock-debug.sayHello',
  submenu: undefined,
  alt: undefined,
  group: 'navigation',
  when: "debugType == 'mock'"
} Error: Could not find submenu with id debug/toolBar
    at MenuModelRegistry.getMenuNode (file:///Users/a.kitta/dev/git/theia/examples/electron/lib/bundle.js:137499:23)
    at file:///Users/a.kitta/dev/git/theia/examples/electron/lib/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:6634:66
    at Array.forEach (<anonymous>)
    at MenusContributionPointHandler.handle (file:///Users/a.kitta/dev/git/theia/examples/electron/lib/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:6628:37)
    at file:///Users/a.kitta/dev/git/theia/examples/electron/lib/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:7350:71
    at pushContribution (file:///Users/a.kitta/dev/git/theia/examples/electron/lib/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:7245:32)
    at PluginContributionHandler.handleContributions (file:///Users/a.kitta/dev/git/theia/examples/electron/lib/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:7350:9)
    at HostedPluginSupport.loadContributions (file:///Users/a.kitta/dev/git/theia/examples/electron/lib/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:446:61)
    at HostedPluginSupport.doLoad (file:///Users/a.kitta/dev/git/theia/examples/electron/lib/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:358:42)
    at async ProgressService.withProgress (file:///Users/a.kitta/dev/git/theia/examples/electron/lib/bundle.js:140547:20)
```

```
2022-11-16T15:08:02.681Z root WARN Failed to register a menu item for plugin kittaakos.mock-debug contributed to debug/variables/context {
  command: 'extension.mock-debug.sayVariableContextMenu',
  submenu: undefined,
  alt: undefined,
  group: 'navigation',
  when: "inDebugMode && debugType == 'mock' && debugState == stopped"
} Error: Could not find submenu with id debug/variables/context
    at MenuModelRegistry.getMenuNode (file:///Users/a.kitta/dev/git/theia/examples/electron/lib/bundle.js:137499:23)
    at file:///Users/a.kitta/dev/git/theia/examples/electron/lib/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:6634:66
    at Array.forEach (<anonymous>)
    at MenusContributionPointHandler.handle (file:///Users/a.kitta/dev/git/theia/examples/electron/lib/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:6628:37)
    at file:///Users/a.kitta/dev/git/theia/examples/electron/lib/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:7350:71
    at pushContribution (file:///Users/a.kitta/dev/git/theia/examples/electron/lib/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:7245:32)
    at PluginContributionHandler.handleContributions (file:///Users/a.kitta/dev/git/theia/examples/electron/lib/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:7350:9)
    at HostedPluginSupport.loadContributions (file:///Users/a.kitta/dev/git/theia/examples/electron/lib/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:446:61)
    at HostedPluginSupport.doLoad (file:///Users/a.kitta/dev/git/theia/examples/electron/lib/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:358:42)
    at async ProgressService.withProgress (file:///Users/a.kitta/dev/git/theia/examples/electron/lib/bundle.js:140547:20)
```

----

Missing features:

1. The custom command is missing from the debug toolbar (`debug/toolbar`).
    Screen Shot 2022-11-16 at 17 51 09

    Screen Shot 2022-11-16 at 17 04 53

2. The context menu is unavailable for the _Variables_ view (`debug/variables/context`).
    Screen Shot 2022-11-16 at 15 05 53
    Screen Shot 2022-11-16 at 17 06 22

3. The `debugState` when context is `undefined`. It should be one of the following: `'inactive'`, `'initializing'`, `'stopped'`, `'running'`. To verify this, I have written a [sample command](https://github.com/eclipse-theia/theia/compare/master...kittaakos:theia:vscode-mock-debug--theia) to show the `when` context value for a key.
    - `inDebugMode` is supported, ✅ 
    - `debugType` is supported, ✅ 
    - `debugState` is `undefined`. ❌ 
        Screen Shot 2022-11-16 at 17 00 14
        Screen Shot 2022-11-16 at 17 00 25
        Screen Shot 2022-11-16 at 17 00 46

### LINKED ISSUE #11879: [debug]: Cannot stop debug session of `vscode-mock-debug`
### Bug Description:

It's impossible to terminate the debug session in Theia. It works very well from Code.

### Steps to Reproduce:

1. Start the [Microsoft/vscode-mock-debug](https://github.com/Microsoft/vscode-mock-debug) debugger in Theia.
2. Stop the debug session.
3. It cannot terminate and will timeout after 5 sec

```
2022-11-18T11:59:05.246Z root ERROR Error on disconnect
```

```
{
    "type": "response",
    "seq": 0,
    "request_seq": 12,
    "success": false,
    "command": "disconnect",
    "message": "Request #12: disconnect timed out"
}
```

----
If you do not want to build the `vscode-mock-debug` extension on your own, you can use the VS Code extension mock debugger from https://github.com/eclipse-theia/theia/issues/11871

### Additional Information

- Operating System: macOS, 12.5.1
- Theia Version: fe8e4c1

### LINKED ISSUE #11880: [debug] Error: Illegal value for lineNumber when `"stopOnEntry": true` in the `launch.json`
### Bug Description:

When `stopOnEntry` is set to `true` in the `launch.json` config, Theia throws an error when starting the debugger, as it cannot correctly map the column number extracted from the raw`DebugProtol.StackFrame`. Debug stack frame tries to open the following location:

```json
{
    "start": {
        "line": 0,
        "character": -1
    }
}
```

```
textModel.ts:832 Uncaught (in promise) Error: Illegal value for lineNumber
    at TextModel.getLineMaxColumn (textModel.ts:832)
    at MonacoEditorModel.getLineMaxColumn (monaco-editor-model.ts:293)
    at EditorPreviewManager.getSelection (editor-manager.ts:260)
    at EditorPreviewManager.revealSelection (editor-manager.ts:242)
    at EditorPreviewManager.tryGetPendingWidget (editor-manager.ts:99)
    at EditorPreviewManager.tryGetPendingWidget (editor-preview-manager.ts:102)
    at EditorPreviewManager.getOrCreateWidget (editor-preview-manager.ts:110)
    at EditorPreviewManager.open (widget-open-handler.ts:89)
    at EditorPreviewManager.open (editor-manager.ts:203)
    at DebugSource.open (debug-source.ts:48)
```

### Steps to Reproduce:

1. Start the [Microsoft/vscode-mock-debug](https://github.com/Microsoft/vscode-mock-debug) debugger in Theia.
2. It throws an error.

If you do not want to build the `vscode-mock-debug` extension on your own, you can use the VS Code extension mock debugger from https://github.com/eclipse-theia/theia/issues/11871. Please make sure to open the `sampleWorkspace` from the https://github.com/Microsoft/vscode-mock-debug repo.

### Additional Information

- Operating System: macOS, 12.5.1
- Theia Version: fe8e4c1

### LINKED ISSUE #11885: [debug] Theia does not stop on breakpoints with the debugger provided by the `vscode.mock-debug` extension
### Steps to Reproduce:

1. Build the `vscode.mock-debug` extension from [their repo](https://github.com/Microsoft/vscode-mock-debug). Alternatively, you can follow the steps from https://github.com/eclipse-theia/theia/issues/11871 and get the `mock-debug` VS Code extension from my fork.
2. Open the `sampleWorkspace` folder from the repo as a workspace in Theia.
3. Set a breakpoint to line 11,
4. Start the `Debug readme.md` file,
5. Debugger stops on entry,
6. `Continue`,
7. Debugger does *not* stop on line 11, instead it falls to the end of the readme. 

VS Code:

https://user-images.githubusercontent.com/1405703/202741131-e6d4516d-6d22-4b7e-940a-e45a53bae94d.mp4

Theia:

https://user-images.githubusercontent.com/1405703/202741053-f364a646-db8b-4971-8a8c-61315e32654f.mp4

When the debugger session starts in Theia, I see the following error in the logs. I do not know if it's related to this bug:

```
logger-protocol.ts:113 2022-11-18T15:27:58.287Z root ERROR Error setting breakpoints: Cannot read properties of undefined (reading 'breakpoints')
log @ logger-protocol.ts:113
(anonymous) @ logger-frontend-module.ts:42
(anonymous) @ logger.ts:312
(anonymous) @ logger.ts:304
Promise.then (async)
log @ logger.ts:299
log @ logger.ts:45
sendFunctionBreakpoints @ debug-session.tsx:683
async function (async)
sendFunctionBreakpoints @ debug-session.tsx:671
updateBreakpoints @ debug-session.tsx:645
async function (async)
updateBreakpoints @ debug-session.tsx:649
configure @ debug-session.tsx:325
(anonymous) @ debug-session.tsx:121
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
doFire @ debug-session-connection.ts:331
handleEvent @ debug-session-connection.ts:312
handleMessage @ debug-session-connection.ts:265
(anonymous) @ debug-session-connection.ts:171
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
fireMessageReceived @ connection.ts:37
$sendMessage @ connection.ts:82
doInvokeHandler @ rpc-protocol.ts:287
invokeHandler @ rpc-protocol.ts:272
receiveRequest @ rpc-protocol.ts:231
receiveOneMessage @ rpc-protocol.ts:192
(anonymous) @ rpc-protocol.ts:101
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
(anonymous) @ rpc-protocol.ts:343
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
(anonymous) @ hosted-plugin.ts:540
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
postMessage @ hosted-plugin-watcher.ts:35
onRequest @ proxy-factory.ts:167
(anonymous) @ proxy-factory.ts:146
handleRequest @ rpc-protocol.ts:188
handleMessage @ rpc-protocol.ts:86
(anonymous) @ rpc-protocol.ts:75
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
handleData @ channel.ts:239
handleMessage @ channel.ts:197
(anonymous) @ channel.ts:155
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
(anonymous) @ web-socket-channel.ts:38
(anonymous) @ ws-connection-provider.ts:84
Emitter.emit @ index.mjs:136
emitEvent @ socket.js:385
onevent @ socket.js:372
onpacket @ socket.js:340
Emitter.emit @ index.mjs:136
(anonymous) @ manager.js:240
Promise.then (async)
(anonymous) @ websocket-constructor.browser.js:8
ondecoded @ manager.js:239
Emitter.emit @ index.mjs:136
add @ index.js:148
ondata @ manager.js:226
Emitter.emit @ index.mjs:136
onPacket @ socket.js:348
Emitter.emit @ index.mjs:136
onPacket @ transport.js:114
onData @ transport.js:106
ws.onmessage @ websocket.js:87
Show 33 more frames
```

### Additional Information

- Operating System: macOS, 12.5.1
- Theia Version: fe8e4c1

### LINKED ISSUE #11886: [debug]: Debug session might be configured with an empty capabilities object
### Bug Description:

There could be a race condition when starting a debug session. I can consistently reproduce the issue with the debugger from the [vscode.mock-debug](https://github.com/Microsoft/vscode-mock-debug) VS Code extension. You can also use this: https://github.com/kittaakos/vscode-mock-debug/raw/theia/mock-debug-0.51.0.vsix

Problem:

1. Capabilities is initialized as an empty object:
https://github.com/eclipse-theia/theia/blob/fe8e4c1276854baad22a2ffcde6acfb1e8e50926/packages/debug/src/browser/debug-session.tsx#L130-L133

2. Theia sends the `'initialize'` request here to get the debugger capabilities:
https://github.com/eclipse-theia/theia/blob/fe8e4c1276854baad22a2ffcde6acfb1e8e50926/packages/debug/src/browser/debug-session.tsx#L275

3. But the `initialized` event is received before the `sendRequest('initialize')` resolves:
https://github.com/eclipse-theia/theia/blob/fe8e4c1276854baad22a2ffcde6acfb1e8e50926/packages/debug/src/browser/debug-session.tsx#L112

4. Theia starts the debug session configuration (e.g., exception breakpoint filters) with the empty, uninitialized capabilities object:
https://github.com/eclipse-theia/theia/blob/fe8e4c1276854baad22a2ffcde6acfb1e8e50926/packages/debug/src/browser/debug-session.tsx#L307-L318

5. Once the debug session is configured, the capabilities are set:
https://github.com/eclipse-theia/theia/blob/fe8e4c1276854baad22a2ffcde6acfb1e8e50926/packages/debug/src/browser/debug-session.tsx#L287

I can confirm I cannot reproduce the same with the Node.js debugger in Theia (from the sources).

### Additional Information

- Operating System: macOS 12.5.1
- Theia Version: fe8e4c1

### LINKED ISSUE #11916: [debug] debug-ext prematurely fires `didStart` event on `didCreate`
### Bug Description:

As the title says, the debug-ext will incorrectly fire the `didStart` event,  on `didCreate` and will call the debug adapter. It's too early.

https://github.com/eclipse-theia/theia/blob/b58de21ca1a9371ffe8779919a174e85781cfe5a/packages/plugin-ext/src/plugin/debug/debug-ext.ts#L248-L253

Some debug adapters will run custom DAP requests on session start, such as the [`cortex-debug`](https://marketplace.visualstudio.com/items?itemName=marus25.cortex-debug) extension [here](https://github.com/Marus/cortex-debug/blob/c48d323d53e7cd08c51a9f1dc91c5788eae2e24c/src/frontend/extension.ts#L638-L644), and will break, as the session has not been `initialized` yet.

```
2022-11-24T13:19:18.818Z root ERROR [hosted-plugin: 30330] /Users/a.kitta/dev/git/theia/plugins/cortex-debug/extension/dist/debugadapter.js:16423
            if (this.serverController.customRequest(command, response, args)) {
                                      ^

TypeError: Cannot read properties of undefined (reading 'customRequest')
    at GDBDebugSession.<anonymous> (/Users/a.kitta/dev/git/theia/plugins/cortex-debug/extension/dist/debugadapter.js:16423:39)
    at Generator.next (<anonymous>)
    at /Users/a.kitta/dev/git/theia/plugins/cortex-debug/extension/dist/debugadapter.js:15519:71
    at new Promise (<anonymous>)
    at __webpack_modules__../src/gdb.ts.__awaiter (/Users/a.kitta/dev/git/theia/plugins/cortex-debug/extension/dist/debugadapter.js:15515:12)
    at GDBDebugSession.customRequest (/Users/a.kitta/dev/git/theia/plugins/cortex-debug/extension/dist/debugadapter.js:16418:16)
    at GDBDebugSession.dispatchRequest (/Users/a.kitta/dev/git/theia/plugins/cortex-debug/extension/dist/debugadapter.js:515:22)
    at GDBDebugSession.dispatchRequest (/Users/a.kitta/dev/git/theia/plugins/cortex-debug/extension/dist/debugadapter.js:1183:15)
    at GDBDebugSession.handleMessage (/Users/a.kitta/dev/git/theia/plugins/cortex-debug/extension/dist/debugadapter.js:1364:18)
    at GDBDebugSession._handleData (/Users/a.kitta/dev/git/theia/plugins/cortex-debug/extension/dist/debugadapter.js:1458:34)
```

### Steps to Reproduce:

1. Get the 1.5.1 `cortex-debug` VSIX from my fork: https://github.com/kittaakos/cortex-debug/raw/1.5.1/marus25.cortex-debug-1.5.1-development.vsix
2. Configure the debug session based on the official documentation: https://github.com/Marus/cortex-debug#installation
3. Start the debug session

### Additional Information

- Operating System: macOS 12.5.1
- Theia Version: 1.31.1

### PR DESCRIPTION
**Pull request by kittaakos**
#### What it does

 - feat: added support for `debug/toolbar` and `debug/variables/context`,
 - feat: added support for `debugState` when context (https://github.com/eclipse-theia/theia/issues/11871),
 - feat: can customize debug session timeout, and error handling (https://github.com/eclipse-theia/theia/issues/11879),
 - fix: the `debugType` context that was not updated on session stop,
 - fix: `configure` must happen after receiving capabilities (https://github.com/eclipse-theia/theia/issues/11886),
 - fix: added missing conext menu in the _Variables_ view,
 - fix: handle `setFunctionBreakboints` response with no `body` (https://github.com/eclipse-theia/theia/issues/11885),
 - fix: `DebugExt` fires `didStart` event on `didCreate` (https://github.com/eclipse-theia/theia/issues/11916),
 - fix: validate editor selection based on the text model (https://github.com/eclipse-theia/theia/issues/11880)

Closes #11871
Closes #11879
Closes #11885
Closes #11886
Closes #11916
Closes #11880

#### How to test

 - Get the modified version of the `vscode.mock-debug` extension from my fork: https://github.com/kittaakos/vscode-mock-debug/blob/theia/mock-debug-0.51.0.vsix. Here is the diff with the changes from the upstream version: https://github.com/microsoft/vscode-mock-debug/compare/main...kittaakos:vscode-mock-debug:theia.
 - Open the [`./vscode-mock-debug/sampleWorkspace`](https://github.com/kittaakos/vscode-mock-debug/tree/theia/sampleWorkspace) folder as a workspace in Theia. There is a readme file in it and the `launch.json` in the `.vscode` folder.
 - Press <kbd>F5</kbd>, `readme.md` opens, and the top stack frame is the first line of the readme file. Check the `DevTools` console; there is no `Error: Illegal value for lineNumber`. ([#11880](https://github.com/eclipse-theia/theia/issues/11880))

https://user-images.githubusercontent.com/1405703/207561043-1194968d-5855-40a0-b257-e6d5cae56569.mp4

 - Set a breakpoint before any variable declarations (line 17) and after (line 28). You can use other lines too. Continue the debugger. It hits the breakpoint. ([#11885](https://github.com/eclipse-theia/theia/issues/11885)). You see no local variable. Continue the debugger. It hits the next breakpoint when there are variables. It's visible from the _Variables_ view. Right-click the variable, and you will see the `debugType` and `debugState` dependent content menu from the VSIX. Click on it. It works. You also see two additional debug toolbar items—one with the ❤️ `codicon` and the other with text. Click on them, and both work. ([#11871](https://github.com/eclipse-theia/theia/issues/11871))

https://user-images.githubusercontent.com/1405703/207563422-7a496e8b-521b-4246-ab06-1a2912f47b9a.mp4

#### For reviewers:

> * fix: `DebugExt` fires `didStart` event on `didCreate` ([[debug] debug-ext prematurely fires `didStart` event on `didCreate` #11916](https://github.com/eclipse-theia/theia/issues/11916)),

This 👆  requires a more complex setup and another VSIX (`marus25.cortex-debug-1.5.1.vsix` from https://downloads.arduino.cc/marus25.cortex-debug/marus25.cortex-debug-1.5.1.vsix). The fix cannot be verified with the `mock-debug` extension. Also, I used a physical board (Arduino Zero) where the code runs. The code runs on the device, and the debugger talks to it via dgb. I am happy to provide the steps to set up the toolchain, but the board is needed. Let me know it's required.

#### Review checklist

- [ ] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/debug/src/browser/view/debug-toolbar-widget.tsx [hunk 1]
```diff
@@ -77,6 +81,29 @@ export class DebugToolBar extends ReactWidget {
             {this.renderStart()}
         </React.Fragment>;
     }
+
+    protected renderContributedCommands(): React.ReactNode {
+        return this.menuModelRegistry
+            .getMenu(DebugToolBar.MENU)
+            .children.filter(node => node instanceof CompositeMenuNode)
```
Comment (colin-grant-work) [inline packages/debug/src/browser/view/debug-toolbar-widget.tsx:88]: Use `CompoundMenuNode.is` here rather than the `instanceof` check, and add a `when` clause check here, as well, since submenus can have their own `when` requirements.

File: packages/debug/src/browser/view/debug-toolbar-widget.tsx [hunk 2]
```diff
@@ -77,6 +81,29 @@ export class DebugToolBar extends ReactWidget {
...
+            .map(node => (node as CompositeMenuNode).children)
+            .reduce((acc, curr) => acc.concat(curr), [])
+            .filter(node => node instanceof ActionMenuNode)
```
Comment (colin-grant-work) [inline packages/debug/src/browser/view/debug-toolbar-widget.tsx:91]: Use `CommandMenuNode.is` rather than the `instanceof` check, and add the `when` clause check here rather than below in `debugAction`.

**Comment by kittaakos** [comment]
Hi, is there any update on this PR? Can somebody please help with the review? Thank you!

**Comment by kittaakos** [comment]
@marcdumais-work and @JonasHelming, could you please help move this PR forward? We at Arduino would like to get these fixes in Theia. Could you tell me the procedure for contacting other interested parties in the verification? Something like the community did here: https://github.com/eclipse-theia/theia/pull/10333. Thank you!

**Comment by vince-fugnitto** [comment]
> Press F5, readme.md opens, and the top stack frame is the first line of the readme file. Check the DevTools console; there is no Error: Illegal value for lineNumber. (https://github.com/eclipse-theia/theia/issues/11880)

In my case (Ubuntu) pressing <kbd>F5</kbd> will trigger the error in the devConsole, is it expected?

image

File: packages/debug/src/browser/debug-session.tsx [hunk 3]
```diff
@@ -274,19 +287,26 @@ export class DebugSession implements CompositeTreeElement {
...
-            pathFormat: 'path',
-            supportsVariableType: false,
-            supportsVariablePaging: false,
-            supportsRunInTerminalRequest: true
-        });
-        this.updateCapabilities(response?.body || {});
+        const clientName = FrontendApplicationConfigProvider.get().applicationName;
+        try {
+            const response = await this.connection.sendRequest('initialize', {
+                clientID: clientName.toLocaleLowerCase().replace(/\s+/g, '_'),
```
Comment (tsmaeder) [inline packages/debug/src/browser/debug-session.tsx:293]: Is there a technical reason to use the application name here or is this just branding? I feel the same _implementation_ should have the same client id, kind of like the `user-agent` of a browser.

File: packages/debug/src/browser/debug-session.tsx [hunk 4]
```diff
@@ -74,7 +83,11 @@ export class DebugSession implements CompositeTreeElement {
     protected readonly childSessions = new Map<string, DebugSession>();
     protected readonly toDispose = new DisposableCollection();
 
-    private isStopping: boolean = false;
+    protected isStopping: boolean = false;
+    /**
+     * Number of millis after a `stop` request times out.
+     */
+    protected stopTimeout = 5_000;
```
Comment (tsmaeder) [inline packages/debug/src/browser/debug-session.tsx:90]: This just doesn't feel like a constant that should be different for different _products_. If it varies, I would argue it should be either a user setting (slow machine) or different by debug adapter (slow adapter). Also: how would downstream adopters customize this value? Wouldn't a constructor parameter be more appropriate?

File: packages/debug/src/browser/debug-session.tsx [hunk 5]
```diff
@@ -304,8 +324,17 @@ export class DebugSession implements CompositeTreeElement {
         }
     }
 
+    /**
+     * The `send('initialize')` request could resolve later than `on('initialized')` emits the event.
```
Comment (tsmaeder) [inline packages/debug/src/browser/debug-session.tsx:328]: This seems odd: doesn't https://microsoft.github.io/debug-adapter-protocol/specification#Events_Initialized state that the `initialize` request has been handled before the `initialized` event is sent? How would the event overtake the reply? Are we handling incorrect debug adapter implementations here?

File: packages/debug/src/browser/debug-session.tsx [hunk 6]
```diff
@@ -340,24 +369,39 @@ export class DebugSession implements CompositeTreeElement {
...
                 }
             }
             callback();
         }
     }
 
+    /**
+     * Invoked when sending the `terminate` request to the debugger is rejected or timed out.
+     */
+    protected handleTerminateError(err: unknown): void {
```
Comment (tsmaeder) [inline packages/debug/src/browser/debug-session.tsx:394]: This introduces new API, and I don't really see why. What's the use case?

File: packages/debug/src/browser/view/debug-toolbar-widget.tsx [hunk 7]
```diff
@@ -77,6 +81,36 @@ export class DebugToolBar extends ReactWidget {
...
+            .filter(CompoundMenuNode.is)
+            .filter(compoundNode => match(compoundNode))
+            .map(compoundNode => compoundNode.children)
+            .reduce((acc, curr) => acc.concat(curr), [])
+            .filter(CommandMenuNode.is)
+            .filter(commandNode => match(commandNode))
+            .map(commandNode => this.debugAction(commandNode));
+    }
+
+    protected debugAction(node: CommandMenuNode): React.ReactNode {
```
Comment (tsmaeder) [inline packages/debug/src/browser/view/debug-toolbar-widget.tsx:98]: `toDebugAction` or `createDebugAction` would more accurately describe this method.

File: packages/editor/src/browser/editor.ts [hunk 8]
```diff
@@ -33,6 +33,14 @@ export interface TextEditorDocument extends lsp.TextDocument, Saveable, Disposab
      * @since 1.8.0
      */
     findMatches?(options: FindMatchesOptions): FindMatch[];
+    /**
+     * Create a valid position.
+     */
+    validatePosition(position: Position): Position;
```
Comment (tsmaeder) [inline packages/editor/src/browser/editor.ts:39]: The name sounds like it would throw an exception for non-valid position. I would prefer `toValidPosition`.  Also, documentation of how it will or should adjust the position would be nice.

File: CHANGELOG.md [hunk 9]
```diff
@@ -9,6 +9,10 @@
 - [plugin] added support for `isTransient` of `TerminalOptions` and `ExternalTerminalOptions` VS Code API [#12055](https://github.com/eclipse-theia/theia/pull/12055) - Contributed on behalf of STMicroelectronics
 - [terminal] added support for preference `terminal.integrated.enablePersistentSessions` to allow disabling restoring terminals on reload [#12055](https://github.com/eclipse-theia/theia/pull/12055) - Contributed on behalf of STMicroelectronics
 
+<a name="breaking_changes_1.34.0">[Breaking Changes:](#breaking_changes_1.34.0)</a>
+
+- [plugin-ext] `DebugExtImpl#sessionDidCreate` has been replaced with `DebugExtImpl#sessionDidStart` to avoid prematurely firing a `didStart` event on `didCreate` [#11916](https://github.com/eclipse-theia/theia/issues/11916)
```
Comment (tsmaeder) [inline CHANGELOG.md:14]: `didStart` and `didCreate` seem like two different events which both may have their use cases. I wonder why you removed the `didCreate`?

**Review by tsmaeder — COMMENTED** [review]
First reading of the code with some suggestions and questions.

**Comment by kittaakos** [comment]
Thank you!

> In my case (Ubuntu) pressing F5 will trigger the error in the devConsole, is it expected?

No. It does not. I see that the `vscode-mock-debug` sends `0` for the `column` although `columnsStartAt1` is `true`. These checks will always be `false`, as the `Position` properties must be unsigned integers:

https://github.com/kittaakos/theia/blob/76f93cb0d9c2e7e79d5dc943094bc2c8a0eff027/packages/editor/src/browser/editor-manager.ts#L256-L257

For the time being, I have opened an issue and will provide a workaround against the negative integer properties: https://github.com/microsoft/vscode-mock-debug/issues/85.

File: packages/debug/src/browser/debug-session-connection.ts [hunk 10]
```diff
@@ -215,7 +215,7 @@ export class DebugSessionConnection implements Disposable {
             };
 
             this.pendingRequests.set(request.seq, result);
-            if (timeout) {
+            if (typeof timeout === 'number') {
```
[the remark this answers is not in the document]
Comment (kittaakos) [reply packages/debug/src/browser/debug-session-connection.ts:218]: > Unless there's a reason for this change, I would revert it.

OK, let's revert it. I do not understand if the entire debugger logic is based on VS Code and [Code uses `typeof timeout === 'number'` condition](https://github.com/microsoft/vscode/blob/1148f03a4c4aa18768d2dfae8fe0e8e8f7584ed7/src/vs/workbench/contrib/debug/common/abstractDebugAdapter.ts#L80), why Theia should use a different one.

[the remark this answers is not in the document]
Comment (tsmaeder) [reply packages/debug/src/browser/debug-session-connection.ts:218]: It's not based on VS Code, it's based on the the debug adapter protocol, but an independent implementation (otherwise, the copyright notice would indicate it). As a community, we're trying not to break adapters if there is no upside to it. I was simply asking what the upside is.

File: packages/debug/src/browser/debug-session.tsx (hunk 5 above)
Comment (kittaakos) [reply packages/debug/src/browser/debug-session.tsx:328]: > Are we handling incorrect debug adapter implementations here?

Yes, on the spot. Please reference https://github.com/eclipse-theia/theia/issues/11886 describing the nature of the problem.

File: packages/debug/src/browser/debug-session.tsx (hunk 6 above)
Comment (kittaakos) [reply packages/debug/src/browser/debug-session.tsx:394]: It will help downstream to customize the error handling without overriding the entire `stop` method and copy-pasting code from Theia to downstream. This generally simplifies the Theia version bumps for extenders.

> What's the use case?
I can add dummy customization to the `api-samples` extension.

File: packages/debug/src/browser/debug-session-connection.ts (hunk 10 above)
[the remark this answers is not in the document]
Comment (kittaakos) [reply packages/debug/src/browser/debug-session-connection.ts]: https://github.com/eclipse-theia/theia/pull/11984/commits/e10d75eeeb447e99c785144b644f418d8578eeba

File: packages/debug/src/browser/debug-session.tsx [hunk 11]
```diff
@@ -43,13 +43,22 @@ import { DebugContribution } from './debug-contribution';
...
 
 export enum DebugState {
     Inactive,
     Initializing,
     Running,
     Stopped
 }
+export function debugStateLabel(state: DebugState): string {
+    switch (state) {
+        case DebugState.Initializing: return 'initializing';
```
[the remark this answers is not in the document]
Comment (kittaakos) [reply packages/debug/src/browser/debug-session.tsx:60]: https://github.com/eclipse-theia/theia/pull/11984/commits/963cc3d6105367609d9a85f589232a72766c2da5

File: packages/debug/src/browser/debug-session.tsx (hunk 3 above)
Comment (kittaakos) [reply packages/debug/src/browser/debug-session.tsx]: https://github.com/eclipse-theia/theia/pull/11984/commits/57e7f39edcb2f5f3236d26552d2c303594b819e4

File: packages/debug/src/browser/view/debug-toolbar-widget.tsx (hunk 7 above)
Comment (kittaakos) [reply packages/debug/src/browser/view/debug-toolbar-widget.tsx]: https://github.com/eclipse-theia/theia/pull/11984/commits/2b6e114695481f0b723230fbb93f03eba3381ecb

File: packages/editor/src/browser/editor.ts (hunk 8 above)
Comment (kittaakos) [reply packages/editor/src/browser/editor.ts]: https://github.com/eclipse-theia/theia/pull/11984/commits/96954d28fc72319d5e6b179b80b3789adc311899

File: packages/debug/src/browser/debug-session.tsx (hunk 4 above)
Comment (kittaakos) [reply packages/debug/src/browser/debug-session.tsx]: Good idea. I moved it to the ctor.

https://github.com/eclipse-theia/theia/pull/11984/commits/7d995566abc9c5165bc22a15955fb9854b2c04e8

File: CHANGELOG.md (hunk 9 above)
Comment (kittaakos) [reply CHANGELOG.md]: https://github.com/eclipse-theia/theia/pull/11984/commits/2b79c77b314dc500d541b83eafa192557d55845a

**Comment by kittaakos** [comment]
Thanks a lot for the help! I pushed some changes based on the API review and also added a workaround for the `Illegal value for lineNumber` error mentioned in https://github.com/eclipse-theia/theia/pull/11984#issuecomment-1385749871.

**Comment by kittaakos** [comment]
> Code now LGTM after some rewrites

:) Thanks for the help

**Comment by kittaakos** [comment]
@thegecko, would you be interested in checking if this PR does not break anything with your debug adapter as you did here: https://github.com/eclipse-theia/theia/pull/10333#pullrequestreview-805134161. Thank you!

**Comment by thegecko** [comment]
> @thegecko, would you be interested in checking if this PR does not break anything with your debug adapter as you did here: [#10333 (review)](https://github.com/eclipse-theia/theia/pull/10333#pullrequestreview-805134161). Thank you!

I can

**Comment by thegecko** [comment]
OK, browser-based debug has been broken in the latest (1.33.0 release). I need to investigate this before checking your PR.

**Review by thegecko — APPROVED** [review]
I have tested this changeset hasn't broken Arm's browser debugger, but haven't tested the additional functionality.

**Comment by thegecko** [comment]
By the way @kittaakos please reach out if you want any information with testing the browser-based arm debugger yourself:

https://open-vsx.org/extension/arm/embedded-debug

**Comment by tsmaeder** [comment]
@thegecko would it be possible to design some tests that would break when we break front end debugging? Or are the breakages to diverse?

**Comment by thegecko** [comment]
> thegecko would it be possible to design some tests that would break when we break front end debugging? Or are the breakages to diverse?

I was thinking about this. One key thing which often breaks browser debugging is accidental inclusion of node libraries. I'd hope we can mitigate that at build time with the correct webpack configs.

I wonder if a simple inline debug adapter test harness could be created (perhaps based on mock-debug) which could be used to test the UI in browser mode?

**Comment by msujew** [comment]
@paul-marechal Do you plan on merging this before the release?

**Comment by paul-marechal** [comment]
@msujew I was waiting on @thegecko to confirm this change doesn't make things worse for their use cases, LGTM now.
