### PR TITLE
[FIX] menus are not closed when clicking inside webviews

### LINKED ISSUE #7752: Menu not collapsed when clicking on webviews
### Bug Description:
Menu not collapsed when clicking on webviews 

### Steps to Reproduce:

1. Open some webview.
2. Click on the 'file' top menu item
3. Click somewhere on the webview and see the the menu is not collapsed.

screen recording from my local Theia:
ezgif com-video-to-gif (1)

### Additional Information

- Operating System: Mac Os Catalina
- Theia Version: master 1.1.0

### PR DESCRIPTION
**Pull request by shahar-h**
Signed-off-by: Shahar Harari <shahar.harari@sap.com>

#### What it does
Menus are now closed when clicking inside webviews.
In order to achieve this `mousedown` event needs to be dispatched to main window. 
Fixes #7752 

#### How to test
See described steps in #7752.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by vince-fugnitto — DISMISSED** [review]
@shahar-h do you mind updating the pull-request to not include unnecessary changes (formatting)?

**Comment by vince-fugnitto** [comment]
Please note that there is already an open pull-request which attempts to resolve the issue: https://github.com/eclipse-theia/theia/pull/8576.

**Comment by shahar-h** [comment]
> @shahar-h do you mind updating the pull-request to not include unnecessary changes (formatting)?

Sorry for that, VS Code converted all tabs to spaces, reverted all unrelated changes.

**Comment by shahar-h** [comment]
> Please note that there is already an open pull-request which attempts to resolve the issue: #8576.

I know, I'm trying to address only #7752 with a different approach.

**Comment by shahar-h** [comment]
@vince-fugnitto Windows build is failing with:
> Downloading tarball...
> Failed to download https://yarnpkg.com/downloads/1.13.0/yarn-v1.13.0.tar.gz.
The command "curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0" failed and exited with 1 during .

**Comment by shahar-h** [comment]
@vince-fugnitto this PR attempts to resolve only #7752 without breaking other functionality.
Can we go forward with it?

**Review by vince-fugnitto — COMMENTED** [review]
@shahar-h the following pull-request introduces a flickering bug when navigating menus which I believe the previous pull-request attempted to address. For example, you can see how not only the tab flickers, but also the toolbar items which gives a bad user experience:

webview

**Comment by shahar-h** [comment]
> the following pull-request introduces a flickering bug when navigating menus which I believe the previous pull-request attempted to address.
> 
This issue is not related to my PR, it is also reproduced on master.

**Comment by vince-fugnitto** [comment]
> > the following pull-request introduces a flickering bug when navigating menus which I believe the previous pull-request attempted to address.
> 
> This issue is not related to my PR, it is also reproduced on master.

@shahar-h this is `master`, the toolbar items on master do not flicker (disappear and reappear completely):

master

As compared to the _pull-request_:

webview

**Comment by shahar-h** [comment]
@vince-fugnitto I'm not sure how you checked, I've just reproduced the same behavior on master:
flickering

BTW, is there any reason there are two `Open Preview to the Side` buttons?
image

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I'm not sure how you checked, I've just reproduced the same behavior on master:

I was able to reproduce more consistently on `master` as well :+1: 

> BTW, is there any reason there are two `Open Preview to the Side` buttons?
> image

There are two items since we provide the functionality from `@theia/preview` and the builtin extension (plugin).
In an actual application, we'd only choose one extension to provide the functionality: https://github.com/eclipse-theia/theia/issues/6984

**Review by vince-fugnitto — APPROVED** [review]
Functionally the changes work very well :+1: 
I'll open a follow-up issue regarding the webview stealing focus and how toolbar items flicker.

File: packages/plugin-ext/src/main/browser/webview/webview.ts [hunk 1]
```diff
@@ -308,6 +318,16 @@ export class WebviewWidget extends BaseWidget implements StatefulWidget {
         return this.doSend('did-load-localhost', { origin, location: redirect });
     }
 
+    protected dispatchMouseEvent(type: string, data: MouseEvent): void {
+        const domRect = this.node.getBoundingClientRect();
+        this.node.dispatchEvent(new MouseEvent(type, {
+            ...data, ...{
+                clientX: domRect.x + data.clientX,
+                clientY: domRect.y + data.clientY
+            }
```
Comment (marechal-p) [inline packages/plugin-ext/src/main/browser/webview/webview.ts:327]: Don't `...{` but rather just define the options directly after `...data,`?

**Review by marechal-p — COMMENTED** [review]
LGTM otherwise.

File: packages/plugin-ext/src/main/browser/webview/webview.ts (hunk 1 above)
Comment (shahar-h) [reply packages/plugin-ext/src/main/browser/webview/webview.ts]: Good catch 👍, Fixed.

**Review by marechal-p — APPROVED** [review]
