### PR TITLE
fix: ensure reveal scrolls to selected tree row

### LINKED ISSUE #15605: Reveal in Explorer does not work from the first time if the parent folder is collapsed
### Bug Description:
Hi,
This happens when the navigator tree has a vertical scroll, and the file parent folder is collapsed and not in view.

### Steps to Reproduce:

1. Open any text file under a folder
2. Collapse its parent folder
3. Navigate the explorer tree up until the parent folder is not in the view
4. Run the Reveal in Explorer command
5. The navigator tree will not scroll to the file in the tree
6. Now it works!

https://github.com/user-attachments/assets/a888ec16-87fb-4f64-bebe-b9d01d75a41b

### Additional Information

- Operating System: Mac (on chrome)
- Theia Version: 1.61

### PR DESCRIPTION
**Pull request by eneufeld**
#### What it does

- recompute `scrollToRow` as soon as tree rows refresh so the first reveal has a valid target
- trigger `scrollIntoViewIfNeeded` after mount and when virtualized rows change, ensuring the selected node is scrolled into view immediately

Fixes #15605

#### How to test

1. Open any text file under a folder
2. Collapse its parent folder
3. Navigate the explorer tree up until the parent folder is not in the view
4. Run the Reveal in Explorer command
5. The navigator tree will should now scroll to the file in the tree

#### Breaking changes

- [ ] This PR introduces breaking changes and requires careful review. If yes, the breaking changes section in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) has been updated.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/core/src/browser/tree/tree-widget.tsx [hunk 1]
```diff
@@ -1661,18 +1662,35 @@ export namespace TreeWidget {
...
+                });
+            }
+        };
+
+        override componentDidMount(): void {
+            this.scrollIntoViewIfNeeded();
+        }
+
+        override componentDidUpdate(prevProps: ViewProps): void {
+            if (this.props.scrollToRow !== undefined && (this.props.scrollToRow !== prevProps.scrollToRow || this.props.rows !== prevProps.rows)) {
```
Comment (sdirix) [inline packages/core/src/browser/tree/tree-widget.tsx]: Minor: The `scrollToRow` is already checked in `scrollIntoViewIfNeeded`

**Comment by JonasHelming** [comment]
@eneufeld Could you get this finished (either create a follow-up or fix) please?

**Comment by eneufeld** [comment]
I'll check today
