### PR TITLE
fix #6767: don't reuse integrated terminal that has child processes

### LINKED ISSUE #6767: Integrated terminal should not be resused if a process is running in it
### Description
If a process is running in an integrated terminal, then a new integrated terminal should be provided for `runInTerminal` request. Otherwise, it could be problematic, even dangerous.

### Reproduction Steps
integrated-terminal
In the demo above, if the terminal is already running python, sending command text to that terminal will end in chaos.

**What's worse?** Think about a situation where a user happens to be operating a database, e.g. MySQL, in the opened integrated terminal, it could be dangerous to send commands to that terminal!

### Propose
1. Remove integrated terminals with any child process from for-reuse candidates
I learned the logic from VSCode. Please refer to:
https://github.com/microsoft/vscode/blob/4636be2b71c87bfb0bfe3c94278b447a5efcc1f1/src/vs/workbench/api/node/extHostDebugService.ts#L83-L87
and
https://github.com/microsoft/vscode/blob/4636be2b71c87bfb0bfe3c94278b447a5efcc1f1/src/vs/workbench/contrib/debug/node/terminals.ts#L50-L75

Demo from VSCode:
integrated-terminal-vscode

2. Don't change the title of the integrated terminal
Compare the title of the integrated terminal of VSCode to theia:
VSCode:
image
Theia:
image
- In the case of theia, I believe it is hard for users to distinguish the *special* integrated terminals from the *normal* ones and they are more likely to run command in that terminal.
- In the case of VSCode, it's not hard to imagine that users will be aware of which ones are integrated terminal. And even if they mistakenly run a process in that terminal, which ends in prompting VSCode opening a new terminal, they are more likely to understand what's happening and avoid using that terminal the next time.

**OS and Theia version:**
OS: Linux
Theia: Latest(582ae9d)

**Diagnostics:**

### PR DESCRIPTION
**Pull request by a1994846931931**
Signed-off-by: Cai Xuye <a1994846931931@gmail.com>

#### What it does
Fix #6767.

#### How to test
1. Check whether the reuse of the integrated terminal is still working.
2. Check if an integrated terminal is in use, it won't be reused.
Demo gif for the 1st commit (propose 1 in #6767):
integrated-terminal-fixed
3. Check if the title of the integrated terminal keeps its original value
Update gif for the 2nd commit (propose 2 in #6767):
integrated-terminal-fixed2

I've tested in only on Linux. Could anyone test it on windows as well? Thanks!

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)
- [x] CQ approval needed before merge https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21340

### CODE REVIEW

File: packages/debug/src/browser/debug-session.tsx [hunk 1]
```diff
@@ -368,13 +368,19 @@ export class DebugSession implements CompositeTreeElement {
     }
 
     protected async runInTerminal({ arguments: { title, cwd, args, env } }: DebugProtocol.RunInTerminalRequest): Promise<DebugProtocol.RunInTerminalResponse['body']> {
-        const terminal = await this.doCreateTerminal({ title, cwd, env });
+        const terminal = await this.doCreateTerminal({ title, cwd, env, useServerTitle: false });
```
Comment (akosyakov) [inline packages/debug/src/browser/debug-session.tsx]: Where `useServerTitle` is used?

Comment (a1994846931931) [reply packages/debug/src/browser/debug-session.tsx]: @akosyakov 
It's from `TerminalWidgetOptions. Please refer to:
https://github.com/eclipse-theia/theia/blob/938bc4885bc0257f3d2d467d6933f102734961ef/packages/terminal/src/browser/base/terminal-widget.ts#L89-L93

Setting it to `false` here makes the title of the integrated in accordance with `RunInTerminalRequestArguments.title` (please refer to propose 2 in #6767).

File: packages/debug/src/browser/debug-session.tsx [hunk 2]
```diff
@@ -368,13 +368,19 @@ export class DebugSession implements CompositeTreeElement {
...
         terminal.sendText(args.join(' ') + '\n');
         return { processId: await terminal.processId };
     }
 
     protected async doCreateTerminal(options: TerminalWidgetOptions): Promise<TerminalWidget> {
-        let terminal = this.terminalServer.all.find(t => t.title.label === options.title || t.title.caption === options.title);
+        let terminal = undefined;
+        for (const t of this.terminalServer.all) {
+            if ((t.title.label === options.title || t.title.caption === options.title) && (await t.hasChildProcesses()) === false) {
+                terminal = t;
```
Comment (vince-fugnitto) [inline packages/debug/src/browser/debug-session.tsx]: Should we exit early if we find a terminal that matches our criteria instead of continuing to iterate?

Comment (a1994846931931) [reply packages/debug/src/browser/debug-session.tsx]: @vince-fugnitto 
Yes, indeed! Just updated the code.

File: packages/terminal/src/node/shell-terminal-server.ts [hunk 3]
```diff
@@ -41,4 +43,35 @@ export class ShellTerminalServer extends BaseTerminalServer {
...
         }
     }
+
+    // copied and modified from https://github.com/microsoft/vscode/blob/4636be2b71c87bfb0bfe3c94278b447a5efcc1f1/src/vs/workbench/contrib/debug/node/terminals.ts#L50-L75
+    async hasChildProcesses(processId: number | undefined): Promise<boolean> {
+        if (processId) {
+            try {
+                // if shell has at least one child process, assume that shell is busy
+                if (isWindows) {
+                    const result = cp.spawnSync('wmic', ['process', 'get', 'ParentProcessId']);
```
Comment (marechal-p) [inline packages/terminal/src/node/shell-terminal-server.ts]: Please prefer the asynchronous API

**Comment by marechal-p** [comment]
Thanks for the patch @a1994846931931, please note that I am working on the shell argument escaping for the `runInTerminal` request, I don't know if you had issues with this too.

File: packages/terminal/src/node/shell-terminal-server.ts (hunk 3 above)
Comment (a1994846931931) [reply packages/terminal/src/node/shell-terminal-server.ts]: OK

**Comment by a1994846931931** [comment]
> Thanks for the patch @a1994846931931, please note that I am working on the shell argument escaping for the `runInTerminal` request, I don't know if you had issues with this too.

@marechal-p 
Hi, I do notice that we simply join the argument and before send it as the command to terminal:
https://github.com/eclipse-theia/theia/blob/f54e970d09fa26bfab0afad96e2c5541e556d393/packages/debug/src/browser/debug-session.tsx#L372
which may be problematic, while VSCode's implementation is far more complicated:
https://github.com/microsoft/vscode/blob/4636be2b71c87bfb0bfe3c94278b447a5efcc1f1/src/vs/workbench/contrib/debug/node/terminals.ts#L79-L210

Although I haven't encountered any broken issues so far, it reminds me of a line in `cdt-gdb-adapter`:
https://github.com/eclipse-cdt/cdt-gdb-adapter/blob/7b04c93f7e3a0646f6be5b6eac45c5f071e04829/src/GDBBackend.ts#L67
```
        let args = [gdb, '-ex', `new-ui mi2 ${pty.name}`];
```
where the argument `new-ui mi2 ${pty.name}` should be quoted before being send as a text command. 
So I tested it on theia, and it does have a problem:
image
image

I hope the information helpful.

File: packages/terminal/src/node/shell-terminal-server.ts (hunk 3 above)
Comment (a1994846931931) [reply packages/terminal/src/node/shell-terminal-server.ts]: @marechal-p 
Code updated.

**Comment by marechal-p** [comment]
Yes, thank you for the infos. So again, just so that we do not duplicate work: I already have a [commit for the command escaping](https://github.com/eclipse-theia/theia/commit/b9c544ad3f3f4a0a43bcd0b38677c14e12178e6c), I will open and attend a PR with it first week of January as I will be taking vacations. With your patch + the commit I made, we should be pretty close to what VS Code does :)

**Comment by akosyakov** [comment]
@elaihau @vince-fugnitto @marechal-p please finish the review

File: packages/terminal/src/node/shell-terminal-server.ts [hunk 4]
```diff
@@ -41,4 +43,46 @@ export class ShellTerminalServer extends BaseTerminalServer {
             return Promise.resolve(-1);
         }
     }
+
+    // copied and modified from https://github.com/microsoft/vscode/blob/4636be2b71c87bfb0bfe3c94278b447a5efcc1f1/src/vs/workbench/contrib/debug/node/terminals.ts#L32-L75
```
Comment (vince-fugnitto) [inline packages/terminal/src/node/shell-terminal-server.ts]: I created a CQ for the following copied code:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21340

**Comment by a1994846931931** [comment]
> I played with the change and found the following behavior - should this scenario be covered by this change? Maybe it is unrelated?

@elaihau 
No, it's not covered in this PR. But similar behaviour could be realized, by changing:
https://github.com/eclipse-theia/theia/blob/44efdc41d2d6fc75dbc7008f415fc10b553ab5ab/packages/task/src/browser/task-service.ts#L924
to
```typescript
if (!terminal || (await terminal.hasChildProcesses())) {
```
after this commit.

But I'm sure whether the `Run selected text` command should open a new terminal when the current one is running a program. I just tested it on VSCode, and it actually send the text directly to the current one, *even if it's running a program*.

**Comment by akosyakov** [comment]
@a1994846931931 please merge!
