### PR TITLE
vsx-registry: Skip extension resolution if already installed

### LINKED ISSUE #10560: Installing a VSCode extension always reinstalls its dependencies
### Bug Description:
When installing a plugin that has dependencies, its dependencies are always downloaded from the marketplace.  
It doesn't matter if the dependencies are already installed or if the plugin is installed from the marketplace or *.vsix.  
It also doesn't matter if the VSCode extensions (dependencies) are provided built-in (`theiaPlugins`).

I see a problem with this behavior for two reasons:
- Needles downloads of plugins, that are already installed in the exact version
- Effectively performs a downgrade of the dependencies if the newest version is not in the marketplace (but older versions are)
  → e.g. when testing a snapshot locally

### Steps to Reproduce:

1. Create a VSCode extension with `extensionDependencies` set to any extension in the marketplace
2. Install the latest version of the extensionDependencies
3. Install the Plugin that has dependencies
    → Dependencies will be downloaded again

### Additional Information

- Operating System: Windows 10
- Theia Version: 1.21.0 (electron)
- Tested with own marketplace instance & docker image: `openvsx-server:92ae306`  

#### Log
I have replaced some values in the log.  
It shows the output when installing `EXTENSION-WITH-DEPENDENCIES`, which has a dependency to `DEPENDENCY-EXTENSION_A` and `DEPENDENCY-EXTENSION_B`.

Versions in Marketplace:
* EXTENSION-WITH-DEPENDENCIES @0.1.0
* DEPENDENCY-EXTENSION_A @0.2.0
* DEPENDENCY-EXTENSION_B @0.2.0

Built-In VSCode extensions:
* DEPENDENCY-EXTENSION_A @0.3.0-dev
* DEPENDENCY-EXTENSION_B @0.3.0-dev

```
root INFO [36e5b3bd-25d6-4efc-8345-1d5e658efd98][OUR-NAMESPACE.UNRELATED-EXTENSION-1]: Started plugin.
root INFO [36e5b3bd-25d6-4efc-8345-1d5e658efd98][OUR-NAMESPACE.UNRELATED-EXTENSION-2]: Started plugin.
root INFO [36e5b3bd-25d6-4efc-8345-1d5e658efd98][OUR-NAMESPACE.UNRELATED-EXTENSION-3]: Started plugin.
root INFO [36e5b3bd-25d6-4efc-8345-1d5e658efd98][OUR-NAMESPACE.UNRELATED-EXTENSION-4]: Started plugin.
root INFO [36e5b3bd-25d6-4efc-8345-1d5e658efd98][OUR-NAMESPACE.DEPENDENCY-EXTENSION_B]: Started plugin.
root INFO [36e5b3bd-25d6-4efc-8345-1d5e658efd98][OUR-NAMESPACE.DEPENDENCY-EXTENSION_A]: Started plugin.
root INFO [36e5b3bd-25d6-4efc-8345-1d5e658efd98][OUR-NAMESPACE.UNRELATED-EXTENSION-5]: Started plugin.
root INFO [36e5b3bd-25d6-4efc-8345-1d5e658efd98] Start of 7 plugins took: 23614.9 ms [Finished 28.380 s after frontend start]
root INFO [EXTENSION-WITH-DEPENDENCIES-0.2.0-dev.vsix]: trying to decompress into "c:\Users\MY-USER\.theia\extensions\EXTENSION-WITH-DEPENDENCIES-0.2.0-dev.vsix"...
root INFO [EXTENSION-WITH-DEPENDENCIES-0.2.0-dev.vsix]: decompressed
root INFO PluginTheiaDirectoryHandler: accepting plugin with path c:\Users\MY-USER\.theia\extensions\EXTENSION-WITH-DEPENDENCIES-0.2.0-dev.vsix
root INFO Resolved "EXTENSION-WITH-DEPENDENCIES-0.2.0-dev.vsix" to a VS Code extension "EXTENSION-WITH-DEPENDENCIES@0.2.0-dev" with engines: { vscode: '^1.45.0' }   
root INFO [OUR-NAMESPACE.DEPENDENCY-EXTENSION_B]: trying to resolve latest version...
root INFO [OUR-NAMESPACE.DEPENDENCY-EXTENSION_A]: trying to resolve latest version...
root INFO [OUR-NAMESPACE.DEPENDENCY-EXTENSION_A]: resolved to 'OUR-NAMESPACE.DEPENDENCY-EXTENSION_A-0.2.0'
root INFO [OUR-NAMESPACE.DEPENDENCY-EXTENSION_A-0.2.0]: trying to download from "http://OUR-MARKETPLACE-HOST/api/OUR-NAMESPACE/DEPENDENCY-EXTENSION_A/0.2.0/file/OUR-NAMESPACE.DEPENDENCY-EXTENSION_A-0.2.0.vsix"...
root INFO [OUR-NAMESPACE.DEPENDENCY-EXTENSION_B]: resolved to 'OUR-NAMESPACE.DEPENDENCY-EXTENSION_B-0.2.0'
root INFO [OUR-NAMESPACE.DEPENDENCY-EXTENSION_B-0.2.0]: trying to download from "http://OUR-MARKETPLACE-HOST/api/OUR-NAMESPACE/DEPENDENCY-EXTENSION_B/0.2.0/file/OUR-NAMESPACE.DEPENDENCY-EXTENSION_B-0.2.0.vsix"...
root INFO [OUR-NAMESPACE.DEPENDENCY-EXTENSION_A-0.2.0]: downloaded to C:\Users\MY-USER\AppData\Local\Temp\0c145b31-9527-4e93-977e-73445167683c\OUR-NAMESPACE.DEPENDENCY-EXTENSION_A-0.2.0.vsix"
root INFO [OUR-NAMESPACE.DEPENDENCY-EXTENSION_A-0.2.0]: trying to decompress into "c:\Users\MY-USER\.theia\extensions\OUR-NAMESPACE.DEPENDENCY-EXTENSION_A-0.2.0"...
root INFO [OUR-NAMESPACE.DEPENDENCY-EXTENSION_A-0.2.0]: decompressed
root INFO PluginTheiaDirectoryHandler: accepting plugin with path c:\Users\MY-USER\.theia\extensions\OUR-NAMESPACE.DEPENDENCY-EXTENSION_A-0.2.0
root INFO Resolved "OUR-NAMESPACE.DEPENDENCY-EXTENSION_A-0.2.0" to a VS Code extension "DEPENDENCY-EXTENSION_A@0.2.0" with engines: { vscode: '^1.45.0' }
root INFO [OUR-NAMESPACE.DEPENDENCY-EXTENSION_B-0.2.0]: downloaded to C:\Users\MY-USER\AppData\Local\Temp\0c145b31-9527-4e93-977e-73445167683c\OUR-NAMESPACE.DEPENDENCY-EXTENSION_B-0.2.0.vsix"
root INFO [OUR-NAMESPACE.DEPENDENCY-EXTENSION_B-0.2.0]: trying to decompress into "c:\Users\MY-USER\.theia\extensions\OUR-NAMESPACE.DEPENDENCY-EXTENSION_B-0.2.0"...
root INFO [OUR-NAMESPACE.DEPENDENCY-EXTENSION_B-0.2.0]: decompressed
root INFO PluginTheiaDirectoryHandler: accepting plugin with path c:\Users\MY-USER\.theia\extensions\OUR-NAMESPACE.DEPENDENCY-EXTENSION_B-0.2.0
root INFO Resolved "OUR-NAMESPACE.DEPENDENCY-EXTENSION_B-0.2.0" to a VS Code extension "DEPENDENCY-EXTENSION_B@0.2.0" with engines: { vscode: '^1.45.0' }
root INFO Deploying backend plugin "EXTENSION-WITH-DEPENDENCIES@0.2.0-dev" from "c:\Users\MY-USER\.theia\extensions\EXTENSION-WITH-DEPENDENCIES-0.2.0-dev.vsix\extension\dist\extension.js"
root INFO Deploy plugin entry took: 12250.4 ms
root INFO [36e5b3bd-25d6-4efc-8345-1d5e658efd98] Waiting for backend deployment took: 11.8 ms [Finished 51.884 s after frontend start]
root INFO [36e5b3bd-25d6-4efc-8345-1d5e658efd98] Sync of 1 plugin took: 25.0 ms [Finished 51.909 s after frontend start]
root INFO [36e5b3bd-25d6-4efc-8345-1d5e658efd98][OUR-NAMESPACE.EXTENSION-WITH-DEPENDENCIES]: Loaded contributions.
root INFO [36e5b3bd-25d6-4efc-8345-1d5e658efd98] Load contributions of 1 plugin took: 0.1 ms [Finished 51.910 s after frontend start]
root INFO [hosted-plugin: 28676] PLUGIN_HOST(28676): PluginManagerExtImpl/init()
root INFO [hosted-plugin: 28676] PLUGIN_HOST(28676): initializing(EXTENSION-WITH-DEPENDENCIES@0.2.0-dev with C:\OUR-THEIA-PROJECT\node_modules\@theia\plugin-ext-vscode\lib\node\plugin-vscode-init)
root INFO [hosted-plugin: 28676] PLUGIN_HOST(28676): PluginManagerExtImpl/loadPlugin(c:\Users\MY-USER\.theia\extensions\EXTENSION-WITH-DEPENDENCIES-0.2.0-dev.vsix\extension\dist\extension.js)
root INFO [36e5b3bd-25d6-4efc-8345-1d5e658efd98][OUR-NAMESPACE.EXTENSION-WITH-DEPENDENCIES]: Started plugin.
root INFO [36e5b3bd-25d6-4efc-8345-1d5e658efd98] Start of 1 plugin took: 114.0 ms [Finished 52.028 s after frontend start]
```

### PR DESCRIPTION
**Pull request by msujew**
#### What it does

Closes #10560 by comparing the versions of already installed extensions with the to-be-resolved extension version. When the extension already exists and its version is greater or equal to the one that should be installed, its download is skipped.

#### How to test

1. Install the `hbenl.test-adapter-converter` and `hbenl.vscode-test-explorer` (in this exact order) extension from [here](https://github.com/eclipse-theia/theia/files/7856099/hbenl.test-extensions.zip). The `hbenl.vscode-test-explorer` version has been increased to `2.42.0` to recreate the original issue.
2. Search for the "Mocha Test Explorer" (`hbenl.vscode-mocha-test-adapter`) and install it. It requires the `hbenl.version-test-explorer` as an extension dependency.
3. In the console where Theia was started, the message `[hbenl.vscode-test-explorer]: is already installed with the same or newer version '2.42.0'` should appear.
4. Confirm that no old version of the test adapter extension has been downloaded into your `<user>/.theia` directory.

---

5. Repeat all of the above but instead of installing the extension from the `.vsix` file, unpack the extensions into your `plugins` folder. Additionally perform the test by adding the `.vsix` directly to the `plugins` folder without unpacking them.

---

6. Restart the application and also confirm here that no downgrade is performed. 

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by msujew** [comment]
cc @luettmaSICKAG this should fix the issue you were experiencing. Do you mind testing this PR to confirm that the resolution works as expected?

File: packages/vsx-registry/src/common/vsx-version.ts [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+ ********************************************************************************/
+
+export type VSXExtensionVersion = number[];
+
+export function parseVersion(versionString: string): VSXExtensionVersion | undefined {
+    const array = versionString.split('.').map(e => Number(e));
+    return array.some(isNaN) ? undefined : array;
+}
+
+export function compareVersion(a: VSXExtensionVersion, b: VSXExtensionVersion): (-1 | 0 | 1) {
```
Comment (colin-grant-work) [inline packages/vsx-registry/src/common/vsx-version.ts:24]: @vince-fugnitto, this looks like it's recreating some of the work you recently wrote tests for - is there already a way to do this?

Comment (vince-fugnitto) [reply packages/vsx-registry/src/common/vsx-version.ts:24]: I use `semver` which should handle most of the use-cases we have included in the changes I believe.

Ex:
https://github.com/eclipse-theia/theia/blob/dd900be938f6981d2a08edb60e42151d96804ec0/dev-packages/ovsx-client/src/ovsx-client.ts#L194-L209

Comment (msujew) [reply packages/vsx-registry/src/common/vsx-version.ts]: @vince-fugnitto Thanks for the pointer, I implemented the comparison using `semver` and removed the custom implementation 👍

**Comment by luettmaSICKAG** [comment]
> cc @luettmaSICKAG this should fix the issue you were experiencing. Do you mind testing this PR to confirm that the resolution works as expected?

Hmm sadly not completely. I couldn't test it with your plugins and the public OpenVSX marketplace due to our company proxy and no support in Theia yet.
I tested it with this branch and our private OpenVSX marketplace though.

The issue we have is a little bit different to the test you described in the PR.
Our problem is that **the dependency is downgraded** (in your example the `hbenl.test-adapter-converter`, not the `hbenl.vscode-test-explorer`).

When installing the plugins manually (from vsix) everything seems to work correctly (no downgrades).
When the dependencies are built-in they're resolved correctly during installation, but after a restart it just tries to download/update all plugins and seems to ignore the check.

**Logs**
I have renamed the plugins/files in the log entries, but haven't removed anything.
So this is what happens when I have a `PLUGIN_WITH_DEPENDENCIES` which depends on `DEPENDENCY_A` and `DEPENDENCY_B`.
`DEPENDENCY_A` and `DEPENDENCY_B` are provided built-in.
`PLUGIN_WITH_DEPENDENCIES` is installed manually ("Install from vsix"), but is also available in the Marketplace.

First start and installing the `PLUGIN_WITH_DEPENDENCIES`: [1_plugin-install-fresh-installation.log](https://github.com/eclipse-theia/theia/files/7864145/1_plugin-install-fresh-installation.log)
Second start where the downgrade happens: [2_plugin-install-second-start.log](https://github.com/eclipse-theia/theia/files/7864154/2_plugin-install-second-start.log)

**Comment by msujew** [comment]
@luettmaSICKAG I was able to reproduce the dependency downgrade issue with the exact configuration that I use here as my testing steps on `master`.

Basically the dependency situation is as follows:

`hbenl.vscode-mocha-test-adapter` -> `hbenl.vscode-test-explorer` -> `hbenl.test-adapter-converter`

When installing my custom version 2.42.0 of `hbenl.vscode-test-explorer` through a `vsix` file, and afterwards downloading the `hbenl.vscode-mocha-test-adapter` extension using the vsx-registry UI, Theia automatically downloads the `2.20.3` version (a downgrade) of `hbenl.vscode-test-explorer` (which is an extension dependency of `hbenl.vscode-mocha-test-adapter`) and replaces the previously running version.

The `hbenl.test-adapter-converter` extension doesn't really have anything to do with it, it is just needed by the `hbenl.vscode-test-explorer` extension, but doesn't get automatically downloaded when installing the test explorer from the `vsix` file.

My PR fixes this exact behavior by identifying whether an extension dependency already exists in the list of deployed plugins and  stops the extension resolution if the fetched version is not a version upgrade.

I hope that clears things up. Am I still wrong in the assumption that it mimics your setup?

**Comment by luettmaSICKAG** [comment]
Oh right sorry, I missed that. No the setup is correct.

Do you mind trying to test it with `hbenl.test-adapter-converter` and `hbenl.vscode-test-explorer` as built-in extension again and afterwards downloading the "Mocha Test Explorer"?
That'd be basically the same situation where I was still experiencing the issue.

**Comment by msujew** [comment]
@luettmaSICKAG No worries :)

I just retested the fix with unpacking the vsix files first and adding them to the list of built-in extensions. It still works correctly. I added the additional testing step to the original PR comment 👍

File: packages/vsx-registry/src/node/vsx-extension-resolver.ts [hunk 2]
```diff
@@ -71,6 +82,19 @@ export class VSXExtensionResolver implements PluginDeployerResolver {
         context.addPlugin(resolvedId, extensionPath);
     }
 
+    protected hasSameOrNewerVersion(id: string, extension: VSXExtensionRaw): string | undefined {
+        const existingPlugin = this.pluginDeployerHandler.getDeployedPlugin(id);
+        if (existingPlugin) {
+            const modelVersion = existingPlugin.metadata.model.version;
+            const existingVersion = semver.clean(modelVersion);
+            const version = semver.clean(extension.version);
```
Comment (colin-grant-work) [inline packages/vsx-registry/src/node/vsx-extension-resolver.ts:90]:
```suggestion
            const existingVersion = semver.clean(existingPlugin.metadata.model.version);
            const desiredVersion = semver.clean(extension.version);
```
```suggestion
            const modelVersion = existingPlugin.metadata.model.version;
            const existingVersion = semver.clean(modelVersion);
            const version = semver.clean(extension.version);
```

**Review by colin-grant-work — APPROVED** [review]
I have confirmed the bug on `master` and that this change addresses the issue. I have [some misgivings](https://github.com/eclipse-theia/theia/pull/9330#issuecomment-977015059) about what happens in cases when this code does _not_ apply and we do download a new version of the plugin, but this code reduces the frequency of that event, so it's at least a step in the right direction. 👍

**Comment by luettmaSICKAG** [comment]
I just tested it again on my private device, with your setup and the public OVSX registry.  
I could still reproduce the problem with built-in plugins.

Not quite sure if the problem is on my side, so I just recorded it :s

**What I did**
- I built Theia using `yarn && yarn build`
- I added the two plugins from "How to test, step 1" to the `/plugins` directory of the repo (without extracting)
- Cleared the directories `%USERPROFILE%/.theia/extensions` and `%LOCALAPPDATA%/Temp/vscode-unpacked`
- Started Theia (electron) `yarn electron start`
- Installed the "Mocha Test Explorer" ("How to test, step 2")
- Restart Theia
- Now `hbenl.vscode-test-explorer` is downgraded and installed to `%USERPROFILE%/.theia/extensions`

VSX_Builtin_Downgrade

**Comment by msujew** [comment]
@luettmaSICKAG Thanks for looking into this again. You're right, when restarting the app, the plugin resolving mechanism start a second time, this time downloading the outdated version, since the plugins aren't deployed yet. I'll look into a solution for this 👍

**Comment by msujew** [comment]
@colin-grant-work Do you mind checking out step 6 of the testing steps? My newest changes fixes a restart-related downgrade issue. Previously, `system` and `user` extensions where resolved independently of each other when starting the plugin host, resulting in a downgrade of `system` extensions when a `user` extension depends on it.

File: packages/plugin-ext/src/main/node/plugin-deployer-impl.ts [hunk 3]
```diff
@@ -132,69 +137,75 @@ export class PluginDeployerImpl implements PluginDeployer {
...
 
-    async deploy(pluginEntry: string, type: PluginType = PluginType.System): Promise<void> {
+    async deploy(plugin: UnresolvedPluginEntry): Promise<void> {
         const startDeployTime = performance.now();
-        await this.deployMultipleEntries([pluginEntry], type);
+        await this.deployMultipleEntries([plugin]);
         this.logMeasurement('Deploy plugin entry', startDeployTime);
     }
 
-    protected async deployMultipleEntries(pluginEntries: ReadonlyArray<string>, type: PluginType = PluginType.System): Promise<void> {
```
Comment (colin-grant-work) [inline packages/plugin-ext/src/main/node/plugin-deployer-impl.ts:141]: Is this (and `resolvePlugins`) the change that requires the introduction of the  `UnresolvedPluginEntry` interface? It looks like previously we could only have a list of plugins with uniform plugin types, and now we want to have a list of plugin with mixed types. Otherwise, it looks like the same information was being passed around everywhere, just not necessarily in the same package?

Comment (msujew) [reply packages/plugin-ext/src/main/node/plugin-deployer-impl.ts:141]: Exactly, we need the mixed type since we need to resolve **all** user and builtin extensions in the first step. Though it's mostly `resolvePlugins`, since the main culprit of this issue is introduced here:

https://github.com/eclipse-theia/theia/blob/c56aa230fe50f20b598b2b4c4273cad4486b4750/packages/plugin-ext/src/main/node/plugin-deployer-impl.ts#L121-L124
