### PR TITLE
Modify next-node selection logic for PreferenceTreeModel

### LINKED ISSUE #9655: Arrows should select only visible preferences
### Bug Description:

When navigating the preference tree using the arrow keys, and when there is a search filter hiding some of the preferences, it appears that arrow keys also select the hidden preferences. They should select only visible preferences.

### Steps to Reproduce:

1. Open the Preferences widget.
2. Search for "selection", or other text of your choosing.
3. Click on "Text Editor".
image
4. Press the down arrow and notice that it takes 4x before selecting"Find", and then another 9x before selecting "Suggest".
5. Clear the search filter and expand the "Text Editor" category, and you see the 4x & 9x above suggest the arrows were selecting the hidden entries.
image

### Additional Information

- Operating System: RHEL 7, Firefox 89.0
- Theia Version: 1.14.0, browser example

### PR DESCRIPTION
**Pull request by colin-grant-work**
#### What it does

Fixes #9655 by changing the logic for choosing the 'next selectable node' in preferences tree. For extensibility, I've made that check a protected method in the base `TreeModel` class and overridden it in the `PreferenceTreeModel`

#### How to test

1. Open the Preferences widget.
2. Search for "selection", or other text of your choosing.
3. Click on "Text Editor".
4. Press the down arrow and notice that it takes 1x before selecting "Find", and then another 1x before selecting "Suggest".
5. Perform the same test on an unfiltered tree and see that each keyboard press moves you 1 item.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: Colin Grant <colin.grant@ericsson.com>

### CODE REVIEW

File: packages/core/src/browser/tree/tree-model.ts [hunk 1]
```diff
@@ -302,21 +302,22 @@ export class TreeModelImpl implements TreeModel, SelectionProvider<ReadonlyArray
         return iterator && this.doGetNextNode(iterator);
     }
 
-    protected doGetNextNode(iterator: TreeIterator): SelectableTreeNode | undefined {
+    protected doGetNextNode(iterator: IterableIterator<TreeNode>): SelectableTreeNode | undefined {
```
Comment (colin-grant-work) [inline packages/core/src/browser/tree/tree-model.ts:305]: I'd rather just change this to be `extends IterableIterator<TreeNode>`, but that might be slightly more breaking. Anyone who's implemented an iterator that isn't iterable would probably be grateful in the long run, though. Who wants to type `.next()` all the time?

https://github.com/eclipse-theia/theia/blob/210fa4ac6875716f23ac70f94fe6f0ffc693bfe5/packages/core/src/browser/tree/tree-iterator.ts#L20

**Review by vince-fugnitto — APPROVED** [review]
I confirmed the presence of the bug on master and that the pull-request resolves the issue 👍
