### PR TITLE
[preferences] fix the display of file icons

### LINKED ISSUE #6990: [firefox] incorrect display of workspace settings file icon
**Description**

The **workspace** `settings.json` file displayed in the tab when using the `preferences view` is incorrectly displayed (the file icon is too large) when using the application on **Firefox**.

<div align='center'>

Screen Shot 2020-01-28 at 7 24 59 PM

</div>

**Steps to Reproduce**
1. start the application on **Firefox** with a workspace (ex: theia)
2. open the `preferences widget`
3. notice the _workspace_ tab's icon is displayed too large

### LINKED ISSUE #7010: [file-icon] 'preferences widget' settings tab displays incorrect icon
**Description**

The `preferences widget` settings tab (user) displays the incorrect icon when updating the applications `file icon` theme. 

Screen Shot 2020-01-29 at 11 32 18 AM

**Steps to Reproduce**:
1. start the application using Theia as a workspace and open the `preferences` widget
2. change the `file icon` theme using the command `Preferences: File Icon Theme`
3. notice the incorrect and mismatched icons

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

Fixes #6990
Fixes #7010

- fixes an issue where the file icon was not properly displayed
- fixes an issue where the file icon was not properly updated
based on the current file icon theme. This problem is solved by
programmatically getting the icon based on the `file-icon` using
the `labelProvider#getIcon` method.

~TODO~:
- [x] fix the `user` file icon not being updated once a file icon theme change event occurs (this is probably due to how the user preferences editor is created).
- [x] fix the display of file icons in the tab (make it consistent with other tabs) when changing file icon themes.

#### How to test

1. start the application and open the `preferences widget`.
2. change the `file icon` theme (the settings tabs (user + workspace)) should properly be updated with the corresponding file icon theme and should also be displayed properly.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
@akosyakov do you know as to why the file-icon for the user would not be updated but others will when updating the file-icon theme?

**Comment by akosyakov** [comment]
@vince-fugnitto one has to listen for changes on label provider and call getIcon again if a uri is affected

File: packages/preferences/src/browser/preferences-tree-widget.ts [hunk 1]
```diff
@@ -313,12 +317,19 @@ export class PreferencesEditorsContainer extends DockPanel {
 
         super.onAfterAttach(msg);
         this.onInitEmitter.fire(undefined);
+        this.toDispose.push(
+            this.labelProvider.onDidChange(() => {
+                // Explicitly update the icon for the user preference editor widget.
+                this.userPreferenceEditorWidget.title.iconClass = this.labelProvider.getIcon(new URI('settings.json'));
```
Comment (akosyakov) [inline packages/preferences/src/browser/preferences-tree-widget.ts]: what about workspace preference editor widget?

Comment (vince-fugnitto) [reply packages/preferences/src/browser/preferences-tree-widget.ts]: > what about workspace preference editor widget?

I originally asked https://github.com/eclipse-theia/theia/pull/7011#issuecomment-580057029 because I was confused as why the workspace icon was updated and the user one wasn't. At the moment the workspace icon does get updated but I can be explicit here as well.

File: packages/preferences/src/browser/preferences-tree-widget.ts [hunk 2]
```diff
@@ -313,12 +317,19 @@ export class PreferencesEditorsContainer extends DockPanel {
 
         super.onAfterAttach(msg);
         this.onInitEmitter.fire(undefined);
+        this.toDispose.push(
```
Comment (akosyakov) [inline packages/preferences/src/browser/preferences-tree-widget.ts]: It should be toDisposeOnDetach otherwise a new listener will be added on each drag and drop

**Comment by elaihau** [comment]
I tested in gitpod with both Chrome and Firefox:

File icons across all tabs in the preference editor now look consistent.

Tested all 4 Icon themes, they all look good.

**Comment by elaihau** [comment]
One thing needs improvement though:

In a multi-root workspace the icons could look inconsistent.

Screenshot from 2020-02-02 21-24-12

the screenshot was from Chrome.

**Comment by akosyakov** [comment]
Code-wise looks good, @elaihau could you finish the review please.

**Comment by elaihau** [comment]
> Code-wise looks good, @elaihau could you finish the review please.

Sure I will see what Vincent says regarding this comment https://github.com/eclipse-theia/theia/pull/7011#issuecomment-581211425

**Comment by vince-fugnitto** [comment]
> One thing needs improvement though:
> 
> In a multi-root workspace the icons could look inconsistent.
> 
> Screenshot from 2020-02-02 21-24-12
> 
> the screenshot was from Chrome.
> I understand why it happens - and I am not sure if it is in the scope of this PR.

Could you help me reproduce the problem you've experienced @elaihau ?

I tried on my end with multiple different file-icon themes and experienced the following:

_Theia_

Screen Shot 2020-02-03 at 8 30 47 AM


_Seti_

Screen Shot 2020-02-03 at 8 30 26 AM


_Minimal_

Screen Shot 2020-02-03 at 8 30 36 AM


_None_

Screen Shot 2020-02-03 at 8 30 57 AM

**Comment by elaihau** [comment]
@vince-fugnitto this is what i see from gitpod. browser is Chrome.

Peek 2020-02-03 20-00

**Comment by vince-fugnitto** [comment]
@elaihau do you expect that the workspace file should display the `.json` icon?
It is a different type of file (`.theia-workspace`) and is displayed different in other areas (explorer, file dialog, quick-file-open).

**Comment by elaihau** [comment]
> @elaihau do you expect that the workspace file should display the `.json` icon?
> It is a different type of file (`.theia-workspace`) and is displayed different in other areas (explorer, file dialog, quick-file-open).

i don't expect the code to be smart enough to detect json data from a file that doesn't have the ".json" extension.

the question in my mind is: why is the workspace tab header and file icon displayed properly when the multi-root workspace is created, but refreshed into "Untitled.work-space" after the execution of "change file icon theme" command? 

like i said earlier, i am not sure if it is in the scope of this PR, and i am OK with not fixing this scenario

**Comment by elaihau** [comment]
i will approve this pr after you fix the travis biuld

**Comment by vince-fugnitto** [comment]
> i will approve this pr after you fix the travis biuld

There seems to be an issue with the Windows build at the moment for multiple pull-requests :(
https://github.com/eclipse-theia/theia/issues/7064

**Comment by vince-fugnitto** [comment]
> > @elaihau do you expect that the workspace file should display the `.json` icon?
> > It is a different type of file (`.theia-workspace`) and is displayed different in other areas (explorer, file dialog, quick-file-open).
> 
> i don't expect the code to be smart enough to detect json data from a file that doesn't have the ".json" extension.
> 
> the question in my mind is: why is the workspace tab header and file icon displayed properly when the multi-root workspace is created, but refreshed into "Untitled.work-space" after the execution of "change file icon theme" command?

What do you think should be the correct behavior, to display `Workspace` or the `*.theia-workspace` name?

**Comment by elaihau** [comment]
> There seems to be an issue with the Windows build at the moment for multiple pull-requests :(
> #7064

yea your latest css change shouldn't have the power of failing the build :)



> What do you think should be the correct behavior, to display `Workspace` or the `*.theia-workspace` name?

as a user i would expect the tab header text "workspace" stays unchanged.
please double check with others in the team. it is just my opinion.

**Comment by vince-fugnitto** [comment]
> > There seems to be an issue with the Windows build at the moment for multiple pull-requests :(
> > #7064
> 
> yea your latest css change shouldn't have the power of failing the build :)

I hope not haha :)

> > What do you think should be the correct behavior, to display `Workspace` or the `*.theia-workspace` name?
> 
> as a user i would expect the tab header text "workspace" stays unchanged.
> please double check with others in the team. it is just my opinion.

I'll see what I can do :) I believe vscode keeps it as `workspace` as well.

**Comment by vince-fugnitto** [comment]
@elaihau it should be fixed in the latest iteration :)

**Comment by elaihau** [comment]
> @elaihau it should be fixed in the latest iteration :)

yep, i played with it one more time and it looks good.
Thank you for your work !
