### PR TITLE
plugin-ext: default the folderExpanded icon

### LINKED ISSUE #12727: Unexpected folder behavior with file icon theme contribution from VS Code extension
### Bug Description:
I was playing around creating a file icon theme with a VS Code extension. My theme has but one icon--it tries to replace what's shown for a folder. 

And it works...kind of. My icon is shown when the folder is collapsed, but isn't shown when the folder is expanded. In VS Code, my icon override is shown in both collapsed and expanded states.

In Theia, it ends up looking like this:
image
image

BTW, when the default icon theme is active, the folder icon is shown in both states. 

### Steps to Reproduce:
```
git clone -b icon_themes https://github.com/jcortell68/theiasandbox
cd theiasandbox
yarn
yarn start:electron
```
Choose `My File Icon Theme` as the icon theme in Theia's preferences.

### Additional Information

- Operating System: Windows
- Theia Version: 1.39

### PR DESCRIPTION
**Pull request by cdamus**
#### What it does

In file icon themes, VS Code will use the `"folder"` icon also for expanded folders in the case that the theme omits the `"folderExpanded"` entry.

This PR implements the same fall-back in Theia for consistency.

Fixes #12727

#### How to test

1. Follow the OP's directions in #12727 to clone and build a same `myext` extension with a custom file icon theme.
2. Link the `myext` extension package into your `plugins/` folder.
3. As directed in the issue description, launch Theia and select the "My File Icon Theme" file icon theme.
4. See that the custom folder icon is shown in both expanded and collapsed states.

Furthermore, edit the file icon theme in the `myext` to

- set a different icon (the extension `resources/` conveniently includes additional icons) as the `"folderExpanded"` and see that it works as expected, showing that icon in expanded state and the other in collapsed state
- set `"folderExpanded": null` or `"folderExpanded": ""` to explicitly ask for no icon for expanded state and see that this also works

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/plugin-ext/src/main/browser/plugin-icon-theme-service.ts [hunk 1]
```diff
@@ -390,6 +390,12 @@ export class PluginIconTheme extends PluginIconThemeDefinition implements IconTh
     ): void {
         if (associations.folder) {
             accept(associations.folder, this.folderIcon);
+            if (!('folderExpanded' in associations)) {
```
Comment (msujew) [inline packages/plugin-ext/src/main/browser/plugin-icon-theme-service.ts:393]: Suggestion: Maybe use the following, as it is more type safe?
```suggestion
            if (associations.folderExpanded === undefined) {
```

**Review by msujew — APPROVED** [review]
Looks good to me 👍

File: packages/plugin-ext/src/main/browser/plugin-icon-theme-service.ts (hunk 1 above)
Comment (msujew) [reply packages/plugin-ext/src/main/browser/plugin-icon-theme-service.ts]: Right, that was my thought as well.

**Comment by jcortell68** [comment]
@cdamus Thanks for fixing this!
