### PR TITLE
fix debug exception height computation

### LINKED ISSUE #8225: node debug exception breakpoint stripe issues
### Bug Description:

When stopping with node debugger over an exception breakpoint there is a strip with exception stack trace that cover the program code behind.
I would expect the code to move down (like in vs code) or to make this stripe closable by end user.

Theia:
image

Vscode:
image

See how line 4 and 5 are before and after the stripe so nothing gets lost.

Another issue with the stripe is that it stays even when openning another code editor tabs on the same line...

### Steps to Reproduce:

Create a.js script:

```javascript
var a = 5;
console.log(a);
if (a>2) {
    throw new Error("Error");
}
console.log("End");
```

Create node launcher:
```json
{
"type": "node",
"request": "launch",
"name": "Launch Program",
"program": "${workspaceFolder}/a.js",
"runtimeExecutable": "node"
}
```

- From debug pane set "Uncought Exceptions" breakpoint.
- Launch "Launch Program"

Now progran stops on exception breakpoint with:
- Stripe covering the code. 
- When moving to another opened tab the stripe stays.

### Additional Information

- Operating System: Windows, debian
- Theia Version: master

### PR DESCRIPTION
**Pull request by akosyakov**
Signed-off-by: Anton Kosyakov <anton.kosyakov@typefox.io>

#### What it does

- fix #8225: fix debug exception height computation

#### How to test

- create a.js file with following content:
```
var a = 5;
console.log(a);
if (a>2) {
    throw new Error("Error");
}
console.log("End");
```

- use `Launch with Node.js` debug configuration to debug it
- enable exception breakpoint
- rerun the debug configuration again
- the exception breakpoint should not overflow editor content
- it should stay the same when you modify a file
- when you switch to another file the exception widget should not be visible
- but should appear when you come back

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by danidoedel** [comment]
The margin at the bottom is now bigger than the one at the top. Is that intended behavior? According to the screenshot in the ticket it seems to be equal for VS Code. Just wondering 😉

**Comment by akosyakov** [comment]
@danidoedel I've noticed it too. That's because zone (distance between lines) height is computed by Monaco, but content height is by browser. If it try to match it then with each edit content height grows by 2px which leads to overflow eventually. I guess it is the same issue in VS Code.

**Comment by DoroNahari** [comment]
I tried this change on gitpod now and it doesn't worked well for me:
image

**Comment by akosyakov** [comment]
@DoroNahari hm, I cannot reproduce it. Are sure that you are trying Theia from this PR, not Gitpod Theia? on the image below it is a tab without Gitpod logo:
Screenshot 2020-08-16 at 14 24 22

@vince-fugnitto @amiramw Could you try to reproduce?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto @amiramw Could you try to reproduce?

I verified again using Gitpod and it worked correctly:

Screen Shot 2020-08-16 at 11 43 32 AM

File: packages/debug/src/browser/editor/debug-editor-model.ts [hunk 1]
```diff
@@ -175,7 +175,7 @@ export class DebugEditorModel implements Disposable {
 
     protected async toggleExceptionWidget(): Promise<void> {
         const { currentFrame } = this.sessions;
-        if (!currentFrame) {
+        if (!currentFrame || !currentFrame.source || currentFrame.source.uri.toString() !== this.uri.toString()) {
```
Comment (amiramw) [inline packages/debug/src/browser/editor/debug-editor-model.ts:178]: maybe `currentFrame?.source?.uri?.toString() !== this.uri.toString()`

**Comment by akosyakov** [comment]
@amiramw Could you try again? resizing should be handled as well now

**Comment by amiramw** [comment]
Resizing is responding well now. 👍

**Comment by akosyakov** [comment]
@amiramw Could you check please with @DoroNahari as well? If you can do it offline. It is important for me that we don't overlook something.

**Comment by DoroNahari** [comment]
LGTM
