### PR TITLE
GH-7347: Added scroll-lock to the Output view

### LINKED ISSUE #7008: [shell] Widget activation causes a resource leak
### Description
 

In a downstream project, I have updated to recent Theia and it started to fail with a resource leak. I added an example to reproduce it. Note: `yourViewContribution.openView({ activate: true })` causes the leak, `yourViewContribution..openView({ reveal: true })` does not. I think the bug is here

https://github.com/eclipse-theia/theia/blob/914e9e2ec39e55a61981eb8150198d6524a85827/packages/core/src/browser/shell/application-shell.ts#L968

And this is the actual problem, the condition will be `false`, unless I manually activate the `Output` view which does not make sense.

https://github.com/eclipse-theia/theia/blob/914e9e2ec39e55a61981eb8150198d6524a85827/packages/core/src/browser/shell/application-shell.ts#L981

**Workaround**:
Use `yourViewContribution..openView({ reveal: true })`.

### Reproduction Steps

Start the example app from here: https://github.com/eclipse-theia/theia/pull/7007

CC: @akosyakov 

**OS and Theia version:**

**Diagnostics:**

### LINKED ISSUE #7347: [output] Implement output scroll-lock
### Description
 
It should be possible to lock a channel in the output view. If a channel is locked, incoming messages must not change the selected channel.

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

### PR DESCRIPTION
**Pull request by kittaakos**
#### What it does

 - Adds a scroll-lock to the Output view,
 - Removes the `@theia/output` dependency from the `@theia/languages` extension,
 - Replaces the Output view with a `monaco` editor,
 - Adds context menu to the Output view,
 - Removes the `<no output yet>` when there is no output on the selected channel,
 - Fixes a runtime error when creating an in-memory (no URI) `monaco.editor.ITextModel`,
 - Can add decoration via `append` (previously it was supported with `appendLine` only),
 - Aligns the `OutputChannel` API with VS Code (via commands), and
 - Adds quick pick for _showing_, _hiding_, and _closing_ and output channel.

#### How to test

 - You can lock the scrolling in the view,
 - You can use the context menu from the Output view,
 - You can clear the Output view,
 - You can show, hide and close output channels from the _Command Palette_,
 - Clicking on the tab or in the widget sets the focus properly on the widget. You can see the bluish focus color (with the dark theme) when it's active. Also, there are no warnings due to widget did not activate in the logs (#7008),
 - You can alter the max output line count from the preferences, the output scales, (set it to e.g. 20)
 - Once you are done with the testing, make sure you dispose one of the output channels (use the `Output: Close Output Channel...` command), refresh the browser, make a memory snapshot, verify that the previously disposed channel is not in the snapshot.

 Feel free using the interim commands for populating the output channels with some dummy inputs:
   - `API Sample: Post Date.now() to the 'X' channel.`
   - `API Sample: Stop Date.now() on 'X' channel.`

Closes #7347.
Closes #7008.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by marechal-p** [comment]
The locked behavior feels weird: in VS Code, it just disables auto-scrolling, but you can still manually scroll around. This implementation prevents me from manually scrolling elsewhere. Is this intended?

File: packages/output/src/common/output-channel.ts [hunk 1]
```diff
@@ -103,20 +153,35 @@ export class OutputChannelManager implements Disposable {
...
 
-export class OutputChannel {
+export class OutputChannel implements Disposable {
 
     private readonly visibilityChangeEmitter = new Emitter<{ visible: boolean }>();
+    private readonly lockedChangeEmitter = new Emitter<{ locked: boolean }>();
     private readonly contentChangeEmitter = new Emitter<OutputChannel>();
+    private readonly toDispose = new DisposableCollection(
+        this.visibilityChangeEmitter,
+        this.lockedChangeEmitter,
```
Comment (kittaakos) [inline packages/output/src/common/output-channel.ts:171]: `lockedChangeEmitter` -> `lockChangeEmitter`

File: packages/output/src/common/output-channel.ts [hunk 2]
```diff
@@ -78,7 +119,16 @@ export class OutputChannelManager implements Disposable {
     }
 
     deleteChannel(name: string): void {
+        const existing = this.channels.get(name);
+        if (!existing) {
+            console.warn(`Could not delete channel '${name}'. The channel does not exist.`);
+            return;
+        }
         this.channels.delete(name);
+        const toDisposePerChannel = this.toDisposeOnChannelDeletion.get(name);
```
Comment (kittaakos) [inline packages/output/src/common/output-channel.ts:128]: `toDisposePerChannel` -> `toDispose`.

File: packages/output/src/common/output-channel.ts [hunk 3]
```diff
@@ -14,32 +14,60 @@
...
     protected readonly listOrSelectionEmitter: Emitter<void> = new Emitter<void>();
+    protected readonly channelLockedEmitter = new Emitter<OutputChannel>();
     readonly onChannelDelete = this.channelDeleteEmitter.event;
     readonly onChannelAdded = this.channelAddedEmitter.event;
     readonly onSelectedChannelChange = this.selectedChannelEmitter.event;
     readonly onListOrSelectionChange = this.listOrSelectionEmitter.event;
+    readonly onLockChange = this.channelLockedEmitter.event;
 
     protected toDispose = new DisposableCollection();
+    protected toDisposeOnChannelDeletion = new Map<string, DisposableCollection>();
```
Comment (kittaakos) [inline packages/output/src/common/output-channel.ts:39]: `toDisposeOnChannelDeletion` -> `toDisposePerChannel`

File: packages/output/src/browser/output-widget.tsx [hunk 4]
```diff
@@ -14,136 +14,244 @@
...
+    get name(): string {
+        return this.channel.name;
     }
+
+    private get anchorId(): string {
+        return `output-channel-${this.name}-anchor`;
+    }
+
+    private get anchor(): HTMLElement | undefined {
+        const anchor = document.getElementById(this.anchorId);
```
Comment (kittaakos) [inline packages/output/src/browser/output-widget.tsx:245]: TODO: The React way `ref={this.setRef}` would be better, however, the original logic did it via `getElementById` lookup too.

File: packages/output/src/browser/output-widget.tsx [hunk 5]
```diff
@@ -14,136 +14,244 @@
...
+                }
+            }, 1);
+        }
+    }
+
+    protected onActivateRequest(message: Message): void {
+        super.onActivateRequest(message);
+        const anchor = this.anchor;
+        if (anchor && !this.channel.isLocked) {
+            anchor.focus();
```
Comment (kittaakos) [inline packages/output/src/browser/output-widget.tsx:204]: Same as for anchor 👇

File: packages/output/src/browser/output-widget.tsx [hunk 6]
```diff
@@ -14,136 +14,244 @@
...
-        return <div id={OutputWidget.IDs.CONTENTS}>{this.renderLines()}</div>;
+    private get selectedChannel(): OutputChannel | undefined {
+        return this.outputChannelManager.selectedChannel;
     }
 
-    protected renderLines(): React.ReactNode[] {
-        let id = 0;
-        const result = [];
+    private getChannelWidget(name: string): OutputChannelWidget | undefined {
+        for (const widget of toArray(this.channelsContainer.widgets())) {
```
Comment (kittaakos) [inline packages/output/src/browser/output-widget.tsx:131]: TODO: Use `find`.

**Comment by akosyakov** [comment]
I see that output content is rendered even if the output widget is not visible. We should not render anything if the output widget is not selected and visible. It will cause performance issues.

**Comment by kittaakos** [comment]
> I see that output content is rendered even if the output widget is not visible. We should not render anything if the output widget is not selected and visible.

Yes. Otherwise, you cannot keep the scroll-bar.

**Comment by akosyakov** [comment]
> Yes. Otherwise, you cannot keep the scroll-bar.

VS Code does not keep it as well and use only one Monaco editor. I also don't like an idea of having many Monaco editors later. I've seen before in profiling session that `text.split(/[\n\r]+/)` is hot spot sometime.

**Comment by kittaakos** [comment]
> I've seen before in profiling session that `text.split(/[\n\r]+/)` is hot spot

Yes, but I have not changed that within this PR.

**Comment by akosyakov** [comment]
> Yes, but I have not changed that within this PR.

On master we never render a channel if it is not selected and visible. With this PR whenever the ouput view is attached all channels get constantly rendered making situation much worse.

Plus if we switch to Monaco editor it forces us to have many instances instead of only one editor which content gets replaced when a channel is switched.

**Comment by kittaakos** [comment]
> if we switch to Monaco editor

@akosyakov, I could not pull in the `@theia/monaco` dependency into `@theia/output`. Sadly, `@theia/languages` already depends on `@theia/output`. There is a cycle. Is it OK to depend on `@theia/monaco-editor-core`? We can also clean up the dependencies first, then target `@theia/monaco` instead. Both have their pros and cons. What do you think? Thanks!

**Comment by akosyakov** [comment]
> Sadly, @theia/languages already depends on @theia/output.

We are going to drop monaco-languageclient then `@theia/languages` will be removed.

**Comment by kittaakos** [comment]
> We are going to drop monaco-languageclient then `@theia/languages` will be removed.

What should we do before we drop `@theia/languages`? Thank you!

**Comment by marechal-p** [comment]
There is a bug when I open the output view for the first time, width is too small:

image

It is fixed after switching channels.

**Comment by kittaakos** [comment]
> > We are going to drop monaco-languageclient then `@theia/languages` will be removed.
> 
> What should we do before we drop `@theia/languages`? Thank you!

@akosyakov, ping.

**Comment by kittaakos** [comment]
> What should we do before we drop `@theia/languages`? Thank you!

I can create Output commands and invoke them from `@theia/languages`. It's just a string so no hard dependencies are required. Thoughts?

**Comment by kittaakos** [comment]
> create Output commands

We could align the new commands with the [current VS Code `OutputChannel` API](https://github.com/microsoft/vscode/blob/a4208b1e976e1a2bd4e276718e1d6a19ba131c87/src/vs/vscode.d.ts#L5121-L5174).

**Comment by akosyakov** [comment]
> What should we do before we drop @theia/languages? Thank you!

https://github.com/eclipse-theia/theia/issues/7100 It is in plans to work on it next months. cc @svenefftinge @marcdumais-work

**Comment by kittaakos** [comment]
> The lock states are handled per channel, just like in VS Code.

The VS Code guys have removed the per channel `lock` property and made it global per view: https://github.com/microsoft/vscode/commit/849aadb72c43dffa8018ec23bca82e6c35d30b3c#diff-d6f53b2a222288cbc239a4df801596efL108-L112

**Comment by kittaakos** [comment]
I was wondering if we need to show the `<no output yet>` in the Output if there is no output. I've never seen a terminal/log-view that shows no output yet when there is no output. Showing nothing has the same semantics. VS Code does not show anything either:

Screen Shot 2020-05-18 at 10 25 15

What do you think? If we still need this, I can make it happen with `editor.addOverlayWidget()`. If there is no interest in deciding whether we need or not I won't include the `<no output yet>` label in the PR.

CC: @akosyakov , @marcdumais-work

**Comment by marcdumais-work** [comment]
> I was wondering if we need to show the <no output yet> in the Output if there is no output.

Hi @kittaakos ,

It does seem strange to have this, I agree. I would not miss it if it were removed. 

Searching a bit, I think this came from here: https://github.com/eclipse-theia/theia/pull/1040#discussion_r160767973

**Comment by kittaakos** [comment]
> It does seem strange to have this, I agree. I would not miss it if it were removed.

👍 

> Searching a bit, I think this came from here: [#1040 (comment)](https://github.com/eclipse-theia/theia/pull/1040#discussion_r160767973)

Thank you, great help!

**Comment by kittaakos** [comment]
The PR is ready for the review, please see the updated description.

**Comment by marechal-p** [comment]
Only concern I have: Is the `Find Command` item supposed to be in the Output View context menu?

image

**Comment by kittaakos** [comment]
> Is the `Find Command` item supposed to be in the Output View context menu?

Thanks for asking! It's intentional. Actually, I do not mind if it's there or not, I won't ever use it, but I wanted to align the context-menu with VS Code:

Screen Shot 2020-05-27 at 18 38 29

VS Code has it as _Comannd Palette..._, we call it [_Find Commands..._](https://github.com/eclipse-theia/theia/blob/99a7aa3c10e00de269329e48b0929fb5b7301dd7/packages/core/src/browser/quick-open/quick-command-contribution.ts#L51-L52).

I leave the decision to the community.

File: packages/output/src/browser/output-widget.tsx [hunk 7]
```diff
@@ -14,137 +14,238 @@
...
-                if (outputChannelLine.severity === OutputChannelSeverity.Error) {
-                    className = 'theia-output-error';
-                } else if (outputChannelLine.severity === OutputChannelSeverity.Warning) {
-                    className = 'theia-output-warning';
-                }
-                for (const line of lines) {
-                    result.push(<div className={`theia-output-lines ${className}`} key={id++}>{line}</div>);
-                }
+    get isLocked(): boolean {
+        return !!this.state.locked;
```
[the remark this answers is not in the document]
Comment (kittaakos) [reply packages/output/src/browser/output-widget.tsx:177]: VS Code calls it `scrollLock`, I wanted to keep it aligned with the _lock_/_unlock_ verbs but I do not mind changing if the community requests this. Otherwise, I am going to leave as is.

**Comment by lmcbout** [comment]
I noticed the context menu on MAC seems different than the one in UBUNTU. I have the same as @marechal-p  above.

I vote to keep the command palette.

Note: When I add a new plugins ( vscode-coverage-gutters-2.4.3.vsix) , I noticed that the context menu is modified in VSCode, but the context menu in Theia is not modified.

Note2: I think it would be nice also to have in the context menu an entry: "Copy all" to copy all the data from that output channel or "Select all"

**Comment by kittaakos** [comment]
> I noticed the context menu on MAC seems different than the one in UBUNTU. I have the same as @marechal-p above.

FYI: My [screenshot](https://github.com/eclipse-theia/theia/pull/7570#issuecomment-634791882) was from VS Code, and not Theia.

> Note: When I add a new plugins ( vscode-coverage-gutters-2.4.3.vsix) , I noticed that the context menu is modified in VSCode, but the context menu in Theia is not modified.

👍 Feel free to open a feature request for it.

> Note2: I think it would be nice also to have in the context menu an entry: "Copy all" to copy all the data from that output channel or "Select all"

Sounds great, can you please file a feature request so that we won't forget to implement it. Thanks!

File: packages/monaco/src/browser/monaco-editor-model.ts [hunk 8]
```diff
@@ -42,6 +45,44 @@ export interface MonacoModelContentChangedEvent {
...
+        resource: Resource,
+        m2p: MonacoToProtocolConverter,
+        p2m: ProtocolToMonacoConverter,
+        options?: { encoding?: string | undefined }
+    ): MaybePromise<MonacoEditorModel>;
+
+}
+
+@injectable()
+export class MonacoEditorModelFactory {
```
Comment (akosyakov) [inline packages/monaco/src/browser/monaco-editor-model.ts:63]: Have you seen `MonacoTextModelService.registerTextModelContentProvider`? Should not we rather implement it instead of adding new concepts?

Also it should be inlined into  `MonacoTextModelService`, only this service should be used to create models, nothing else. `MonacoEditorModelFactoryHandler` then could be renamed to `MonacoEditorModelFactory`.

File: packages/monaco/src/browser/monaco-editor-provider.ts [hunk 9]
```diff
@@ -35,11 +35,22 @@ import { MonacoBulkEditService } from './monaco-bulk-edit-service';
 
 import IEditorOverrideServices = monaco.editor.IEditorOverrideServices;
 import { ApplicationServer } from '@theia/core/lib/common/application-protocol';
-import { OS } from '@theia/core';
+import { OS, MaybePromise, ContributionProvider, Prioritizeable } from '@theia/core';
 import { KeybindingRegistry, OpenerService, open, WidgetOpenerOptions } from '@theia/core/lib/browser';
 import { MonacoResolvedKeybinding } from './monaco-resolved-keybinding';
 import { HttpOpenHandlerOptions } from '@theia/core/lib/browser/http-open-handler';
 
+export const MonacoEditorOptionsProvider = Symbol('MonacoEditorOptionsProvider');
```
Comment (akosyakov) [inline packages/monaco/src/browser/monaco-editor-provider.ts:43]: I would prefer to have one contribution which is scheme based instead of priotirizable. I don't think there will be many use cases and they can be resolved by `scheme` only. Otherwise we introduce new contribution point in ad-hoc manner to satisfy a single use case. It would be better to move in direction of some simple design, something like:
```ts
export interface MonacoEditorFactory {
   readonly scheme: string;
   create(model: MonacoEditorModel, defaultsOptions: MonacoEditor.IOptions, defaultServices: IEditorOverrideServices): MonacoEditor;
}

@injectable()
export class MonacoEditorProvider {
    @inject(ContributionProvider)
    @named(MonacoEditorFactory)
    protected readonly factories: ContributionProvider<MonacoEditorFactory>;
}
```

`MonacoEditorFactory` could be an abstract class not an interface providing template methods to override scheme, options and services for subclasses.

If there is a middle ground for now which does not require much refactorings but moves in direction of design above i would be fine too.

File: packages/monaco/src/browser/monaco-editor-model.ts (hunk 8 above)
Comment (kittaakos) [reply packages/monaco/src/browser/monaco-editor-model.ts:63]: > Have you seen `MonacoTextModelService.registerTextModelContentProvider`? Should not we rather implement it instead of adding new concepts?

I do not get this, the current implementation is a NOOP. How should this work?

File: packages/monaco/src/browser/monaco-editor-provider.ts (hunk 9 above)
Comment (kittaakos) [reply packages/monaco/src/browser/monaco-editor-provider.ts]: I made these changes, thanks for the pointer. :+1:

File: packages/monaco/src/browser/monaco-editor-model.ts (hunk 8 above)
Comment (kittaakos) [reply packages/monaco/src/browser/monaco-editor-model.ts]: I could not implement it without two distinct ~contributions~ factories; one for the mode, the other for the editor. Let me know what you think.

File: packages/monaco/src/browser/monaco-text-model-service.ts [hunk 10]
```diff
@@ -14,13 +14,27 @@
...
 import { MonacoEditorModel } from './monaco-editor-model';
 
+export const MonacoEditorModelFactory = Symbol('MonacoEditorModelFactory');
+export interface MonacoEditorModelFactory {
+
+    readonly scheme: string;
+
+    createModel(
+        resource: Resource,
+        m2p: MonacoToProtocolConverter,
```
Comment (akosyakov) [inline packages/monaco/src/browser/monaco-text-model-service.ts:31]: I don't think we need to pass converters. They can be injected by subclasses. Or we can convert interface to abstract class to replace interface + symbol and inject converters for all subclasses.

File: packages/monaco/src/browser/monaco-editor-model.ts (hunk 8 above)
Comment (akosyakov) [reply packages/monaco/src/browser/monaco-editor-model.ts]: ok, let's go with a model factory

File: packages/output/src/browser/output-contribution.ts [hunk 11]
```diff
@@ -14,100 +14,168 @@
...
     }
 
-    protected withWidget<T>(widget: Widget | undefined = this.tryGetWidget(), cb: (problems: OutputWidget) => T): T | false {
-        if (widget instanceof OutputWidget && widget.id === OUTPUT_WIDGET_KIND) {
-            return cb(widget);
-        }
-        return false;
+    open(uri: URI, options?: OpenerOptions): Promise<OutputWidget> {
+        return new Promise<OutputWidget>((resolve, reject) => {
+            if (!OutputUri.is(uri)) {
```
Comment (akosyakov) [inline packages/output/src/browser/output-contribution.ts:162]: why not to use `async/await`? this method will hang if something goes wrong in `openView` or  `setInptu`

File: packages/output/src/browser/output-resource.ts [hunk 12]
```diff
@@ -0,0 +1,58 @@
...
+
+export class OutputResource implements Resource {
+
+    protected _textModel: monaco.editor.ITextModel | undefined;
+    protected onDidChangeContentsEmitter = new Emitter<void>();
+    protected toDispose = new DisposableCollection(
+        this.onDidChangeContentsEmitter
+    );
+
+    constructor(readonly uri: URI, readonly editorModel: Deferred<MonacoEditorModel>) {
```
Comment (akosyakov) [inline packages/output/src/browser/output-resource.ts:30]: we should better to pass `MonacoEditorModel` here, otherwise there can be a race that resource disposed but model was not resolved yet.

**Comment by akosyakov** [comment]
@kittaakos does it resolves https://github.com/eclipse-theia/theia/issues/2702 and https://github.com/eclipse-theia/theia/issues/2385 as well?

File: packages/output/src/browser/output-resource.ts (hunk 12 above)
Comment (kittaakos) [reply packages/output/src/browser/output-resource.ts:30]: > we should better pass MonacoEditorModel here

I am with you but we can't, that's the point. If you have a better idea without changing the API too much, we can adjust it. But such vague advice "we should not pass" does not help much.

From [here](https://github.com/eclipse-theia/theia/pull/7570/files#diff-c288f39cebca6c7afc5167fe59b166ebR194-R196):
> // We have to register the resource first, because `textModelService#createModelReference` will require it
        // right after creating the monaco.editor.ITextModel.
        // All `append` and `appendLine` will be deferred until the underlying text-model instantiation.

Comment (akosyakov) [reply packages/output/src/browser/output-resource.ts:30]: ok, please add a check in `then` closure that if `toDispose.disposed` already then we should dispose the model and exit.

Thinking about it we should not dispose a model but a reference. Model will be auto disposed when all references are disposed. If we do differently there can be another race condition there a channel can end up with a disposed model.

Comment (kittaakos) [reply packages/output/src/browser/output-resource.ts:30]: Let's do that. Thanks!

Comment (kittaakos) [reply packages/output/src/browser/output-resource.ts:30]: > Thinking about it we should not dispose a model but a reference.

Great pointer. Well, it was a bug. I have fixed it now.  👍 We cannot pass the deferred `MonacoEditorModel`, but I had to use the `monaco.editor.IReference<MonacoEditorModel>` instead.

> please add a check in `then` closure that if `toDispose.disposed`

Sorry, which `toDispose.disposed` do you mean?

Comment (akosyakov) [reply packages/output/src/browser/output-resource.ts]: I meant:
```ts
this.editorModelRef.promise.then(modelRef => {
            if (this.toDispose.disposed) {
                modelRef.dispose();            
                return;
            }
            const textModel = modelRef.object.textEditorModel;
            this._textModel = textModel;
            this.toDispose.push(modelRef);
            this.toDispose.push(this._textModel!.onDidChangeContent(() => this.onDidChangeContentsEmitter.fire()));
        });
```

**Comment by kittaakos** [comment]
Thank you all for the review!

File: packages/output/src/browser/output-widget.tsx [hunk 13]
```diff
@@ -14,137 +14,238 @@
...
+    constructor(options?: DockPanel.IOptions) {
+        super(options);
+        NoopDragOverDockPanel.prototype['_evtDragOver'] = (event: IDragEvent) => {
+            event.preventDefault();
+            event.stopPropagation();
+            event.dropAction = 'none';
+        };
+    }
+
+}
```
Comment (colin-grant-work) [inline packages/output/src/browser/output-widget.tsx:251]: @kittaakos, it looks like this code is responsible for #10932. Do you recall the motivation for making the Output view undroppable?

Comment (kittaakos) [reply packages/output/src/browser/output-widget.tsx:251]: Thanks for taking care of this!

> it looks like this code is responsible for #10932.

Do you want to have the same behavior as the _Problem_ view? Split the view like this:

https://user-images.githubusercontent.com/1405703/172688966-70e94802-d816-46f0-9dab-9811712cef70.mp4

It is not possible with the _Output_ view; it's a bug.
 
The main reason I used a custom panel implementation was to avoid dropping an editor into the panel. Like this:

https://user-images.githubusercontent.com/1405703/172689342-a5101c63-3a55-4642-a38d-2f9db9bea451.mp4

I hope this helps. Let me know if there is anything I can assist you with fixing this.

Comment (colin-grant-work) [reply packages/output/src/browser/output-widget.tsx:251]: Thanks for the screen casts; they help clarify things quite a bit. I didn't realize the Output widget behaved as a panel with each of the channels as a child widget. I think it would be nice if the Output view could allow drops as other widgets do, to either place the new widget on the bottom tabbar or split the bottom pane. Otherwise, it feels like a bug, even though it's deliberate, since it isn't clear to users why the Output widget would be different from other widgets in this respect.

Comment (colin-grant-work) [reply packages/output/src/browser/output-widget.tsx:251]: It looks like something like this might do the trick:

```typescript

/**
 * Customized `DockPanel` that does not allow dropping widgets into it.
 * Intercepts `'p-dragover'` events, and sets the desired drop action to `'none'`.
 */
class NoopDragOverDockPanel extends DockPanel { }
const noop = () => { };
NoopDragOverDockPanel.prototype['_evtDragOver'] = noop;
NoopDragOverDockPanel.prototype['_evtDrop'] = noop;
NoopDragOverDockPanel.prototype['_evtDragLeave'] = noop;
```
By preventing the Output widget from handling any of those events, we pass them up to the bottom pane dock panel and allow it to handle them. What do you think of that?
