### PR TITLE
GH-6428: Refactored the built-in monaco commands.

### LINKED ISSUE #2756: [electron] Ctrl/Cmd+A does not select the content of the quick open item
This `Select All` functionality works in VS Code.

### LINKED ISSUE #6428: [electron] The `Select All` command executes incorrectly
### Description
 

I have forcefully enabled all menu items in electron to see the `Selection` menu (#6425). When I did a `Select All`, not the focus item was selected, but the monaco editor's content. It works perfectly in the browser.

Electron:
screencast 2019-10-21 19-16-51

Browser:
screencast 2019-10-21 19-19-16

Note, the `Select All` does not work in electron either when I close the editor and have the focus on an  `input`.

### Reproduction Steps

**OS and Theia version:**
macOS, f255f5a8c

**Diagnostics:**

### LINKED ISSUE #7460: Search behaves differently than it used to (and compared to VS code)
### Description
When searching in an editor (Cmd+F) is used to be able to jump to the next search result by pressing `enter`. Now, when pressing enter the editor gets the focus with the cursor placed at the last found result.

### Reproduction Steps
1. Open an editor
2. Open the search box (Cmd+F) and search for a string that's present in the editor
3. Press enter

**OS and Theia version:**
latest master

### LINKED ISSUE #7474: [core] Revisit core commands, such as Find, Replace, Select All, Undo, and `Redo`
### Description
 

Core commands do not have an active handler when no editors are open.

```
root ERROR Failed to execute command: Error: The command 'core.find' cannot be executed. There are no active handlers available for the command. (args: [null])
    at e.<anonymous> (https://a1b11df7-2f7c-4238-ba5e-663642a4eb98.ws-eu01.gitpod.io/bundle.js:1:88902)
    at https://a1b11df7-2f7c-4238-ba5e-663642a4eb98.ws-eu01.gitpod.io/bundle.js:1:85102
    at Object.next (https://a1b11df7-2f7c-4238-ba5e-663642a4eb98.ws-eu01.gitpod.io/bundle.js:1:85207)
    at https://a1b11df7-2f7c-4238-ba5e-663642a4eb98.ws-eu01.gitpod.io/bundle.js:1:84120
    at new Promise (<anonymous>)
    at a (https://a1b11df7-2f7c-4238-ba5e-663642a4eb98.ws-eu01.gitpod.io/bundle.js:1:83897)
    at e.executeCommand (https://a1b11df7-2f7c-4238-ba5e-663642a4eb98.ws-eu01.gitpod.io/bundle.js:1:88444)
    at e.executeKeyBinding (https://a1b11df7-2f7c-4238-ba5e-663642a4eb98.ws-eu01.gitpod.io/bundle.js:12:120459)
    at e.run (https://a1b11df7-2f7c-4238-ba5e-663642a4eb98.ws-eu01.gitpod.io/bundle.js:12:121395)
    at HTMLDocument.<anonymous> (https://a1b11df7-2f7c-4238-ba5e-663642a4eb98.ws-eu01.gitpod.io/bundle.js:12:290680)
```

The above error happens when you do `Ctr/Cmd+F` without an editor open. But you can try `Undo`, and `Redo` too by closing all editors and setting the focus to the SCM's `textArea` or SIW's `input`. 

Related: https://github.com/eclipse-theia/theia/pull/7339#issuecomment-605918781

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

### LINKED ISSUE #7483: [monaco] Select all does not work in inline, embedded editors
### Description
 

Originally from [here](https://github.com/eclipse-theia/theia/pull/7339#issuecomment-605918781):
 > Peek for references, do a select all in the inline editor. It is broken as the Monaco Command Registry works with the current editor and not the one that has the text focus; it ignores the embedded code editor.
screencast 2020-03-30 12-23-35

screencast 2020-03-30 12-23-35

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

### PR DESCRIPTION
**Pull request by kittaakos**
Signed-off-by: Akos Kitta <kittaakos@typefox.io>

#### What it does
Changes the way how we handle monaco commands, and hopefully providers a better UX for the `Undo`, `Redo`, and `Select All` commands. It is the fix for electron, as it 

### Test Plan:

- Preconditions:
   - If you are verify this in electron, you have to be avere of the non-dynamic nature of the application menu. (https://github.com/eclipse-theia/theia/issues/6425).
   - Run `Reset Workbench Layout`.
   - Open the SIW widget; the `input` widget has the focus.
- Steps:
   - Type _**foo**_ and press <kbd>Ctrl/⌘</kbd>+<kbd>A</kbd> (`Select All`). Assert: the `input` value is _**foo**_ and is selected.
   - Press <kbd>Del</kbd>. Assert: the `input` is empty.
   - Press <kbd>Ctrl/⌘</kbd>+<kbd>Z</kbd> (`Undo`). Assert: the `input` value is _**foo**_ and is selected.
   - Press <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>Z</kbd> (`Redo`). Assert: the `input` is empty.
   - Type _**bar**_ and select the `Selection` > `Select All` menu item. Assert: the input value is _**bar**_ and is selected.
   - Press <kbd>Del</kbd>. Assert: the `input` is empty.
   - Select the `Edit` > `Undo` menu item. Assert: the input is _**bar**_ and is selected. (Note: there is a bug here. The SIW widget's `input` does not listen on value change and does not re-run the query.)
   - Select the `Edit` > `Redo` menu item. Assert: the input is empty.

-----

- Preconditions:
   - If you are verify this in electron, you have to be avere of the non-dynamic nature of the application menu. (https://github.com/eclipse-theia/theia/issues/6425).
   - Open `theia` as a workspace in Theia.
   - Run `Reset Workbench Layout`.
   - Open the SIW widget; the `input` widget has the focus, type _**baz**_.
   - Open the `os.ts` module via the _Command Palette_. If it is opened in a preview mode, make sure the editor has the focus; the cursor blinks inside the editor.
- Steps:
   - Type _**foo**_ somewhere in the editor and press <kbd>Ctrl/⌘</kbd>+<kbd>Z</kbd> (`Undo`). Assert: _**foo**_ is not there.
   - Press <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>Z</kbd> (`Redo`). Assert: _**foo**_ is there.
   - Press <kbd>Ctrl/⌘</kbd>+<kbd>Z</kbd> (`Undo`). Assert: _**foo**_ is not there.
   - Press <kbd>Ctrl/⌘</kbd>+<kbd>A</kbd> (`Select All`). Assert: the editor content is selected.
   - Press <kbd>Esc</kbd>. Assert: the cursor blinks at the end of the file, nothing is selected.
   - Type _**bar**_ and select the `Edit` > `Undo` menu item. Assert: _**bar**_ is not there.
   - Select the `Edit` > `Redo` menu item. Assert: _**bar**_ is in the editor.
   - Set the focus (single-click) into the SIW's `input`.
   - Press <kbd>Ctrl/⌘</kbd>+<kbd>A</kbd> (`Select All`). Assert: _**baz**_ is selected.
   - Make sure the cursor blinks once again in the editor and select the `Selection` > `Select All` menu item. Assert: the editor content is selected.
   - Press <kbd>Esc</kbd>. Assert: the cursor blinks at the end of the file, nothing is selected.
   - Right-click on `isWindows` in the editor and select `Peek` > `Peek References` from the context menu. Assert: embedded editor is open. The cursor blinks on `isWindows` in the main editor.
   - Press <kbd>Ctrl/⌘</kbd>+<kbd>A</kbd> (`Select All`). Assert: the main editor content is selected.
   - Make sure the cursor blinks this time in the embedded editor and press <kbd>Ctrl/⌘</kbd>+<kbd>A</kbd> (`Select All`). Assert: the embbedded editor content is selected. (Fixes #7483)

----

🎖Let's verify other issues:
 - Inside the `os.ts` module, press <kbd>Ctrl/⌘</kbd>+<kbd>F</kbd>, type `is` into the search widget. If you press <kbd>Enter</kbd> (multiple times) the selection jumps to the next `is` occurrence position in the editor. Bonus: it works inside the embedded editor too. (Fixes #7460) 
 - If you are verifying the changes with the electron example (Fixes #6428), open the _Command Palette_ and make sure you can do `Undo`, `Redo`, and `Select All` from the keyboard. (Fixes #2756)
 - Close all editors and press <kbd>Ctrl/⌘</kbd>+<kbd>F</kbd>. Assert: no errors because of the missing handler for `core.find` command. (Fixes #7474)

----
TODOs:
 - [x] Verify [this](https://github.com/microsoft/vscode/issues/88610). From time to time, I can see the `Commiting pending changes before change accessor leaves due to read access.` warning when running the electron example. Hmm, but the logger code was removed by the VS Code guys in January. Let's double-check it. Verified ✅ (https://github.com/microsoft/vscode/commit/6beb75765e492b47e32554e093b77317fec397a8)

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

@akosyakov, @RomanNikitenko, here is an early preview of my changes. I am going to verify the behavior locally and write down the verification steps. Please take a look at my changes. Thank you!

### CODE REVIEW

File: packages/monaco/src/browser/monaco-command.ts [hunk 1]
```diff
@@ -122,19 +123,50 @@ export class MonacoEditorCommandHandlers implements CommandContribution {
...
+                        return true;
+                    }
+                    return false;
+                }
+            };
+        }
+
+        // Ouch :(
+        throw new Error(`Could not find monaco command with ID: ${id}`);
     }
```
Comment (akosyakov) [inline packages/monaco/src/browser/monaco-command.ts:166]: error logging is enough, no need to break the whole app startup

File: packages/core/src/browser/keybinding.ts [hunk 2]
```diff
@@ -91,6 +91,30 @@ export namespace KeybindingContexts {
...
+
+    isEnabled(): boolean {
+        return NativeTextInputFocusContext.is();
+    }
+
+    /**
+     * `true` if the argument is an `input` or a `textArea`. Otherwise, `false`.
+     * The `element` argument defaults to the "focused" DOM element (`document.activeElement`).
+     */
+    static is(element: Element | null = document.activeElement): element is HTMLInputElement | HTMLTextAreaElement {
```
Comment (akosyakov) [inline packages/core/src/browser/keybinding.ts:114]: I wonder why don't we inject `NativeTextInputFocusContext` and call `isEnabled`?

File: packages/monaco/src/browser/monaco-keybinding-contexts.ts [hunk 3]
```diff
@@ -41,3 +44,32 @@ export class MonacoStrictEditorTextFocusContext extends StrictEditorTextFocusCon
...
+ * It is enabled if the focus is on an `input` or `textArea` and not contained in a Monaco editor.
+ */
+@injectable()
+export class MonacoNativeTextInputFocusContext extends NativeTextInputFocusContext {
+
+    @inject(MonacoEditorProvider)
+    protected readonly editorProvider: MonacoEditorProvider;
+
+    isEnabled(): boolean {
+        return super.isEnabled() && !this.activeElementIsInEditor();
```
Comment (akosyakov) [inline packages/monaco/src/browser/monaco-keybinding-contexts.ts:59]: I think you can do `super.isEnabled() && !this.contextKeyService.match('editorFocus')`

docs for when keys: https://code.visualstudio.com/docs/getstarted/keybindings#_contexts

File: packages/monaco/src/browser/monaco-keybinding-contexts.ts [hunk 4]
```diff
@@ -41,3 +44,32 @@ export class MonacoStrictEditorTextFocusContext extends StrictEditorTextFocusCon
     }
 
 }
+
+/**
+ * The Monaco editor itself is a `textArea` so we have to restrict the default native text input focus context.
+ * It is enabled if the focus is on an `input` or `textArea` and not contained in a Monaco editor.
+ */
+@injectable()
+export class MonacoNativeTextInputFocusContext extends NativeTextInputFocusContext {
```
Comment (akosyakov) [inline packages/monaco/src/browser/monaco-keybinding-contexts.ts:53]: I wonder can we get aways without it? As far as I understood monaco handler now will be evaluated first anyway?

File: packages/core/src/browser/common-frontend-contribution.ts [hunk 5]
```diff
@@ -240,6 +235,24 @@ export const supportPaste = browser.isNative || (!browser.isChrome && document.q
 
 export const RECENT_COMMANDS_STORAGE_KEY = 'commands';
 
+@injectable() export abstract class DomCommandHandler implements CommandHandler {
+    constructor(@unmanaged() protected domCommand: string) { }
+    execute(): void { document.execCommand(this.domCommand); }
+}
+@injectable() export abstract class NativeTextInputCommandHandler extends DomCommandHandler {
```
Comment (akosyakov) [inline packages/core/src/browser/common-frontend-contribution.ts:242]: `Native` looks misleading, I usually think about Electron

we also have `browser.isNative` which means something else

Maybe use `Dom` instead of `Native`?

File: packages/core/src/browser/common-frontend-contribution.ts [hunk 6]
```diff
@@ -109,14 +109,9 @@ export namespace CommonCommands {
         id: 'core.redo',
         label: 'Redo'
     };
-
-    export const FIND: Command = {
```
Comment (akosyakov) [inline packages/core/src/browser/common-frontend-contribution.ts:113]: We should it in CHANGELOG and specify what should be called instead.

File: packages/core/src/common/command.ts [hunk 7]
```diff
@@ -371,7 +362,8 @@ export class CommandRegistry implements CommandService {
      */
     getAllHandlers(commandId: string): CommandHandler[] {
         const handlers = this._handlers[commandId];
-        return handlers ? handlers.slice() : [];
+        // We intentionally reverse the array of handlers, so if there are multiple handlers for a command, you can find the more specific, enabled one.
+        return handlers ? handlers.slice().reverse() : [];
```
Comment (akosyakov) [inline packages/core/src/common/command.ts:366]: We should add it to CHANGELOG.

Please add also a point to `How to test` whether we have multiple handlers and check that they work.

File: packages/monaco/src/browser/monaco-command.ts [hunk 8]
```diff
@@ -94,11 +82,24 @@ export class MonacoEditorCommandHandlers implements CommandContribution {
...
+            return this.editorService as any as T;
+        }
+    };
+
     registerCommands(): void {
-        this.registerCommonCommandHandlers();
-        this.registerEditorCommandHandlers();
-        this.registerMonacoActionCommands();
-        this.registerInternalLanguageServiceCommands();
+        this.registerEditorCommandHandlers(); // Custom commands and handlers for setting the EOL or the indentation, for instance.
```
Comment (akosyakov) [inline packages/monaco/src/browser/monaco-command.ts:100]: line docs can be js-doc on each method

File: packages/monaco/src/browser/monaco-keybinding-contexts.ts (hunk 4 above)
Comment (kittaakos) [reply packages/monaco/src/browser/monaco-keybinding-contexts.ts:53]: I need to check; if possible, sure let's remove it.

File: packages/core/src/browser/common-frontend-contribution.ts (hunk 5 above)
Comment (kittaakos) [reply packages/core/src/browser/common-frontend-contribution.ts:242]: > Native looks misleading, I usually think about Electron

The naming is from VSCode: https://github.com/microsoft/vscode/blob/d9d476d17a454ffb84d384be0e81b45dfaa9e059/src/vs/editor/browser/controller/coreCommands.ts#L1597

I do not mind changing the name, but the current one is at least in sync with VS Code.

File: packages/core/src/browser/common-frontend-contribution.ts (hunk 6 above)
Comment (kittaakos) [reply packages/core/src/browser/common-frontend-contribution.ts:113]: 👍 Yeah, I have to update the changelog.

File: packages/core/src/browser/common-frontend-contribution.ts (hunk 5 above)
Comment (marechal-p) [reply packages/core/src/browser/common-frontend-contribution.ts:242]: If it end up being a bit confusing, you can still carefully explain the meaning with a jsdoc comment.

Comment (akosyakov) [reply packages/core/src/browser/common-frontend-contribution.ts:242]: I don't think we need to copy stuff from VS Code to our core as is. It does not even important for VS Code compatibility. To me is good enough that we learn something from there, but it is up to you.

**Comment by akosyakov** [comment]
@marechal-p Could you help with testing please too?

File: packages/core/src/browser/common-frontend-contribution.ts (hunk 5 above)
Comment (kittaakos) [reply packages/core/src/browser/common-frontend-contribution.ts:242]: > I don't think we need to copy stuff from VS Code to our core as is

Comment (kittaakos) [reply packages/core/src/browser/common-frontend-contribution.ts:242]: > but it is up to you.

Then we leave as-is unless you have a good reason to change it.

Comment (akosyakov) [reply packages/core/src/browser/common-frontend-contribution.ts:242]: > I did not copy, why do you say I have copied something.

I meant naming, code. Sorry for the confusion.

File: packages/monaco/src/browser/monaco-keybinding-contexts.ts (hunk 4 above)
Comment (kittaakos) [reply packages/monaco/src/browser/monaco-keybinding-contexts.ts:53]: I cannot remove this. If we do not use this customization we have two matching bindings here
https://github.com/eclipse-theia/theia/blob/cf86e86857c45ab82366508cd270d217d6d66b04/packages/core/src/browser/keybinding.ts#L615

These are the two valid bindings:

Screen Shot 2020-04-02 at 09 14 45


And we blindly pick the first one, which is the core and it does not work.

Comment (akosyakov) [reply packages/monaco/src/browser/monaco-keybinding-contexts.ts:53]: ok, probably noone will try to rebind `NativeTextInputFocusContext`, so it should be fine

Comment (kittaakos) [reply packages/monaco/src/browser/monaco-keybinding-contexts.ts:53]: I added the above-described caveat as a jsdoc.

File: packages/core/src/common/command.ts (hunk 7 above)
Comment (kittaakos) [reply packages/core/src/common/command.ts:366]: Added. See the PR description.

File: packages/plugin-ext-vscode/src/browser/plugin-vscode-commands-contribution.ts [hunk 9]
```diff
@@ -194,13 +194,16 @@ export class PluginVscodeCommandsContribution implements CommandContribution {
...
         });
         commands.registerCommand({ id: 'actions.find' }, {
-            execute: () => commands.executeCommand(CommonCommands.FIND.id)
+            execute: () => commands.executeCommand('actions.find')
         });
         commands.registerCommand({ id: 'undo' }, {
             execute: () => commands.executeCommand(CommonCommands.UNDO.id)
         });
+        commands.registerCommand({ id: 'redo' }, {
+            execute: () => commands.executeCommand(CommonCommands.REDO.id)
```
Comment (kittaakos) [inline packages/plugin-ext-vscode/src/browser/plugin-vscode-commands-contribution.ts:203]: This seems incorrect. `redo` was missing, so the addition is OK, but I believe this should delegate into `redo` instead of `core.redo`.
@akosyakov, how can I verify this?

File: packages/core/src/browser/common-frontend-contribution.ts (hunk 6 above)
Comment (kittaakos) [reply packages/core/src/browser/common-frontend-contribution.ts:113]: Done.

**Comment by kittaakos** [comment]
I did my best to address all remarks, the PR is ready for the review. @RomanNikitenko, @marechal-p can you please help with the verification? Thank you! 🙏

**Comment by RomanNikitenko** [comment]
@kittaakos 
I can start to test the changes for `browser`.
Does it make sense?

or according to 
> It is the fix for electron

it's expected to test the changes for `electron` only

**Comment by kittaakos** [comment]
> I can start to test the changes for `browser`.
> Does it make sense?

Yes. Always 😊

> it's expected to test the changes for `electron` only

Just go for the browser now.

**Comment by RomanNikitenko** [comment]
Sorry for misleading you, I have a meeting, can start testing in ~2 hours...

**Comment by kittaakos** [comment]
> I have the different behavior from VS Code

I see 😕 This behaves differently in electron. I'll look into it. Thank you for your time so far.

> But it works from context menu.

This is a completely different topic, especially for electron. It is your browser's context menu. Anyway, let's put this aside for now.

> For master I have another behavior,

I can confirm, this PR wants to change it.

> I think because:
> 
> * the command is executed using [this method](https://github.com/eclipse-theia/theia/pull/7467/files#diff-3e78733f92a6f6b63b219e5fec2097f6R63)
>   and
> * `editor.focus()` is present in `master` branch

Yes.

> Please let me know if my testing steps are wrong.

No, the problem is with my code.

**Comment by RomanNikitenko** [comment]
@kittaakos @akosyakov 
Should I create a separate issue for styles problem for context menu?
Please see on `gif`s in the comment above.

**Comment by kittaakos** [comment]
> Should I create a separate issue for styles problem for context menu?

No.

Longer story: I think you're confused with the browser's context menu 😊 but maybe it's me. Try right-clicking in the terminal, for instance, it's the same. If your OS is configured to use the OS's dark theme (I know Win10 and macOS can do this), then you have dark context menu. See on my env:

Screen Shot 2020-04-02 at 20 34 23

But if I change the OS theme to light, the context menu is lighter:

Screen Shot 2020-04-02 at 20 35 40

Also see: https://github.com/eclipse-theia/theia/pull/6430)

**Comment by RomanNikitenko** [comment]
@kittaakos 
> I think you're confused with the browser's context menu...
Try right-clicking in the terminal, for instance, it's the same.

yes, you are right!
thanks!

**Comment by kittaakos** [comment]
> This behaves differently in electron.

Yes, we lose the focus when popping up the app- and context menus. This is not an issue with electron as we do not support dynamic menus (#446) 🙃

**Comment by RomanNikitenko** [comment]
@kittaakos 
`Undo`, `Redo` from `Edit` menu are not working for me, at some step they become disabled.
But maybe the cause of the problem is the same as for `Selection > Select All `

Undo_Redo

**Comment by kittaakos** [comment]
It should be fixed now, please review, verify. Thank you!

**Comment by kittaakos** [comment]
> It should be fixed now,

No, I found an issue 😕 

> please review, verify.

Let's wait.

**Comment by kittaakos** [comment]
> No, I found an issue 😕

I hope, I have really fixed the issue this time 🤞

> Let's wait.

Please verify.

**Comment by RomanNikitenko** [comment]
@kittaakos 
I'm testing the changes for `browser`.

About:
>
- Right-click on isWindows in the editor and select Peek > Peek References from the context menu. Assert: **embedded editor is open. The cursor blinks on isWindows in the main editor.**
- Press Ctrl/⌘+A (Select All). Assert: the main editor content is selected.

I'm not sure where the cursor is at this step
You can see the behavior here:

Selection_peek

But I can apply `Select All` action for any area at this step, it fixes the `master` branch behavior  and I have the same behavior for VS Code, so it looks good to me.

**Comment by kittaakos** [comment]
> * t: **embedded editor is open. The cursor blinks on isWindows in the main editor.**

Well, your cursor does not blink in the main editor, at least I cannot see it.

**Comment by RomanNikitenko** [comment]
@kittaakos 
Regarding
> Close all editors and press Ctrl/⌘+F. Assert: no errors because of the missing handler for core.find command. (Fixes #7474)

Looks like it's not fixed for me for `browser` side:

find_bug

**Comment by kittaakos** [comment]
> I'm not sure where the cursor is at this step

You can clearly see when you open the embedded editor, the selection is on the right-hand side, the selected item is blueish:

Screen Shot 2020-04-06 at 11 50 03

**Comment by kittaakos** [comment]
> Looks like it's not fixed for me for `browser` side:

👍 Thanks for finding it. Checking...

**Comment by kittaakos** [comment]
> Regarding
> 
> > Close all editors and press Ctrl/⌘+F. Assert: no errors because of the missing handler for core.find command. (Fixes #7474)
> 
> Looks like it's not fixed for me for `browser` side:

Very useful findings. The following commands do not have a `when` clause.
```
root INFO actions.findWithSelection when null
logger-protocol.ts:112 root INFO actions.find when null
```
VS Code refs: 
 - Find: https://github.com/microsoft/vscode/blob/master/src/vs/editor/contrib/find/findController.ts#L452
 - Find with selection: https://github.com/microsoft/vscode/blob/master/src/vs/editor/contrib/find/findController.ts#L489

**Comment by kittaakos** [comment]
> Looks like it's not fixed for me for `browser` side:

Fixed now. It delegates to the browser's `Find` functionality, if there is no opened editor.

**Comment by RomanNikitenko** [comment]
> Fixed now. 

Testing...

**Comment by kittaakos** [comment]
> I still can see ` Commiting pending changes before change accessor leaves due to read access.`:

We are not yet using that version. https://github.com/microsoft/vscode/commit/6beb75765e492b47e32554e093b77317fec397a8
By the way, it happens with you open and close the `Find` widget in the editor.

> Faced with the issue related to `Ctrl+z` withing testing the changes

Let me check this one too. Ohh, sorry 😕

**Comment by kittaakos** [comment]
> Faced with the issue related to `Ctrl+z` withing testing the changes

@RomanNikitenko, did you see this when undoing in the editor? https://github.com/eclipse-theia/theia/issues/7486

**Comment by RomanNikitenko** [comment]
@kittaakos 
I think yes:
errors_typescript

**Comment by kittaakos** [comment]
I leave this open till the end of the day if anyone wants to object. Thank you for the review @akosyakov and for the multiple verifications @RomanNikitenko 🙏
