### PR TITLE
VSX: Add Toolbar Menu and Support 'Install from VSIX...' Command

### LINKED ISSUE #7538: Install .vsix extension from UI
### Description
UI doesn't allow to install .vsix extensions, you have to stop server, copy vsix to plugins folder, start server again, no runtime install, which would be helpful

### Reproduction Steps
1. Open extensions view
2. Find out that you only have built-in extensions from Theia's directory and Open VSX, no way to install a .vsix extension without copying it to server.

**OS and Theia version:**
OS: Ubuntu 19.10
Theia: 1.0.0 (`master`)

**Diagnostics:**

### PR DESCRIPTION
**Pull request by seantan22**
#### What it does

Fixes #7538

- Adds a `_more_` toolbar menu to the `extensions view` to which additional commands may be registered.
- Adds an `Install from VSIX...` command that supports installation of extensions from a locally available `.vsix` file.

image

#### How to test

1. Visit [open-vsx.org](https://open-vsx.org/) and download an extension as a `.vsix` file.
2. Open the `extensions` view.
3. Select the `_more_` menu item in the toolbar and execute the `Install from VSIX...` command
4. Select a local `.vsix` file in the file dialog and click `Install`.
5. Confirm that the selected extension has been installed by checking the `extensions` view.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: seantan22 <sean.a.tan@ericsson.com>

### CODE REVIEW

File: packages/vsx-registry/src/browser/vsx-extensions-contribution.ts [hunk 1]
```diff
@@ -75,8 +96,36 @@ export class VSXExtensionsContribution extends AbstractViewContribution<VSXExten
...
+            command: VSXExtensionsCommands.INSTALL_FROM_VSIX.id,
+            tooltip: VSXExtensionsCommands.INSTALL_FROM_VSIX.label,
+            group: 'other_1'
+        });
     }
 
+    /**
+     * Register commands to the `More Actions...` extensions toolbar item.
+     */
+    public registerMoreToolbarItem = (item: Mutable<TabBarToolbarItem>) => {
```
Comment (kittaakos) [inline packages/vsx-registry/src/browser/vsx-extensions-contribution.ts:111]: Please remove `public`. This project tries to avoid using `public`. It's the default visibility. Thanks!

File: packages/vsx-registry/src/browser/vsx-extensions-contribution.ts [hunk 2]
```diff
@@ -107,4 +156,33 @@ export class VSXExtensionsContribution extends AbstractViewContribution<VSXExten
...
+        const extensionUri = await this.fileDialogService.showOpenDialog(props);
+        if (extensionUri) {
+            if (extensionUri.path.ext === '.vsix') {
+                const extensionName = this.labelProvider.getName(extensionUri);
+                try {
+                    await this.commandRegistry.executeCommand(VscodeCommands.INSTALL_FROM_VSIX.id, extensionUri);
+                    this.messageService.info(`Completed installing ${extensionName} from VSIX.`);
+                } catch (e) {
+                    this.messageService.error(`Failed to install ${extensionName} from VSIX.`);
+                    console.warn(e);
```
Comment (kittaakos) [inline packages/vsx-registry/src/browser/vsx-extensions-contribution.ts:179]: Should we return with `undefined`?

File: packages/vsx-registry/src/browser/vsx-extensions-contribution.ts [hunk 3]
```diff
@@ -107,4 +156,33 @@ export class VSXExtensionsContribution extends AbstractViewContribution<VSXExten
...
+                }
+            } else {
+                this.messageService.error('The selected file is not a valid "*.vsix" plugin.');
```
Comment (kittaakos) [inline packages/vsx-registry/src/browser/vsx-extensions-contribution.ts:182]: If the selected URI is not a `.vsix` file, can we return with `undefined`? Strange to me that this method "randomly" resolves with a URI even if the installation has failed or the selected file is not a valid extension. You can also make the method return type to `Promise<void>`. What do you think?

File: packages/vsx-registry/src/browser/vsx-extensions-contribution.ts [hunk 4]
```diff
@@ -32,14 +38,25 @@ export namespace VSXExtensionsCommands {
...
 
 @injectable()
 export class VSXExtensionsContribution extends AbstractViewContribution<VSXExtensionsViewContainer>
     implements ColorContribution, FrontendApplicationContribution, TabBarToolbarContribution {
 
-    @inject(VSXExtensionsModel)
-    protected readonly model: VSXExtensionsModel;
+    @inject(VSXExtensionsModel) protected readonly model: VSXExtensionsModel;
+    @inject(CommandRegistry) protected readonly commandRegistry: CommandRegistry;
+    @inject(PluginServer) protected readonly pluginServer: PluginServer;
```
Comment (kittaakos) [inline packages/vsx-registry/src/browser/vsx-extensions-contribution.ts:55]: Unused. Please remove.

**Review by kittaakos — COMMENTED** [review]
I tried it, and it works as expected. 👍  Could you please address my remarks, @seantan22? Thank you!

**Review by kittaakos — APPROVED** [review]
Thank you, @seantan22 👍
