### PR TITLE
13030 Localized some warns and infos

### LINKED ISSUE #13030: Some warnings are not localized
### Bug Description:
Some warnings are not localized

### Steps to Reproduce:

https://github.com/eclipse-theia/theia/blob/c745963ca6df8ac3f2619aa84c2329317f018d61/packages/core/src/browser/common-frontend-contribution.ts#L741

https://github.com/eclipse-theia/theia/blob/c745963ca6df8ac3f2619aa84c2329317f018d61/packages/core/src/browser/common-frontend-contribution.ts#L750

https://github.com/eclipse-theia/theia/blob/c745963ca6df8ac3f2619aa84c2329317f018d61/packages/core/src/browser/common-frontend-contribution.ts#L759

https://github.com/eclipse-theia/theia/blob/c745963ca6df8ac3f2619aa84c2329317f018d61/packages/core/src/browser/common-frontend-contribution.ts#L772

### Additional Information

- Operating System: any
- Theia Version: the latest

### PR DESCRIPTION
**Pull request by Zebsterpasha**
#### What it does

Fixes #13030 

#### How to test

Just check the keys)

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/core/src/browser/common-frontend-contribution.ts [hunk 1]
```diff
@@ -738,7 +738,7 @@ export class CommonFrontendContribution implements FrontendApplicationContributi
                 if (supportCut) {
                     document.execCommand('cut');
                 } else {
-                    this.messageService.warn("Please use the browser's cut command or shortcut.");
+                    this.messageService.warn(nls.localize('theia/workspace/cut', "Please use the browser's cut command or shortcut."));
```
Comment (msujew) [inline packages/core/src/browser/common-frontend-contribution.ts:741]: Suggestion: Why use `theia/workspace/...` as the key? We are in the `@theia/core` package. Also, the key should explain a bit more to prevent accidental ambiguities in the future.
```suggestion
                    this.messageService.warn(nls.localize('theia/core/cutWarn', "Please use the browser's cut command or shortcut."));
```

Comment (Zebsterpasha) [reply packages/core/src/browser/common-frontend-contribution.ts]: Okey, and we have one more key, it had been before my changes. Should I correct it, or not?

https://github.com/eclipse-theia/theia/blob/4cb425c9012f72d3101b482252f9b21322860fb2/packages/core/src/browser/common-frontend-contribution.ts#L934
