### PR TITLE
fix: Correctly handle reasoning output of openai/gpt-oss-120b

### LINKED ISSUE #16186: [Theia AI] Groq does not work as a provider with Theia AI
It would be nice if Groq would work as a provider, as it is very fast and also supports interesting models such as GPT-OSS. However, my first try failed, seems to be an issue wih their OpenAI API implementation, but we should check.

### Steps to Reproduce:

1. Enter groq as a custom OpenAI Provider:
{
        "model": "openai/gpt-oss-120b",
        "url": "https://api.groq.com/openai/v1",
        "id": "groq/gpt-oss-120b",
        "apiKey": "key",
    },

2. Set the model for an agent
3. Do a prompt that triggers a tool call:

Image

### Additional Information

- Operating System: Linux
- Theia Version: 1.64

### PR DESCRIPTION
**Pull request by eneufeld**
#### What it does

- Handle reasoning output by outputing it as thinking but removing it otherwise
- improve tool description

fixes #16186

#### How to test

See initial issue

#### Follow-ups

The OpenAI ChatCompletion API should be replaced with the newer Response API.

#### Breaking changes

- [ ] This PR introduces breaking changes and requires careful review. If yes, the breaking changes section in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) has been updated.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by JonasHelming** [comment]
I can confirm I can use GPT-OSS now on Groq, @sdirix could you have another quick look, please? (no need to retest GPT-OSS)

File: packages/ai-openai/src/node/openai-streaming-iterator.ts [hunk 1]
```diff
@@ -83,6 +83,14 @@ export class StreamingAsyncIterator implements AsyncIterableIterator<LanguageMod
                     }
                 });
             }
+            // OpenAI can push out reasoning tokens, but can't handle it as part of messages
+            if (Object.keys(snapshot.choices[0].message).includes('reasoning')) {
+                const reasoning = (snapshot.choices[0].message as { reasoning: string }).reasoning;
+                this.handleIncoming({ thought: reasoning, signature: '' });
+                delete (snapshot.choices[0].message as { reasoning?: string }).reasoning;
+                delete (snapshot.choices[0].message as { channel?: string }).channel;
```
Comment (sdirix) [inline packages/ai-openai/src/node/openai-streaming-iterator.ts:92]: Why do we need to delete them here?

**Review by sdirix — CHANGES_REQUESTED** [review]
Please check the openai test cases as they are failing now
