### PR TITLE
Workspace: Rename files/folder is case sensitive

### LINKED ISSUE #9663: Rename of files and folder are case insensitive
### Bug Description:
On rename files or folders the registry is not taking into count.
The rename should be case-sensitive.

### Steps to Reproduce:

1. Create a new file.
2. Change some characters of the file name to a different registry.
3. Wrong error appears about the file already exists.

image

### Additional Information

- Operating System: Windows 10
- Theia Version: 1.14.0

### PR DESCRIPTION
**Pull request by OmarSdt-EC**
#### What it does

Fixes #9663
This commit fixes the rename command for windows users by making possible
the case sensitive rename of files and folders. Also, it adds the test file
`workspace-commands.spec.ts` which verifies that the implementation works as expected.

#### How to test

If your operating system is Windows, you can test this commit with the following steps in the browser or electron target :
1. Create a new folder : `foo`
2. Create two files in it : `a.txt` and `b.txt`
3. Rename `a.txt` to `A.txt`
4. It should let you do the rename
5. Rename `b.txt` to `a.txt`
6. It should not let you do the rename and the message : "A file or folder 'a.txt' already exists at this location" should appear

You can also test the commit by running : 
` npx run build @theia/workspace && npx run test @theia/workspace`

#### Review checklist

- [ ] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/workspace/src/browser/workspace-commands.ts [hunk 1]
```diff
@@ -394,8 +394,19 @@ export class WorkspaceCommandContribution implements CommandContribution {
...
+            if (initialValue) {
+                const actualUri = parent.resource.resolve(initialValue);
+                if (actualUri.isEqual(childUri, false)) {
+                    return '';
+                };
+            }
+            // Determine if the case-insensitive version already exists at the location.
+            if (parent.children?.some(child => child.resource.isEqual(childUri, false))) {
+                return `A file or folder "${this.trimFileName(name)}" already exists at this location.`;
+            }
```
Comment (msujew) [inline packages/workspace/src/browser/workspace-commands.ts:409]: I don't believe that this check is actually necessary. Assuming `exists` is already true on windows, we don't need to determine again whether a case-insensitive version already exists, since that's exactly what `exists` represents.

Comment (OmarSdt-EC) [reply packages/workspace/src/browser/workspace-commands.ts:409]: That's true, I removed it thank you !

**Review by msujew — APPROVED** [review]
I tested the changes on Windows and Ubuntu. The behavior on Ubuntu didn't change, while it fixed the issue on Windows. I tried:

* Renaming a file to the same name but with a different case.
* Renaming a file to create a name collision with an existing file with the **same case** as the other file.
* Renaming a file to create a name collision with an existing file with a **different case**.

LGTM 👍

File: packages/workspace/src/browser/workspace-commands.ts [hunk 2]
```diff
@@ -368,19 +380,26 @@ export class WorkspaceCommandContribution implements CommandContribution {
...
+        }
+        return this.validateFileName(name, parent, false);
+    }
+
     /**
      * Returns an error message if the file name is invalid. Otherwise, an empty string.
      *
      * @param name the simple file name of the file to validate.
      * @param parent the parent directory's file stat.
      * @param recursive allow file or folder creation using recursive path
```
Comment (vinokurig) [inline packages/workspace/src/browser/workspace-commands.ts:395]: This has to be updated since it is renamed in the method

**Comment by vinokurig** [comment]
The code is OK for me but I can't approve it because I don't have a Windows workstation to test it.

File: packages/workspace/src/browser/workspace-commands.ts (hunk 2 above)
Comment (OmarSdt-EC) [reply packages/workspace/src/browser/workspace-commands.ts:395]: Hi, unfortunately, I didn't understand what you meant, can you explain it to me ?

Comment (msujew) [reply packages/workspace/src/browser/workspace-commands.ts:395]: @OmarSdt-EC You renamed the `recursive` argument to `allowNested`, but didn't change the documentation to reflect that. At least I think that's what he meant.

**Review by msujew — APPROVED** [review]
I tested everything again, as the code changed a lot since the last time I took a look at it. However, everything still performs as expected.

File: packages/workspace/src/browser/workspace-commands.ts [hunk 3]
```diff
@@ -196,10 +197,18 @@ export class WorkspaceCommandContribution implements CommandContribution {
...
     @inject(WorkspaceCompareHandler) protected readonly compareHandler: WorkspaceCompareHandler;
+    @inject(ApplicationServer) protected readonly applicationServer: ApplicationServer;
 
     private readonly onDidCreateNewFileEmitter = new Emitter<DidCreateNewResourceEvent>();
     private readonly onDidCreateNewFolderEmitter = new Emitter<DidCreateNewResourceEvent>();
 
+    protected _backendOS: Promise<OS.Type>;
+
+    @postConstruct()
+    async onStart(): Promise<void> {
```
Comment (paul-marechal) [inline packages/workspace/src/browser/workspace-commands.ts:208]: Please rename to either `async postConstruct()` or `async init()`.

File: packages/workspace/src/browser/workspace-commands.ts [hunk 4]
```diff
@@ -196,10 +197,18 @@ export class WorkspaceCommandContribution implements CommandContribution {
     @inject(WorkspaceDeleteHandler) protected readonly deleteHandler: WorkspaceDeleteHandler;
     @inject(WorkspaceDuplicateHandler) protected readonly duplicateHandler: WorkspaceDuplicateHandler;
     @inject(WorkspaceCompareHandler) protected readonly compareHandler: WorkspaceCompareHandler;
+    @inject(ApplicationServer) protected readonly applicationServer: ApplicationServer;
 
     private readonly onDidCreateNewFileEmitter = new Emitter<DidCreateNewResourceEvent>();
     private readonly onDidCreateNewFolderEmitter = new Emitter<DidCreateNewResourceEvent>();
 
+    protected _backendOS: Promise<OS.Type>;
```
Comment (paul-marechal) [inline packages/workspace/src/browser/workspace-commands.ts:205]: No need for the leading underscore AFAIK?

**Comment by msujew** [comment]
@paul-marechal Anything blocking you from approving/retesting?

**Review by paul-marechal — APPROVED** [review]
Code LGTM, and I confirm that I am now able to rename files by just changing the case on Windows.
