### PR TITLE
[SIW] Add support to search in outside workspace content

### LINKED ISSUE #6867: [search-in-workspace] opening files outside the workspace root are not included in the search results
### Description
When using the Search view, no results are shown for files that are opened in an editor, but are not contained in the workspace root. I would expect such files to be included in the search.
Related: #6641

### Reproduction Steps
 * Open a file that is not in the workspace root directory
 * Open the Search view and enter a string that should be found in that file

### PR DESCRIPTION
**Pull request by DukeNgn**
#### What it does
Fixes #6867 
+ `search-in-workspace` now supports searching in files that are opened in an editor but are not in the workspace root.
+ Group those files under a root node folder `Other files` in Search view.
+ **Note:** This PR is a work based on #8579 

#### How to test
+ Open a file that is not in the workspace root directory.
+ Search for content that should be found in that file.
+ **Expected behavior:** The search result comes from that file is displayed under `Other files` node in Search view.
+ `Other files` node is only displayed when there's multi-root in the search result tree (including the `Other files` node)

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: DukeNgn <duc.a.nguyen@ericsson.com>

### CODE REVIEW

File: packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx [hunk 1]
```diff
@@ -106,6 +106,8 @@ export class SearchInWorkspaceResultTreeWidget extends TreeWidget {
     protected _showReplaceButtons = false;
     protected _replaceTerm = '';
     protected searchTerm = '';
+    protected outsideWorkspaceRootUri = 'Other files';
```
Comment (vince-fugnitto) [inline packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx:109]: `protected readonly`?

File: packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx [hunk 2]
```diff
@@ -534,11 +541,27 @@ export class SearchInWorkspaceResultTreeWidget extends TreeWidget {
...
     }
 
-    protected filenameAndPath(rootUriStr: string, uriStr: string): { name: string, path: string } {
+    /**
+     * Get file name and construct a path of a file relatively to its root.
+     * @param rootUriStr the string of root uri.
+     * @param uriStr the string of the file uri.
+     * @param getAbsolutePath option to get absolute path instead of relative path.
+     */
+    protected filenameAndPath(rootUriStr: string, uriStr: string, getAbsolutePath?: boolean): {
```
Comment (vince-fugnitto) [inline packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx:550]:
```suggestion
    protected filenameAndPath(rootUriStr: string, uriStr: string, absolute?: boolean): {
```

I believe this name would be sufficient.

File: packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx [hunk 3]
```diff
@@ -374,6 +380,7 @@ export class SearchInWorkspaceResultTreeWidget extends TreeWidget {
 
         // Collect search results for opened editors which otherwise may not be found by ripgrep (ex: dirty editors).
         const { numberOfResults: monacoNumberOfResults, matches: monacoMatches } = this.searchInOpenEditors(searchTerm, searchOptions);
+        this.hasOutsideWorkspaceResult = monacoMatches.some(m => m.root === this.outsideWorkspaceRootUri);
```
Comment (vince-fugnitto) [inline packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx:383]:
```suggestion
        const { numberOfResults, matches } = this.searchInOpenEditors(searchTerm, searchOptions);
        this.hasOutsideWorkspaceResult = matches.some(m => m.root === this.outsideWorkspaceRootUri);
```

**Review by marechal-p — COMMENTED** [review]
Code LGTM with few nitpicks, feature wise I noticed that it shows the `Other files` root node even when there is no matches for workspaces. The expected behavior in this case is to not show this `Other files` node, and only display it if there's others roots to display.

File: packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx [hunk 4]
```diff
@@ -107,6 +107,10 @@ export class SearchInWorkspaceResultTreeWidget extends TreeWidget {
     protected _replaceTerm = '';
     protected searchTerm = '';
 
+    // The common root name to add external search results in the case that a workspace is opened.
+    protected readonly externalRootName = 'Other files';
```
[the remark this answers is not in the document]
Comment (DukeNgn) [reply packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx]: I changed to `defaultRootName` since this technically isn't a root, but rather a name.

**Comment by DukeNgn** [comment]
@marechal-p Thanks for the review. I tried to address the use case you mentioned but unfortunately, I don't see an approach that is available with our current implementation.


One approach is to get the number of root folder node in `resultTree` and set `visible` based on it. 

https://github.com/DukeNgn/theia/blob/430dc7d2b8c010a878406796259dea55aa76d23f/packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx#L526

However, because `visible` is `readonly`, it needs to be determined before any call of `appendToResultTree()` to make all the root folder node appear in search view (when `other files` presents) . But the `resultTree` is not updated until we create root folder node in the search tree, hence we have no way to find out the visibility prior to creating the tree.

With my current approach in this PR, I believe the main functionality is not being affected. The only thing that is a bit off is the UX for a specific use-case (`Other files` is displayed when no matches in the workspace).

File: packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx [hunk 5]
```diff
@@ -491,7 +523,7 @@ export class SearchInWorkspaceResultTreeWidget extends TreeWidget {
             expanded: true,
             id: rootUri,
             parent: this.model.root as SearchInWorkspaceRoot,
-            visible: this.workspaceService.isMultiRootWorkspaceOpened
+            visible: this.forceVisibleRootNode || this.workspaceService.isMultiRootWorkspaceOpened
```
Comment (marechal-p) [inline packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx:526]: I think we can simplify the condition to `this.resultTree.size > 1` to align with VS Code.

Right now it displays the root node while in a multi-root workspace even if we find results under a single root, VS Code does not.

Comment (marechal-p) [reply packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx:526]: Just tried and apparently it doesn't work like this alone.

**Comment by DukeNgn** [comment]
I just rebased against `master`. Other than that, nothing has changed since the previous review. The PR is ready to be merged in my opinion. 

About the mentioned use-case (no ws results are found, `other files` is still being displayed), I and @vince-fugnitto discussed offline. And we think that:
+ Our current implementation in `siw` does not allow such behavior. 
+ The behavior in this PR is maybe even better since it makes a clear distinction that the results are from outside workspace files.

**Review by marechal-p — APPROVED** [review]
LGTM, works well.

**Review by vince-fugnitto — COMMENTED** [review]
There is currently a bug which can be reproduced as follows:
1. start the application with a single-root workspace
2. open a file outside the workspace
3. perform a search which does **not** yield results in the external file
4. the search tree is incorrectly rendered with a root node of the workspace

**Comment by DukeNgn** [comment]
I fixed the bug and tested again 👍

**Review by vince-fugnitto — APPROVED** [review]
The latest changes work well for me :+1:
