### PR TITLE
Adjust behavior of all close tab commands

### LINKED ISSUE #7268: Can close widget tab via context menu even if set as not closeable
### Description
Setting `title.closable = false` on a widget doesn't prevent it from being closed via context menu.

### Reproduction Steps

1. Create a widget.
2. Set `title.closable = false` in constructor/init.
3. Right click on the tab.
4. The "Close" menu item shows, it should not.

### PR DESCRIPTION
**Pull request by Hanksha**
Fixes #7268, adjust behavior of all close tab commands so that they respect the `widget.title.closable` property.

#### What it does
This PR improves the close tab commands so that they take into account the `widget.title.closable` property. It means that a widget cannot be closed using any of the commands if `widget.title.closable === false`.

The behavior is as follow:
- `Close` and `Close Tab in Main Area` are enabled when the current widget is closable
- `Close Others` and `Close Other Tabs in Main Area` are enabled if at least one other widget is closable
- `Close All` and `Close All Tabs in Main Area` enabled if at least one widget is closable
- `Close to the Right` is enabled if at least one widget to the right is closable

#### How to test
I added a sample view to the examples so you can open the `Sample Unclosable View` and toggle the checkbox in it to set `title.closable` and try the logic described above.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
As far as I understood this PR only tries to prevent closing from user perspective, from programming perspective one can still close. I think it is reasonable, just checking.

**Comment by Hanksha** [comment]
@akosyakov Yes it only affects the commands, one can still close the tab programmatically using the `ApplicationShell` methods.

File: examples/api-samples/src/browser/sample-view.tsx [hunk 1]
```diff
@@ -0,0 +1,43 @@
+/********************************************************************************
+ * Copyright (C) 2019 Arm and others.
```
Comment (akosyakov) [inline examples/api-samples/src/browser/sample-view.tsx]: 2019? ARM? :) Could you check other new files that it points to 2020 and a proper entity, either you or your organisation

**Comment by akosyakov** [comment]
@Hanksha fyi https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords

File: examples/api-samples/src/browser/sample-view.tsx (hunk 1 above)
Comment (Hanksha) [reply examples/api-samples/src/browser/sample-view.tsx]: Oops, I didn't even read it, I just saw the error for it and copy/pasted the one in the same directory :). So I should change it to something like `Copyright (C) 2020 TORO Limited and others.`?

File: packages/core/src/browser/common-frontend-contribution.ts [hunk 2]
```diff
@@ -530,19 +537,23 @@ export class CommonFrontendContribution implements FrontendApplicationContributi
         commandRegistry.registerCommand(CommonCommands.CLOSE_OTHER_TABS, {
             isEnabled: (event?: Event) => {
                 const tabBar = this.findTabBar(event);
-                return tabBar !== undefined && tabBar.titles.length > 1;
+                if (!tabBar) {
+                    return false;
+                }
+                const currentTitle = this.findTitle(tabBar, event);
+                return tabBar.titles.some(title => title !== currentTitle && title.closable);
```
Comment (spoenemann) [inline packages/core/src/browser/common-frontend-contribution.ts]: This condition checks only the selected tab bar, while `execute` closes all other tab bars, too.

File: packages/core/src/browser/common-frontend-contribution.ts [hunk 3]
```diff
@@ -551,32 +562,38 @@ export class CommonFrontendContribution implements FrontendApplicationContributi
...
-                this.shell.closeTabs(tabBar, (_, index) => index > currentIndex);
+                this.shell.closeTabs(tabBar, (title, index) => index > currentIndex && title.closable);
             }
         });
         commandRegistry.registerCommand(CommonCommands.CLOSE_ALL_TABS, {
-            isEnabled: (event?: Event) => this.findTabBar(event) !== undefined,
-            execute: (event?: Event) => this.shell.closeTabs(this.findTabArea(event)!)
+            isEnabled: (event?: Event) => {
+                const tabBar = this.findTabBar(event);
+                return tabBar !== undefined && tabBar.titles.some(title => title.closable);
```
Comment (spoenemann) [inline packages/core/src/browser/common-frontend-contribution.ts]: This condition checks only the selected tab bar, while `execute` closes all other tab bars, too.

File: packages/core/src/browser/common-frontend-contribution.ts [hunk 4]
```diff
@@ -551,32 +562,38 @@ export class CommonFrontendContribution implements FrontendApplicationContributi
...
+                const currentWidget = this.shell.getCurrentWidget('main');
+                return currentWidget !== undefined && currentWidget.title.closable;
+            },
             execute: () => this.shell.getCurrentWidget('main')!.close()
         });
         commandRegistry.registerCommand(CommonCommands.CLOSE_OTHER_MAIN_TABS, {
             isEnabled: () => {
                 const tabBars = this.shell.mainAreaTabBars;
-                return tabBars.length > 1 || tabBars.length === 1 && tabBars[0].titles.length > 1;
+                return tabBars.length > 1 || tabBars.length === 1 && tabBars[0].titles.some(title => title.closable);
```
Comment (spoenemann) [inline packages/core/src/browser/common-frontend-contribution.ts]: In case there are multiple tab bars, we should check the `closable` property, too. Maybe like this?
```typescript
const currentWidget = this.shell.getCurrentWidget('main');
return currentWidget !== undefined && this.shell.mainAreaTabBars.some(tb => tb.titles.some(title => title.widget !== currentWidget && title.closable));
```
Then you can safely remove the `currentWidget !== undefined` check in `execute`.

File: examples/api-samples/src/browser/api-samples-contribution.ts [hunk 5]
```diff
@@ -16,8 +16,9 @@
 
 import { injectable, inject } from 'inversify';
 import { Command, CommandContribution, CommandRegistry, CommandHandler } from '@theia/core';
-import { FrontendApplicationContribution } from '@theia/core/lib/browser';
+import { AbstractViewContribution, FrontendApplicationContribution } from '@theia/core/lib/browser';
 import { SampleDynamicLabelProviderContribution } from './sample-dynamic-label-provider-contribution';
+import { SampleView } from '@theia/api-samples/lib/browser/sample-view';
```
Comment (spoenemann) [inline examples/api-samples/src/browser/api-samples-contribution.ts]: Here I get
```
error TS2307: Cannot find module '@theia/api-samples/lib/browser/sample-view'.
```
when I run `yarn`. Did I miss something?

File: examples/api-samples/src/browser/sample-view.tsx (hunk 1 above)
Comment (spoenemann) [reply examples/api-samples/src/browser/sample-view.tsx]: If you made this contribution as part of your work at TORO, yes. Otherwise just use your name.

File: examples/api-samples/src/browser/api-samples-contribution.ts (hunk 5 above)
Comment (spoenemann) [reply examples/api-samples/src/browser/api-samples-contribution.ts]: Same error in Travis CI:
https://travis-ci.com/eclipse-theia/theia/jobs/294291205#L729

Comment (westbury) [reply examples/api-samples/src/browser/api-samples-contribution.ts]: This import should be

`import { SampleView } from './sample-view';`

When importing from the same package one must use relative paths, picking up the ts(x) file from the src folder.  The lib folder and the js files will not exist until the package is compiled.

Comment (westbury) [reply examples/api-samples/src/browser/api-samples-contribution.ts]: 'SampleView' should have a more specific name.  Many sample views may be added to this package over time.  Perhaps ExampleUnclosableView (as 'example' and not 'sample' is being used in this package, we should also be keeping that consistent).  See https://github.com/eclipse-theia/theia/wiki/Coding-Guidelines#unique-names

Comment (Hanksha) [reply examples/api-samples/src/browser/api-samples-contribution.ts]: I don't know what happened with the import, Webstorm imported it correctly in `api-samples-frontend-module.ts` but not in `api-samples-contribution.ts`... I should have doubled checked.

File: examples/api-samples/src/browser/api-samples-contribution.ts [hunk 6]
```diff
@@ -53,3 +54,16 @@ export class ExampleLabelProviderCommandHandler implements CommandHandler {
...
+@injectable()
+export class SampleViewContribution extends AbstractViewContribution<SampleView> {
+    constructor() {
+        super({
+            widgetId: SampleView.ID,
+            widgetName: 'Sample',
+            defaultWidgetOptions: {
+                area: 'main'
+            }
+        });
```
[the remark this answers is not in the document]
Comment (Hanksha) [reply examples/api-samples/src/browser/api-samples-contribution.ts]: You can open it via View > Open View... and then find it in the list that appears but I'll add the toggle if it makes things easier.

File: examples/api-samples/src/browser/api-samples-frontend-module.ts [hunk 7]
```diff
@@ -17,12 +17,20 @@
...
     bind(CommandContribution).to(ApiSamplesContribution).inSingletonScope();
 
     bind(SampleDynamicLabelProviderContribution).toSelf().inSingletonScope();
     bind(LabelProviderContribution).toService(SampleDynamicLabelProviderContribution);
+    bindViewContribution(bind, SampleViewContribution);
+    bind(SampleView).toSelf();
+    bind(WidgetFactory).toDynamicValue(ctx => ({
+        id: SampleView.ID,
+        createWidget: () => ctx.container.get<SampleView>(SampleView)
+    }));
```
[the remark this answers is not in the document]
Comment (Hanksha) [reply examples/api-samples/src/browser/api-samples-frontend-module.ts]: Ok I see what you mean, I'll improve that.

File: packages/core/src/browser/common-frontend-contribution.ts (hunk 2 above)
Comment (Hanksha) [reply packages/core/src/browser/common-frontend-contribution.ts]: Ah you're right, so the original execute logic was wrong too?

File: packages/core/src/browser/common-frontend-contribution.ts (hunk 3 above)
Comment (Hanksha) [reply packages/core/src/browser/common-frontend-contribution.ts]: Same thing here seems the original logic was wrong.

File: packages/core/src/browser/common-frontend-contribution.ts (hunk 4 above)
Comment (Hanksha) [reply packages/core/src/browser/common-frontend-contribution.ts]: Ok I was unsure here why in the first place it checked only one tabBar. I'll change it.

**Comment by Hanksha** [comment]
> 1. When a view is not closable (and there are other closable views), the action 'Close Others' is disabled.  I would expect it to be enabled.
> 2. It looks like 'close others' should only close views within the same location.  We need to be sure this is all consistent.

1. I cannot reproduce it, "Close Others" is disabled only when there are no other closable views.
2. Yes that's right, I changed it to behave that way.

File: examples/api-samples/src/browser/api-samples-frontend-module.ts (hunk 7 above)
[the remark this answers is not in the document]
Comment (Hanksha) [reply examples/api-samples/src/browser/api-samples-frontend-module.ts]: I gave it a try, tell me what you think.

File: examples/api-samples/src/browser/view/sample-uncloable-view-contribution.ts [hunk 8]
```diff
@@ -0,0 +1,45 @@
...
+ *
+ * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
+ ********************************************************************************/
+
+import { AbstractViewContribution, bindViewContribution, WidgetFactory } from '@theia/core/lib/browser';
+import { SampleViewUnclosableView } from './sample-unclosable-view';
+import { injectable, interfaces } from 'inversify';
+
+@injectable()
+export class SampleUnclosableViewContribution extends AbstractViewContribution<SampleViewUnclosableView> {
```
Comment (spoenemann) [inline examples/api-samples/src/browser/view/sample-uncloable-view-contribution.ts]: File name: `sample-uncloable-view-contribution` => `sample-unclosable-view-contribution`

Comment (Hanksha) [reply examples/api-samples/src/browser/view/sample-uncloable-view-contribution.ts]: Fixed.

**Comment by akosyakov** [comment]
@spoenemann please merge

**Comment by westbury** [comment]
> 1. cannot reproduce it, "Close Others" is disabled only when there are no other closable views.

 I was misunderstanding what was the same or a different area.  It's working fine.
