### PR TITLE
only run selected texts in a user terminal

### LINKED ISSUE #7323: 'Run Selected Text' is not working when a task is stopped
### Description
'Run Selected Text' action is not working when current terminal widget is completed task widget. 

### Reproduction Steps
1. Run any task
2. Stop the task
3. Select a command and use `Run Selected Text` action

runSelected

  

**OS and Theia version:**
Ubuntu 18.04.1
Theia: ced3f90a3b1ebf6fcfaf5a62e082dcdfa1f0304c

**Diagnostics:** 
I guess `Run Selected Text` action tries to use stopped task as current terminal widget.

### PR DESCRIPTION
**Pull request by elaihau**
- The selected texts are only run in a user terminal.
  If the terminal widget that has the focus
  1) is not a user terminal, or
  2) is a user terminal that has an actively running command,
  Theia should create a new user terminal and run the selected texts in that new terminal.

- fixes #7323

Signed-off-by: Liang Huang <lhuang4@ualberta.ca>

#### How to test

1. Start a task.
2. Highlight texts
3. Run highlighted texts by going to the top menu bar `Terminal -> Run selected text`
Expected: 
- The selected text should not simply be dumped into the terminal (where the task is running / ran) as a string
- The selected text should be run as a shell command in a user terminal
- If the visible terminal is not a user terminal, a new user terminal should be created to run the selected text as a shell command

Peek 2020-03-30 15-35

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

### CODE REVIEW

File: packages/task/src/browser/task-service.ts [hunk 1]
```diff
@@ -970,8 +970,8 @@ export class TaskService implements TaskConfigurationClient {
             selectedRange = Range.create(startLine, 0, endLine + 1, 0);
         }
         const selectedText: string = this.editorManager.currentEditor.editor.document.getText(selectedRange).trimRight() + '\n';
-        let terminal = this.terminalService.currentTerminal;
-        if (!terminal) {
+        let terminal = this.terminalService.lastUsedTerminal;
+        if (!terminal || terminal.kind !== 'user' || (await terminal.hasChildProcesses())) {
```
Comment (akosyakov) [inline packages/task/src/browser/task-service.ts]: What the last predicate for? `terminal.hasChildProcesses`?

Comment (elaihau) [reply packages/task/src/browser/task-service.ts:974]: `terminal.hasChildProcesses()` was introduced in https://github.com/eclipse-theia/theia/pull/6769, where it was used to check if the terminal that has a shell is in use.

Comment (akosyakov) [reply packages/task/src/browser/task-service.ts:974]: ok, not sure whether a user expects it, but let's try like that
