### PR TITLE
Correct Handling of Plugin QuickPick selections

### LINKED ISSUE #10970: vscode: `showQuickPick` does not return proper result
#### Bug Description:

The `vscode.window.showQuickPick` API does not return the proper result, instead it returns `undefined` always.

#### Steps to Reproduce:

1. include the following test extension ([quick-pick-0.0.1.zip](https://github.com/eclipse-theia/theia/files/8390197/quick-pick-0.0.1.zip)).
2. start the application.
3. execute the command `Quick Pick: A`, choose a item, and confirm that the notification does not print the proper result.
4. repeat the steps for `Quick Pick: B` and `Quick Pick: C`.

### PR DESCRIPTION
**Pull request by colin-grant-work**
#### What it does

Fixes #10970 by improving the handling of the `pick` method of the `MonacoQuickInputService` to ensure that the return retains all the fields of the original item.

#### How to test

1. Install this plugin in your `theia/plugins` folder: [quick-pick-test-0.0.1.zip](https://github.com/eclipse-theia/theia/files/8391961/quick-pick-test-0.0.1.zip)
2. Use the command `show a quick pick`
3. Select one of the options.
4. See a backend log in the console with the text `SENTINEL FOR THE THING PICKED FROM A PLUGIN` and the correct label of the item you picked.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by vince-fugnitto — APPROVED** [review]
I confirmed that the three example `showQuickPick` commands work well :+1: 
Internal calls such as `change language mode` also still work correctly.

File: packages/monaco/src/browser/monaco-quick-input-service.ts [hunk 1]
```diff
@@ -227,15 +227,23 @@ export class MonacoQuickInputService implements QuickInputService {
...
+            return pick as M;
         });
-        return this.monacoService.pick(monacoPicks, options as any, token) as any; /* eslint-disable-line @typescript-eslint/no-explicit-any */
+        const monacoOptions = options as IPickOptions<M>;
+        const picked = await this.monacoService.pick(monacoPicks, monacoOptions, token);
+        if (!picked) { return picked; }
+        if (options?.canPickMany) {
+            return (Array.isArray(picked) ? picked : [picked]) as R;
+        }
+        return Array.isArray(picked) ? picked[0] : picked;
```
Comment (paul-marechal) [inline packages/monaco/src/browser/monaco-quick-input-service.ts:246]: This one I'm less sure if worth or not but I feel like there's a couple cases that shouldn't happen, though we can keep handling them like you did:

```suggestion
        if (options?.canPickMany) {
            if (!Array.isArray(picked)) {
                console.error('expected the returned picks to be an array');
                return [picked] as R;
            }
            return picked;
        }
        if (Array.isArray(picked)) {
            console.error('expected the returned pick to not be an array');
            return picked[0]; // if picked.length === 0 this will return undefined...
        }
        return picked as R;
```
