### PR TITLE
GH-9262: Fixed the double hover issue for the `currentFrame` editor

### LINKED ISSUE #9262: [debug] Multiple hovers are available when inspecting a variable in the editor with the `currentFrame`
### Bug Description:

VS Code disables the default editor-contribution hover when an editor has the `currentFrame`. Theia shows both.

https://user-images.githubusercontent.com/1405703/112614344-743aaf00-8e21-11eb-8aeb-52faa53c41c1.mp4

Expected:
 - only the debug hover is visible for the `currentFrame` editor.

Bonus:
 - toggle between the default and debug hovers with `Ctrl`/`Option` key.

Screen Shot 2021-03-26 at 10 54 21

### Steps to Reproduce:

1.
2.
3.

### Additional Information

- Operating System:
- Theia Version:

### PR DESCRIPTION
**Pull request by kittaakos**
#### What it does

 - This PR disables the default editor-contribution hover (such has `textdocument/hover` for JS/TS) from `monaco` for the `currentFrame` editor.
 - Fixes the string, number, and boolean coloring in the debug hover and the _Variables_ view.
 - This PR makes the debug hover content `hidden` when the expression is not complex (`!expression.hasChildren`).

Closes #9262

#### How to test

```ts
const x = 'alma';
const y = 36;
const z = true;
const complex = {
    foo: 'bar'
};
const large = {
    ...complex,
    'some string': 1
};

console.log(x, y, z, complex, large);
```

 - Test with the snippet.
 - Before the debug session, verify that you can see the default editor hover.
 - Start a debug session, check that the default hover is not there. (Please also check the color of the variables),
 - Stop the debug session, the default hover is available again.
 - Verify the colors in the _Variables_ view.

Screen Shot 2021-03-29 at 10 54 26

https://user-images.githubusercontent.com/1405703/112813316-5c139b80-907e-11eb-89f5-f8144cf54146.mp4

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/debug/src/browser/editor/debug-hover-widget.ts [hunk 1]
```diff
@@ -171,17 +175,43 @@ export class DebugHoverWidget extends SourceTreeWidget implements monaco.editor.
...
+            }
+        }
+
+        super.show();
+        new Promise<void>(resolve => {
+            setTimeout(() => window.requestAnimationFrame(() => {
+                this.editor.getControl().layoutContentWidget(this);
+                resolve();
+            }), 0);
+        });
```
Comment (marechal-p) [inline packages/debug/src/browser/editor/debug-hover-widget.ts:210]: Unawaited promise.

Comment (kittaakos) [reply packages/debug/src/browser/editor/debug-hover-widget.ts]: Nice catch. I have fixed it. Please proceed with the review. Thanks!

File: packages/debug/src/browser/editor/debug-hover-widget.ts [hunk 2]
```diff
@@ -171,17 +175,43 @@ export class DebugHoverWidget extends SourceTreeWidget implements monaco.editor.
...
+        const expression = await this.hoverSource.evaluate(matchingExpression);
+        if (!expression) {
             toFocus.dispose();
             this.hide();
             return;
         }
-        this.editor.getControl().layoutContentWidget(this);
+
+        this.contentNode.hidden = false;
+        this.domNode.classList.remove();
```
Comment (colin-grant-work) [inline packages/debug/src/browser/editor/debug-hover-widget.ts:186]: Does this call do anything? I don't see an API for `.remove()` with no arguments, but I may be missing something.

Comment (kittaakos) [reply packages/debug/src/browser/editor/debug-hover-widget.ts]: No. It's garbage. Thanks for the note. I fixed it.

**Comment by kittaakos** [comment]
@colin-grant-work, @marechal-p, I have made the changes based on your feedback. Could you please continue with the review. Thanks!

**Review by marechal-p — APPROVED** [review]
Code LGTM, I verified that hovering is only showing either debug or LS info depending on the debugging state, and that colors are better.

**Comment by kittaakos** [comment]
Thank you!
