### PR TITLE
electron: restore last window state if the layout still exists

### LINKED ISSUE #10412: electron window not launching properly
### Bug Description:
The application window doesn't launch in prop position, make it invisible.
It seems launch at another monitor which isn't connected currently, but was connected before.

### Steps to Reproduce:

1. connect one more monitor M1
2. start electron application
3. drag electron window to M1 area. 
4. kill electron application
5. disconnect M1
6. start electron application
7. confirm electron window not launching properly 

### Additional Information

- Operating System: windows 10
- Theia Version: master

### PR DESCRIPTION
**Pull request by smart-bo**
#### What it does

Fixes #10412
After disconnect extra monitor, electron window display properly.
#### How to test

1. connect one more monitor M1
2. start electron application
3. drag electron window to M1 area.
4. kill electron application
5. start electron application
6. confirm electron window is launching properly
7. kill electron application
8. disconnect M1
9. start electron application
10. confirm electron window is launching properly

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/core/src/electron-main/electron-main-application.ts [hunk 1]
```diff
@@ -42,6 +42,8 @@ const createYargs: (argv?: string[], cwd?: string) => Argv = require('yargs/yarg
 export interface TheiaBrowserWindowOptions extends BrowserWindowConstructorOptions {
     isMaximized?: boolean;
     isFullScreen?: boolean;
+    // screenLayout record the monitor information, so we can know if the monitors have been changed.
+    screenLayout: string;
```
Comment (vince-fugnitto) [inline packages/core/src/electron-main/electron-main-application.ts:46]:
```suggestion
    /**
     * Represents the complete screen layout for all available displays.
     * - Used to determine if the layout was updated since the electron window was last opened.
     */
    screenLayout: string;
```

Comment (smart-bo) [reply packages/core/src/electron-main/electron-main-application.ts]: Thanks. have changed.

**Review by vince-fugnitto — APPROVED** [review]
The changes work well, and I confirm that the updates should more elegantly open the electron window in case the previous display state no longer exists :+1:
