### PR TITLE
Multiple chat fixes

### LINKED ISSUE #17061: AI Chat: in-progress tool calls do not render their arguments
### Bug Description:

When a tool is running, we don't see the tool call arguments. We can only see the argument when the response is complete. This can be quite annoying for long-running tool calls, or worse, tool calls that are stuck in an infinite loop/await, as we don't see which inputs actually triggered the issue; making it difficult to debug/observe the tool call.

### Steps to Reproduce:

1. Trigger a long tool call (e.g. `Ask Universal to tell a long story ~delegateToAgent`)
2. While the tool is running, notice that you can't expand the tool call arguments section, as the `(...)` button is missing

Image

### Additional Information

- Operating System: Any
- Theia Version: 1.68.201

### PR DESCRIPTION
**Pull request by eneufeld**
#### What it does

This are actually 3 different changes. I can open 3 different PRs if this is then easier.
- Fix #17061 - render arguments while the tool is executing
- Allow to cancel the tool confirmation (deny) based on timeout
- Correctly inline delegation parts, instead of two different parts, this is now one part

#### How to test

- call a long running tool and see that the arguments appear immediately
- activate the cancel tool confirmation via settings or chat setting, see the tool is denied after the timeout
- ask universal to use coder in parallel to summarize 3 different files in parallel, see the agent delegation parts are shown in correct order

#### Follow-ups

The delegation does not fix the fact that the delegation is not correctly stored in the model. there is a ticket already for this.

#### Breaking changes

- [ ] This PR introduces breaking changes and requires careful review. If yes, the breaking changes section in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) has been updated.

#### Review checklist

- [ ] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)
- [x] User-facing text is internationalized using the `nls` service (for details, please see the [Internationalization/Localization section](https://github.com/theia-ide/theia/blob/master/doc/coding-guidelines.md#internationalizationlocalization) in the Coding Guidelines)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/ai-chat/src/browser/agent-delegation-tool.ts [hunk 1]
```diff
@@ -29,12 +29,13 @@ import {
     ChatSession,
     ChatRequestInvocation,
 } from '../common';
-import { DelegationResponseContent } from './delegation-response-content';
 
 @injectable()
 export class AgentDelegationTool implements ToolProvider {
     static ID = AGENT_DELEGATION_FUNCTION_ID;
 
+    readonly pendingDelegations = new Map<string, { agentName: string; prompt: string; invocation: ChatRequestInvocation }>();
```
Comment (sdirix) [inline packages/ai-chat/src/browser/agent-delegation-tool.ts]: `pendingDelegations` entries are added but never cleaned up and therefore retain forever.

File: packages/ai-chat-ui/src/browser/chat-response-renderer/tool-confirmation.tsx [hunk 2]
```diff
@@ -24,6 +24,44 @@ import { GroupImpl } from '@theia/core/lib/browser/menu/composite-menu-node';
...
+        return () => clearInterval(intervalId);
+    }, [effectiveTimeout]);
+
+    if (remainingSeconds <= 0) {
+        // eslint-disable-next-line no-null/no-null
+        return null;
+    }
+
+    return (
+        <div className='theia-tool-confirmation-countdown'>
```
Comment (sdirix) [inline packages/ai-chat-ui/src/browser/chat-response-renderer/tool-confirmation.tsx:66]: There is no CSS rule for `.theia-tool-confirmation-countdown`. We don't necessarily need one, just fyi.

File: packages/ai-chat-ui/src/browser/chat-response-renderer/delegation-tool-renderer.tsx [hunk 3]
```diff
@@ -13,46 +13,71 @@
...
+            prompt={delegation?.prompt ?? prompt}
+            finished={response.finished}
             parentNode={parentNode}
-            subChatWidgetFactory={this.subChatWidgetFactory} />;
+            subChatWidgetFactory={this.subChatWidgetFactory}
+        />;
     }
 }
 
+// --- DelegatedChat component (ported from delegation-response-renderer.tsx) ---
```
Comment (sdirix) [inline packages/ai-chat-ui/src/browser/chat-response-renderer/delegation-tool-renderer.tsx]: This comment can be removed

File: packages/ai-chat/src/common/tool-call-response-content.spec.ts [hunk 4]
```diff
@@ -229,3 +229,184 @@ describe('ToolCallChatResponseContentImpl', () => {
...
+
+    afterEach(() => {
+        clock.restore();
+    });
+
+    function createToolCallContent(id = 'test-id', name = 'test-tool'): ToolCallChatResponseContentImpl {
+        return new ToolCallChatResponseContentImpl(id, name, '{}');
+    }
+
+    async function runTimeoutPattern(
```
Comment (sdirix) [inline packages/ai-chat/src/common/tool-call-response-content.spec.ts]: `runTimeoutPattern` duplicates the exact logic from `FrontendChatToolRequestService`. If the production code changes, this test will keep passing against its own copy. Consider extracting the timeout racing logic into a shared utility that both the service and the test use.

File: packages/ai-chat/src/browser/chat-tool-request-service.ts [hunk 5]
```diff
@@ -77,7 +84,27 @@ export class FrontendChatToolRequestService extends ChatToolRequestService {
...
+                                });
+                                confirmed = await Promise.race([toolCallContent.confirmed, timeoutPromise]);
+                            } finally {
+                                if (timeoutId !== undefined) {
+                                    clearTimeout(timeoutId);
+                                }
+                            }
+                        } else {
+                            confirmed = await toolCallContent.confirmed;
+                        }
```
Comment (sdirix) [inline packages/ai-chat/src/browser/chat-tool-request-service.ts]: We perform all this timeout logic even if the tool was already allowed/confirmed. It is not a "bug" in the sense that it still works but it should be only done if we actually wait for the user.

File: packages/ai-chat/src/browser/agent-delegation-tool.ts (hunk 1 above)
Comment (eneufeld) [reply packages/ai-chat/src/browser/agent-delegation-tool.ts]: yes. but we don't want to clean them while our session can be reopened which is basically while theia is running. as long as we don't save delegation in the model there is no way around this.

File: packages/ai-chat-ui/src/browser/chat-response-renderer/tool-confirmation.tsx (hunk 2 above)
Comment (eneufeld) [reply packages/ai-chat-ui/src/browser/chat-response-renderer/tool-confirmation.tsx:66]: yeah we could remove it. or add css styling.

File: packages/ai-chat-ui/src/browser/chat-response-renderer/delegation-tool-renderer.tsx (hunk 3 above)
Comment (eneufeld) [reply packages/ai-chat-ui/src/browser/chat-response-renderer/delegation-tool-renderer.tsx]: good point will clean up.

File: packages/ai-chat/src/browser/agent-delegation-tool.ts (hunk 1 above)
Comment (sdirix) [inline packages/ai-chat/src/browser/agent-delegation-tool.ts]: `pendingDelegations` should be `protected`

File: packages/ai-chat/src/common/chat-tool-confirmation-timeout.ts [hunk 6]
```diff
@@ -0,0 +1,50 @@
...
+    content: ToolCallChatResponseContent,
+    timeoutSeconds: number
+): Promise<boolean> {
+    if (timeoutSeconds > 0) {
+        let timeoutId: ReturnType<typeof setTimeout> | undefined;
+        try {
+            const timeoutPromise = new Promise<boolean>(resolve => {
+                timeoutId = setTimeout(() => {
+                    if (!content.finished) {
+                        content.deny(`Confirmation timed out after ${timeoutSeconds} seconds`);
```
Comment (sdirix) [inline packages/ai-chat/src/common/chat-tool-confirmation-timeout.ts]: This denial reason is user-visible (rendered in `toolcall-part-renderer` and `shell-execution-tool-renderer`). It should be localized via `nls.localize`.

File: packages/ai-chat/src/browser/chat-tool-request-service.ts [hunk 7]
```diff
@@ -64,21 +65,29 @@ export class FrontendChatToolRequestService extends ChatToolRequestService {
                     default: {
                         const toolCallContent = this.findToolCallContent(toolRequest, arg_string, request, toolCallId);
 
+                        // Session setting overrides global preference
+                        const sessionTimeout = request.session.settings?.commonSettings?.confirmationTimeout;
+                        const timeoutSeconds = sessionTimeout !== undefined && sessionTimeout > 0
+                            ? sessionTimeout
+                            : this.preferences[TOOL_CONFIRMATION_TIMEOUT_PREFERENCE];
+                        toolCallContent.confirmationTimeout = timeoutSeconds;
```
Comment (sdirix) [inline packages/ai-chat/src/browser/chat-tool-request-service.ts]: Minor: should we even set the `confirmationTimeout` in case of auto allow or auto deny?

File: packages/ai-chat-ui/src/browser/chat-response-renderer/delegation-tool-renderer.tsx [hunk 8]
```diff
@@ -13,46 +13,69 @@
...
     }
-    render(response: DelegationResponseContent, parentNode: ResponseNode): React.ReactNode {
-        return this.renderExpandableNode(response, parentNode);
-    }
 
-    private renderExpandableNode(response: DelegationResponseContent, parentNode: ResponseNode): React.ReactNode {
+    render(response: ToolCallChatResponseContent, parentNode: ResponseNode): React.ReactNode {
+        const delegation = response.id ? this.agentDelegationTool.getDelegation(response.id) : undefined;
+
+        let agentId = response.name ?? AGENT_DELEGATION_FUNCTION_ID;
```
Comment (sdirix) [inline packages/ai-chat-ui/src/browser/chat-response-renderer/delegation-tool-renderer.tsx:47]: `response.name` is the tool name (`delegateToAgent`), not an agent identifier. This fallback will display the tool name as the agent header. Consider using a more descriptive default like `'Agent'` or omitting the fallback to `response.name` entirely.

File: packages/ai-chat-ui/src/browser/chat-response-renderer/delegation-tool-renderer.tsx [hunk 9]
```diff
@@ -1,5 +1,5 @@
 // *****************************************************************************
-// Copyright (C) 2025 EclipseSource GmbH.
+// Copyright (C) 2026 EclipseSource GmbH.
```
Comment (sdirix) [inline packages/ai-chat-ui/src/browser/chat-response-renderer/delegation-tool-renderer.tsx]: We usually don't update copyright years

File: packages/ai-chat-ui/src/browser/chat-response-renderer/delegation-tool-renderer.tsx [hunk 10]
```diff
@@ -63,40 +86,47 @@ interface DelegatedChatState {
 
 class DelegatedChat extends React.Component<DelegatedChatProps, DelegatedChatState> {
     private widget: ReturnType<SubChatWidgetFactory>;
-    private readonly toDispose = new DisposableCollection();
+    private toDispose = new DisposableCollection();
```
Comment (sdirix) [inline packages/ai-chat-ui/src/browser/chat-response-renderer/delegation-tool-renderer.tsx:89]: We usually don't do privates

File: packages/ai-chat/src/browser/agent-delegation-tool.ts (hunk 1 above)
Comment (sdirix) [reply packages/ai-chat/src/browser/agent-delegation-tool.ts]: I don't get it. Can't we remove an entry when we delete the corresponding session?

File: packages/ai-chat-ui/src/browser/chat-response-renderer/delegation-tool-renderer.tsx (hunk 10 above)
Comment (eneufeld) [reply packages/ai-chat-ui/src/browser/chat-response-renderer/delegation-tool-renderer.tsx:89]: but this is a non exported class, and nobody should access widget or toDispose from outside?

File: packages/ai-chat-ui/src/browser/chat-response-renderer/delegation-tool-renderer.tsx (hunk 8 above)
Comment (eneufeld) [reply packages/ai-chat-ui/src/browser/chat-response-renderer/delegation-tool-renderer.tsx:47]: the tool renderer also shows the tool name, so imho this is fine.
Especially as we only show this until an `agentId` is available.

File: packages/ai-chat/src/common/tool-call-response-content.spec.ts [hunk 11]
```diff
@@ -1,5 +1,5 @@
 // *****************************************************************************
-// Copyright (C) 2025 EclipseSource GmbH.
+// Copyright (C) 2025-2026 EclipseSource GmbH.
```
Comment (sdirix) [inline packages/ai-chat/src/common/tool-call-response-content.spec.ts]: Minor: Should not update copyright year

File: packages/ai-chat-ui/src/browser/chat-response-renderer/tool-confirmation.tsx [hunk 12]
```diff
@@ -24,6 +24,44 @@ import { GroupImpl } from '@theia/core/lib/browser/menu/composite-menu-node';
...
 import { ToolConfirmationManager } from '@theia/ai-chat/lib/browser/chat-tool-preference-bindings';
 
+export interface CountdownTimerProps {
+    response: ToolCallChatResponseContent;
+}
+
+export const CountdownTimer: React.FC<CountdownTimerProps> = ({ response }) => {
+    const timeoutSeconds = response.confirmationTimeout;
+    const effectiveTimeout = timeoutSeconds !== undefined && timeoutSeconds > 0 ? timeoutSeconds : 0;
+    const [remainingSeconds, setRemainingSeconds] = React.useState(effectiveTimeout);
```
Comment (sdirix) [inline packages/ai-chat-ui/src/browser/chat-response-renderer/tool-confirmation.tsx:43]: Timers become unpredictable once a Browser tab is no longer active. For example after 5 minutes, this timer will only fire every minute in Chrome.

To avoid drift between the visual countdown and the actual `setTimeout` in `raceConfirmationWithTimeout`, you could store an absolute deadline timestamp instead of a duration. Both sides then derive remaining time from the same wall-clock reference.

**Comment by eneufeld** [comment]
Created https://github.com/eclipse-theia/theia/issues/17216
