### PR TITLE
[preferences] fix indentation when updating preferences through the tree

### LINKED ISSUE #5052: [preferences] inconsistent formatting when adding a preference through the tree
**Description**
If a new preference is added by the `preferences-tree` the formatting becomes inconsistent with existing preferences.

**Steps to reproduce**
1. Start with a `settings.json` with exisitng preferences (in my case `json` had 2 spaces).
2. Add a new preference through the preferences tree.
3. Notice the inconsistent formatting (in my case the last two preferences are unformatted).

<div align='center'>

image

</div>

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

Fixes #5052

Fixes the inconsistent formatting when attempting to update/set preferences using the `preferences-tree` widget. Since the formatting options passed to `jsoncparser` were hardcoded, the formatting would be inconsistent with whichever formatting the editor currently has:

https://github.com/eclipse-theia/theia/blob/928e1e00b47268c7ea8b8f2889c520e5fa3d5f0a/packages/preferences/src/browser/abstract-resource-preference-provider.ts#L107

In order to fix the issue, the following method `detectIndentation` was implemented which attempts to determine the `tabSize` and `indentType` (`insertSpaces`) directly from the `TextEditorDocument` of the `settings.json` file in question. This is done in order to get a more accurate representation of the actual formatting present in the file.

The following is the before and after when adding a new preference `terminal.enableCopy` through the `preferences-tree`:

| Before (using `tabSize`=8) | After (using `tabSize`=8) |
|:---:|:---:|
|Screen Shot 2019-12-11 at 6 42 54 PM | Screen Shot 2019-12-11 at 6 40 30 PM |

#### How to test

1. attempt to add preferences through the preferences-tree widget
2. update the `tabSize` using the statusbar and format the document accordingly (repeat step 1)
3. update the `indentType` (spaces or tabs) using the statusbar, format the document accordingly (repeat step 1)
4. repeat step 1 using both `user` and `workspace` files

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

File: packages/preferences/src/browser/abstract-resource-preference-provider.ts [hunk 1]
```diff
@@ -102,9 +104,15 @@ export abstract class AbstractResourcePreferenceProvider extends PreferenceProvi
             return true;
         }
         try {
+            const editor = await this.editorManager.getByUri(new URI(resourceUri!));
```
Comment (akosyakov) [inline packages/preferences/src/browser/abstract-resource-preference-provider.ts]: What is there is no open editor? Should not we use preferences then?

File: packages/preferences/src/browser/abstract-resource-preference-provider.ts [hunk 2]
```diff
@@ -221,4 +229,33 @@ export abstract class AbstractResourcePreferenceProvider extends PreferenceProvi
...
     }
 
+    /**
+     * Detect the minimum indentation and type of indentation to be used
+     * as formatting options when using `jsoncparser`.
+     * @param text the preference text editor document.
+     *
+     * @returns a tuple representing the indentation size, and if it spaces.
+     */
+    protected detectIndentation(text: TextEditorDocument): [number, boolean] {
```
Comment (akosyakov) [inline packages/preferences/src/browser/abstract-resource-preference-provider.ts]: we should not do it like that, but rather get it from editor options

File: packages/preferences/src/browser/abstract-resource-preference-provider.ts (hunk 1 above)
Comment (vince-fugnitto) [reply packages/preferences/src/browser/abstract-resource-preference-provider.ts]: Yes, I think that'd be a better fallback.
I thought of it initially, if no open editors are present, use the preference value for JSON editors.

File: packages/preferences/src/browser/abstract-resource-preference-provider.ts (hunk 2 above)
Comment (vince-fugnitto) [reply packages/preferences/src/browser/abstract-resource-preference-provider.ts]: I implemented it this way because I could not find a way to get the information through editor options or other means.Any ideas?

**Comment by lmcbout** [comment]
Test the format on Ubuntu 16.04 and Chrome: works fine

File: packages/preferences/src/browser/abstract-resource-preference-provider.ts (hunk 1 above)
Comment (akosyakov) [reply packages/preferences/src/browser/abstract-resource-preference-provider.ts]: So we agree on it?

I generally don't like that we couple it here with the editor extension, maybe we always rely on preferences? by using preference service and strings as identifires? If an editor extension is not installed then we can fall back to `2` as tabSize  and `true` as insertSpaces.

File: packages/preferences/src/browser/abstract-resource-preference-provider.ts (hunk 2 above)
Comment (akosyakov) [reply packages/preferences/src/browser/abstract-resource-preference-provider.ts]: Why don't get them from the preference service? Even dirty editors should respect them and if they don't do then a user will commit some bogusly formatted code.

Comment (vince-fugnitto) [reply packages/preferences/src/browser/abstract-resource-preference-provider.ts]: True, in most cases the preferences values would be sufficient and only be inconsistent when the editor is dirty or a user chooses to update the values from the statusbar. I wanted to be smarter and try and determine the current indentation, but perhaps the preferences would be simpler.

File: packages/preferences/src/browser/abstract-resource-preference-provider.ts (hunk 1 above)
Comment (vince-fugnitto) [reply packages/preferences/src/browser/abstract-resource-preference-provider.ts]: > So we agree on it?
> 
> I generally don't like that we couple it here with the editor extension, maybe we always rely on preferences? by using preference service and strings as identifires? If an editor extension is not installed then we can fall back to `2` as tabSize and `true` as insertSpaces.

Yes, for simplicity I'll update the PR and only use the preferences instead.
I won't check for the editor and attempt to determine the current indentation and type.

File: packages/preferences/src/browser/abstract-resource-preference-provider.ts (hunk 2 above)
Comment (akosyakov) [reply packages/preferences/src/browser/abstract-resource-preference-provider.ts]: Using preference values should work for dirty editors, since editors always listening to the preference service and update options according. It can cause an issue if someone changes options from the status bar, but i would like to way till someone opens the real issue for it.

Comment (vince-fugnitto) [reply packages/preferences/src/browser/abstract-resource-preference-provider.ts]: > Using preference values should work for dirty editors, since editors always listening to the preference service and update options according. It can cause an issue if someone changes options from the status bar, but i would like to way till someone opens the real issue for it.

Sounds good, I'll make the updates.

Comment (vince-fugnitto) [reply packages/preferences/src/browser/abstract-resource-preference-provider.ts]: @akosyakov just a general question, is it possible to get a language specific preference?
In this case I only care about the corresponding JSON value for the preferences.

Comment (akosyakov) [reply packages/preferences/src/browser/abstract-resource-preference-provider.ts]: `[json].my.preference`

Comment (vince-fugnitto) [reply packages/preferences/src/browser/abstract-resource-preference-provider.ts]: > `[json].my.preference`

Thanks!

File: packages/core/src/browser/preferences/preference-service.ts [hunk 3]
```diff
@@ -70,7 +70,7 @@ export interface PreferenceService extends Disposable {
     readonly ready: Promise<void>;
     get<T>(preferenceName: string): T | undefined;
     get<T>(preferenceName: string, defaultValue: T): T;
-    get<T>(preferenceName: string, defaultValue: T, resourceUri: string): T;
+    get<T>(preferenceName: string, defaultValue: T, resourceUri?: string): T;
```
Comment (vince-fugnitto) [inline packages/core/src/browser/preferences/preference-service.ts]: I updated the typings as I believe they are incorrect. If a `defaultValue` is present, calling the method should not return `undefined` but rather the `defaultValue` if a preference cannot be found for a given `resourceUri`.

**Comment by vince-fugnitto** [comment]
@akosyakov I noticed a potential issue with the preferences for languages. During testing, I updated the global preference `editor.insertSpaces` to false, but it did not look to apply to the JSON language when getting the preference. Is this by design?

I had to do the following as a workaround:

```json
"[json]": {
    "editor.insertSpaces": false
}
```

Also, not sure if we should use `[json]` or `[jsonc]` when checking for preferences.

**Comment by akosyakov** [comment]
@vince-fugnitto I think `jsonc` should be proper for preferences.

File: packages/preferences/src/browser/abstract-resource-preference-provider.ts [hunk 4]
```diff
@@ -221,4 +223,28 @@ export abstract class AbstractResourcePreferenceProvider extends PreferenceProvi
...
+    /**
+     * Get the formatting options to be used when calling `jsoncparser`.
+     * The formatting options are based on the corresponding preference values.
+     * @param uri the preference settings URI.
+     *
+     * @returns a tuple representing the tab indentation size, and if it is spaces.
+     */
+    protected getFormattingOptions(uri?: string): [number, boolean] {
+        // Get the global `tabSize` preference value. Defaults to 2.
+        const globalTabSize = this.preferenceService.get('editor.tabSize', 2, uri);
```
Comment (akosyakov) [inline packages/preferences/src/browser/abstract-resource-preference-provider.ts]: it should not be necessary, if there are not `[json].editor.tabSize` then the preference service will try `editor.tabSize` as well. Clients should not care about reimplementing overriding logic, It's a responsibility of `PreferenceService`.

File: packages/preferences/src/browser/abstract-resource-preference-provider.ts [hunk 5]
```diff
@@ -221,4 +223,28 @@ export abstract class AbstractResourcePreferenceProvider extends PreferenceProvi
...
+        // Get the global `insertSpaces` preference value. Defaults to true.
+        const globalInsertSpaces = this.preferenceService.get('editor.insertSpaces', true, uri);
+        // Get the JSON `tabSize` preference value. Defaults to the global `tabSize` value.
+        const jsonTabSize = this.preferenceService.get('[json].editor.tabSize', globalTabSize, uri);
+        // Get the JSON `insertSpaces` preference value. Defaults to the global `insertSpaces` value.
+        const jsonInsertSpaces = this.preferenceService.get('[json].editor.insertSpaces', globalInsertSpaces, uri);
+        return [
```
Comment (akosyakov) [inline packages/preferences/src/browser/abstract-resource-preference-provider.ts]: object is better

File: packages/preferences/src/browser/abstract-resource-preference-provider.ts (hunk 4 above)
Comment (vince-fugnitto) [reply packages/preferences/src/browser/abstract-resource-preference-provider.ts]: It did not seem to work well initially. I noticed that if the global `editor.insertSpaces` was updated to false and no `[json].insertSpaces` was user defined, the value remained true (which caused incorrect indentation). In this way we explicitly fallback to the values we care about.

File: packages/preferences/src/browser/abstract-resource-preference-provider.ts (hunk 5 above)
Comment (vince-fugnitto) [reply packages/preferences/src/browser/abstract-resource-preference-provider.ts]: Updated, thank you!

File: packages/preferences/src/browser/abstract-resource-preference-provider.ts (hunk 4 above)
Comment (vince-fugnitto) [reply packages/preferences/src/browser/abstract-resource-preference-provider.ts]: @akosyakov during testing I noticed an odd behavior that made me conclude it might be necessary or better to fallback to the values at a higher scope. For example, when updating the preference `editor.insertSpaces` to false and no user preference `[json].editor.insertSpaces` was defined, the global preference was never read which lead to an odd behavior. Instead, the fallback used to be always `true`.

Comment (akosyakov) [reply packages/preferences/src/browser/abstract-resource-preference-provider.ts]: It sounds like a bug, I would try to debug later.

File: packages/preferences/src/browser/abstract-resource-preference-provider.ts [hunk 6]
```diff
@@ -104,7 +105,7 @@ export abstract class AbstractResourcePreferenceProvider extends PreferenceProvi
         try {
             let newContent = '';
             if (path.length || value !== undefined) {
-                const formattingOptions = { tabSize: 3, insertSpaces: true, eol: '' };
+                const formattingOptions = this.getFormattingOptions();
```
Comment (akosyakov) [inline packages/preferences/src/browser/abstract-resource-preference-provider.ts]: Should not we pass URI?

File: packages/preferences/src/browser/abstract-resource-preference-provider.ts [hunk 7]
```diff
@@ -221,4 +222,30 @@ export abstract class AbstractResourcePreferenceProvider extends PreferenceProvi
...
+        const globalTabSize = this.preferenceService.get('editor.tabSize', 2, uri);
+        const globalInsertSpaces = this.preferenceService.get('editor.insertSpaces', true, uri);
+
+        // Get the superset JSON formatting options for both `tabSize` and `insertSpaces`.
+        const jsonTabSize = this.preferenceService.get('[json].editor.tabSize', globalTabSize, uri);
+        const jsonInsertSpaces = this.preferenceService.get('[json].editor.insertSpaces', globalInsertSpaces, uri);
+
+        return {
+            tabSize: this.preferenceService.get('[jsonc].editor.tabSize', jsonTabSize, uri),
+            insertSpaces: this.preferenceService.get('[json].editor.insertSpaces', jsonInsertSpaces, uri),
```
Comment (akosyakov) [inline packages/preferences/src/browser/abstract-resource-preference-provider.ts]: `[jsonc]`

Comment (vince-fugnitto) [reply packages/preferences/src/browser/abstract-resource-preference-provider.ts]: Thank you! I updated the code.

**Comment by vince-fugnitto** [comment]
@lmcbout if you get a chance, can you please re-test the pull request? 
The overall strategy has been changed and simplified.

**Comment by lmcbout** [comment]
Tested with @vince-fugnitto not perfect, but OK

**Comment by vince-fugnitto** [comment]
> Tested with @vince-fugnitto not perfect, but OK

@lmcbout I completely understand, the pull request becomes best effort when the settings document is not properly formatted or is formatted inconsistently (different `tabSize` and `indentation` throughout the document).

When the document is properly formatted, inserting preferences from the `preferences-tree` is more consistent. Overall, the pull request improves upon the original implementation which used hard coded values and would always format inconsistently.

Perhaps we can improve the pull request further in the future, but I am unsure what an appropriate strategy would be when working with un-formatted documents.
