### PR TITLE
reload plugins on reconnect

### LINKED ISSUE #4590: Vscode Go debugger freeze on web-socket disconnect
### Description
ms-vscode.Go extension debugger (could be general issue with vscode extension debug) do not handle well server restart or brief web-socket disconnect.

There is a difference between node.js debug and go debug (based on vs-code-ext):
- Node.js: when web-socket disconnects, the debug session resets, the debuggee stops. This behavior seems normal.
- Go: when web-socket disconnects, the debug session on the browser side seems stuck, no button of debug has any effect, and you must reload the webpage entirely to recover. The debuggee continues to run.

### Reproduction Steps

- Install ms-vscode.Go version 0.9.2
- Start debug session
- Simulate web-socket disconnect

To simulate web-socket disconnects, one can use this code for reverse proxy, and access theia via port 3001

```
var express  = require('express');
var app      = express();
var httpProxy = require('http-proxy');
var proxy = httpProxy.createProxyServer({ target: 'http://localhost:3000', ws: true });

var server = require('http').createServer(app);

// proxy HTTP GET / POST
app.get('/*', function(req, res) {
  console.log("proxying GET request", req.url);
  proxy.web(req, res, {});
});
app.post('/*/*', function(req, res) {
  console.log("proxying POST request", req.url);
  proxy.web(req, res, {});
});

// Proxy websockets
server.on('upgrade', function (req, socket, head) {
  console.log("proxying upgrade request", req.url);
  proxy.ws(req, socket, head);
});

server.listen(3001);
```

**OS and Theia version:**
OS: Debian GNU/Linux
Thiea: 0.4.0

### LINKED ISSUE #5025: After a disconnect of the browser, commands from a VSCode extension do not work
### Description
If the browser disconnects from the server, either briefly due to network error, or if the server restarted, VSCode extension commands stop working.
I also noticed that if the server restarted, the browser reconnects but the VSCode extension was not activated. 

Maybe related to this: 
https://github.com/theia-ide/theia/issues/4590

in that case the whole extension may stop functioning and commands is just a special case.

### Reproduction Steps
You may clone this vscode extension: https://github.com/ariel-bentu/theia-vscode-gaps.git
when you start the browser first time, you can see that it functions (right click on a node in the view that was added, click one of the commands and see that they work.

Now restart Theia server, and wait for the browser to reconnect - see that now these commands don't work.
Also, in the server log, you can see that the extension did not load (it prints: 
`console.log('Congratulations, your extension "bugs" is now active!');`)

In addition, try disconnecting the network w/o restart and still these commands don't work after the reconnect. (for disconnecting technic, see https://github.com/theia-ide/theia/issues/4590)

**OS and Theia version:**
MAC, latest version

**Diagnostics:** 
See above

### LINKED ISSUE #5829: ensure that no plugin can be loaded twice
This code is not thread-safe: https://github.com/theia-ide/theia/blob/98bf44fbc831b2c64714315ebc1fbe5e6fdeb0a4/packages/plugin-ext/src/hosted/browser/hosted-plugin.ts#L159

Loading plugin should be filtered out as well, otherwise calling `loadPlugins` multiple times for the same plugin can cause race conditions.

### LINKED ISSUE #6186: Duplicate language server results when installing a second language plugin
### Description
 

When you have a java file and an xml file open in the workspace, then install `redhat.vscode-xml` followed by `redhat.java` there is duplicate results from the java language server. It also works in the inverse, if you have both java and an xml file open in the workspace then install `redhat.java` then  `redhat.vscode-xml` you'll get duplicates from the xml language server.

I'm not using @theia/java or @theia/java-debug in my package.json.

### Reproduction Steps

Open a project and create and open a java file and an xml file. Install `redhat.vscode-xml` and then `redhat.java`. From inside of the xml file you just created, try doing document symbols. Everything should be working correctly. Then in the java file try doing document symbols and you should see duplicate results.

Video: https://youtu.be/d_NSbRV38BI

**OS and Theia version:**
Both OS x and Fedora 30 on master

**Diagnostics:** 

I'm getting

```
root ERROR onWillSave listeners should provide edits, not directly alter the document.
```

and 

```
rpc-protocol.ts:224 Uncaught (in promise) Error: Assertion failed (document 'file:///home/joshpinkney/Documents/Work/console-java-simple/src/main/java/org/eclipse/che/examples/test.xml' already exists!)
    at Object.ok (:3000/home/joshpinkney/Documents/Test/theia/packages/plugin-ext/lib/common/assert.js:21)
    at EditorsAndDocumentsExtImpl.$acceptEditorsAndDocumentsDelta (:3000/home/joshpinkney/Documents/Test/theia/packages/plugin-ext/lib/plugin/editors-and-documents.js:81)
    at RPCProtocolImpl.doInvokeHandler (:3000/home/joshpinkney/Documents/Test/theia/packages/plugin-ext/lib/common/rpc-protocol.js:207)
    at RPCProtocolImpl.invokeHandler (:3000/home/joshpinkney/Documents/Test/theia/packages/plugin-ext/lib/common/rpc-protocol.js:192)
    at RPCProtocolImpl.receiveRequest (:3000/home/joshpinkney/Documents/Test/theia/packages/plugin-ext/lib/common/rpc-protocol.js:154)
    at RPCProtocolImpl.receiveOneMessage (:3000/home/joshpinkney/Documents/Test/theia/packages/plugin-ext/lib/common/rpc-protocol.js:123)
    at :3000/home/joshpinkney/Documents/Test/theia/packages/plugin-ext/lib/common/rpc-protocol.js:55
    at :3000/home/joshpinkney/Documents/Test/theia/packages/plugin-ext/lib/common/rpc-protocol.js:233
    at :3000/home/joshpinkney/Documents/Test/theia/packages/core/lib/common/event.js:162
    at CallbackList.invoke (:3000/home/joshpinkney/Documents/Test/theia/packages/core/lib/common/event.js:177)
```

in the console.

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

- [x] fix #5025: reload plugins on reconnect
  - [x] unload plugin static contributions
    - [x] only if a plugin was undeployed
    - [x] unload languages
    - [x] unload tasks
    - [x] unload commands
    - [x] unload menus
    - [x] unload view containers
    - [x] unload views
    - [x] unload keymaps
    - [x] unload schemas
    - [x] unload snippets
    - [x] unload shared css styles
  - [x] unload plugin code and dynamic contributions
    - [x] unload rpc (dispose internal state and does not allow to add new proxies, services and so on)
    - [x] unload command registry (dispose command and handlers)
    - [x] unload quick open (hide quick open and dispose its listeners)
    - [x] unload workspace (dispose workspace and fs watch listeners, content providers) 
      - [x] install only one fs watcher for all plugins instead of for each plugin
    - [x] unload dialogs (no listeners or state to dispose)
    - [x] unload message registry (no listeners or state to dispose)
    - [x] unload preference registry (dispose preference service listeners)
    - [x] unload documents (dispose editor and model listeners)
    - [x] unload editors (remove editor decorations)
    - [x] unload status bar registry (remove status bar entries)
    - [x] unload env (no listeners or state to dispose)
    - [x] unload notification (cancel all running progress reporting)
    - [x] unload terminal (dispose terminal service and terminal listeners)
    - [x] unload tree view (unregister tree data providers and remove tree view listeners)
      - [x] preserve tree views on reconnect
    - [x] unload output (not listeners, output channels are preserved)
    - [x] unload languages (language features gets disposed, but diagnostics are preserved)
    - [x] unload webview (dispose webviews and its serializers)
    - [x] unload storage (no listeners or state to dispose, but path service is rewritten to avoid forever pending promises and accepting workspace URI as an arg for each request instead of caching a random one)
    - [x] unload connection (remove connections)
    - [x] unload tasks (unregister task providers, preserve running tasks)
    - [x] unload languages contribution (stop them)
    - [x] unload debug (dispose debug listeners and remove debug contributions)
      - debug sessions are not preserved, we have to implement: https://github.com/eclipse-theia/theia/issues/3361
    - [x] unload fs (dispose fs providers)
    - [x] unload scm (dispose scm listeners and remove contributed repositories)
    - [x] unload explorer decorations (dispose providers)
    - [x] unload window (remove event listeners)
    - [x] unload clipboard (no listeners or state to dispose)
    - [x] unload shared css styles
- [x] fix #5829: ensure that each plugin is loaded only once
- [x] revert https://github.com/theia-ide/theia/pull/5257: it was bogus to introduce in the first place
- [x] fix #6186: start only one plugin host process for the same host instead of a new for each load as before
- [x] update the changelog with a breaking change
  - [x] clarify how to treat custom main services, see https://github.com/eclipse-theia/theia/pull/6159#issuecomment-532993749
- [x] fix #4590: plugin debug sessions are closed on reconnection for now, track https://github.com/eclipse-theia/theia/issues/4591 and https://github.com/eclipse-theia/theia/issues/3361 for improvements

Out of scope:
- handling extension dependencies on stop
- UI to uninstall extensions

#### How to test

- [x] reconnect because of a connection failure
  - no reproducible with Chrome since it cannot throttle web socket connections
  - throttle with the system proxy instead, for instance with https://www.charlesproxy.com/
- [x] reconnect on the server restart
- [x] test everything with multiple windows for the same backend

Hints:
- Take memory snapshots when a connection is gone to check that there is no main services are left.

Tested with following VS Code extensions:
- [x] trees - [tree-view-sample](https://github.com/microsoft/vscode-extension-samples/tree/master/tree-view-sample)
- [x] languages - [ms-vscode.Go](https://marketplace.visualstudio.com/items?itemName=ms-vscode.Go)
- [x] debugging - [node-debug](https://marketplace.visualstudio.com/items?itemName=ms-vscode.node-debug) and [node-debug2](https://marketplace.visualstudio.com/items?itemName=ms-vscode.node-debug2)
- [x] scm - [built-in git](https://registry.npmjs.org/@theia/vscode-builtin-git/-/vscode-builtin-git-0.2.1.tgz)
- [x] webviews - [webview-sample](https://github.com/microsoft/vscode-extension-samples/tree/master/webview-sample)
  - make sure to use [this commit](https://github.com/microsoft/vscode-extension-samples/commit/104c10a3f20c347d1a8e4c2cedc01391e6f677dc), never versions use `asWebviewUri` api
- [x] quick pick/input - [quickinput-sample](https://github.com/microsoft/vscode-extension-samples/tree/master/quickinput-sample)

##### Reconnecting tree views
reconnect_tree_views

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by amiramw** [comment]
@akosyakov do you think custom APIs should also be treated to allow unload?

**Comment by akosyakov** [comment]
> do you think custom APIs should also be treated to allow unload?

@amiramw Custom main services should implement `Disposable` interface, then they will be disposed. I will add it in the changelog.

**Comment by akosyakov** [comment]
@eclipse-theia/eclipse-theia I'm still trying different extensions to check reload of all contributions, but the code should be in final state and help with testing is welcomed!

File: packages/plugin-ext/src/main/browser/plugin-shared-style.ts [hunk 1]
```diff
@@ -83,26 +93,31 @@ export class PluginSharedStyle {
         }
     }
 
+    private readonly icons = new ReferenceCollection<PluginIconKey, PluginIcon>(key => this.createPluginIcon(key));
```
Comment (svenefftinge) [inline packages/plugin-ext/src/main/browser/plugin-shared-style.ts]: Would it make sense to create a synchronous version of `ReferenceCollection` to avoid the seemingly unnecessary async change?

File: packages/plugin-ext/src/plugin/plugin-manager.ts [hunk 2]
```diff
@@ -97,25 +97,44 @@ export class PluginManagerExtImpl implements PluginManagerExt, PluginManager {
...
-        this.activatedPlugins.forEach(plugin => {
-            if (plugin.stopFn) {
-                plugin.stopFn();
-            }
+    async $stop(pluginId?: string): Promise<void> {
+        if (!pluginId) {
+            this.stopAll();
+            return;
+        }
+        // TODO what to do about transitive extensions?
```
Comment (svenefftinge) [inline packages/plugin-ext/src/plugin/plugin-manager.ts]: I don't think we need this TODO, as transitive plugins are installed as proper first class plugins, so they will be discarded as well. Keeping it might distract readers.

**Comment by svenefftinge** [comment]
Works great as well! 

I noticed that after disconnecting and reconnecting again, there is an additional reconnection. 
I.e. I see 
```
root INFO Registering scopes for language: java.
logger-protocol.ts:112 root INFO The scopes have been successfully registered for java.
index.js:94 Error: Connection timeout
    at index.js:85
(anonymous) @ index.js:94
setTimeout (async)
emitError @ index.js:84
(anonymous) @ index.js:127
setTimeout (async)
connect @ index.js:124
setTimeout (async)
handleClose @ index.js:113
logger-protocol.ts:112 root INFO Unregistering scopes for language: java.
logger-protocol.ts:112 root INFO The scopes have been successfully unregistered for java.
```

but I think you mentioned that once to me and it is also unrelated to this PR as it happens without the change, too. With this PR this at least doesn't have such a bad side effect anymore. 🎉

File: packages/plugin-ext/src/common/rpc-protocol.ts [hunk 3]
```diff
@@ -61,37 +62,60 @@ export function createProxyIdentifier<T>(identifier: string): ProxyIdentifier<T>
...
     }
 
     set<T, R extends T>(identifier: ProxyIdentifier<T>, instance: R): R {
-        this.locals[identifier.id] = instance;
+        if (this.isDisposed) {
+            throw new Error('connection is closed');
+        }
+        this.locals.set(identifier.id, instance);
+        if (Disposable.is(instance)) {
+            this.toDispose.push(instance);
```
[the remark this answers is not in the document]
Comment (akosyakov) [reply packages/plugin-ext/src/common/rpc-protocol.ts]: i actually thought that it should be replaced by a contribution point, something like `PluginRPCService`, then contributions will be created by `RPCProtocol` and installed, but first we need to refactor the plugin system to use DI.

**Comment by akosyakov** [comment]
merging if the build is green

File: packages/plugin-ext/src/common/plugin-api-rpc.ts [hunk 4]
```diff
@@ -163,7 +163,7 @@ export const emptyPlugin: Plugin = {
 };
 
 export interface PluginManagerExt {
-    $stopPlugin(contextPath: string): PromiseLike<void>;
+    $stop(pluginId?: string): PromiseLike<void>;
```
Comment (benoitf) [inline packages/plugin-ext/src/common/plugin-api-rpc.ts]: why break the name of this method ?

File: packages/plugin-ext/src/hosted/node/plugin-host-rpc.ts [hunk 5]
```diff
@@ -80,16 +80,6 @@ export class PluginHostRPC {
         }
     }
 
-    /*
```
Comment (benoitf) [inline packages/plugin-ext/src/hosted/node/plugin-host-rpc.ts]: Hello, why stopContext has been removed ? it's also not referenced in changelog ?


plugin-host-rpc is quite sensitive as it's used downstream like Eclipse Che.

Also I don't see it related to the changes of this PR

File: packages/plugin-ext/src/common/plugin-api-rpc.ts (hunk 4 above)
Comment (akosyakov) [reply packages/plugin-ext/src/common/plugin-api-rpc.ts]: Because it does not do what it means: It does not stop one plugin but all plugins. `contextPath` is unused, changing `contextPath` to optional `pluginId` to stop either one plugin or all was already a breaking change. I could introduce another method, but then `stopPlugin` won't be used anywhere in the Theia repo. I did not see a reason why to keep an unused method.

File: packages/plugin-ext/src/hosted/node/plugin-host-rpc.ts (hunk 5 above)
Comment (akosyakov) [reply packages/plugin-ext/src/hosted/node/plugin-host-rpc.ts]: There were a clean up of plugin unloading that they can be uninstalled and unused clients of refactored code were removed. Code which should be used in a downstream project should be moved to a corresponding project, not kept in the Theia repo without any internal clients and ability to test by any committer.

There is a record that this PR breaks the plugin system. So far we were not listing individual changes only notified that some part will be broken in next release by some PRs, since we did not really document anything as APIs. Please raise it at the dev meeting if you suggest that each a change to each function should be listed.

Please review a PR while it is not merged, not afterwards. It was 9 days while it was in draft mode for the design review. Committers are not expected to review and test PRs against downstream projects or wait when someone does it.

Please also opened follow-up issues to already merged PRs. Not many committers read comments on them and it can get lost.

Comment (benoitf) [reply packages/plugin-ext/src/hosted/node/plugin-host-rpc.ts]: If you're considering that removing code or changing structural behavior is only requiring one approval from a committer of the same company, I think something is wrong.

Comment (akosyakov) [reply packages/plugin-ext/src/hosted/node/plugin-host-rpc.ts]: Please add to discuss to the dev meeting.

Regarding to 
> Code which should be used in a downstream project should be moved to a corresponding project, not kept in the Theia repo without any internal clients and ability to test by any committer.

I remembered that we don't have something like DI in the plugin host process yet, not sure whether you can actually extend it. If not please let me know, the issue will be the best.
