### PR TITLE
[scm] refesh on widget activation

### LINKED ISSUE #7873: Git changes list does not get updated
### Bug Description:
The list of git changes is not updated automatically. One has to do some action first in the git widget (such as expanding/collapsing the list or refreshing it...)
Note: this happens with non-active git widget only.
theia-git-list-not-updated
 

### Steps to Reproduce:

1. open a file and leave filebrowser active
2. change something
3. open git widget - changes are not displayed until some action in git widget

### Additional Information

- Operating System:
- Theia Version:

### PR DESCRIPTION
**Pull request by svenefftinge**
#### What it does
fixes #7873

#### How to test
Try reproduce #7873

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by lmcbout** [comment]
Suggestion: In this PR, there should be 1-2 lines changes, not the whole file. Everyone should use the same format, it would make it easier to identify the changes  while performing the review.

File: packages/scm/src/browser/scm-widget.tsx [hunk 1]
```diff
@@ -149,6 +149,7 @@ export class ScmWidget extends BaseWidget implements StatefulWidget {
 
     protected onActivateRequest(msg: Message): void {
         super.onActivateRequest(msg);
+        this.refresh();
```
Comment (akosyakov) [inline packages/scm/src/browser/scm-widget.tsx:152]: I think the real issue is that `ScmRepository.onDidChange` does not fire then `GitWatcher.onGitEvent` reports a change event for the repository.

Comment (akosyakov) [inline packages/scm/src/browser/scm-widget.tsx:152]: I wonder should not we rather move it to `onAfterShow`, so it gets refreshed whenever the widget is revealed not focused?
