### PR TITLE
Save as command correctly creates a new file before saving

### LINKED ISSUE #8373: "Save As..." should open the new file
### Bug Description:
Currently "Save as..." will keep the original file open, instead of opening the new file which is very unintuitive as most (all?) programs open the new file. In particular, vscode will open the new file. 

### Steps to Reproduce:

1. Execute "Save as..."

### Additional Information

- Operating System: Linux
- Theia Version: Current Gitpod version

### LINKED ISSUE #8504: "Save as..." should not save changes to original file
### Bug Description:
Currently "Save as..." will save any changes made to the original file to the original file, then copy it to the new file. This is contrary to how most programs handle it, where the changes made are only saved to the new file.

### Steps to Reproduce:

1. Open a file and make some changes
2. Execute "Save As..."

### Additional Information

- Operating System: macOS
- Theia Version: Current Gitpod version

### PR DESCRIPTION
**Pull request by Darkgaja**
#### What it does

Fixes #8373
Fixes #8504
Closes https://github.com/eclipse-theia/theia/pull/8514

When using the "save as" command, a new file will be created with the new changes, and the old file will be unchanged. The text editor will then close the old file and open the new one.

#### How to test

* Open a file and make some changes
* Use "Save as" command
* The text editor will now open the new file created with the changes. The old file will be closed.
* The old file will be unchanged.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by vince-fugnitto — COMMENTED** [review]
@Darkgaja thank you for taking care of the issue, the changes look very good already.
We should possibly change the `enabled` of the command to be available only when an editor is opened. With these changes, if a file node is selected in the `explorer`, the command is available, prompts the user to choose a name but does not perform an actual save (given that `sourceWidget` is undefined).

Else, we may not want to show the dialog at all when no editor is opened (similarly to vscode).

**Comment by Darkgaja** [comment]
@vince-fugnitto sure, I'll look into this as well

**Comment by marechal-p** [comment]
The change seems to work, but I don't know what to think about a new tab being opened and the old one closing? Is there a way to not do that?

**Comment by vince-fugnitto** [comment]
> The change seems to work, but I don't know what to think about a new tab being opened and the old one closing? Is there a way to not do that?

@marechal-p I believe that is the intended behavior (similarly to vscode), when `save as...` is performed, the original editor is closed while the new one is opened. I believe vscode handles it more gracefully (without the UI change) by replacing the editor if that's what you're referring to.

**Comment by marechal-p** [comment]
> by replacing the editor if that's what you're referring to.

This is what I meant. It is weird how it works right now, but if that's all we can do I'm fine.

File: packages/workspace/src/browser/workspace-frontend-contribution.ts [hunk 1]
```diff
@@ -418,14 +420,32 @@ export class WorkspaceFrontendContribution implements CommandContribution, Keybi
...
             } catch (e) {
                 console.warn(e);
             }
         }
     }
 
+    private async copySave(source: URI, selected: URI, overwrite: boolean): Promise<void> {
+        const sourceWidget = this.applicationShell.currentWidget;
+        const sourceSaveable = Saveable.get(sourceWidget);
+        if (sourceWidget && sourceSaveable && sourceSaveable.createSnapshot && sourceSaveable.revert) {
```
Comment (colin-grant-work) [inline packages/workspace/src/browser/workspace-frontend-contribution.ts:433]: Would it be desirable to give the user some indication that a save-as operation had failed if their particular brand of `Saveable` doesn't have `createSnapshot` or `revert`? As a practical matter, that's very unlikely to occur, but it looks like this code would just fail silently in that case, and that might be confusing.

Comment (Darkgaja) [reply packages/workspace/src/browser/workspace-frontend-contribution.ts:433]: Sure, makes sense. Do you have a preference how this indicator should look like? (Notification?)

Comment (colin-grant-work) [reply packages/workspace/src/browser/workspace-frontend-contribution.ts:435]: Notification sounds reasonable to me.

Comment (Darkgaja) [reply packages/workspace/src/browser/workspace-frontend-contribution.ts:433]: Using the `NotificationManager` leads to tsc errors (as seen in 5937ccc). Any idea how I can resolve these?

Comment (colin-grant-work) [reply packages/workspace/src/browser/workspace-frontend-contribution.ts:433]: It looks like you didn't add an explicit dependency on the `messages` package in the `workspace` package. If you add `@theia/messages` to the `packages/workspace/package.json` and a `reference` to the `messages` package in `packages/workspace/compile.tsconfig.json`, you should be able to use notifications.

Comment (colin-grant-work) [reply packages/workspace/src/browser/workspace-frontend-contribution.ts:433]: (It looks like that won't create any circularity, but if you'd rather not bother with that, you could show a toast using the `MessageService`, which is in `core` and so already accessible in the `workspace` package.)

Comment (vince-fugnitto) [reply packages/workspace/src/browser/workspace-frontend-contribution.ts:433]: @Darkgaja please use the `MessageService` to display messages to end-users (in this case a warning or error might be the best option).
- https://eclipse-theia.github.io/theia/docs/next/classes/core.messageservice-1.html

**Review by DukeNgn — COMMENTED** [review]
1. Open 2 editors: `./a.ts` and `./folder/b.ts`
2. Make changes in `a.ts` and call `Save as ...` in the file, overwrite `./folder/b.ts`
3. A dialog displays upon saving:

image

Do you know if we can bypass this dialog?
The PR looks good to me otherwise

**Comment by Darkgaja** [comment]
@DukeNgn I noticed that the dialog comes up because of the `fileSystem.copy` call. Checking whether the file exists beforehand eliminates the dialog.

**Review by vince-fugnitto — COMMENTED** [review]
@Darkgaja do you mind squashing your changes to a single commit with a nice commit message? I'll perform a review in the meantime.

**Comment by vince-fugnitto** [comment]
> Do you know if we can bypass this dialog?

@DukeNgn the dialog is presented when we attempt to overwrite a file (it should ask for confirmation first).
The same behavior is present in other applications, like vscode for instance under the same use-case.

**Comment by Darkgaja** [comment]
@vince-fugnitto Actually, this is a different dialog. The confirmation dialog correctly pops up while selecting a file. The dialog @DukeNgn is talking about pops up because the `fileSystem.copy` call modifies a file that is opened within a dirty editor. In this case a competely unrelated event triggers and asks the user whether he wants to overwrite the dirty editor state with the changes made on the filesystem. This additional dialog doesn't trigger in vscode.

Nevertheless, I will squash my commits.

**Review by vince-fugnitto — COMMENTED** [review]
@Darkgaja do you mind rebasing and resolving conflicts?

**Comment by Darkgaja** [comment]
@vince-fugnitto done.

File: packages/workspace/src/browser/workspace-frontend-contribution.ts [hunk 2]
```diff
@@ -418,14 +421,36 @@ export class WorkspaceFrontendContribution implements CommandContribution, Keybi
...
-                await this.fileService.copy(uri, selected, { overwrite });
+                await this.copySave(uri, selected, overwrite);
             } catch (e) {
                 console.warn(e);
             }
         }
     }
 
+    private async copySave(source: URI, selected: URI, overwrite: boolean): Promise<void> {
+        const sourceWidget = this.applicationShell.currentWidget;
```
Comment (marechal-p) [inline packages/workspace/src/browser/workspace-frontend-contribution.ts:432]: I didn't understand the relationship between the `source` parameter and the `sourceWidget` ref?

Should you rather try to find the widget that has `source` as URI instead?

Comment (Darkgaja) [reply packages/workspace/src/browser/workspace-frontend-contribution.ts:432]: So the relationship is quite implicit. We can use the `currentWidget` here savely for multiple reasons. First off, we know that the `currentWidget` is definitely a saveable item by checking for it in the `isEnabled` flag of the command. Secondly, the `source` parameter is provided by the `SelectionService` which contains the currently selected editor (which is a child of the `currentWidget` afaik). 

Also, saving always uses the `currentWidget` of the `ApplicationShell` as shown in [here](https://github.com/Darkgaja/theia/blob/9333761db1e9822d63888893af82ed63dc164bf3/packages/core/src/browser/shell/application-shell.ts#L1731-L1736). Furthermore, I think there isn't even a trivial method to find a widget by its uri.

Comment (marechal-p) [reply packages/workspace/src/browser/workspace-frontend-contribution.ts:432]: Thanks for the explanation. Essentially we use the selection service just to get a URI and use the `currentWidget` for everything else, I really find that confusing... Since I'm the one having issues with that logic, I made a commit on top of your PR, please tell me what you think and feel free to apply those changes here: https://github.com/Darkgaja/theia/compare/save-as-create-file...marechal-p:save-as-create-file-2

My commit simplifies the command handler for `SAVE_AS`, makes most checks on the `currentWidget` before calling the `saveAs` logic, and uses said widget as source-of-truth all the way down.

Comment (Darkgaja) [reply packages/workspace/src/browser/workspace-frontend-contribution.ts]: Thank you, your code is definitely easier to follow. I merged your contribution.

**Review by marechal-p — COMMENTED** [review]
LGTM, thanks!

**Review by marechal-p — APPROVED** [review]

File: packages/workspace/src/browser/workspace-frontend-contribution.ts [hunk 3]
```diff
@@ -149,17 +150,27 @@ export class WorkspaceFrontendContribution implements CommandContribution, Keybi
             isEnabled: () => this.workspaceService.isMultiRootWorkspaceEnabled,
             execute: () => this.saveWorkspaceAs()
         });
-        commands.registerCommand(WorkspaceCommands.SAVE_AS,
-            UriAwareCommandHandler.MonoSelect(this.selectionService, {
-                execute: (uri: URI) => this.saveAs(uri),
-            }));
+        commands.registerCommand(WorkspaceCommands.SAVE_AS, {
+            isEnabled: () => this.canBeSavedAs(this.applicationShell.currentWidget),
+            execute: () => {
```
Comment (vince-fugnitto) [inline packages/workspace/src/browser/workspace-frontend-contribution.ts:155]: I just wanted to mention that with this approach we lose the following abilities:

- we lose the ability to rely on the selection in order to perform `save_as` and now rely on the widget
- we lose the ability to callers to execute the command with a passed uri like so:


```ts
registry.registerCommand({ id: 'test-saveAs', label: 'test-saveAs' }, {
    execute: async () => {
        await registry.executeCommand(WorkspaceCommands.SAVE_AS.id, new URI('/tmp/a.ts'));
    }
});
```

If we are fine with this behavior, we should probably document it as such in the changelog's breaking changes.

Comment (marechal-p) [reply packages/workspace/src/browser/workspace-frontend-contribution.ts:155]: Despite the old change including the `UriAware...` handler, since it used a URI from one place and the `currentWidget` at the same time it lead to weird cases (e.g. passed `uri` to the command doesn't match the `currentWidget`'s uri).

So either we definitely break that behavior, or this PR requires a bit more changes to address this use case?

Comment (vince-fugnitto) [reply packages/workspace/src/browser/workspace-frontend-contribution.ts:155]: @marechal-p I'd be fine to break the behavior and align more closely to [vscode's implementation](https://github.com/microsoft/vscode/blob/9c78fa40ca7ab6b58d0ab5cd33858a39a2b7102d/src/vs/workbench/contrib/files/browser/fileCommands.ts#L371-L425) which also relies on the `currentEditor`. I wanted to bring it up so that we properly document the breaking change and the fact we cannot call the method anymore the way I wrote in the snippet.

Comment (marechal-p) [reply packages/workspace/src/browser/workspace-frontend-contribution.ts:155]: I don't see a nice way to handle saving a random URI and properly handling eventual opened editors. @Darkgaja wdyt?

Comment (Darkgaja) [reply packages/workspace/src/browser/workspace-frontend-contribution.ts:155]: I think so too. This was the reason I implemented it for the `currentWidget` in the first place.

Comment (Darkgaja) [reply packages/workspace/src/browser/workspace-frontend-contribution.ts:155]: @marechal-p @vince-fugnitto I rebased my branch and documented the breaking change.

**Review by vince-fugnitto — COMMENTED** [review]
The changes look good :+1: I did encounter a minor bug that can likely be handled:

1. open a file, and perform some dirty changes (ex: 'readme.md')
2. execute the command _Save As..._
3. save the file with the original name ('readme.md')
4. a confirmation box will appear asking if you want to overwrite the original file
5. the file is saved and immediately closed


https://user-images.githubusercontent.com/40359487/114876000-defd5b80-9dcb-11eb-856e-2a3c7b8d0b9d.mp4

**Comment by Darkgaja** [comment]
@vince-fugnitto When encountering the same `URI` as the source widget, my changes will now only execute the normal `SAVE` command.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto When encountering the same `URI` as the source widget, my changes will now only execute the normal `SAVE` command.

@Darkgaja I'll verify the new behavior, vscode behaves the following way:
1. document is dirty.
2. `save as` is performed with the same URI.
3. the confirmation dialog appears.
4. the save occurs, but the file is not closed.

**Comment by Darkgaja** [comment]
Right, I also took vscodes behavior as a sort of template. It should behave as you've laid out.

**Review by vince-fugnitto — APPROVED** [review]
I confirmed that the changes work well :+1:

**Review by DukeNgn — APPROVED** [review]
The PR looks good to me 👍  
I confirmed it aligns our `save as` behaviour with vscode.
