### PR TITLE
12568 Localized debug session status

### LINKED ISSUE #12568: State of debuging session is not localized
### Steps to Reproduce:

1. Go to Debug Tab
2. Start debuging
3. You will see the label "RUNNING"

https://github.com/eclipse-theia/theia/blob/c1a2b7b021cb67db4cc05a57cd3561bcba023ab9/packages/debug/src/browser/debug-session.tsx#L870

### Additional Information

- Operating System: Any
- Theia Version: Latest

### PR DESCRIPTION
**Pull request by Zebsterpasha**
#### What it does

Fixes #12568

I added localized strings in status of bebug session.

#### How to test

Just check the key of localized strings)

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/debug/src/browser/debug-session.tsx [hunk 1]
```diff
@@ -867,7 +868,11 @@ export class DebugSession implements CompositeTreeElement {
         }
         return <div className='theia-debug-session' title='Session'>
             <span className='label'>{this.label + label}</span>
-            <span className='status'>{this.state === DebugState.Stopped ? 'Paused' : 'Running'}</span>
+            <span className='status'>
+                    {this.state === DebugState.Stopped
+                        ? nls.localizeByDefault('Paused')
+                        : nls.localizeByDefault('Running')}
+                </span>
```
Comment (vince-fugnitto) [inline packages/debug/src/browser/debug-session.tsx:875]: The formatting here is a bit odd, we should clean up or even extract the `status` to a variable before we `return`.

Comment (Zebsterpasha) [reply packages/debug/src/browser/debug-session.tsx]: I had just added a localization, i hadn't changed formatting) But ok, I've just made a commit with fixes)
