### PR TITLE
Fix using copy/paste from a menu in electron. 

### LINKED ISSUE #12487: **breaking** `Edit` > `Copy` + `Edit` > `Paste` has no effect in the electron application after the electron version update
### Bug Description:

Originally from https://github.com/arduino/arduino-ide/pull/2027#pullrequestreview-1414148945.

It's impossible to copy-paste using the `Edit` menu with Theia Blueprint (Version 1.37.0 (Beta)).

### Steps to Reproduce:

1. You have an editor opened with some content
2. Select the content in the editor
3. Click `Edit` > `Copy`
4. Click `Edit` > `Paste`
5. Nothing happens besides the warning notification

⚠ Please use the browser's paste command or shortcut.

https://user-images.githubusercontent.com/1405703/236428486-7edb790b-fdcf-4755-b6d1-1e23f0d03106.mp4

It works when copy-pasting with the keyboard:

https://user-images.githubusercontent.com/1405703/236428543-afa7df24-0ac1-4fd3-887d-466804e53cbe.mp4

### Additional Information

It works on macOS due to this:

https://github.com/eclipse-theia/theia/blob/b6de8847ab17829e18c46745d58fb6ea1cd2902b/packages/core/src/electron-browser/menu/electron-main-menu-factory.ts#L190-L191

- Operating System: Windows/Linux
- Theia Version: 1.37.0

### PR DESCRIPTION
**Pull request by tsmaeder**
#### What it does
The fix is to replace a old test for whether we run on electron with on that works on current electron.

Fixes #12487

Contributed on behalf of STMicroelectronics

#### How to test
Start Theia Electron and make sure that copy/pasting from a menu actually works (for example in the terminal or in the editor)

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/core/src/browser/common-frontend-contribution.ts [hunk 1]
```diff
@@ -351,12 +351,12 @@ export namespace CommonCommands {
...
 
-export const supportCut = browser.isNative || document.queryCommandSupported('cut');
-export const supportCopy = browser.isNative || document.queryCommandSupported('copy');
+export const supportCut = environment.electron.is() || document.queryCommandSupported('cut');
+export const supportCopy = environment.electron.is() || document.queryCommandSupported('copy');
 // Chrome incorrectly returns true for document.queryCommandSupported('paste')
 // when the paste feature is available but the calling script has insufficient
 // privileges to actually perform the action
-export const supportPaste = browser.isNative || (!browser.isChrome && document.queryCommandSupported('paste'));
+export const supportPaste = environment.electron.is() || (!browser.isChrome && document.queryCommandSupported('paste'));
```
Comment (martin-fleck-at) [inline packages/core/src/browser/common-frontend-contribution.ts:359]: I'm not sure that we need the special Chrome handling anymore, see https://github.com/w3c/editing/issues/167, https://bugs.chromium.org/p/chromium/issues/detail?id=757140#c4, and https://chromium.googlesource.com/chromium/src.git/+/29e7204c4d91b754fe8df8e264695a695a5ab974.

File: packages/core/src/browser/common-frontend-contribution.ts [hunk 2]
```diff
@@ -351,12 +351,12 @@ export namespace CommonCommands {
     });
 }
 
-export const supportCut = browser.isNative || document.queryCommandSupported('cut');
-export const supportCopy = browser.isNative || document.queryCommandSupported('copy');
+export const supportCut = environment.electron.is() || document.queryCommandSupported('cut');
```
Comment (martin-fleck-at) [inline packages/core/src/browser/common-frontend-contribution.ts:354]: Just to note it down somewhere cause I quickly looked into it: `queryCommandSupported` is officially [deprecated but still supported in all major browsers](https://developer.mozilla.org/en-US/docs/Web/API/Document/queryCommandSupported#browser_compatibility). From what I gather, we could use the [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API) as an alternative.

**Review by martin-fleck-at — APPROVED** [review]
Changes look good to me and solve the original problem, thank you Thomas! From what I understand the `isNative` flag was really just introduced for the copy/paste scenario to distinguish between the Electron and the Browser case (see [here](https://github.com/eclipse-theia/theia/commit/000649e8702ed736e5ca429a4e2f2f410f490ce1#diff-751ed2e98ff7186ccbe41993a7cc0e173fa9826c3ff7f093d20a5db5455a2decR20)) but who can say for sure ;-) Anyway, great work and I just left two comments regarding the browser API that we can probably skip for now.

**Comment by tsmaeder** [comment]
Using the browser copy/paste commands is not really what we want: we want to react differently depending on the source/target of the paste: for example, "paste" will always paste into the widget with keyboard focus even though the active widget might be the Navigator, for example. There is a related issue talking about the Terminal, for example: https://github.com/eclipse-theia/theia/issues/10724
