### PR TITLE
Fix 13588 output wordwrap

### LINKED ISSUE #13588: The output channel does not wrap automatically
### Bug Description:
I set 'editor.wordWrap=on', but when I add characters through 'appendLine', characters in the output channel don't wrap automatically.

image

### Steps to Reproduce:

```js
commands.registerCommand(SampleCommand, {
      execute: () => {
          const channel = this.outputChannelManager.getChannel('sample:output');
          channel.appendLine('This is a sample output!');
          // eslint-disable-next-line max-len
          channel.appendLine('This is a sample output222! This is a sample output222!This is a sample output222! This is a sample output222! This is a sample output222! This is a sample output222! This is a sample output222!This is a sample output222!This is a sample output222!');
          channel.show();
      }
  });
```

### Additional Information

- Operating System: Windows 11
- Theia Version: master

### PR DESCRIPTION
**Pull request by ankitsharma101**
#### What it does
Fixes #13588

This PR resolves an issue where the Output panel ignored the user's global `editor.wordWrap` setting, forcing users to scroll horizontally for long log lines. 

Previously, `OutputEditorFactory` hardcoded `wordWrap: 'off'` during the Monaco Editor initialization. This fix:
* Injects the `PreferenceService` (via `@theia/core/lib/common`).
* Dynamically fetches the `editor.wordWrap` preference, defaulting to `'off'` if unset.
* Passes the dynamic preference into the Monaco `IOptions` object, allowing the output channel to wrap text correctly based on user preferences.

#### How to test
1. Open Theia and navigate to **File > Settings > Open Preferences**.
2. Ensure **Editor: Word Wrap** is set to `on`.
3. Open the **Output** panel at the bottom of the screen.
4. Generate a long string of text in the output channel (either by setting the Log Level to `Trace` via the Command Palette to flood the logs, or by using a custom sample command).
5. Verify that the long text strings wrap automatically to the next line instead of spawning a horizontal scrollbar.

#### Follow-ups
None at this time.

#### Breaking changes

- [ ] This PR introduces breaking changes and requires careful review. If yes, the breaking changes section in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) has been updated.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)
- [x] User-facing text is internationalized using the `nls` service (for details, please see the [Internationalization/Localization section](https://github.com/theia-ide/theia/blob/master/doc/coding-guidelines.md#internationalizationlocalization) in the Coding Guidelines)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/output/src/browser/output-editor-factory.ts [hunk 1]
```diff
@@ -43,12 +47,14 @@ export class OutputEditorFactory implements MonacoEditorFactory {
...
+        // Grab the user's preference, defaulting to 'off' if they haven't set one
+        const userWordWrap = this.preferenceService.get<string>('editor.wordWrap', 'off');
         return {
             ...defaultOptions,
             overviewRulerLanes: 3,
             lineNumbersMinChars: 3,
             fixedOverflowWidgets: true,
-            wordWrap: 'off',
+            wordWrap: userWordWrap as 'on' | 'off' | 'wordWrapColumn' | 'bounded',
             lineNumbers: 'off',
```
Comment (msujew) [inline packages/output/src/browser/output-editor-factory.ts]: Suggestion: As far as I can tell, word wrap in the VS Code output widget is always on, regardless of any user preference.  Setting `editor.wordWrap` to `off`, still keeps word wrap in the VS Code output widget. I think this makes the most sense for us as well.

File: packages/keymaps/src/browser/keybindings-widget.tsx
Comment (msujew) [inline packages/keymaps/src/browser/keybindings-widget.tsx:1]: I believe the changes in this file belong to a different PR/issue, right? Please drop them from this PR.

**Comment by ankitsharma101** [comment]
Thanks for the review and the context regarding VS Code parity! That makes total sense and definitely simplifies things. I've updated the PR to simply hardcode wordWrap: 'on', and I've also rebased to drop those accidental keymap commits that leaked into the branch. It should be clean now!
