### PR TITLE
Fix test extensions (e.g., Python unittest) and improve test output UX

### LINKED ISSUE #16389: Python unit tests are not working
### Bug Description:

Running the python unitest in the interface doesn't work well. They work "sometimes" and it is really hard for the extension to find them.

### Steps to Reproduce:

1. Install the python extension and go to the testing tab
2. No tests are found and pressing the refresh button gives the error `[Error] Unable to find test adapter for workspace.`
3. For there, one can obtain the tests by doing from the command palette: Python: Configure Test -> unittest -> tests -> *test*.py
4. The test appear in the testing panel and can be ran.
5. _However_, if one were to do step 3 again, the tests won't run ever again.

### Additional Information

- Operating System: Ubuntu 25
- Theia Version: 1.64.100

### PR DESCRIPTION
**Pull request by ndoschek**
#### What it does

Fixes multiple bugs that prevented test extensions (e.g. Python unittest, Playwright Test) from working reliably in Theia. Resolves #16389 

Bug fixes:

- `getWorkspaceFolder` now returns the original folder object instead of creating a new one, preserving reference equality for extensions that use `workspace.uri` as a `Map` key
- Root-level test discovery is now triggered by calling `resolveHandler(undefined)` when a controller registers, matching VS Code behavior
- `TestRun.end()` now flushes the change batcher so pending state updates are not silently dropped
- `TestItemCollection.replace()` no longer deletes newly-added items that share IDs with old ones
- `AbstractIndexedCollection.doAdd()` now actually replaces existing entries instead of silently discarding the new value

UX improvements:

- Auto-open Test Output panel when a test run starts
- Add "Show Test Output" toolbar button to the Test Runs view
- Open Test Output panel on double-click of test run/item nodes
- Show the selected test item's own output if present, falling back to the failure messages for failed/errored tests and to a placeholder for everything else

#### How to test

Python unittest:

1. Start an example application and make sure the builtins are downloaded; python is a builtin
2. Create a workspace folder and add a test file, e.g. as example this `test/mytest.py`:
   ```python
   import unittest

   def add(a, b):
       return a + b

   class TestAddFunction(unittest.TestCase):
       def test_add_positive_numbers(self):
           self.assertEqual(add(2, 3), 5)

       def test_add_negative_numbers(self):
           self.assertEqual(add(-1, -1), -2)

       def test_add_mixed_sign_numbers(self):
           self.assertEqual(add(-1, 1), 0)
       def test_expect_failure(self):
           self.assertEqual(add(-1, 1), 5, "This test fails intentionally")

   if __name__ == '__main__':
       unittest.main()
   ```
3. Open the Command Palette and run "Python: Configure Tests" → select "unittest" → select `./test` as root → `*test.py` as pattern
4. Open the Testing panel - tests should appear automatically (reload can be necessary on the first setup though)
5. Run tests - verify they pass and results appear in the Test Runs section below the Test Explorer
6. Modify the test file (e.g. change an expected value) and run again - verify results update correctly
7. Run multiple times consecutively - verify tests remain stable

Playwright Test:

1. Install the "Playwright Test for VS Code" extension from Open VSX (`ms-playwright.playwright`)
2. Open a the theia repo (has `playwright.config.ts` and `.spec.ts` test files)
3. Tests should appear in the Testing panel and can be run

Test output visibility:

1. After running any test, verify the Test Output panel opens automatically in the bottom area
2. In the Test Runs area, click the icon to open/focus the Test Output panel
3. Select the test run and verify the output summary is shown in the test output view
4. Select individual test items in Test Runs and verify output is shown in the test output view
   - for the expected failing test case you can see the error stack
   - for the successful ones you see the placeholder string `The test case did not report any output.`

#### Follow-ups

- The `ms-python.vscode-python-envs` extension's PET binary is not included when the Python extension is downloaded as a universal (non-platform-specific) VSIX from Open VSX. This causes the Python environment picker to not work properly. A follow-up could ensure Theia downloads platform-specific extension packages when available.
- The `ms-python.vscode-python-envs` extension may register a duplicate "Select Python Interpreter" status bar item alongside the one from `ms-python.python`, likely because both extensions register their own item and the coordination between them relies on VS Code-specific internals.
- Show extension-contributed welcome views (e.g. "Configure Python Tests" button) in the Testing panel when no tests are configured
- Catch and surface errors from `resolveHandler` (e.g. "Test provider types are not aligned") as error items in the test tree, matching VS Code's UX
- Defer the initial root-level resolveHandler(undefined) call until the user reveals the Test Explorer, so we don't populate test trees that never get looked at. The follow-up needs to also cover command-palette workflows (e.g. "Run All Tests", "Refresh Tests") so they still trigger discovery when the view was never opened, see review thread on https://github.com/eclipse-theia/theia/pull/17341#discussion_r3080983872.  

#### Breaking changes

- [ ] This PR introduces breaking changes and requires careful review. If yes, the breaking changes section in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) has been updated.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)
- [x] User-facing text is internationalized using the `nls` service (for details, please see the [Internationalization/Localization section](https://github.com/theia-ide/theia/blob/master/doc/coding-guidelines.md#internationalizationlocalization) in the Coding Guidelines)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/plugin-ext/src/plugin/tests.ts [hunk 1]
```diff
@@ -428,9 +429,14 @@ export class TestingExtImpl implements TestingExt {
...
         if (controller.resolveHandler) {
-            const item = controller.items.find(path);
-            if (item?.canResolveChildren) { // the item and resolve handler might have been been changed, but not sent to the front end
-                controller.resolveHandler?.(item);
+            if (path.length === 0) {
+                // Root-level resolve: discover top-level test items
+                controller.resolveHandler(undefined);
+            } else {
+                const item = controller.items.find(path);
+                if (item?.canResolveChildren) { // the item and resolve handler might have been been changed, but not sent to the front end
```
Comment (colin-grant-work) [inline packages/plugin-ext/src/plugin/tests.ts]: The comment is old, but it's also a bit confusing. The logic looks normal: if `canResolveChildren`, we call `resolveHandler`. I'm not sure I understand what exceptional case the comment is flagging. It sounds like maybe the two can get out of synch, so something like this might be more informative.

```
// The `main` side should only request resolution for items with `canResolveChildren`, but with event batching, the flag can be out of synch with the state on the `plugin` side. The state on the `plugin` side is authoritative.
```

File: packages/plugin-ext/src/plugin/workspace.ts [hunk 2]
```diff
@@ -347,7 +346,7 @@ export class WorkspaceExtImpl implements WorkspaceExt {
             const folderPath = folder.uri.toString();
 
             if (resourcePath === folderPath) {
-                return toWorkspaceFolder(folder);
+                return folder;
```
Comment (colin-grant-work) [inline packages/plugin-ext/src/plugin/workspace.ts:364]: It looks like we might still have problems through calls to `$onWorkspaceFoldersChanged`. Should we try to preserve identity there for any folders that are not changed?

File: packages/test/src/browser/test-execution-progress-service.ts [hunk 3]
```diff
@@ -45,6 +49,7 @@ export class DefaultTestExecutionProgressService implements TestExecutionProgres
                 this.openTestResultView();
             }
         }
+        this.testOutputView.openView({ activate: !preserveFocus });
     }
```
Comment (colin-grant-work) [inline packages/test/src/browser/test-execution-progress-service.ts:53]: Opening the test output view in this case used to be gated by the `testing.openTesting` preference. Now it's unconditional. Is that intended?

File: packages/test/src/common/collections.ts [hunk 4]
```diff
@@ -128,13 +128,9 @@ abstract class AbstractIndexedCollection<K, T> {
...
-        if (previous !== undefined) {
-            return previous;
-        } else {
-            this.keys.set(key, value);
-            this._values = undefined;
-            return undefined;
-        }
+        this.keys.set(key, value);
+        this._values = undefined;
+        return previous !== undefined ? previous : undefined;
```
Comment (colin-grant-work) [inline packages/test/src/common/collections.ts]: I think this is the same as


```suggestion
        return previous;
```

File: packages/test/src/browser/view/test-run-widget.tsx [hunk 5]
```diff
@@ -211,13 +213,22 @@ export class TestRunTreeWidget extends TreeWidget {
...
                     get output(): readonly TestOutputItem[] {
-                        return node.parent.run.getOutput(node.item);
+                        const itemOutput = node.parent.run.getOutput(node.item);
+                        return itemOutput.length > 0 ? itemOutput : node.parent.run.getOutput();
                     },
-                    onDidAddTestOutput: Event.map(node.parent.run.onDidChangeTestOutput, evt => evt.filter(item => item[0] === node.item).map(item => item[1]))
+                    onDidAddTestOutput: Event.map(node.parent.run.onDidChangeTestOutput, evt => {
+                        const itemEvents = evt.filter(item => item[0] === node.item).map(item => item[1]);
+                        return itemEvents.length > 0 ? itemEvents : evt.map(item => item[1]);
+                    })
```
Comment (colin-grant-work) [inline packages/test/src/browser/view/test-run-widget.tsx]: These changes look a little odd. It looks like in VSCode, if a given item doesn't have output, it shows 'The test case did not report any output.' rather than showing the full run. We also have a little bit of inconsistency here: we're listening to events from the run, and then filtering to events from the item of interest if there are any, or all events otherwise. But over the course of a run, some events may have to do with the item of interest and some may not. Is it correct to forward events differently in the two cases?

File: packages/plugin-ext/src/main/browser/test-main.ts [hunk 6]
```diff
@@ -510,6 +511,10 @@ class TestControllerImpl implements TestController {
         }
         if ('canResolve' in change) {
             this.canResolveChildren = change.canResolve!;
+            if (change.canResolve && !this.hasTriggeredInitialResolve) {
+                this.hasTriggeredInitialResolve = true;
+                this.resolveChildren();
+            }
```
Comment (colin-grant-work) [inline packages/plugin-ext/src/main/browser/test-main.ts:517]: Will this happen even if the UI isn't open? I.e. are we resolving tests even if the user hasn't shown interest in them?

File: packages/plugin-ext/src/plugin/workspace.ts (hunk 2 above)
Comment (ndoschek) [reply packages/plugin-ext/src/plugin/workspace.ts:364]: Thanks, good catch! I updated `$onWorkspaceFoldersChanged` to reuse existing folder objects when the URI and index haven't changed, preserving reference equality for unchanged folders.

File: packages/test/src/browser/test-execution-progress-service.ts (hunk 3 above)
Comment (ndoschek) [reply packages/test/src/browser/test-execution-progress-service.ts:53]: Ah thanks for catching that, it was not intended!
I fixed it by opening the output view only alongside the test result view when `openOnTestStart` is set.

File: packages/test/src/common/collections.ts (hunk 4 above)
Comment (ndoschek) [reply packages/test/src/common/collections.ts]: Oh yes, definitely :sweat_smile:

File: packages/test/src/browser/view/test-run-widget.tsx (hunk 5 above)
Comment (ndoschek) [reply packages/test/src/browser/view/test-run-widget.tsx]: You're right, I removed the inconsistent fallback-to-full-run-output logic. Now the behavior is:
- Event stream: consistently filtered to the selected item only
- Output snapshot: shows per-item output if available; for failed/errored tests without per-item output, shows the failure messages (e.g. assertion errors from Python unittest); otherwise shows "The test case did not report any output." This matches VS Code's behavior more closely now.

**Comment by ndoschek** [comment]
Thank you for the feedback, Colin!
I addressed your review comments and additionally, I removed the double-click handler on test run/item nodes as I found it not very intuitive (conflicted with expand/collapse on parent nodes, and the toolbar icon is sufficient I think). I addition to your comment I also made sure that individual test cases can now report output to the test output view, and updated the test example with a failing test that can be used to verify that.

File: packages/plugin-ext/src/main/browser/test-main.ts (hunk 6 above)
Comment (ndoschek) [reply packages/plugin-ext/src/main/browser/test-main.ts:517]: Yes, currently this triggers eagerly. In VS Code, when a `TestController` sets a `resolveHandler`, it calls it with `undefined` immediately to discover root-level items, regardless of whether the Test Explorer is visible. This is how extensions like Python unittest populate the test tree so items are ready when the user opens the Testing panel. That said, I can see the argument for deferring this until the user actually opens the panel. Do think we should make it lazy instead?

Comment (colin-grant-work) [reply packages/plugin-ext/src/main/browser/test-main.ts:517]: I'd say a low-ish priority follow-up, but it would make sense to me not to populate that view if it never gets looked at. Not sure, though, what commands might try to interact with the test system before / as soon as the view is visible, though, so waiting could have some unforeseen impact.

File: packages/test/src/browser/view/test-run-widget.tsx [hunk 7]
```diff
@@ -209,13 +209,26 @@ export class TestRunTreeWidget extends TreeWidget {
...
+                        return [];
                     },
-                    onDidAddTestOutput: Event.map(node.parent.run.onDidChangeTestOutput, evt => evt.filter(item => item[0] === node.item).map(item => item[1]))
+                    onDidAddTestOutput: Event.map(node.parent.run.onDidChangeTestOutput, evt =>
+                        evt.filter(item => item[0] === node.item).map(item => item[1])
+                    ),
+                    noOutputMessage: nls.localizeByDefault('The test case did not report any output.')
                 };
-                this.uiModel.selectedTestState = node.parent.run.getTestState(node.item);
+                this.uiModel.selectedTestState = testState;
```
Comment (colin-grant-work) [inline packages/test/src/browser/view/test-run-widget.tsx]: Would it be possible to have timing issues here if:

- A node is selected while running (or idle)
- The same node remains selected throughout a run
- We enter the `output()` getter and check `testState`, but `testState` reflects the state on initial selection, rather than states computed in the meantime?

File: packages/plugin-ext/src/plugin/tests.ts [hunk 8]
```diff
@@ -299,6 +299,7 @@ export class TestRun implements theia.TestRun {
     }
 
     end(): void {
+        this.changeBatcher.flush();
         this.ended = true;
         this.proxy.$notifyTestRunEnded(this.controller.id, this.id);
     }
```
Comment (colin-grant-work) [inline packages/plugin-ext/src/plugin/tests.ts:308]: Flushing is definitely correct here; should we continue to run the whole routine if `ended` is already true?

File: packages/plugin-ext/src/main/browser/test-main.ts (hunk 6 above)
Comment (ndoschek) [reply packages/plugin-ext/src/main/browser/test-main.ts:517]: Agreed, let's leave this as a follow-up then. One concern maybe: if a user triggers "Run All Tests" from the command palette for example without ever opening the Test Explorer, having the root-level items already populated is convenient, and we'd need to re-introduce a reveal trigger for that path to avoid a regression. I've added it to the follow-ups.

File: packages/test/src/browser/view/test-run-widget.tsx (hunk 7 above)
Comment (ndoschek) [reply packages/test/src/browser/view/test-run-widget.tsx]: Ah yes, that was indeed a real issue. I addressed it in two places:
- The `output()` getter now reads `run.getTestState(item)` on each access, rather than using a value captured at selection time.
- While the same `TestItemNode` stays selected, we subscribe to `run.onDidChangeTestState` and update `uiModel.selectedTestState` whenever the selected item's state changes, so the derived context key stays in sync too. The subscription is held in a `DisposableCollection` that is reset on every selection change and disposed with the widget.

File: packages/plugin-ext/src/plugin/tests.ts (hunk 8 above)
Comment (ndoschek) [reply packages/plugin-ext/src/plugin/tests.ts:308]: Good point, an early return if `this.ended` is already set is the right thing to do. `end()` now short-circuits in that case, so we no longer re-flush or emit a duplicate `$notifyTestRunEnded`.

**Review by colin-grant-work — APPROVED** [review]
