### PR TITLE
Fix notebook kernel selection

### LINKED ISSUE #13167: Connecting to an existing Jupyter Kernel not possible
### Bug Description:

After installing the Python and Jupyter notebook extensions, users cannot use the `Existing Jupyter Kernel` quick pick entry for selecting the kernel that's used to run the notebook. Every time it is clicked, an error in the plugin host occurs that is thrown on [this line](https://github.com/eclipse-theia/theia/blob/469bd744a02e5dcdbcbc338af178d410dd909616/packages/plugin-ext/src/plugin/command-registry.ts#L209).

### Steps to Reproduce:

1. Install all the necessary Jupyter plugins
2. Try to select the `Existing Jupyter Kernel` to run a cell.

### Additional Information

- Operating System: Ubuntu
- Theia Version: 1.44.0

### PR DESCRIPTION
**Pull request by msujew**
#### What it does

Closes #13167

Fixes quite a few issues which prevented the notebook kernel selection from working correctly. The most major issue was related to the fact that the safe command wasn't transmitted correctly (it was missing its arguments). See changes in the `command.ts` and `command-registry.ts` file.

There where also a few issues related to the way we communicated open/focused editors to the plugin host. This was fixed in `notebook-editor-widget-service.ts` and `notebook-documents-and-editors-main.ts`.

#### How to test

1. Install the Jupyter notebook related extensions.
2. Select a different notebook kernel. All options should work as expected.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/core/src/common/command.ts [hunk 1]
```diff
@@ -46,6 +46,13 @@ export interface Command {
      */
     category?: string;
     originalCategory?: string;
+    /**
+     * Default arguments for the command.
+     *
+     * Arguments specified in the command invocation are appended to this array.
+     */
+    // eslint-disable-next-line @typescript-eslint/no-explicit-any
+    arguments?: any[];
```
Comment (msujew) [inline packages/core/src/common/command.ts:55]: @tsmaeder What are your thoughts on this change? I'm not sure where these changes are supposed to go otherwise.

**Review by jonah-iden — APPROVED** [review]
Code looks good to me and everything seems to work fine. 
Tested with different notebook kernels (python installations, venv and conda) and [jupyter_server](https://github.com/jupyter-server/jupyter_server)

the extra options in the cell toolbars contributed by jupyter are not yet working. But i don't think thats in the scope of this PR

File: packages/core/src/common/command.ts (hunk 1 above)
Comment (jonah-iden) [reply packages/core/src/common/command.ts:55]: to me this seems to be just an additional feature for commands in general so why should this be a problem?

Comment (msujew) [reply packages/core/src/common/command.ts]: FYI, I improved on this. Changes to the command/command registry are no longer necessary.

Comment (jonah-iden) [reply packages/core/src/common/command.ts]: ah ok nice. Looks good
