### PR TITLE
Don't accept/cancel breakpoint editor while its suggest widget is visible

### LINKED ISSUE #16284: Don't accept/cancel breakpoint editor while its suggest widget is visible
### Bug Description:

While the breakpoint editor's suggest widget is visible, pressing 'Enter' or 'Escape' will currently close the breakpoint widget instead of closing the suggest widget.

### Steps to Reproduce:

Using a simple Node.JS program

```js
let abc = 1;
console.log(abc);
```

1. Set a source breakpoint on line 2, right-click on the breakpoint and choose `Edit Breakpoint...`

2. Type `a` in the breakpoint editor. The suggest widget will open.

    Image

3. Press 'Enter' or 'Escape' while the suggest widget is visible. Observe that the breakpoint widget will close instead of closing the suggest widget.

### Additional Information

I'm going to submit a fix.

- Operating System: all
- Theia Version: current master

### PR DESCRIPTION
**Pull request by pisv**
#### What it does

Fixes #16284.

#### How to test

Verify that pressing 'Enter' or 'Escape' while the breakpoint editor's suggest widget is visible will now close the suggest widget (with accepting or ignoring the selected proposal respectively) instead of closing the breakpoint widget.

See #16284 for detailed steps.

#### Breaking changes

- [ ] This PR introduces breaking changes and requires careful review. If yes, the breaking changes section in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) has been updated.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/debug/src/browser/debug-frontend-application-contribution.ts [hunk 1]
```diff
@@ -1206,12 +1206,12 @@ export class DebugFrontendApplicationContribution extends AbstractViewContributi
...
             command: DebugBreakpointWidgetCommands.ACCEPT.id,
             keybinding: 'enter',
-            when: 'breakpointWidgetFocus'
+            when: 'breakpointWidgetFocus && !suggestWidgetVisible'
         });
         keybindings.registerKeybinding({
             command: DebugBreakpointWidgetCommands.CLOSE.id,
             keybinding: 'esc',
-            when: 'isBreakpointWidgetVisible || breakpointWidgetFocus'
+            when: 'isBreakpointWidgetVisible || breakpointWidgetFocus && !suggestWidgetVisible'
```
Comment (ndoschek) [inline packages/debug/src/browser/debug-frontend-application-contribution.ts]: nit: consider adding parentheses for clarity:
```suggestion
            when: 'isBreakpointWidgetVisible || (breakpointWidgetFocus && !suggestWidgetVisible')
```

**Review by ndoschek — COMMENTED** [review]
Thanks @pisv, great catch and thanks for the fix - it works great! :tada: 
I just added a small nit inline, just for clarity.

**Comment by pisv** [comment]
@ndoschek I have committed your suggestion. Thanks a lot for your review! 👍

File: packages/debug/src/browser/debug-frontend-application-contribution.ts [hunk 2]
```diff
@@ -1206,12 +1206,12 @@ export class DebugFrontendApplicationContribution extends AbstractViewContributi
...
             command: DebugBreakpointWidgetCommands.ACCEPT.id,
             keybinding: 'enter',
-            when: 'breakpointWidgetFocus'
+            when: 'breakpointWidgetFocus && !suggestWidgetVisible'
         });
         keybindings.registerKeybinding({
             command: DebugBreakpointWidgetCommands.CLOSE.id,
             keybinding: 'esc',
-            when: 'isBreakpointWidgetVisible || breakpointWidgetFocus'
+            when: 'isBreakpointWidgetVisible || (breakpointWidgetFocus && !suggestWidgetVisible')
```
Comment (ndoschek) [inline packages/debug/src/browser/debug-frontend-application-contribution.ts]: Oops sorry, there was a typo in my earlier suggestion :zipper_mouth_face: 
```suggestion
            when: 'isBreakpointWidgetVisible || (breakpointWidgetFocus && !suggestWidgetVisible)'
```

**Review by ndoschek — APPROVED** [review]
