### PR TITLE
[plugin] handle plugin host activation exceptions

### LINKED ISSUE #8018: [plugin] module resolution needs to be fully qualified
### Bug Description:

TypeScript modules can be exported from index files to make it easier for importing.

For example, [this file](https://github.com/eclipse-theia/theia/blob/master/packages/core/src/node/index.ts#L19) exports `file-uri` so that it can be imported like this:

```typescript
import { FileUri } from '@theia/core/lib/node';
```

However, plugins in the plugin system don't seem to resolve modules exported in this manner and have to be fully qualified, e,g,:

```typescript
import { FileUri } from '@theia/core/lib/node/file-uri';
```

This would be fine if the build fails, however in this case the plugin correctly builds, but fails to load without any error. This situation is prone to lead to some difficult issues to debug.

I would expect either:

- User doesn't need to fully-qualify imports

or

- Imports not fully-qualified would error during compilation of the plugin

### Steps to Reproduce:

A repo with a theia plugin outlining the issue is here:

https://github.com/thegecko/theia-plugin

Build this and include it in the plugins when launching Theia. Use [these lines](https://github.com/thegecko/theia-plugin/blob/master/src/backend.ts#L2) to switch between the plugin working and not.

The plugin code to reproduce is short:

```typescript
import * as theia from '@theia/plugin';
import { FileUri } from '@theia/core/lib/node';     // doesn't work
// import { FileUri } from '@theia/core/lib/node/file-uri';     // works

export const start = async () => {
    const path = FileUri.fsPath(__dirname);
    theia.window.showInformationMessage(path);
};
```

### Additional Information

- Operating System: macOS
- Theia Version: 1.2.0

cc @benoitf Have you seen this issue when writing che plugins?

### PR DESCRIPTION
**Pull request by thegecko**
Signed-off-by: Rob Moran <rob.moran@arm.com>

#### What it does
Resolves #8018 

Added catch to plugin host to handle exceptions thrown while resolving dependencies in plugins.

- Activation promise rejected if it exists
- Exception logged and shown to user in notification.

#### How to test
Follow steps in #8018 

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/plugin-ext/src/plugin/plugin-manager.ts [hunk 1]
```diff
@@ -291,6 +291,14 @@ export class PluginManagerExtImpl implements PluginManagerExt, PluginManager {
                     // see https://github.com/TypeFox/vscode/blob/70b8db24a37fafc77247de7f7cb5bb0195120ed0/src/vs/workbench/api/common/extHostExtensionService.ts#L372-L376
                     pluginMain = pluginMain || {};
                     return await this.startPlugin(plugin, configStorage, pluginMain);
+                } catch (err) {
+                    if (this.pluginActivationPromises.has(plugin.model.id)) {
```
Comment (akosyakov) [inline packages/plugin-ext/src/plugin/plugin-manager.ts:295]: Could we somehow get rid of duplicate code? maybe `startPlugin` should return plugin export but the rest be handled here?

File: packages/plugin-ext/src/plugin/plugin-manager.ts [hunk 2]
```diff
@@ -291,6 +291,14 @@ export class PluginManagerExtImpl implements PluginManagerExt, PluginManager {
...
+                        this.pluginActivationPromises.get(plugin.model.id)!.reject(err);
+                    }
+                    const message = `Activating extension '${plugin.model.displayName || plugin.model.name}' failed: ${err.message}`;
+                    this.messageRegistryProxy.$showMessage(MainMessageType.Error, message, {}, []);
```
Comment (akosyakov) [inline packages/plugin-ext/src/plugin/plugin-manager.ts:299]: I was wondering maybe instead of using message service, we should a special service then you can custoimize it in your product to complete stop the execution if some core extensions are failed, by default it will delegate to the notification center.

File: packages/plugin-ext/src/plugin/plugin-manager.ts (hunk 1 above)
Comment (thegecko) [reply packages/plugin-ext/src/plugin/plugin-manager.ts:295]: There is a lot of duplicated code in this file. Recommend de-duplication is revisited in a separate PR.

File: packages/plugin-ext/src/plugin/plugin-manager.ts (hunk 2 above)
Comment (thegecko) [reply packages/plugin-ext/src/plugin/plugin-manager.ts:299]: Again, this feels like a separate PR to change architecture rather than this bug fix.

File: packages/plugin-ext/src/plugin/plugin-manager.ts (hunk 1 above)
Comment (akosyakov) [reply packages/plugin-ext/src/plugin/plugin-manager.ts:295]: ok

File: packages/plugin-ext/src/plugin/plugin-manager.ts (hunk 2 above)
Comment (akosyakov) [reply packages/plugin-ext/src/plugin/plugin-manager.ts:299]: ok

File: packages/plugin-ext/src/plugin/plugin-manager.ts (hunk 1 above)
Comment (thegecko) [reply packages/plugin-ext/src/plugin/plugin-manager.ts:289]: It wasn't hard to fix :) Updated

**Comment by akosyakov** [comment]
code looks good, but I have to check 2 cases:
- some vs code extensions stub main field in package.json if they don't have any code, we should not notify user about such
- some vs code extensions don't have main field in package.json if they don't have any code, we should not notify user about such as well
