### PR TITLE
Minor Improvements MCP View

### LINKED ISSUE #15363: [Theia AI] Minor Improvements MCP View
- The "copy all single line" action uses a wrong string (should be #prompt:servername_tools)
- String are not localized
- The description of the "copy all" toolbar items could be improved

### PR DESCRIPTION
**Pull request by JonasHelming**
fixed #15363

#### What it does

Very nice new view, very useful!!
I have some minor improvements, after using it.
see  #15363

#### How to test

see  #15363
Use the Copy all (single prompt fragment with all tools) option and verify it works

#### Follow-ups
https://github.com/eclipse-theia/theia/issues/15371
https://github.com/eclipse-theia/theia/issues/15372

#### Breaking changes

- [ ] This PR introduces breaking changes and requires careful review. If yes, the breaking changes section in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) has been updated.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/ai-ide/src/browser/ai-configuration/mcp-configuration-widget.tsx [hunk 1]
```diff
@@ -211,29 +212,30 @@ export class AIMCPConfigurationWidget extends ReactWidget {
...
                         )}
                         {this.renderButton(
                             <i className="codicon codicon-copy"></i>,
-                            'Copy all (single line prompttemplate)',
+                            nls.localize('theia/ai/mcpConfiguration/copyAllSingle', 'Copy all (single prompt fragment with all tools)'),
                             e => {
                                 e.stopPropagation();
-                                navigator.clipboard.writeText(`~{${this.mcpFrontendService.getPromptTemplateId(server.name)}}`);
-                                this.messageService.info('Copied all tools to clipboard (single line prompttemplate)');
+                                navigator.clipboard.writeText(`#${PROMPT_VARIABLE.name}:${this.mcpFrontendService.getPromptTemplateId(server.name)}`);
```
Comment (sgraband) [inline packages/ai-ide/src/browser/ai-configuration/mcp-configuration-widget.tsx:236]: This copied text can be added to the chat, right?
Is there a way to add all tools of a server to a prompttemplate? Or do you need to put all the tools there in a single line? If there is a way i would also add a button for that, because i would personally use it more that adding all tool calls to the chat.

**Review by sgraband — COMMENTED** [review]
Apart from my comment below, this LGTM :+1: Thanks a lot!

Regarding the follow-up: Yes i just tested and the copied line for the prompttemplate works in the chat as well. So we can remove the chat icons imho. 

Just a minor nitpick: The format ~{toolname} is not autocompleted in the chat. I think it should be autocompleted the same way as ~toolname is. Otherwise if i copy from the config view and delete the last part, because i want to change the toolcall i do not get autocompletion.

File: packages/ai-ide/src/browser/ai-configuration/mcp-configuration-widget.tsx [hunk 2]
```diff
@@ -211,29 +212,41 @@ export class AIMCPConfigurationWidget extends ReactWidget {
...
-                                    this.messageService.info('Copied all tools to clipboard (multiple lines prompttemplate)');
+                                    this.messageService.info(nls.localize('theia/ai/mcpConfiguration/copiedAllList', 'Copied all tools to clipboard (list of all tools)'));
                                 }
                             },
                             'mcp-copy-tool-button'
                         )}
                         {this.renderButton(
                             <i className="codicon codicon-copy"></i>,
-                            'Copy all (single line prompttemplate)',
+                            nls.localize('theia/ai/mcpConfiguration/copyAllSingle', 'Copy all (single prompt fragment with all tools)'),
```
Comment (sgraband) [inline packages/ai-ide/src/browser/ai-configuration/mcp-configuration-widget.tsx:233]:
```suggestion
                            nls.localize('theia/ai/mcpConfiguration/copyAllSingle', 'Copy all for chat (single prompt fragment with all tools)'),
```

File: packages/ai-ide/src/browser/ai-configuration/mcp-configuration-widget.tsx [hunk 3]
```diff
@@ -211,29 +212,41 @@ export class AIMCPConfigurationWidget extends ReactWidget {
...
-                                this.messageService.info('Copied all tools to clipboard (single line prompttemplate)');
+                                navigator.clipboard.writeText(`#${PROMPT_VARIABLE.name}:${this.mcpFrontendService.getPromptTemplateId(server.name)}`);
+                                this.messageService.info(nls.localize('theia/ai/mcpConfiguration/copiedAllSingle', 'Copied all tools to clipboard (single prompt fragment with \
+                                    all tools)'));
+                            },
+                            'mcp-copy-tool-button'
+                        )}
+                        {this.renderButton(
+                            <i className="codicon codicon-bracket"></i>,
+                            nls.localize('theia/ai/mcpConfiguration/copyForPromptTemplate', 'Copy all for prompt template((single prompt fragment with all tools))'),
```
Comment (sgraband) [inline packages/ai-ide/src/browser/ai-configuration/mcp-configuration-widget.tsx:244]:
```suggestion
                            nls.localize('theia/ai/mcpConfiguration/copyForPromptTemplate', 'Copy all for prompt template (single prompt fragment with all tools)'),
```

File: packages/ai-ide/src/browser/ai-configuration/mcp-configuration-widget.tsx [hunk 4]
```diff
@@ -211,29 +212,41 @@ export class AIMCPConfigurationWidget extends ReactWidget {
...
                                 e.stopPropagation();
-                                navigator.clipboard.writeText(`~{${this.mcpFrontendService.getPromptTemplateId(server.name)}}`);
-                                this.messageService.info('Copied all tools to clipboard (single line prompttemplate)');
+                                navigator.clipboard.writeText(`#${PROMPT_VARIABLE.name}:${this.mcpFrontendService.getPromptTemplateId(server.name)}`);
+                                this.messageService.info(nls.localize('theia/ai/mcpConfiguration/copiedAllSingle', 'Copied all tools to clipboard (single prompt fragment with \
+                                    all tools)'));
+                            },
+                            'mcp-copy-tool-button'
+                        )}
+                        {this.renderButton(
```
Comment (sgraband) [inline packages/ai-ide/src/browser/ai-configuration/mcp-configuration-widget.tsx:242]: Nitpick: Can we move this button before the other one (one to the left)? Then the `Copy` icons are aligned on the right side

**Comment by sgraband** [comment]
Added follow ups to the pr description

**Review by sgraband — APPROVED** [review]
Thanks LGTM :+1:
