### PR TITLE
Remove now unneeded EditorManager override

### LINKED ISSUE #15930: Editor previews inappropriately replacing non-preview editors
### Steps to Reproduce:

1. Open an editor to non-preview mode (e.g. double-click in the file explorer)
2. Trigger opening of same file as a preview (e.g. single-click in the file explorer)
3. Non-preview editor will be closed (triggering on close behavior, such as save confirmation) and new preview editor will be opened.

### Additional Information

- Operating System: MacOS Sequoia
- Theia Version: 7ec36e2bf51d1da37bea34040f4227cb1248aa52

### PR DESCRIPTION
**Pull request by colin-grant-work**
#### What it does

Fixes #15930

In [#15302](https://github.com/eclipse-theia/theia/pull/15302/files#diff-1a887d95ae8a5096ac2938047832f5430fb5f1118712600bb042c82d3759d29f) the part of `EditorManager.tryGetPendingWidget` that returned something in the positive case was removed, meaning that the method always returned nothing. This removes the override completely, since it no longer does any work.

#### How to test

1. Open an editor as a non-preview. (Double click in File Explorer)
2. Open the editor as a preview. (Single click in File Explorer)
3. The non-preview should remain, and no on-close behavior should be triggered.

#### Breaking changes

- [ ] This PR introduces breaking changes and requires careful review. If yes, the breaking changes section in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) has been updated.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by kachurun** [comment]
Thank you!  Hope it will be merged soon, this bug is just killing me 😵

File: packages/editor-preview/src/browser/editor-preview-manager.ts [hunk 1]
```diff
@@ -101,7 +101,8 @@ export class EditorPreviewManager extends EditorManager {
     }
 
     protected override tryGetPendingWidget(uri: URI, options?: EditorOpenerOptions): MaybePromise<EditorWidget> | undefined {
-        return super.tryGetPendingWidget(uri, { ...options, preview: true }) ?? super.tryGetPendingWidget(uri, { ...options, preview: false });
+        return super.tryGetPendingWidget(uri, { ...options, preview: true } as WidgetOpenerOptions) ??
```
Comment (tsmaeder) [inline packages/editor-preview/src/browser/editor-preview-manager.ts:104]: What's the change here?

**Comment by tsmaeder** [comment]
> In [#15302](https://github.com/eclipse-theia/theia/pull/15302/files#diff-1a887d95ae8a5096ac2938047832f5430fb5f1118712600bb042c82d3759d29f) the part of EditorManager.tryGetPendingWidget that returned something in the positive case was removed

@colin-grant-work hmh...I don't see `EditorManager.tryGetPendingWidget` being touched in the linked PR. Could you expound, please? It would be helpful if you could give a quick explainer of how the problem occurs and how this change fixes it.

**Comment by colin-grant-work** [comment]
@tsmaeder, the default hides the method name where the modifications have been made, but if you expand the diff, you can see these changes:

image

You can see there that no matter what, we return `editorPromise` after we've done some post-processing related to selection revelation, but after the changes, we only return `editorPromise` if it was `undefined`, which means that we now think we're never getting an existing editor and we always have to create a new one - the bug.

**Comment by tsmaeder** [comment]
> @tsmaeder, the default hides the method name where the modifications have been made, but if you expand the diff, you can see these changes:

Yay for github PR UI 🤣 


> You can see there that no matter what, we return `editorPromise` after we've done some post-processing related to selection revelation, but after the changes, we only return `editorPromise` if it was `undefined`, which means that we now think we're never getting an existing editor and we always have to create a new one - the bug.

<sigh> how is not having a valid return statement even valid syntax 🤦  wat!?

File: packages/editor-preview/src/browser/editor-preview-manager.ts (hunk 1 above)
Comment (colin-grant-work) [reply packages/editor-preview/src/browser/editor-preview-manager.ts:104]: It is the same as [this one](https://github.com/eclipse-theia/theia/pull/15302/files#r2014497224) where now that we're delegating up to a method that doesn't mention editor options, TypeScript is confused.

**Review by tsmaeder — APPROVED** [review]
