### PR TITLE
fix: ensure terminal API object identity and respect grouping mode for plugin-created terminals

### LINKED ISSUE #16570: The "Run Python File" button in the ms-python plugin becomes unresponsive after manually closing the terminal and clicking again.
### Bug Description:
The "Run Python File" button in the ms-python plugin becomes unresponsive after manually closing the terminal and clicking again.

### Steps to Reproduce:
1. install ms-python extension
2. run python file

Image

3. close opened terminal
Image

4. run python file again
unresponsive.
5. Actually, after several hours of debugging, I've identified the root cause:

The ms-python plugin uses strict instance equality check in its `terminalCloseHandler` [link](https://github.com/microsoft/vscode-python/blob/2d28f7102ccbaa9e92b6fe13753324219413be6c/src/client/common/terminal/service.ts#L180):
```typescript
private terminalCloseHandler(terminal: Terminal) {
    if (terminal === this.terminal) {
        this.terminalClosed.fire();
        this.terminal = undefined;
    }
}
```
However, the `this.terminal` instance created through Theia is actually wrapped in a `Proxy` object via `createTerminal` [link](https://github.com/eclipse-theia/theia/blob/bd842d456f9f90dafd2f67e7c74ab438053606c9/packages/plugin-ext/src/plugin/plugin-context.ts#L628):
```typescript
export function createAPIObject<T extends Object>(rawObject: T): T {
    return new Proxy(rawObject, {
        get(target, p, receiver) {
            const isOwnProperty = !!Object.getOwnPropertyDescriptor(target, p);
            const val = Reflect.get(target, p);
            if (!isOwnProperty && typeof val === 'function') {
                // bind functions that are inherited from the prototype to the object itself.
                // This should handle the case of events.
                return val.bind(target);
            }
            return val;
        },
    }) as T;
}

createTerminal(nameOrOptions: theia.TerminalOptions | theia.ExtensionTerminalOptions | theia.ExtensionTerminalOptions | (string | undefined),
    shellPath?: string,
    shellArgs?: string[] | string): theia.Terminal {
    return createAPIObject(terminalExt.createTerminal(plugin, nameOrOptions, shellPath, shellArgs));
},
```
Therefore, ms-python cannot properly determine if the instance has been closed, and during the second run, it keeps sending commands to a non-existent terminal.

I don't understand why `createAPIObject` needs to perform this secondary wrapping of the instance. I tried directly returning the `terminal` instance, and it worked normally.

### Additional Information

- Operating System: windows browser
- Theia Version: 1.66.0

### PR DESCRIPTION
**Pull request by ndoschek**
<!--
Thank you for your Pull Request. Please provide a description and review
the requirements below.

Contributors guide: https://github.com/theia-ide/theia/blob/master/CONTRIBUTING.md

Note: Security vulnerabilities should not be disclosed on GitHub, through a PR or any
other means. See SECURITY.md at the root of this repository, to learn how to report
vulnerabilities.
-->

#### What it does

<!-- Include relevant issues and describe how they are addressed. -->

Fixes #16570                                                                                                                                                
                                                                                                                                                              
  The ms-python extension uses strict instance equality (`===`) in its `terminalCloseHandler` to check whether a terminal has been closed. However, Theia wraps terminal objects in a `Proxy` via `createAPIObject`, so the object returned to extensions differs from the one fired in terminal events. This causes the equality check to fail, making the "Run Python File" button unresponsive after closing and reopening a terminal.                                      
                                                                                                                                                              
  - Terminal events (`onDidOpenTerminal`, `onDidCloseTerminal`, `onDidChangeTerminalState`) now fire with the same Proxy-wrapped API object that was returned to extensions
  - The `terminals` getter and `activeTerminal` also return the API objects
  - A `_terminalApiObjects` map in `TerminalServiceExtImpl` tracks the Proxy wrappers alongside the raw terminal instances
  - Plugin-created terminals are now routed through the terminal manager when `terminal.grouping.mode` is set to `tree`, instead of always appearing as separate tabs in the bottom panel 

#### How to test

<!-- Explain how a reviewer can reproduce a bug, test new functionality or verify performance improvements. -->

Terminal identity fix (ms-python):
  1. Open a Python file in the example application
  2. Click "Run Python File" in the editor toolbar
  3. Close the terminal that was opened
  4. Click "Run Python File" again                                                                                                                            
  5. Verify the terminal opens and runs again (previously it became unresponsive)

Terminal manager tree mode with plugin-created terminals:
  1. Set `terminal.grouping.mode` to `tree` in preferences
  2. Click "Run Python File" (or any extension that creates a terminal)
  3. Verify the terminal appears inside the terminal manager tree, not as a separate tab in the bottom panel                                                  
  4. Close and re-run to verify it continues working

Task terminals in tree mode:
  1. With `terminal.grouping.mode` set to `tree`, run a task (e.g. via Terminal > Run Task)
  2. Verify the task terminal appears on the Tasks page in the terminal manager (not as a regular page)                                                       
  3. Verify the task completes normally

Integrated terminal in tree mode:
  1. With `terminal.grouping.mode` set to `tree`, create a new terminal via the command palette or Ctrl+`
  2. Verify it appears in the terminal manager tree                                                                                                           
  3. Split the terminal and verify the split also appears correctly in the tree
  4. Verify typing and command execution works normally

Tabbed mode (regression check):
  1. Switch `terminal.grouping.mode` to `tabbed`                                                                                                              
  2. Create a new terminal, run a task, and run a Python file     
  3. Verify all terminals appear as separate tabs in the bottom panel as before
                                                                                                                                                              
  **Switching modes at runtime:**
  1. Start with `tabbed` mode and create some terminals                                                                                                       
  2. Switch to `tree` mode and verify existing terminals migrate to the manager
  3. Switch back to `tabbed` and verify terminals migrate back to tabs

Example python file to test:
```py
from datetime import datetime

def main():
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"The current time is: {now}")
    date = datetime.now().strftime("%Y-%m-%d")
    print(f"The current date is: {date}")
    weekday = datetime.now().strftime("%A")
    print(f"The current weekday is: {weekday}")

if __name__ == "__main__":
    main()
```

#### Follow-ups

<!-- Please list potential follow-up work, including known issues, possible future work, identified technical debt, and potentially introduced technical debt. If the PR introduces technical debt, specify the reason why this is acceptable. Please create tickets and link them here. Please use the label "technical debt" for new issues when it applies. -->

  - The `editor/title/run` toolbar button uses a hardcoded `debug-alt` icon instead of dynamically picking up the primary command's icon from the contributing
   extension                                                                                                                                                  
  - Localization keys from bundled sub-extensions (e.g. `%debugpy.command.debuginterminal.title%`) may appear unresolved in the toolbar dropdown

#### Breaking changes

- [ ] This PR introduces breaking changes and requires careful review. If yes, the breaking changes section in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) has been updated.

#### Attribution

<!-- If the changelog entry for this change should contain an attribution at the end (e.g. Contributed on behalf of x) add it in this section -->

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)
- [x] User-facing text is internationalized using the `nls` service (for details, please see the [Internationalization/Localization section](https://github.com/theia-ide/theia/blob/master/doc/coding-guidelines.md#internationalizationlocalization) in the Coding Guidelines)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/plugin-ext/src/plugin/terminal-ext.ts
Comment (eneufeld) [inline packages/plugin-ext/src/plugin/terminal-ext.ts:132]: could you check whether this path works correctly? parentTerminal is a proxy (from createAPIObject) but v is the raw object see the obtainTerminal method. This might have been there earlier but we should fix this.

Comment (eneufeld) [inline packages/plugin-ext/src/plugin/terminal-ext.ts:362]: do we need to store an instance in the _terminalApiObject map?

File: packages/plugin-ext/src/plugin/terminal-ext.ts [hunk 1]
```diff
@@ -66,8 +73,8 @@ export class TerminalServiceExtImpl implements TerminalServiceExt {
         this.proxy = rpc.getProxy(PLUGIN_RPC_CONTEXT.TERMINAL_MAIN);
     }
 
-    get terminals(): TerminalExtImpl[] {
-        return [...this._terminals.values()];
+    get terminals(): theia.Terminal[] {
+        return [...this._terminals.keys()].map(id => this.getApiObject(id)!).filter(t => t !== undefined);
```
Comment (eneufeld) [inline packages/plugin-ext/src/plugin/terminal-ext.ts]: why the `!` after getApiObject? we filter anyway don't we?

File: packages/plugin-ext/src/plugin/terminal-ext.ts
Comment (eneufeld) [inline packages/plugin-ext/src/plugin/terminal-ext.ts:1]: should we add tests for this file? what and when is returning the correct instance is quite confusing

File: packages/terminal-manager/src/browser/terminal-manager-frontend-contribution.ts
Comment (eneufeld) [inline packages/terminal-manager/src/browser/terminal-manager-frontend-contribution.ts]: this is unused now

File: packages/terminal-manager/src/browser/terminal-manager-frontend-contribution.ts [hunk 2]
```diff
@@ -62,16 +62,30 @@ export class TerminalManagerFrontendContribution implements FrontendApplicationC
...
-     * Register a listener to route debug terminals to numbered pages in the terminal manager.
+     * Register a listener to route externally created terminals (e.g. from plugins)
+     * into the terminal manager when tree mode is active.
+     * Terminals created internally via {@link TerminalManagerWidget.createTerminalWidget}
+     * are skipped because the command handlers handle their placement.
      */
     protected registerTerminalListener(): void {
         this.commandHandlerDisposables.push(
             this.terminalFrontendContribution.onDidCreateTerminal(async terminal => {
-                if (this.isDebugTerminal(terminal)) {
```
Comment (eneufeld) [inline packages/terminal-manager/src/browser/terminal-manager-frontend-contribution.ts:70]: so we now support all terminals and only ignore the ones for tasks? why this change?

File: packages/terminal-manager/src/browser/terminal-manager-widget.ts [hunk 3]
```diff
@@ -161,17 +161,28 @@ export class TerminalManagerWidget extends BaseWidget implements StatefulWidget,
         }
     }
 
+    /**
+     * Set to `true` while {@link createTerminalWidget} is executing, so that external
+     * listeners can distinguish internally created terminals from external ones (e.g. from plugins).
+     */
+    creatingTerminalInternally = false;
```
Comment (eneufeld) [inline packages/terminal-manager/src/browser/terminal-manager-widget.ts]: if `createTerminalWidget` ever is called concurrently, this simple boolean flag will fail. we could use a counter instead. not sure this is worth doing .

**Review by eneufeld — CHANGES_REQUESTED** [review]
Looks good to me overall. Some small things to check though.

File: packages/plugin-ext/src/plugin/terminal-ext.ts (hunk 1 above)
Comment (ndoschek) [reply packages/plugin-ext/src/plugin/terminal-ext.ts]: You're right, the `!` was unnecessary since the `.filter()` already handles `undefined`. Removed the `!` and added a type predicate to the filter instead: `.filter((t): t is theia.Terminal => t !== undefined)`.

File: packages/terminal-manager/src/browser/terminal-manager-frontend-contribution.ts (hunk 2 above)
Comment (ndoschek) [reply packages/terminal-manager/src/browser/terminal-manager-frontend-contribution.ts:70]: The old code only handled debug terminals (routing them into the manager). The new listener routes all externally-created terminals except tasks and hidden ones. This broadening is intentional: plugin-created terminals have no special `kind` property, so filtering by kind would not catch them. Task terminals are excluded because they have their own dedicated "Tasks" page (see #17105). Hidden terminals are excluded by design. Debug terminals and regular terminals should both appear in the tree manager when created externally.

File: packages/terminal-manager/src/browser/terminal-manager-widget.ts (hunk 3 above)
Comment (ndoschek) [reply packages/terminal-manager/src/browser/terminal-manager-widget.ts]: Replaced with a counter. It's a small change and makes the code correct under concurrent calls. The getter still returns a `boolean` so the external API is unchanged.

File: packages/plugin-ext/src/plugin/terminal-ext.ts
Comment (ndoschek) [reply packages/plugin-ext/src/plugin/terminal-ext.ts:362]: No, this path is fine as-is. `$startProfile` is an RPC call from the Main side, not the `createTerminal` path that plugins use directly. It calls `this.proxy.$createTerminal()`, which later triggers `$terminalCreated` on the Ext side via RPC, populating `_terminals` through `obtainTerminal`. Since no `apiObjectWrapper` is involved (there is no plugin caller receiving the return value), the raw `TerminalExtImpl` in `_terminals` is the API object, and the `getApiObject` fallback handles it correctly.

Comment (ndoschek) [reply packages/plugin-ext/src/plugin/terminal-ext.ts:132]: Good catch! You're right, the `===` comparison would fail when a plugin passes the API proxy object (which is what plugins receive) since `_terminals` only stores the raw `TerminalExtImpl`. Fixed by checking `_terminalApiObjects` first, then falling back to `_terminals`.

**Review by eneufeld — APPROVED** [review]
LGTM, thank you
