### PR TITLE
Enhancement : Avoid electron windows to overlap

### LINKED ISSUE #7431: [electron] Open the new window with different x, y coordinates than the previous one
### Description
 

If the title is not descriptive enough, here is a screencast. I want to see both electron browser windows when I open a new one. Currently, the second, third is exactly on the top of the first window.

screencast 2020-03-27 09-37-08

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

### PR DESCRIPTION
**Pull request by OmarSdt-EC**
With this enhancement, an electron window, when it's newly opened, has
different x and y coordinates than all the previous ones. Therefore,
there's no overlap between all the opened electron windows.

#### What it does

Fixes #7431

With this enhancement, an electron window, when it's newly opened, has
different x and y coordinates than all the previous ones. Therefore,
there's no overlap between all the opened electron windows.

#### How to test

1. Open a new electron window (by opening a folder, a file or a workspace for example)
2. The new window has normally different x and y coordinates than the previous one and there's no overlap.

#### Review checklist

- [ ] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/core/src/electron-main/electron-main-application.ts [hunk 1]
```diff
@@ -214,8 +215,8 @@ export class ElectronMainApplication {
      *
      * @param options
      */
-    async createWindow(asyncOptions: MaybePromise<TheiaBrowserWindowOptions> = this.getDefaultBrowserWindowOptions()): Promise<BrowserWindow> {
-        const options = await asyncOptions;
+    async createWindow(options: TheiaBrowserWindowOptions = this.getDefaultTheiaWindowOptions()): Promise<BrowserWindow> {
```
Comment (kittaakos) [inline packages/core/src/electron-main/electron-main-application.ts:218]: Why did you change the type from `MaybePromise<TheiaBrowserWindowOptions>` to `TheiaBrowserWindowOptions`?

Comment (OmarSdt-EC) [reply packages/core/src/electron-main/electron-main-application.ts:218]: I told to myself that the getDefaultBrowserWindowOptions() wasn't a promise. It returns only default options without waiting for them.

Comment (kittaakos) [reply packages/core/src/electron-main/electron-main-application.ts:218]: Please revert the type and keep the original method name. Thank you!

File: packages/core/src/electron-main/electron-main-application.ts [hunk 2]
```diff
@@ -224,14 +225,32 @@ export class ElectronMainApplication {
...
-        const windowOptionsFromConfig = this.config.electron?.windowOptions || {};
-        let windowState: TheiaBrowserWindowOptions | undefined = this.electronStore.get('windowstate', undefined);
-        if (!windowState) {
-            windowState = this.getDefaultWindowState();
-        }
+    async getLastWindowOptions(): Promise<TheiaBrowserWindowOptions> {
+        const windowState: TheiaBrowserWindowOptions | undefined = this.electronStore.get('windowstate') || this.getDefaultTheiaWindowOptions();
         return {
             ...windowState,
+            ...this.getDefaultOptions()
```
[the remark this answers is not in the document]
Comment (OmarSdt-EC) [reply packages/core/src/electron-main/electron-main-application.ts:232]: Hi Colin, I don't think that it overrides the windowState. The windowState properties are : 

Capture

and the `getDefaultOptions()` method is only adding default options that the window needs to open properly : 

C

File: packages/core/src/electron-main/electron-main-application.ts (hunk 1 above)
Comment (paul-marechal) [reply packages/core/src/electron-main/electron-main-application.ts:218]: @kittaakos I agree that this should be reverted in the context of that PR, but long term I think the method should just take the `TheiaBrowserWindowOptions` and not a promise. If someone deals with a promise, they can resolve it first before calling `createWindow`. Is there anything preventing us from doing that, besides being breaking?

**Review by msujew — APPROVED** [review]
I confirmed that the issue can be reproduced on `master` and this change addresses it nicely (tested on windows).

Code LGTM as well. 👍

**Review by colin-grant-work — APPROVED** [review]

**Comment by msujew** [comment]
Someone willing to merge this?
