### PR TITLE
Use Monaco when creating files in `DebugConfigurationManager`

### LINKED ISSUE #9310: Fail to add debug configuration when an empty launch.json is opened
### Bug Description:
when I open an empty launch.json, then click add configuration in debug panel, it only show "{}" in the file.
and actually the launch.json is modified in the backend. Because the contents of frontend and backend are inconsistent, so when I close it, it shows "changes will be lost" dialog.

### Steps to Reproduce:

1. open an empty launch.json
image

2. add debug configuration
image

3. if I click "Don't save" and open the file again, the content changed
image

### Additional Information
I have investigated this issue for a while, I notice the "{}" in launch.json is set by https://github.com/eclipse-theia/theia/blob/master/packages/debug/src/browser/debug-configuration-manager.ts#L265
But I dont't understand the meaning of setting it firstly. If I comment this line, then this issue will be fixed.

- Operating System: ubuntu
- Theia Version: fd91f213e15a91abf975329aaa37c9c59149d012

### PR DESCRIPTION
**Pull request by colin-grant-work**
#### What it does

This PR fixes #9310 by using Monaco to manipulate the file contents rather than having the `FileService` make the change on the backend only.

#### How to test

1. Open a workspace with no `launch.json` files.
2. Create an empty `launch.json` file in some root and have it open.
3. Open the debug widget.
4. Open the dropdown to select configurations and select `Add Configuration`.
5. The file you created should be populated with the default content of a `launch.json` file.
6. Save the file.
7. You should see no error message.
8. It should work regardless of whether the file you create is in a `.vscode` or `.theia` folder.
> The behavior may differ depending on whether you've previously had a `launch.json` in the other folder during the same session.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: Colin Grant <colin.grant@ericsson.com>

### CODE REVIEW

File: packages/debug/src/browser/debug-configuration-manager.ts [hunk 1]
```diff
@@ -252,28 +252,28 @@ export class DebugConfigurationManager {
         return this.models.values().next().value;
     }
 
-    protected async doOpen(model: DebugConfigurationModel): Promise<EditorWidget> {
+    protected async doOpen(model: DebugConfigurationModel): Promise<EditorWidget | undefined> {
```
Comment (vince-fugnitto) [inline packages/debug/src/browser/debug-configuration-manager.ts:255]: Should we document this breakage to be safe?
A downstream extension may previously expect `EditorWidget` when calling `doOpen`.

**Review by vince-fugnitto — APPROVED** [review]
I confirm that the changes successfully fix https://github.com/eclipse-theia/theia/issues/9310 :+1:

File: packages/debug/src/browser/debug-configuration-manager.ts (hunk 1 above)
Comment (colin-grant-work) [reply packages/debug/src/browser/debug-configuration-manager.ts:255]: Yes, likely best to be safe. I'll push a changelog entry

**Comment by colin-grant-work** [comment]
@vince-fugnitto, as we discussed offline, I've modified the code so that it handles any case in which a `launch.json` does not contain at least `{configurations: []}`. Rather than changing the signatures of the methods, I've thrown an `Error` in case the `PreferenceService` returns no `URI`. As I note in the code, that should never happen here, since the inputs are known. I have added a breaking change notice about swapping out the `FileService` for `MonacoTextModelService`, however.

**Review by vince-fugnitto — APPROVED** [review]
I confirmed that the changes work well :+1: 
- verified that it properly creates the `launch.json` when it does not exist.
- verified that it properly populates the `launch.json` when it does not contain a `configurations` object.
- verified that it properly adds new configurations (through _add configuration_) for an existing `configurations` object.
- works for both `.vscode` and `.theia`.
