### PR TITLE
terminal: fix color theming

### LINKED ISSUE #7280: terminal: fix terminal theming
**Description**

**terminal** theming from VS Code theming extensions does not work properly.
For example, the [vscode-builtin-theme-tomorrow-night-blue](https://github.com/microsoft/vscode/blob/583dc037dc55d8e70fc2f4ab9ddbbd7691e5b483/extensions/theme-tomorrow-night-blue/themes/tomorrow-night-blue-theme.json#L42-L57) theme contributes colors to the terminal:

```json
"terminal.ansiBlack": "#111111",
"terminal.ansiRed": "#ff9da4",
"terminal.ansiGreen": "#d1f1a9",
"terminal.ansiYellow": "#ffeead",
"terminal.ansiBlue": "#bbdaff",
"terminal.ansiMagenta": "#ebbbff",
"terminal.ansiCyan": "#99ffff",
"terminal.ansiWhite": "#cccccc",
"terminal.ansiBrightBlack": "#333333",
"terminal.ansiBrightRed": "#ff7882",
"terminal.ansiBrightGreen": "#b8f171",
"terminal.ansiBrightYellow": "#ffe580",
"terminal.ansiBrightBlue": "#80baff",
"terminal.ansiBrightMagenta": "#d778ff",
"terminal.ansiBrightCyan": "#78ffff",
"terminal.ansiBrightWhite": "#ffffff"
```

_Theia_

image

_VS Code_

image

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

Fixes #7280

This commit fixes the issue where VS Code terminal theming was not applied correctly. Since the VS Code theming options for terminals and the `xterm` ITheme differed (lower-case), the terminal themes were not applied properly.

#### How to test

1. start the application
2. create a new terminal and produce some output (ex: `ls -al`)
3. change color theme (the terminal foreground colors should be properly themed)

<details>

<summary>Examples:</summary>

<br/>

**Dark+**

<div align='center'>

image

</div>

<br/>

**Tomorrow Night Blue**

<div align='center'>

image

</div>

**Abyss**

<div align='center'>

image

</div>

<br/>

**Light+**

<div align='center'>

image

</div>

</details>

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: Vincent Fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
@varmanishant would you like to review? :)

File: packages/terminal/src/browser/terminal-theme-service.ts [hunk 1]
```diff
@@ -177,7 +177,7 @@ export class TerminalThemeService {
         };
         // eslint-disable-next-line guard-for-in
         for (const id in terminalAnsiColorMap) {
-            const colorName = id.substring(13);
+            const colorName = id.substring(13).toLowerCase();
```
Comment (akosyakov) [inline packages/terminal/src/browser/terminal-theme-service.ts]: I don't think it is correct, it will translate `ansiBrightWhite` to `brightwhite` when a proper one is `brightWhite`. Only first character should be converted to lower case.

**Comment by varmanishant** [comment]
@vince-fugnitto This looks good!
