### PR TITLE
Fix progress notification issues

### LINKED ISSUE #6506: Hide progress notifications without title
Description
Some notifications have no text. I _think_ that I've only seen the problem on progress notifications.

image

**OS and Theia version:** 
image

**Diagnostics:** 

I don't see any pertinent log messages, but here they are anyway:
[theia-logs.txt](https://github.com/eclipse-theia/theia/files/3816496/theia-logs.txt)

### LINKED ISSUE #8421: progress notification cancelable default is different than vscode
### Bug Description:
In the [progress notification](https://github.com/microsoft/vscode-extension-samples/blob/master/progress-sample/src/extension.ts#L10) the default of the cancelable option in Theia is true and in vscode it's false.

### Steps to Reproduce:

Run this extension on Theia and vscode without declaring cancelable. (remove this [line](https://github.com/microsoft/vscode-extension-samples/blob/master/progress-sample/src/extension.ts#L13))

See that on vscode there's no cancel button and in Theia there is.

### Additional Information

- Operating System: mac os
- Theia Version: master

### LINKED ISSUE #8430: progress without title but with progress.report message shows wrong colon prefix ':'
### Bug Description:
When using vscode `window.withProgress()` without title and updating the progress message, the message shows with a colon prefix

Theia:
Screen Shot 2020-08-25 at 10 47 33

vscode:
Screen Shot 2020-08-25 at 9 41 04

### Steps to Reproduce:

Run this extension on Theia and vscode without the progress title. (remove this [line](https://github.com/microsoft/vscode-extension-samples/blob/master/progress-sample/src/extension.ts#L12))

### Additional Information

- Operating System: mac os
- Theia Version: master

### LINKED ISSUE #8587: Progress notification which is not cancellable can be cancelled through the 'X' button
### Bug Description:
Progress notification which is not cancellable can be cancelled through the 'X' button

### Steps to Reproduce:

Run [this](https://github.com/DoroNahari/withprogress.git) vscode extension and run the command `Show Notification Progress` which is not cancellable.
See that you can cancel the progress by clicking on the 'X' on the progress notification

### Additional Information

- Operating System: mac os
- Theia Version: master

### PR DESCRIPTION
**Pull request by DoroNahari**
Signed-off-by: Doron Nahari <doron.nahari@sap.com>

#### What it does
Fixes #6506
Fixes #8421
Fixes #8430
Fixes #8587 

1. #6506 - Fix empty notifications and progress notifications.
2. #8421 - Align progress notification cancelable property default with vscode (from true to false) (in vscode cancelable considered as true if cancelable=true (boolean) or any non-empty value except boolean false.)
3. #8430 - Remove redundant colon when using progress without title.

4. #8587 - Progress notification which is not cancellable can be cancelled through the 'X' button.

#### How to test
Use [this](https://github.com/microsoft/vscode-extension-samples/blob/master/progress-sample/src/extension.ts) vscode extension sample to reproduce and see the fixes.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by DoroNahari** [comment]
@AlexTugarev Can you review please?

**Comment by AlexTugarev** [comment]
@DoroNahari, yes sure! I'm happy to do it.

File: packages/messages/src/browser/notifications-manager.ts [hunk 1]
```diff
@@ -66,8 +66,12 @@ export class NotificationManager extends MessageClient {
     protected readonly onUpdatedEmitter = new Emitter<NotificationUpdateEvent>();
     readonly onUpdated = this.onUpdatedEmitter.event;
     protected readonly fireUpdatedEvent = throttle(() => {
-        const notifications = deepClone(Array.from(this.notifications.values()));
-        const toasts = deepClone(Array.from(this.toasts.values()));
+        const notifications = deepClone(Array.from(this.notifications.values()).filter((notification: Notification) =>
```
Comment (AlexTugarev) [inline packages/messages/src/browser/notifications-manager.ts:69]: `showProgress`/`reportProgress` should handle it. 

if it's called with empty `message` a log entry should be created to give developers (not users!) a hint.

I wonder how `vscode` does it. if you provide no message in in `showProgress` but in `reportProgress`, especially if `reportProgress` is called with empty message in between. 
does it flicker then? which is my concern this the approach ☝️ 

maybe we should just accept `showProgress` with non-empty message.

File: packages/core/src/common/message-service-protocol.ts [hunk 2]
```diff
@@ -42,9 +42,7 @@ export interface ProgressMessage extends Message {
 export namespace ProgressMessage {
     export const Cancel = 'Cancel';
     export function isCancelable(message: ProgressMessage): boolean {
-        return !message.options
-            || message.options.cancelable === undefined
-            || message.options.cancelable === true;
+        return !!message.options && !!message.options.cancelable;
```
Comment (AlexTugarev) [inline packages/core/src/common/message-service-protocol.ts:45]: @akosyakov would that require any change log as it changes the default behavior in theory?

File: packages/messages/src/browser/notifications-manager.ts (hunk 1 above)
Comment (DoroNahari) [reply packages/messages/src/browser/notifications-manager.ts:69]: I didn't want it in showProgress because i wanted to handle empty 'regular' notification as well.
Here, is the place i found that handle all kind of notifications. otherwise i will need to look for empty message in many places (`showProgress`, `reportProgress`, `showMessage` and maybe more).
Can you think about other and better place that centralized all of the notifications?

In vscode (and in Theia with this fix) if no message in `showProgress` it doesn't show the notification until you `reportProgress` with a message. 
if `reportProgress` is called with empty message but with `increment`, the message stays as is and the progress bar updated accordingly. no flickering.

Comment (AlexTugarev) [reply packages/messages/src/browser/notifications-manager.ts:69]: >  otherwise i will need to look for empty message in many places (showProgress, reportProgress, showMessage and maybe more).

as far as as I see in `showProgress` and in `showMessage`, yes. that's where they are added.

Comment (DoroNahari) [reply packages/messages/src/browser/notifications-manager.ts:69]: So do you agree with this approach?

Comment (AlexTugarev) [reply packages/messages/src/browser/notifications-manager.ts:69]: Not sure yet. We need to check with clients which do not require labels at all, e.g. `git` progress with is handled in the progress locations...

Comment (DoroNahari) [reply packages/messages/src/browser/notifications-manager.ts:69]: My fix is for progress notification.
AFAIK, all git progresses are in the "scm" pane and not as notification. i couldn't found any use of progress notification in Theia.

File: packages/core/src/common/message-service-protocol.ts (hunk 2 above)
Comment (DoroNahari) [reply packages/core/src/common/message-service-protocol.ts:45]: @akosyakov @AlexTugarev 
It's been few days since last comment here.
What should be done to promote this pr?

**Comment by DoroNahari** [comment]
@vince-fugnitto hi,
Can something be done from your side to promote this pr?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto hi,
> Can something be done from your side to promote this pr?

I haven't been following discussions related to the pull-request, I initially requested review from Alex since he is the original author of `progress` messages and it looks like he still has concerns/questions related to the implementation.

**Comment by DoroNahari** [comment]
> > @vince-fugnitto hi,
> > Can something be done from your side to promote this pr?
> 
> I haven't been following discussions related to the pull-request, I initially requested review from Alex since he is the original author of `progress` messages and it looks like he still has concerns/questions related to the implementation.

Alex asked Anton a question and since Anton didn't answer, i thought maybe you can.

Regarding the second thread, i answered all Alex's questions.

**Comment by vince-fugnitto** [comment]
> > > @vince-fugnitto hi,
> > > Can something be done from your side to promote this pr?
> > 
> > 
> > I haven't been following discussions related to the pull-request, I initially requested review from Alex since he is the original author of `progress` messages and it looks like he still has concerns/questions related to the implementation.
> 
> Alex asked Anton a question and since Anton didn't answer, i thought maybe you can.

It would of course be good to document the new behavior, if something is breaking (api, behavior or otherwise) then it should be documented as such as well.

> Regarding the second thread, i answered all Alex's questions.

I think he had a concern about other clients and determining if they were properly handled such as `git` progress.
It would be good to identify if anything is broken by the changes for our internal clients.

The provided extension to test with is minimal (it only verifies the `notification` location such as toasts), it would be good to test other types of notifications for any regressions (I believe this was Alex's comment regarding `scm`).

**Comment by DoroNahari** [comment]
- Added details to changelog.
- Attached [vscode extension](https://github.com/DoroNahari/withprogress.git) which you can use to see all kind of progress locations and more: 
    -  you can use the commands: 
        1. "Show Notification Progress"
        2. "Show Cancelable Notification Progress"
        3. "Show SCM Progress"
        4.  "Show Window Progress"
        5. "Show Empty Notification"
        6. "Show Notification"
        you can make changes to this extension as you want and re-run or ask me to add another variations.
- I checked again all usages of `withProgress` in Theia.
    - Regarding the change of the default cancelable option:  There is [one call](https://github.com/eclipse-theia/theia/blob/master/packages/filesystem/src/browser/file-upload-service.ts#L236) to `messageService.showProgress` with explicitly declaring `cancelable: true`. the rest ([debug-session-manager.ts](https://github.com/eclipse-theia/theia/blob/master/packages/debug/src/browser/debug-session-manager.ts#L170), [git-contribution.ts](https://github.com/eclipse-theia/theia/blob/master/packages/git/src/browser/git-contribution.ts), [git-quick-open-service.ts](https://github.com/eclipse-theia/theia/blob/master/packages/git/src/browser/git-quick-open-service.ts), [navigator-model.ts](https://github.com/eclipse-theia/theia/blob/master/packages/navigator/src/browser/navigator-model.ts#L60), [hosted-plugin.ts](https://github.com/eclipse-theia/theia/blob/master/packages/plugin-ext/src/hosted/browser/hosted-plugin.ts#L244), [vsc-extensions-model.ts](https://github.com/eclipse-theia/theia/blob/master/packages/vsx-registry/src/browser/vsx-extensions-model.ts#L113)) are calling `progressService.withProgress` which is explicitly declaring `cancelable: true`.
    - Regarding not showing empty notification/progress-notification i didn't identified any usages of notification/progress-notification with empty content (what is the meaning of it anyway?). empty text in `withProgress` is ok unless the location of the progress is in the `Notification` area.

@AlexTugarev Are there any other concerns i didn't cover here?

**Review by amiramw — COMMENTED** [review]
Tested all notification and they seems fine.
One thing is that even when executing "Show Notification Progress" I still see the X button that allows the user to close the notification (no cancel button though).

**Review by amiramw — APPROVED** [review]
I think you can open a separate issue for the X button on not cancellable. This PR seems fine to me and tested successfully.

File: packages/core/src/common/message-service-protocol.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (DoroNahari) [reply packages/core/src/common/message-service-protocol.ts]: Done

**Comment by DoroNahari** [comment]
> I think you can open a separate issue for the X button on not cancellable. This PR seems fine to me and tested successfully.

Thanks for noticing

> I think you can open a separate issue for the X button on not cancellable. This PR seems fine to me and tested successfully.

I created another issue

**Comment by DoroNahari** [comment]
> Tested all notification and they seems fine.
> One thing is that even when executing "Show Notification Progress" I still see the X button that allows the user to close the notification (no cancel button though).


>I think you can open a separate issue for the X button on not cancellable. This PR seems fine to me and tested successfully.

Thank you for noticing this additional issue. i created another issue and fixed it here.

**Comment by amiramw** [comment]
> Thank you for noticing this additional issue. i created another issue and fixed it here.

Thanks! Fix LGTM and tested again. Now no progress shows with X button, only simple notifications.
