### PR TITLE
tree indent guidelines support

### LINKED ISSUE #6586: [ui/ux][tree] Help the tree indentation with vertical lines, mimic VS Code
### Description
 
From time to time, it is hard to identify the indentation in the tree. We used to have a larger indentation, now we have a [small one](https://github.com/eclipse-theia/theia/commit/f59ecdebc4f65dddda302e37bf0cc99c6149fdda) to adjust Theia's styles to VS Code. Besides using small indentations, VS  Code also shows vertical lines in the tree which is cool. Let's do the same.

See the attached screenshot:
Screen Shot 2019-11-20 at 10 01 53

and the `:hover` behavior too:
screencast 2019-11-20 10-02-15

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

- Fixes #6586:
  - Add preference to set 'workbench.tree.renderIndentGuides' to 'onHover' (default), 'none' or 'always'
  - When nodes are selected, indent guidelines are rendered for all the sibling nodes
  - When parent node is selected, indent guidelines are rendered for all the child nodes
  - When hovering over a tree, indent guidelines are displayed for all expanded nodes
  - Selecting multiple nodes works in a similar fashion

#### How to test

- Set the workspace preference to 'onHover', 'none', 'always' and the rendering of the indent guidelines should change accordingly.
- In different locations in Theia where the tree is being used (for example, in navigator, search in workspace, outline, problems-view and scm (list mode and tree mode)), select one/more nodes to test if the indent guidelines are rendered correctly.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/core/src/browser/tree/tree-widget.tsx [hunk 1]
```diff
@@ -776,6 +789,54 @@ export class TreeWidget extends ReactWidget implements StatefulWidget {
...
+    protected needsActiveIndentGuideline(node: TreeNode): boolean {
+        const parent = node.parent;
+        if (!parent || !this.isExpandable(parent)) {
+            return false;
+        }
+        if (SelectableTreeNode.isSelected(parent)) {
+            return true;
+        }
+        if (parent.expanded) {
+            for (const sibling of parent.children) {
```
Comment (akosyakov) [inline packages/core/src/browser/tree/tree-widget.tsx:831]: TODO: instead we should rather iterate over selected nodes and check whether its parent is a parent. There are usually not many selected nodes compare to children, i.e. test with node modules

Comment (akosyakov) [reply packages/core/src/browser/tree/tree-widget.tsx:832]: It works fast enough even for node modules folder.

**Comment by akosyakov** [comment]
Search looks off indeed, but other don't much different compare to VS Code.

**Comment by akosyakov** [comment]
For search we can remove custom styling of the expand toggle to align with other trees then it looks like:
Screenshot 2020-08-04 at 14 33 15

Should we? For comparison in VS Code:
Screenshot 2020-08-04 at 14 34 12

**Comment by vince-fugnitto** [comment]
@akosyakov I don't think it's necessary, at least not for the moment (should not block the pull-request).
The issue is that some trees define their own custom styling which is different than the base tree which is what @kaiyue0329 was trying to fix with adding new `props`, but it makes the changes complex. I'd be fine with keeping the approach simple and if we ever update we can do so later on.

**Comment by akosyakov** [comment]
@vince-fugnitto I would rather into looking normalizing such trees and removing custom styling. It seems to be also only one case. I've checked other trees like scm, problems, outlines and could not understand why we need to change their styling. They looked aligned with the default implementation without changes.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I would rather looking into normalising such trees with defaults and removing custom styling.

@akosyakov I agree as well, it'd be best if all trees were normalized this way and their behavior was consistent.

**Comment by akosyakov** [comment]
merging tomorrow morning if no objections
