### PR TITLE
[debug] Show the error message when setting a variable fails

### LINKED ISSUE #13728: Debugger doesn't show error of setVariable if it failed
### Bug Description:

Debugger can have ability to set value of a variable. Debug Adapter Protocol has `setVariable` command for this.
But if evaluation of new value fails (for example, if user entered non-valid expression) theia ignores result and error message from Debug Adapter and only logs error to console. As result, user doesn't see any appropriate reaction on his action

### Steps to Reproduce:

1. Launch JS debugging
2. stop at some breakpoint
3. in Variables panel right-click and choose `Set value`
4. enter an invalid JS expression, for example some syntax error
5. Nothing happens in UI. Only in console.log we see message "ERROR setValue failed..."

### Additional Information

Expected behavior:  This is how it works in VSCode
image

Code: https://github.com/eclipse-theia/theia/blob/master/packages/debug/src/browser/console/debug-console-items.tsx#L206

- Operating System: Windows 10
- Theia Version: 1.49.1

### PR DESCRIPTION
**Pull request by pisv**
#### What it does

Fixes #13728.

#### How to test

Using a simple Node.JS program:

```js
let a = 1;
console.log(a);
```

1. Set a breakpoint on line 2 and launch the program.

2. Double-click on the local `a` variable in the `Debug` view.

3. Try entering an invalid value for the variable like `@` or `foo` and press the `OK` button in the dialog.

4. Verify that the `OK` button becomes disabled and the appropriate error message is shown to the user in the dialog.

5. Enter a correct value for the variable, e.g. `123` and press `OK`.

6. Verify that the value has been correctly applied to the variable by the debugger.

#### Breaking changes

- [ ] This PR introduces breaking changes and requires careful review. If yes, the breaking changes section in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) has been updated.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/debug/src/browser/console/debug-console-items.tsx [hunk 1]
```diff
@@ -244,12 +240,28 @@ export class DebugVariable extends ExpressionContainer {
...
+                    try {
+                        await this.setValue(value);
+                    } catch (error) {
+                        console.error('setValue failed:', error);
+                        if (error.body?.error) {
+                            const errorMessage: DebugProtocol.Message = error.body.error;
+                            if (errorMessage.showUser) {
+                                return formatMessage(errorMessage.format, errorMessage.variables);
+                            }
+                        }
```
Comment (sdirix) [inline packages/debug/src/browser/console/debug-console-items.tsx:258]: If we catch an error we should probably always return an error message, even if we didn't get one from the error. At the moment we will end up returning `true` if there is an error with an unexpected type.

**Review by sdirix — CHANGES_REQUESTED** [review]
Works for me, there is just a minor detail regarding the error flow

File: packages/debug/src/browser/console/debug-console-items.tsx (hunk 1 above)
Comment (pisv) [reply packages/debug/src/browser/console/debug-console-items.tsx:258]: Currently, if setting a variable fails, the error is logged in any case. But it is only manifested to the user in the dialog if the `showUser` property is true. I think that this behaviour matches the spec. It also makes sense to me, since errors of other kinds (e.g. system errors) have generally nothing to do with the user input. So, why should we disable the OK button and keep the dialog open in case of any error?

Comment (sdirix) [reply packages/debug/src/browser/console/debug-console-items.tsx:258]: I agree, thanks for the explanation

**Review by sdirix — APPROVED** [review]

**Comment by pisv** [comment]
@sdirix Thanks a lot for your review and approval! 👍
