### PR TITLE
Fix dropdown

### LINKED ISSUE #12619: [style] Selection box style error
### Bug Description:

The style of the selection box will fail when the window resize:
image

### Steps to Reproduce:

1. Drop down any selection box in the preference page
    image

2. Change the width of the window
    image

3. Change the height of the window
    image

### Additional Information

- Operating System: MacOS
- Theia Version: 1.38.0 Electron

### PR DESCRIPTION
**Pull request by ankitsharma101**
#### What it does
Fixes the preference select dropdown staying open and mispositioned when the browser window is resized or when the Lumino split-panel sash is dragged (which shifts the layout but does not fire a standard window resize event).

Closes #12619

#### How to test
1. Open **Settings** (File → Preferences → Open Settings UI)
2. Search for `editor.wordWrap`
3. Click the dropdown to open it
4. **Resize the browser window** by dragging its edge → dropdown should close ✅
5. Repeat steps 2-3, then **drag the sidebar sash** to shift the layout → dropdown should close ✅

#### Follow-ups
The fix uses `(this.selectComponent.current as any).hide()` to call the protected `hide()` method on `SelectComponent` without modifying the core widget. A potential follow-up would be to expose a public `close()` method on `SelectComponent` to avoid this cast. A technical debt issue could be created for this.

#### Breaking changes
- [ ] This PR introduces breaking changes and requires careful review.

#### Review checklist
- [x] As an author, I have thoroughly tested my changes and carefully followed the review guidelines
- [x] User-facing text is internationalized using the `nls` service (no user-facing text introduced in this PR)

#### Reminder for reviewers
- As a reviewer, I agree to behave in accordance with the review guidelines

### CODE REVIEW

File: packages/preferences/src/browser/views/components/preference-select-input.ts [hunk 1]
```diff
@@ -77,6 +81,50 @@ export class PreferenceSelectInputRenderer extends PreferenceLeafNodeRenderer<JS
         const root = createRoot(interactable);
         root.render(selectComponent);
         parent.appendChild(interactable);
+
+        const closeDropdown = () => {
+            if (this.selectComponent && this.selectComponent.current) {
+                // hide() is protected; using cast to avoid modifying core SelectComponent
+                // which would risk regressions across the entire IDE
+                // eslint-disable-next-line @typescript-eslint/no-explicit-any
+                (this.selectComponent.current as any).hide();
```
Comment (sdirix) [inline packages/preferences/src/browser/views/components/preference-select-input.ts]: This is fixing the wrong layer. The window resize problem affects **all** `SelectComponent` consumers, not just the preference renderer. The proper fix is to add `'resize'` handling inside `SelectComponent.attachListeners()` itself (next to the existing `scroll`/`wheel` handlers):

https://github.com/eclipse-theia/theia/blob/afae867a5ffaa073d30c1c74296e595ea5e77d24/packages/core/src/browser/widgets/select-component.tsx#L151-L173

That way every dropdown in the IDE closes on window resize automatically, and no `as any` cast or consumer-side workaround is needed.

File: packages/preferences/src/browser/views/components/preference-select-input.ts [hunk 2]
```diff
@@ -77,6 +81,50 @@ export class PreferenceSelectInputRenderer extends PreferenceLeafNodeRenderer<JS
...
+            }
+        };
+        window.addEventListener('pointerdown', handleGlobalPointerDown, true);
+        window.addEventListener('mousedown', handleGlobalPointerDown, true);
+        this._globalPointerDownHandler = handleGlobalPointerDown;
+
+        this._resizeObserver = new ResizeObserver(() => {
+            closeDropdown();
+        });
+        const mainPanel = parent.closest('.p-Widget') || parent;
```
Comment (sdirix) [inline packages/preferences/src/browser/views/components/preference-select-input.ts]: `.p-Widget` is the old PhosphorJS class prefix. Lumino applies `lm-Widget`. This selector will always return `null`, falling back to `parent`.

https://github.com/eclipse-theia/theia/blob/afae867a5ffaa073d30c1c74296e595ea5e77d24/packages/core/src/browser/shell/application-shell.ts#L1082

File: packages/preferences/src/browser/views/components/preference-select-input.ts [hunk 3]
```diff
@@ -77,6 +81,50 @@ export class PreferenceSelectInputRenderer extends PreferenceLeafNodeRenderer<JS
...
+
+        window.addEventListener('resize', closeDropdown);
+        this._resizeHandler = closeDropdown;
+
+        const handleGlobalPointerDown = (event: Event) => {
+            if (!interactable.contains(event.target as Node)) {
+                closeDropdown();
+            }
+        };
+        window.addEventListener('pointerdown', handleGlobalPointerDown, true);
```
Comment (sdirix) [inline packages/preferences/src/browser/views/components/preference-select-input.ts]: `SelectComponent` already calls `this.hide()` in its `onBlur` handler ([link](https://github.com/eclipse-theia/theia/blob/afae867a5ffaa073d30c1c74296e595ea5e77d24/packages/core/src/browser/widgets/select-component.tsx#L204-L208)). Clicking anywhere outside the select field triggers blur, which closes the dropdown. These capture-phase pointerdown/mousedown listeners are redundant with that

File: packages/preferences/src/browser/views/components/preference-select-input.ts [hunk 4]
```diff
@@ -32,6 +32,10 @@ export class PreferenceSelectInputRenderer extends PreferenceLeafNodeRenderer<JS
 
     protected selectOptions: SelectOption[] = [];
 
+    private _resizeHandler?: () => void;
+    private _resizeObserver?: ResizeObserver;
+    private _globalPointerDownHandler?: (event: Event) => void;
```
Comment (sdirix) [inline packages/preferences/src/browser/views/components/preference-select-input.ts]: [Coding guidelines](https://github.com/eclipse-theia/theia/blob/afae867a5ffaa073d30c1c74296e595ea5e77d24/doc/coding-guidelines.md) say: do not use `_` as a prefix for private properties (unless exposing via get/set).

File: packages/core/src/browser/style/tree.css [hunk 5]
```diff
@@ -148,7 +150,7 @@
   align-items: center;
   flex-grow: 0;
   user-select: none;
-  white-space: nowrap;
+  white-space: pre;
```
Comment (sdirix) [inline packages/core/src/browser/style/tree.css:153]: These changes are already on master via #16932. Please rebase your PR or merge `master`

**Comment by ankitsharma101** [comment]
@sdirix Thank you for the detailed review and guidance! I have applied all of your suggestions:

Moved to Core: Added the resize listener into SelectComponent.attachListeners() so it applies globally. (I also added a quick instanceof Node check to the hide function so the event.target window resize doesn't trigger a contains() TypeError).

Lumino Update: Updated the ResizeObserver target in the preferences wrapper to use .lm-Widget. (Added a brief timeout to ensure the node is attached before querying the closest widget).

Removed Redundancies: Completely removed the custom pointerdown/mousedown capture listeners from the wrapper, relying entirely on the core onBlur behavior.

Coding Guidelines: Removed the _ prefix from the private resizeObserver property.

Synced with Master: Reset the branch to drop the tree.css commit since it is already in master.

I kept the ResizeObserver logic in the preferences wrapper because dragging the Lumino sash does not fire a global window.resize event, so the observer is still necessary to catch that specific layout shift.

Let me know if this looks good to go!

**Comment by ankitsharma101** [comment]
Hi @sdirix, the linting error is fixed and the ResizeObserver logic is updated to observe the parent container directly. The CI is fully green!

File: packages/core/src/browser/widgets/select-component.tsx [hunk 6]
```diff
@@ -149,13 +149,16 @@ export class SelectComponent extends React.Component<SelectComponentProps, Selec
     }
 
     protected attachListeners(): void {
-        const hide = (event: MouseEvent) => {
-            if (!this.dropdownRef.current?.contains(event.target as Node)) {
-                this.hide();
+        const hide = (event: Event) => {
+            // Safely check if target is a Node. If it's a click INSIDE the dropdown, do nothing.
```
Comment (sdirix) [inline packages/core/src/browser/widgets/select-component.tsx]: This is not only checking for clicks

File: packages/preferences/src/browser/views/components/preference-select-input.ts [hunk 7]
```diff
@@ -77,6 +79,30 @@ export class PreferenceSelectInputRenderer extends PreferenceLeafNodeRenderer<JS
         const root = createRoot(interactable);
         root.render(selectComponent);
         parent.appendChild(interactable);
+
+        this.resizeObserver = new ResizeObserver(() => {
```
Comment (sdirix) [inline packages/preferences/src/browser/views/components/preference-select-input.ts]: Why was this not also moved to the `SelectComponent` itself?

File: packages/core/src/browser/widgets/select-component.tsx (hunk 6 above)
Comment (ankitsharma101) [reply packages/core/src/browser/widgets/select-component.tsx]: I've updated the comment to accurately reflect that it handles scroll, wheel, and resize events, not just clicks.

File: packages/preferences/src/browser/views/components/preference-select-input.ts (hunk 7 above)
Comment (ankitsharma101) [reply packages/preferences/src/browser/views/components/preference-select-input.ts]: Makes perfect sense. I moved the ResizeObserver entirely into SelectComponent.attachListeners() so it handles layout shifts globally, and added the cleanup to componentWillUnmount(). Glad to finally get rid of that as any cast, too! Thanks for pushing for the better architecture on this.

File: packages/preferences/src/browser/views/components/preference-select-input.ts [hunk 8]
```diff
@@ -79,6 +79,10 @@ export class PreferenceSelectInputRenderer extends PreferenceLeafNodeRenderer<JS
         parent.appendChild(interactable);
     }
 
+    override dispose(): void {
+        super.dispose();
+    }
+
```
Comment (sdirix) [inline packages/preferences/src/browser/views/components/preference-select-input.ts]: Looks like this can be removed

**Comment by ankitsharma101** [comment]
Hey @sdirix, I just removed that dispose() block!

Regarding the failing Playwright tests: I realized the new ResizeObserver was catching a micro layout shift the millisecond the dropdown opened, causing it to snap shut before the UI bot could click anything. >
To save you some back-and-forth, I went ahead and pushed a quick fix for this. I added a 2-pixel dimension check so the observer ignores the dropdown opening and only fires on an actual sash drag. Tested it locally and the UI feels bulletproof.

If you would rather handle this with a debounce instead, just say the word and I can swap it out in two seconds!

**Review by sdirix — APPROVED** [review]
Works for me. Thanks!
