### PR TITLE
GH-8186: Workaround for  `application.confirmExit`

### LINKED ISSUE #8186: [electron] Backend processes are already terminated before 'will-prevent-unload' is called
### Bug Description:

Start the app, make an editor dirty or set the `application.confirmExit` to `true`. Terminate the app with `Ctrl/Cmd+Q` on macOS, you get the `Any unsaved changes will not be saved.` dialog, but the BE has already terminated so hitting `No` in the dialog will result in an `offline` app.

We need to figure out the followings:
 - ~is it a macOS issue only?~ It is not a macOS only problem. Same bug on Windows when quitting the app with `Alt+F4`. See [here](https://github.com/eclipse-theia/theia/issues/8186#issuecomment-659359289).
 - ~was there a change in electron 9.x?~ It is not related to electron 9.x. See [here](https://github.com/eclipse-theia/theia/issues/8186#issuecomment-659343446)
 - is [it](https://github.com/eclipse-theia/theia/pull/6285) related? ~Maybe; see [here](https://github.com/eclipse-theia/theia/issues/8186#issuecomment-659363942).~ Most likely not: https://github.com/eclipse-theia/theia/issues/8186#issuecomment-659415028 
 - should we switch back to [this](https://github.com/electron/electron/issues/2301#issuecomment-308384017)?

Mentioning @marechal-p, @mcgordonite here. If you have any idea what's causing it, please let me know.

### Steps to Reproduce:

1.
2.
3.

### Additional Information

- Operating System:
- Theia Version:

### PR DESCRIPTION
**Pull request by kittaakos**
#### What it does

 - Moves the `beforeunload` handling logic to the frontend.
 - Removes the `attachWillPreventUnload` from the main electron app.
 - Closes #8186.

#### How to test

Electron env:

 1.
   - start the electron app in debug mode and open the dev-tools.
   - put a breakpoint to `frontend-application.ts`, line 190 ([inside `this.windowsService.onUnload`](https://github.com/eclipse-theia/theia/blob/76b1ffd8cd04f907cf847792fd66b8a9ef14d53c/packages/core/src/browser/frontend-application.ts#L190)).
   - set `confirmExit` to `never`.
   - refresh the window with `Ctrl/Cmd+R`.
 Expectation:
     - you must hit the breakpoint.
     - the window closes.
 2.
   - start the electron app in debug mode and open the dev-tools.
   - put a breakpoint to `frontend-application.ts`, line 190 ([inside `this.windowsService.onUnload`](https://github.com/eclipse-theia/theia/blob/76b1ffd8cd04f907cf847792fd66b8a9ef14d53c/packages/core/src/browser/frontend-application.ts#L190)).
   - set `confirmExit` to `never`.
   - run the `Reload Window` command.
 Expectation:
     - you must hit the breakpoint.
     - the window closes.
 3.
   - start the electron app in debug mode and open the dev-tools.
   - put a breakpoint to `frontend-application.ts`, line 190 ([inside `this.windowsService.onUnload`](https://github.com/eclipse-theia/theia/blob/76b1ffd8cd04f907cf847792fd66b8a9ef14d53c/packages/core/src/browser/frontend-application.ts#L190)).
   - set `confirmExit` to `never`.
   - quit the app (on macOS with `Cmd+Q`)
 Expectation:
     - you must hit the breakpoint.
     - the window closes.
 4.
   - start the electron app in debug mode and open the dev-tools.
   - put a breakpoint to `frontend-application.ts`, line 190 ([inside `this.windowsService.onUnload`](https://github.com/eclipse-theia/theia/blob/76b1ffd8cd04f907cf847792fd66b8a9ef14d53c/packages/core/src/browser/frontend-application.ts#L190)).
   - set `confirmExit` to `never`.
   - close the window by clicking on the `X`.
 Expectation:
     - you must hit the breakpoint.
     - the window closes.
 5.
   - start the electron app in debug mode and open the dev-tools.
   - put a breakpoint to `frontend-application.ts`, line 190 ([inside `this.windowsService.onUnload`](https://github.com/eclipse-theia/theia/blob/76b1ffd8cd04f907cf847792fd66b8a9ef14d53c/packages/core/src/browser/frontend-application.ts#L190)).
   - set `confirmExit` to `never`.
   - close the window by clicking on the `X`.
 Expectation:
     - you must hit the breakpoint.
     - the window closes.
 6.
   - start the electron app in debug mode and open the dev-tools.
   - put a breakpoint to `frontend-application.ts`, line 190 ([inside `this.windowsService.onUnload`](https://github.com/eclipse-theia/theia/blob/76b1ffd8cd04f907cf847792fd66b8a9ef14d53c/packages/core/src/browser/frontend-application.ts#L190)).
   - set `confirmExit` to `always`.
   - close or refresh the window (it's up to you what pick, we've already verified it in `1. - 5.`).
   - see the modal dialog, select `No`.
 Expectation:
     - you must **not** hit the breakpoint.
     - the window does **not** close. 
     - open `src-gen/frontend/index.js` and verify the LS is still running. Try the content assist.
 7.
   - start the electron app in debug mode and open the dev-tools.
   - put a breakpoint to `frontend-application.ts`, line 190 ([inside `this.windowsService.onUnload`](https://github.com/eclipse-theia/theia/blob/76b1ffd8cd04f907cf847792fd66b8a9ef14d53c/packages/core/src/browser/frontend-application.ts#L190)).
   - set `confirmExit` to `always`.
   - Close or refresh the window (it's up to you what pick, we've already verified it in `1. - 5.`).
   - see the modal dialog, select `Yes`.
 Expectation:
     - you must hit the breakpoint.
     - the window closes.
 7.
   - start the electron app in debug mode and open the dev-tools.
   - put a breakpoint to `frontend-application.ts`, line 190 ([inside `this.windowsService.onUnload`](https://github.com/eclipse-theia/theia/blob/76b1ffd8cd04f907cf847792fd66b8a9ef14d53c/packages/core/src/browser/frontend-application.ts#L190)).
   - set `confirmExit` to `ifRequired`.
   - open `src-gen/frontend/index.js` make sure it's **not** dirty.
   - close or refresh the window (it's up to you what pick, we've already verified it in `1. - 5.`).
 Expectation:
     - you do not see the modal dialog.
     - you must hit the breakpoint.
     - the window closes.
 8.
   - start the electron app in debug mode and open the dev-tools.
   - put a breakpoint to `frontend-application.ts`, line 190 ([inside `this.windowsService.onUnload`](https://github.com/eclipse-theia/theia/blob/76b1ffd8cd04f907cf847792fd66b8a9ef14d53c/packages/core/src/browser/frontend-application.ts#L190)).
   - set `confirmExit` to `ifRequired`.
   - disable the auto-save.
   - open `src-gen/frontend/index.js` and make it dirty.
   - close or refresh the window (it's up to you what pick, we've already verified it in `1. - 5.`).
   - see the modal dialog, select `Yes`.
 Expectation:
     - you must hit the breakpoint.
     - the window closes.
 9.
   - start the electron app in debug mode and open the dev-tools.
   - put a breakpoint to `frontend-application.ts`, line 190 ([inside `this.windowsService.onUnload`](https://github.com/eclipse-theia/theia/blob/76b1ffd8cd04f907cf847792fd66b8a9ef14d53c/packages/core/src/browser/frontend-application.ts#L190)).
   - set `confirmExit` to `ifRequired`.
   - disable the auto-save.
   - open `src-gen/frontend/index.js` and make it dirty.
   - close or refresh the window (it's up to you what pick, we've already verified it in `1. - 5.`).
   - see the modal dialog, select `No`.
 Expectation:
     - you must **not** hit the breakpoint.
     - the window does **not** close. 
     - open `src-gen/frontend/index.js` and verify the LS is still running. Try the content assist.

Browser env:

Essentially, do the same as in electron env. However, there is one case that cannot be verified the same way; when you reload the browser window. In such cases, you won't hit the breakpoint in the browser (I use Brave, but it should behave the same in Chrome) but there is a trick for this use-case. Start the backend in debug mode. Check the backend log; you must see `root INFO Changed application state from 'ready' to 'closing_window'.` when you reload the window even if you do not hit the breakpoint. If you start the backend in debug mode from VS Code, you can even filter the Debug Console with `"Changed application state from"` and you will see the expected state transition logs.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by zhaomenghuan** [comment]
Thank you very much，I fix the following minor defects and I tested it runs fine.👍
```
packages/core/src/browser/window/test/mock-window-service.ts:20:14 - error TS2420: Class 'MockWindowService' incorrectly implements interface 'WindowService'.
  Property 'onUnload' is missing in type 'MockWindowService' but required in type 'WindowService'.
```

**Comment by kittaakos** [comment]
Thank you so much for helping with this, @zhaomenghuan. The "confirm exit" seems to work, unfortunately, I noticed a critical issue; https://github.com/eclipse-theia/theia/issues/6530 is back. I need to work on this PR.

File: packages/core/src/electron-browser/window/electron-window-service.ts [hunk 1]
```diff
@@ -30,6 +32,18 @@ export class ElectronWindowService extends DefaultWindowService {
         return undefined;
     }
 
+    registerUnloadListener(): void {
+        remote.getCurrentWindow().on('closed', () => this.onUnloadEmitter.fire());
+    }
+
+    /**
+     * Unlike the default implementation, this even is fires when the `ElectronWindow`
```
Comment (marechal-p) [inline packages/core/src/electron-browser/window/electron-window-service.ts:40]: Typo: `event is fired`

On the other hand, people will most likely interact with the `WindowService` interface. Depending on who this comment is intended:
- Theia devs: move the comment to be the class's jsdoc, no need to duplicate this field just to add documentation.
- Theia users: move the comment to `WindowService.onUnload`'s jsdoc mentioning that this behavior occurs on Electron.

**Comment by kittaakos** [comment]
This is ready for review. I am not totally happy with removing the `attachWillPreventUnload` method, but it works now. I tried to test all the cases (on macOS) with both the electron and browser examples.

@marechal-p and @zhaomenghuan, could you please help with the verification?

@mcgordonite, I would like to kindly ask you to chime in and help with Windows's verification. I have a strong opinion on moving forward with change, and I do not want to break something on your side.

Thank you!

File: packages/core/src/browser/window/test/mock-window-service.ts [hunk 2]
```diff
@@ -14,10 +14,12 @@
...
  ********************************************************************************/
 import { injectable } from 'inversify';
+import { Event } from '../../../common/event';
 import { WindowService } from '../window-service';
 
 @injectable()
 export class MockWindowService implements WindowService {
     openNewWindow(): undefined { return undefined; }
     canUnload(): boolean { return true; }
+    get onUnload(): Event<void> { return Event.None; }
```
Comment (marechal-p) [inline packages/core/src/browser/window/test/mock-window-service.ts:24]: Nitpick: `onUnload = Event.None;`

File: packages/core/src/browser/window/default-window-service.ts [hunk 3]
```diff
@@ -38,7 +40,9 @@ export class DefaultWindowService implements WindowService, FrontendApplicationC
             if (!this.canUnload()) {
                 return this.preventUnload(event);
             }
+            this.onUnloadEmitter.fire();
```
[the remark this answers is not in the document]
Comment (kittaakos) [reply packages/core/src/browser/window/default-window-service.ts:43]: Good point, I have to check.

[the remark this answers is not in the document]
Comment (kittaakos) [reply packages/core/src/browser/window/default-window-service.ts:45]: Fixed.

**Comment by kittaakos** [comment]
@marechal-p, I fixed the issue you have noticed. Thank you! Please check if you are fine with the proposed change or not.

File: packages/core/src/browser/window/default-window-service.ts [hunk 4]
```diff
@@ -61,6 +67,21 @@ export class DefaultWindowService implements WindowService, FrontendApplicationC
         return confirmExit !== 'always';
     }
 
+    protected registerUnloadListener(): void {
+        window.addEventListener('unload', this.fireUnload.bind(this));
```
Comment (marechal-p) [inline packages/core/src/browser/window/default-window-service.ts:71]: Is there any advantage to firing `onUnload` on the `unload` event? My reasoning is that when `this.canUnload()` returns `true`, it will be fired in `beforeunload`. On electron, it will also be fired on `beforeunload` when `this.canUnload()` returns `false`. Only on the browser when `this.canUnload()` returns `false` will the event be fired on `unload`.

See my other comment for my proposed change.

File: packages/core/src/browser/window/default-window-service.ts [hunk 5]
```diff
@@ -38,7 +42,9 @@ export class DefaultWindowService implements WindowService, FrontendApplicationC
             if (!this.canUnload()) {
                 return this.preventUnload(event);
             }
+            this.fireUnload();
```
Comment (marechal-p) [inline packages/core/src/browser/window/default-window-service.ts:45]:
```ts
if (!this.canUnload()) {
    this.preventUnload(event); // should be sync
}
// Will the browser unload?
if (!event.returnValue) {
    this.onUnloadEmitter.fire();
}
```

The idea here would be to fire `onUnload` in `beforeunload` always. This means we need to get rid of the firing in `preventUnload` on electron.

Comment (kittaakos) [reply packages/core/src/browser/window/default-window-service.ts:45]: Thanks! I am fine with your proposal, actually, I am fine with any proposal that works. Did you verify yours? If so, I am happy to apply the changes and proceed but if it works in theory only I would stick to mine.

Comment (kittaakos) [reply packages/core/src/browser/window/default-window-service.ts:45]: @marechal-p, let's put it this way; if you have a better, cleaner idea that works could you please submit a PR. I am more than happy to go through the verification steps and review it.

Comment (marechal-p) [reply packages/core/src/browser/window/default-window-service.ts:45]: Ok after experimenting I now understand that in a browser, once a user is prompted the confirmation window it means that we are out of the `beforeunload` handler, so the event can only be fired from `unload`. I did not now this before hand, it is my bad.

Comment (kittaakos) [reply packages/core/src/browser/window/default-window-service.ts:45]: > after experimenting

Thanks a lot for trying it out. 🙏  I do not like the changes, but I was not able to find another solution that works in both envs. I also tried to [integrate](https://github.com/eclipse-theia/theia/issues/8595#issuecomment-723470426) [`PageLifecycle.js`](https://github.com/GoogleChromeLabs/page-lifecycle), but it did not work for me 😕

**Comment by marechal-p** [comment]
I made a fixup commit based on your work, I would be more comfortable with this logic: https://github.com/eclipse-theia/theia/compare/mp/GH-8186

I applied your how to test steps and everything went right on my machine (Windows 10) both for Electron and browser.

**Comment by kittaakos** [comment]
> I made a fixup commit based on your work,

Cool. I will take a look 👍

**Comment by kittaakos** [comment]
> I made a fixup commit based on your work, I would be more comfortable with this logic:

@marechal-p, I've verified it with both examples on macOS; it works. Let's go with your changes, and thank you for your time to help me. Could you please squash the commits but please do not change anything else.

**Review by marechal-p — APPROVED** [review]

**Comment by kittaakos** [comment]
Thanks, @marechal-p 🙏

I leave the PR open for a few days to see if somebody has a remark.
