### PR TITLE
Handle multiple args to webview console

### LINKED ISSUE #17119: webview: console.log API only passes first argument
### Bug Description:

When a webview logs multiple parameters only the first is surviving the logging infrastructure.

### Steps to Reproduce:

Consider a webview content with:
```js
console.error("Called with some %s or object %o", 'string', {foo:1});
```

results in the console log:

> 2026-03-04T10:42:42.123Z root ERROR [webview: f76e2e33-1e7c-4c16-90f1-8b47655a230f] Called with some string or object %o

The first parameter (`string`) is used, but the second parameter is lost (and the substitution string is unused).

This infrastructure started with https://github.com/eclipse-theia/theia/pull/13084 which serialized only the **first** parameter and pushed it via `postMessage`. 

The existing infrastructure can handle multiple parameters, but it gets only one single parameter injected from webview.

### Additional Information

- Operating System: Windows 11
- Theia Version: 1.69.0

### PR DESCRIPTION
**Pull request by HolgerJeromin**
In https://github.com/eclipse-theia/theia/pull/13084 we got handling
 of console log messages with one single argument.
 But the calls can have multiple parameters:
 ```ts
 console.info("Called with some %s or object %o", 'string', {foo:1});
 ```

#### What it does

On the `postMessage` transport layer it now packs and serializes all parameters an transfer it to the host.

There it is pushed all parameters into the existing Logger infrastructure which itself was capable of handling multiple parameters.

#### How to test

Load a webview with 
```ts
console.error("Called with some %s or object %o", 'string', {foo:1});
```

This should give an output similar to

> 2026-03-04T10:42:42.123Z root ERROR [webview: f76e2e33-1e7c-4c16-90f1-8b47655a230f] Called with some string or object {foo: 1}

fixes #17119 

#### Breaking changes

none

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/plugin-ext/src/main/browser/webview/pre/main.js [hunk 1]
```diff
@@ -154,7 +154,7 @@ globalThis.acquireVsCodeApi = (function() {
 
     let state = ${state ? `JSON.parse(${JSON.stringify(state)})` : undefined};
 
-    const forwardConsoleLog = (level, msg, args) => {
+    const forwardConsoleLog = (level, msg, ...args) => {
```
Comment (sdirix) [inline packages/plugin-ext/src/main/browser/webview/pre/main.js:157]: With rest parameters, `args` is always an array (possibly empty `[]`). Since an empty array is truthy, the existing `if (args)` guard (line 163) is now dead code — it will always serialize and send `optionalParams: "[]"` over postMessage even for single-argument calls like `console.log("hello")`.

Please change the guard to `if (args.length > 0)`.

Comment (HolgerJeromin) [reply packages/plugin-ext/src/main/browser/webview/pre/main.js:157]: Good catch. 
Thanks!
Rebased and fixed the issue.
