### PR TITLE
[merge editor] Fix unexpectedly marking merge conflict as handled

### LINKED ISSUE #16866: [merge editor] Merge conflict is unexpectedly marked as handled
### Bug Description:

In some cases, an unhandled merge conflict can unexpectedly be marked as handled.

### Steps to Reproduce:

Open the 3-way merge editor with the `Merge Editor (Dev): Open Merge Editor State from JSON` command (which is available in the command palette, `F1`) using the following JSON:

```json
{
  "base": "foo\nbar\nbaz",
  "input1": "foo1\nbar\nbaz1",
  "input2": "foo2\nbar\nbaz2",
  "result": "foo\nbar\nbaz"
}
```

Click `Accept Left` on the 2nd merge conflict and observe that both conflicts are now marked as handled, while the 1st conflict has not been actually handled.

### Additional Information

I'm going to submit a PR fixing this issue.

- Operating System: all
- Theia Version: 1.67 (current master)

### PR DESCRIPTION
**Pull request by pisv**
#### What it does

Fixes #16866.

- Fixes a bug in computing the merge ranges affected by a content change
- Refactors a couple of methods pertaining to the merge editor implementation

#### How to test

Use the reproduction steps in #16866 to verify that the issue is fixed.

#### Breaking changes

- [x] This PR introduces breaking changes and requires careful review. If yes, the breaking changes section in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) has been updated.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)
- [x] User-facing text is internationalized using the `nls` service (for details, please see the [Internationalization/Localization section](https://github.com/theia-ide/theia/blob/master/doc/coding-guidelines.md#internationalizationlocalization) in the Coding Guidelines)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/scm/src/browser/merge-editor/model/line-range.ts [hunk 1]
```diff
@@ -58,7 +58,7 @@ export class LineRange {
     }
 
     /**
-     * Returns `false` if there is at least one line between `this` and `other`.
+     * Returns `false` iff there is at least one line between `this` and `other`.
```
Comment (ndoschek) [inline packages/scm/src/browser/merge-editor/model/line-range.ts:61]: nit: The "iff" change is technically correct, but may be confusing or look like a typo to many developers. "If" was already clear enough, so I'd suggest reverting this change, especially since it's the only modification in the file.

Comment (pisv) [reply packages/scm/src/browser/merge-editor/model/line-range.ts:61]: @ndoschek Thank you for your review!

This change was made to align the wording with `RangeUtils.touches` (which is a new method). The previous wording using "if" was, strictly speaking, incomplete, because it does not say "Otherwise, returns `true`". Using "iff" was a concise way to resolve the possible ambiguity, but I can see that it may indeed look confusing.

What about replacing both occurrences of "iff" with "if and only if" to make it more clear, hopefully? Or, just adding "Otherwise, returns `true`", if that would make more sense?

Comment (ndoschek) [reply packages/scm/src/browser/merge-editor/model/line-range.ts:61]: Agreed, then let's leave it like it is :+1:

**Comment by pisv** [comment]
@ndoschek Thanks a lot for your review and help! 👍
