### PR TITLE
Fix TreeView.reveal() behavior. 

### LINKED ISSUE #12488: TreeView.reveal() is broken
### Steps to Reproduce:

1. Install the attached plugin
2. Open the "Test View Drag and Drop" view
3. Select "Say hello" from the view toolbar menu
4. Observe: nothing happens. It's supposed to reveal the item "aaaa".

### Additional Information

- Operating System: Windows
- Theia Version: 1.37 master

### PR DESCRIPTION
**Pull request by tsmaeder**
#### What it does
Fixes the `TreeView.reveal` behavior. The behavior was broken when we moved to a new scheme for generating `TreeNode` ids from `TreeItem`s, In addition, the reveal flags (select, focus, reveal) were not passed to the front end.

Fixes #12488

Contributed on behalf of STMicroelectronics
#### How to test
Make sure the failure case from the related issue now works. In addition, I used the procedure from https://github.com/eclipse-theia/theia/pull/8783 to guard against regressions.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/plugin-ext/src/plugin/tree/tree-views.ts [hunk 1]
```diff
@@ -247,11 +247,14 @@ class TreeViewExtImpl<T> implements Disposable {
 
     async reveal(element: T, options?: Partial<TreeViewRevealOptions>): Promise<void> {
         await this.pendingRefresh;
+        const select = !(options?.select === false); // default to true
```
Comment (vince-fugnitto) [inline packages/plugin-ext/src/plugin/tree/tree-views.ts:250]: suggestion:

```suggestion
        const select = options?.select !== false; // default to true
```

`true` → `true`
`false` → `false`
`undefined` → `true`

File: packages/plugin-ext/src/plugin/tree/tree-views.ts [hunk 2]
```diff
@@ -247,11 +247,14 @@ class TreeViewExtImpl<T> implements Disposable {
...
+        const focus = !!options?.focus;
+        const expand = typeof options?.expand === 'undefined' ? false : options!.expand!;
```
Comment (vince-fugnitto) [inline packages/plugin-ext/src/plugin/tree/tree-views.ts:252]: minor: the trailing `!` does not seem necessary?

```suggestion
        const expand = typeof options?.expand === 'undefined' ? false : options!.expand;
```

File: packages/plugin-ext/src/plugin/tree/tree-views.ts [hunk 3]
```diff
@@ -247,11 +247,14 @@ class TreeViewExtImpl<T> implements Disposable {
...
 
         const elementParentChain = await this.calculateRevealParentChain(element);
         if (elementParentChain) {
             return this.proxy.$reveal(this.treeViewId, elementParentChain, {
-                select: true, focus: false, expand: false, ...options
+                select: select, focus: focus, expand: expand, ...options
```
Comment (vince-fugnitto) [inline packages/plugin-ext/src/plugin/tree/tree-views.ts:257]: suggestion: can be omitted

```suggestion
                select, focus, expand, ...options
```

**Review by vince-fugnitto — APPROVED** [review]
I confirmed that the plugin works as expected :+1:
