### PR TITLE
Make context element mandatory when showing a context menu.

### LINKED ISSUE #14960: Terminal Context Menu on wrong Window
### Bug Description:
When moving a terminal to a secondary window and doing a right-click inside the terminal, the context menu opens on the main window instead of the secondary windows. 

### Steps to Reproduce:

1. Open a terminal
2. Extract the terminal to a secondary window
3. Right-click inside the terminal
4. Observe: the context menu opens in a position relative to the main window, not at the mouse location.

### Additional Information

- Operating System:  Windows
- Theia Version: 1.58.100

### PR DESCRIPTION
**Pull request by tsmaeder**
#### What it does
This PR makes the context menu argument when showing a context menu mandatory. This is necessary to attach the context menu to the correct window when extracting widgets to secondary window. If now context element is available at a call site, clients can just pass `window.document.body` as the context.

Fixes #14960

#### How to test
Check that context menus everywhere are shown in the correct location and have the correct content for the location of the menu. This also includes "more" menus on toolbars, etc. (i.e. all menus other than the main menu bar. Where available, check that the menus work in secondary windows.

#### Breaking changes

- [x] This PR introduces breaking changes and requires careful review. If yes, the breaking changes section in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) has been updated.

#### Attribution

Contributed on behalf of STMicroelectronics

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/core/src/browser/context-menu-renderer.ts [hunk 1]
```diff
@@ -110,10 +110,10 @@ export interface RenderContextMenuOptions {
      */
     includeAnchorArg?: boolean;
     /**
-     * A DOM context to use when evaluating any `when` clauses
-     * of menu items registered for this item.
+     * A DOM context for the menu to be shown
+     * Will be used to attach the menu to a window and to evaluate enablement ("when"-clauses)
      */
-    context?: HTMLElement;
```
Comment (jonah-iden) [inline packages/core/src/browser/context-menu-renderer.ts:116]: If `window.document.body` is a valid working context, why not just keep this element optional and make `window.document.body` the default value?

Comment (sdirix) [reply packages/core/src/browser/context-menu-renderer.ts:116]: If it's optional it's easy to forget and the secondary window usage could break. The caller should always indicate where they want the context menu to appear and then only fallback to `document.body` if they don't have a better choice

Comment (jonah-iden) [reply packages/core/src/browser/context-menu-renderer.ts:116]: ok thanks for the explanation. Makes sense to me

**Review by sdirix — APPROVED** [review]
works for me! thanks!
