### PR TITLE
Fix `cancellable` option for `withProgress`

### LINKED ISSUE #5578: (VS Code Extensions) window.withProgress isCancellable is not respected
### Description
`ProgressOptions.isCancellable` is not respected by Theia. The "Cancel" button is always present.

https://code.visualstudio.com/api/references/vscode-api#ProgressOptions

### Reproduction Steps
- call `window.withProgress` setting the `isCancellable` `ProgressOptions` to `false`.
```
        const validateResponse = await vscode.window.withProgress({
            title: `Processing ${pathToBind}...`,
            location: vscode.ProgressLocation.Notification,
            cancellable: false,
        }, () => {
           // ... your callback
        });
```
In VS Code, the Cancel button is not shown if `cancellable: false` is given. In Theia, the Cancel button is always shown.

**OS and Theia version:**
macOS mojave, theia version `next`

**Diagnostics:**

### PR DESCRIPTION
**Pull request by AlexTugarev**
#### What it does

This PR makes the `cancellable` option being considered for `withProgress` notifications.

Fixes #5578

#### How to test

- install https://github.com/AlexTugarev/txt/blob/master/txt-0.0.1.vsix
- call `TXT: Progress` command

Screen Shot 2019-10-10 at 22 40 41

now the `cancellable: false` option should have the same effect as in vscode

Screen Shot 2019-10-10 at 22 10 26

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/plugin-ext/src/main/browser/notification-main.ts [hunk 1]
```diff
@@ -54,7 +54,8 @@ export class NotificationMainImpl implements NotificationMain, Disposable {
     protected mapOptions(options: string | NotificationMain.StartProgressOptions): ProgressMessage {
         const text = typeof options === 'string' ? options : options.title;
         const location = typeof options === 'string' ? 'notification' : options.location;
-        return { text, options: { location, cancelable: true } };
+        const cancelable = typeof options === 'string' ? true : (options.cancellable === undefined || options.cancellable);
```
Comment (akosyakov) [inline packages/plugin-ext/src/main/browser/notification-main.ts]: When do we pass `options` as a string and why when it should cancellable? I could not find any clients.

Comment (AlexTugarev) [reply packages/plugin-ext/src/main/browser/notification-main.ts]: good question... lemme check

Comment (AlexTugarev) [reply packages/plugin-ext/src/main/browser/notification-main.ts]: https://github.com/eclipse-theia/theia/commit/240f67e5216ed30bd99fbc8ea2e7d04c9db3305a#diff-7eea09f2b0c581de589cb87e1127fb80R666

I hope the link works.
I bet, I did want to avoid a braking change :-(

Comment (AlexTugarev) [reply packages/plugin-ext/src/main/browser/notification-main.ts]: Should I clean up and remove from there? Would that then require to make a change log?

Comment (akosyakov) [reply packages/plugin-ext/src/main/browser/notification-main.ts]: I don't think this code is used anywhere. It would be fine to clean up, otherwise it is confusing.

Comment (AlexTugarev) [reply packages/plugin-ext/src/main/browser/notification-main.ts]: this shouldn't break anything. just updated it. waiting to next build.

**Comment by akosyakov** [comment]
thx @AlexTugarev. looks simpler to me, works nicely as well

**Comment by AlexTugarev** [comment]
thanks for reviewing!
