### PR TITLE
Stop dispatching to keybindings in editing coposition text.

### LINKED ISSUE #6459: [editor] chinese input method error
### Description

at theia when I input at input method then backspace it some thing at editor will clear
temp

I test at monaco don't have this bug
temp

### Reproduction Steps
see gif
**OS and Theia version:**
**Diagnostics:**

### PR DESCRIPTION
**Pull request by monaka**
Signed-off-by: Masaki Muranaka <monaka@monami-ya.com>

#### What it does

Ignores `keydown` event when [IME](https://developer.mozilla.org/en-US/docs/Glossary/Input_method_editor) is working.
This will fix #6459 and gitpod-io/gitpod#875 .

#### How to test

Editing texts like the description of #6459. 

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

This patch was tested on my Chrome only.
I suppose this will work also on another modern browsers, but not tested on them.

### CODE REVIEW

**Comment by akosyakov** [comment]
@502647092 Does it fix the issue for you? Could you check please?

**Comment by akosyakov** [comment]
Does it prevent Monaco from receiving composition events? From code it seems that it expects to receive and have special handling logic, i.e. like here https://github.com/microsoft/vscode/commit/31c7e3bb986f8becfdaa285b10bdf8628d009428 Why is not enough to let Monaco to deal with it?

**Comment by monaka** [comment]
And @mouse484 also will be one of the important reviewer.

**Comment by mouse484** [comment]
Expected behavior 👍 

This makes Theia and its associations better for those who need IME.

**Comment by 502647092** [comment]
#6459 is fixed
#6603 not fixed
temp

**Comment by monaka** [comment]
@akosyakov I cannot be sure as I'm not a Monaco specialist.
But I suspect the base version of `@typefox/monaco-editor-core` is old.

The similar issue was raised on VSCode also and fixed by microsoft/vscode#40546.
`src/vs/editor/browser/controller/textAreaInput.ts` was fixed. But there is no same filename in the fork by TypeFox.

**Comment by monaka** [comment]
@502647092 Hmm... I'm using Japanese IME on ChromeOS and it looks working well.
Could you tell me your environment? OS, Browser, and IME.

replace with Japanese IME

**Comment by 502647092** [comment]
@monaka 
Windows10
Chrome
Chinese IME

**Comment by 502647092** [comment]
temp
when I select content and input at IME
editor have two cursor then will freeze
can't input anything 
must reopen it

**Comment by akosyakov** [comment]
> @akosyakov I cannot be sure as I'm not a Monaco specialist.
But I suspect the base version of @typefox/monaco-editor-core is old.

It would be that we need to catch up with Monaco. Maybe it would be feasible at the beginning of next year. I would fine though to accept this PR as a temporary solution if it works.

Here is the explanation why Theia is using custom monaco-editor-core and which other packages are necessary: https://github.com/eclipse-theia/theia/wiki/LSP-and-Monaco-integration

For previous update we used this branch: https://github.com/TypeFox/vscode/tree/monaco/0.18.0.

We will need a new branch which is forked from latest master, tested with upstream with bug fixes provided to upstream, tree shaking should be removed as in previous version, then it should be published for testing and tested with Theia like here https://github.com/eclipse-theia/theia/pull/5901. We have plans to work on auto testing it in mid December and next January to make it easier.

**Comment by monaka** [comment]
@akosyakov I agree it's a best to fixed by upgrading Monaco to the latest. And you might not recognized, this issue is a show-stopper to the Chinese/Japanese/Korean people.
IMO, this is a hot-fix. Users will move to VSCode based services if this issue was left as it.

**Comment by akosyakov** [comment]
@502647092 What do you think? Does it better despite https://github.com/eclipse-theia/theia/pull/6673#issuecomment-560986290? @mouse484 Do you have something like https://github.com/eclipse-theia/theia/pull/6673#issuecomment-560986290?

File: packages/core/src/browser/frontend-application.ts [hunk 1]
```diff
@@ -157,17 +157,30 @@ export class FrontendApplication {
         return startupElements.length === 0 ? undefined : startupElements[0] as HTMLElement;
     }
 
+    protected inComposition = false;
```
Comment (akosyakov) [inline packages/core/src/browser/frontend-application.ts]: please add a comment to this PR that is a temporary fix and should be removed and retested with newer version of Monaco, that we don't forget

**Comment by mouse484** [comment]
@akosyakov 
IME seems to be different depending on country and language.
No problem in Japanese IME.

**Comment by mouse484** [comment]
It may be different from this problem.
use the [chrome input tool](https://chrome.google.com/webstore/detail/google-input-tools/mclkkofklkfljcocdinagocijmpgbhab), I can't input Japanese Chinese etc

**Comment by svenefftinge** [comment]
@502647092 I understood that the freezing exists with or without this change (i.e. https://github.com/eclipse-theia/theia/issues/6603)? 
If that is the case, I'd like to merge this as an interim solution.

**Comment by monaka** [comment]
@mouse484 It's better to raise new issue for your report, IMO. But your report is interesting to me.
Just my guess for now, your report may be a hint to resolve #6603 that @502647092 reported.

**Comment by monaka** [comment]
@svenefftinge #6603 was raised on 14 days ago. And this PR was raised on 4 days ago. 
So at least #6603 was caused with or without this patch.
@502647092 how about [your comment above](https://github.com/eclipse-theia/theia/pull/6673#issuecomment-560986290)?

File: packages/core/src/browser/frontend-application.ts (hunk 1 above)
Comment (monaka) [reply packages/core/src/browser/frontend-application.ts]: I see. I added some comments for clarifying the code is a hotfix.

**Comment by kittaakos** [comment]
As always; beamers never work during the presentations and [hotfixes](https://github.com/eclipse-theia/theia/pull/6673/files#diff-b3c47e20ff0569909accc8030cc40ea8R160) contain typos -> [`Comosition`](https://github.com/eclipse-theia/theia/pull/6673/files#diff-b3c47e20ff0569909accc8030cc40ea8R169) 😊

**Comment by RomanNikitenko** [comment]
@monaka 
I removed this fix within upgrade Monaco to 0.19.3.
Could you test if it works well for https://github.com/eclipse-theia/theia/pull/7149

thanks in advance!

**Comment by akosyakov** [comment]
@502647092 @mouse484 It would help if you also give it a try: https://github.com/eclipse-theia/theia/pull/6673#issuecomment-599944363 🙏

**Comment by mouse484** [comment]
not Fixed in Japanese IME

**Comment by RomanNikitenko** [comment]
> not Fixed in Japanese IME

thanks, will try to reproduce it on my machine and investigate it.
