### PR TITLE
gracefully terminate plugin host process without rpc connection

### LINKED ISSUE #5019: UnhandledPromiseRejectionWarning: Error: Unknown actor CommandRegistryMain
From here https://github.com/theia-ide/theia/issues/4956#issuecomment-485647346

I can see a lot of them on page reload. Maybe some race between shutting down the host process and sending/processing requests.

### LINKED ISSUE #5839: [plugin] Error: Unknown actor WorkspaceMain
I got these when I was verifying #5279.

Steps:
 - Follow the steps from [here](https://github.com/theia-ide/theia/issues/5279#issue-449133288). (In a nutshell, start a Java debug process with VS Code extensions)
 - Refresh your electron browser window.

```
root WARN Plugin contributes items to a menu with invalid identifier: debug/toolBar
root INFO Started watching the git repository: file:///c%3A/Users/kittaakos/dev/maven-demo
root INFO Config file tasks.json does not exist under file:///c%3A/Users/kittaakos/dev/maven-demo
root INFO [nsfw-watcher: 960] Started watching: c:\Users\kittaakos\dev\maven-demo\.theia\launch.json
root INFO [hosted-plugin: 13388] PLUGIN_HOST(13388): PluginManagerExtImpl/init()
root INFO [hosted-plugin: 13388] PLUGIN_HOST(13388): initializing(java@0.47.0 with C:\Users\kittaakos\dev\theia\packages
\plugin-ext-vscode\lib\node/plugin-vscode-init.js)
PLUGIN_HOST(13388): initializing(vscode-java-debug@0.20.0 with C:\Users\kittaakos\dev\theia\packages\plugin-ext-vscode\l
ib\node/plugin-vscode-init.js)
root INFO [hosted-plugin: 13388] Debugger contribution has been registered: java
root INFO [hosted-plugin: 13388] PLUGIN_HOST(13388): PluginManagerExtImpl/loadPlugin(C:\Users\KITTAA~1\AppData\Local\Tem
p\vscode-unpacked\redhat.java-0.47.0.vsix\extension\dist\extension)
root INFO [nsfw-watcher: 960] Started watching: c:\Users\kittaakos\dev\maven-demo\src\test\java\demo\AppTest.java
Started watching: c:\Users\kittaakos\dev\maven-demo\.theia\launch.json
root INFO [nsfw-watcher: 960] Started watching: c:\Users\kittaakos\dev\maven-demo\src\main\java\demo\App.java
root INFO [hosted-plugin: 13388] { message:
   'Starting Java server with: C:\\PROGRA~1\\Java\\JDK18~1.0_1\\bin\\java -Declipse.application=org.eclipse.jdt.ls.core.
id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=UTF-8 -DwatchPa
rentProcess=false -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -jar C:\\Users\\KITTAA~1\\AppData\\Local\\Te
mp\\vscode-unpacked\\redhat.java-0.47.0.vsix\\extension\\server\\plugins\\org.eclipse.equinox.launcher_1.5.500.v20190715
-1310.jar -configuration C:\\Users\\KITTAA~1\\AppData\\Local\\Temp\\vscode-unpacked\\redhat.java-0.47.0.vsix\\extension\
\server\\config_win -data C:\\Users\\kittaakos\\AppData\\Roaming\\.theia\\workspace-storage\\fa1b2a6a67bcc2e6af7fd211d4a
a4915\\redhat.java\\jdt_ws',
  level: 'info',
  timestamp: '2019-08-02 08:49:43.692' }
root INFO [hosted-plugin: 13388] PLUGIN_HOST(13388): PluginManagerExtImpl/loadPlugin(C:\Users\KITTAA~1\AppData\Local\Tem
p\vscode-unpacked\vscjava.vscode-java-debug-0.20.0.vsix\extension\dist\extension)
root INFO [hosted-plugin: 13388] Debug configuration provider has been registered: java
root INFO [hosted-plugin: 13388] settings: {"maxStringLength":0,"showStaticVariables":false,"showQualifiedNames":false,"
showHex":false,"showLogicalStructure":true,"showToString":true,"logLevel":"WARNING","javaHome":"C:\\PROGRA~1\\Java\\JDK1
8~1.0_1","hotCodeReplace":"manual"}
root INFO Stopped watching the git repository: file:///c%3A/Users/kittaakos/dev/maven-demo
root INFO [nsfw-watcher: 12052] Started watching: c:\Users\kittaakos\.theia
root INFO Using Git [2.22.0.rc3.windows.1] from the PATH. (C:\Program Files\Git\cmd\git.exe)
root INFO [nsfw-watcher: 12052] Started watching: c:\Users\kittaakos\dev\maven-demo
root WARN Collided keybinding is ignored;  {"command":"outlineView:toggle","keybinding":"ctrlcmd+shift+s"}  collided wit
h  {"command":"file.saveAs","keybinding":"ctrl+shift+s"}
root WARN Could not register keybinding:
  {"command":"outlineView:toggle","keybinding":"ctrlcmd+shift+s"}
Error: "ctrlcmd+shift+s" is in collision with something else [scope:0]
root WARN Collided keybinding is ignored;  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}  c
ollided with  {"command":"terminal:clear","keybinding":"ctrlcmd+k","context":"terminalActive"}
root WARN Could not register keybinding:
  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}
Error: "ctrl+k" is in collision with something else [scope:0]
root WARN TabBarToolbarRegistry.onStart is slow, took: 168.7000000383705 ms
root WARN ElectronMenuContribution.onStart is slow, took: 159.8000000230968 ms
root WARN LanguagesFrontendContribution.onStart is slow, took: 684.9999999976717 ms
root INFO [nsfw-watcher: 12052] Started watching: c:\Users\kittaakos\dev\maven-demo
root WARN EditorNavigationContribution.onStart is slow, took: 2547.8000000002794 ms
root WARN Couldn't restore widget state for debug-console. Error: TypeError: Cannot read property 'getControl' of undefi
ned
root ERROR [hosted-plugin: 13388] Promise rejection not handled in one second: Error: Unknown actor WorkspaceMain
With stack trace: Error: Unknown actor WorkspaceMain
    at RPCProtocolImpl.doInvokeHandler (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:200:19)
    at RPCProtocolImpl.invokeHandler (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:192:41)
    at RPCProtocolImpl.receiveRequest (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:154:45)
    at RPCProtocolImpl.receiveOneMessage (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:123:2
2)
    at C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:55:89
    at C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:233:17
    at C:\Users\kittaakos\dev\theia\packages\core\lib\common\event.js:161:33
    at CallbackList.invoke (C:\Users\kittaakos\dev\theia\packages\core\lib\common\event.js:176:39)
    at Emitter.fire (C:\Users\kittaakos\dev\theia\packages\core\lib\common\event.js:264:29)
    at ChildProcess.<anonymous> (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\hosted\node\hosted-plugin-process.
js:145:21)
Promise rejection not handled in one second: Error: Unknown actor WorkspaceMain
With stack trace: Error: Unknown actor WorkspaceMain
    at RPCProtocolImpl.doInvokeHandler (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:200:19)
    at RPCProtocolImpl.invokeHandler (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:192:41)
    at RPCProtocolImpl.receiveRequest (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:154:45)
    at RPCProtocolImpl.receiveOneMessage (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:123:2
2)
    at C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:55:89
    at C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:233:17
    at C:\Users\kittaakos\dev\theia\packages\core\lib\common\event.js:161:33
    at CallbackList.invoke (C:\Users\kittaakos\dev\theia\packages\core\lib\common\event.js:176:39)
    at Emitter.fire (C:\Users\kittaakos\dev\theia\packages\core\lib\common\event.js:264:29)
    at ChildProcess.<anonymous> (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\hosted\node\hosted-plugin-process.
js:145:21)
Promise rejection not handled in one second: Error: Unknown actor WorkspaceMain
With stack trace: Error: Unknown actor WorkspaceMain
    at RPCProtocolImpl.doInvokeHandler (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:200:19)
    at RPCProtocolImpl.invokeHandler (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:192:41)
    at RPCProtocolImpl.receiveRequest (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:154:45)
    at RPCProtocolImpl.receiveOneMessage (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:123:2
2)
    at C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:55:89
    at C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:233:17
    at C:\Users\kittaakos\dev\theia\packages\core\lib\common\event.js:161:33
    at CallbackList.invoke (C:\Users\kittaakos\dev\theia\packages\core\lib\common\event.js:176:39)
    at Emitter.fire (C:\Users\kittaakos\dev\theia\packages\core\lib\common\event.js:264:29)
    at ChildProcess.<anonymous> (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\hosted\node\hosted-plugin-process.
js:145:21)
Promise rejection not handled in one second: Error: Unknown actor WorkspaceMain
With stack trace: Error: Unknown actor WorkspaceMain
    at RPCProtocolImpl.doInvokeHandler (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:200:19)
    at RPCProtocolImpl.invokeHandler (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:192:41)
    at RPCProtocolImpl.receiveRequest (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:154:45)
    at RPCProtocolImpl.receiveOneMessage (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:123:2
2)
    at C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:55:89
    at C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:233:17
    at C:\Users\kittaakos\dev\theia\packages\core\lib\common\event.js:161:33
    at CallbackList.invoke (C:\Users\kittaakos\dev\theia\packages\core\lib\common\event.js:176:39)
    at Emitter.fire (C:\Users\kittaakos\dev\theia\packages\core\lib\common\event.js:264:29)
    at ChildProcess.<anonymous> (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\hosted\node\hosted-plugin-process.
js:145:21)
Promise rejection not handled in one second: Error: Unknown actor WorkspaceMain
With stack trace: Error: Unknown actor WorkspaceMain
    at RPCProtocolImpl.doInvokeHandler (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:200:19)
    at RPCProtocolImpl.invokeHandler (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:192:41)
    at RPCProtocolImpl.receiveRequest (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:154:45)
    at RPCProtocolImpl.receiveOneMessage (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:123:2
2)
    at C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:55:89
    at C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:233:17
    at C:\Users\kittaakos\dev\theia\packages\core\lib\common\event.js:161:33
    at CallbackList.invoke (C:\Users\kittaakos\dev\theia\packages\core\lib\common\event.js:176:39)
    at Emitter.fire (C:\Users\kittaakos\dev\theia\packages\core\lib\common\event.js:264:29)
    at ChildProcess.<anonymous> (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\hosted\node\hosted-plugin-process.
js:145:21)
Promise rejection not handled in one second: Error: Unknown actor WorkspaceMain
With stack trace: Error: Unknown actor WorkspaceMain
    at RPCProtocolImpl.doInvokeHandler (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:200:19)
    at RPCProtocolImpl.invokeHandler (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:192:41)
    at RPCProtocolImpl.receiveRequest (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:154:45)
    at RPCProtocolImpl.receiveOneMessage (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:123:2
2)
    at C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:55:89
    at C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\api\rpc-protocol.js:233:17
    at C:\Users\kittaakos\dev\theia\packages\core\lib\common\event.js:161:33
    at CallbackList.invoke (C:\Users\kittaakos\dev\theia\packages\core\lib\common\event.js:176:39)
    at Emitter.fire (C:\Users\kittaakos\dev\theia\packages\core\lib\common\event.js:264:29)
    at ChildProcess.<anonymous> (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\hosted\node\hosted-plugin-process.
js:145:21)
```

### LINKED ISSUE #6677: [vscode] hosted-plugin error thrown when closing frontend instance
**Description**

An uncaught error is thrown when a Theia instance is closed with a plugin present (due to the output channel):

```
root ERROR [hosted-plugin: 12222] Promise rejection not handled in one second: Error: Unknown actor OutputChannelRegistryMain , reason: Error: Unknown actor OutputChannelRegistryMain
```

```
root ERROR [hosted-plugin: 12222] With stack trace: Error: Unknown actor OutputChannelRegistryMain\n
    at RPCProtocolImpl.doInvokeHandler (/home/evinfug/theia-workspace/theia/packages/plugin-ext/lib/common/rpc-protocol.js:249:19)\n
    at RPCProtocolImpl.invokeHandler (/home/evinfug/theia-workspace/theia/packages/plugin-ext/lib/common/rpc-protocol.js:240:41)\n
    at RPCProtocolImpl.receiveRequest (/home/evinfug/theia-workspace/theia/packages/plugin-ext/lib/common/rpc-protocol.js:204:31)\n
    at RPCProtocolImpl.receiveOneMessage (/home/evinfug/theia-workspace/theia/packages/plugin-ext/lib/common/rpc-protocol.js:173:22)\n
    at /home/evinfug/theia-workspace/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109\n
    at /home/evinfug/theia-workspace/theia/packages/plugin-ext/lib/common/rpc-protocol.js:280:17\n
    at /home/evinfug/theia-workspace/theia/packages/core/lib/common/event.js:162:33\n
    at CallbackList.invoke (/home/evinfug/theia-workspace/theia/packages/core/lib/common/event.js:177:39)\n
    at Emitter.fire (/home/evinfug/theia-workspace/theia/packages/core/lib/common/event.js:265:29)\n
    at ChildProcess.<anonymous> (/home/evinfug/theia-workspace/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)

```

**How to test:**
1. start the application using a plugin (ex: `@theia/vscode-builtin-git`)
2. close the browser instance
3. notice the logs on the backend

### LINKED ISSUE #7113: Error: kill ESRCH when starting, restarting frontend app with the go and yaml VS Code LS extension
### Description
 

I can see occasional `kill ERSCH` error when running (start/restart) Theia with the `go` and `yaml` VS Code LS extensions:

```json
  "theiaPlugins": {
    "vscode-go": "https://github.com/microsoft/vscode-go/releases/download/0.12.0/Go-0.12.0.vsix",
    "redhat.vscode-yaml": "https://github.com/redhat-developer/vscode-yaml/releases/download/0.7.1-prerelease/redhat.vscode-yaml-0.7.1-prerelease.vsix"
}
```

Error:
```
root ERROR Uncaught Exception:  Error: kill ESRCH
root ERROR Error: kill ESRCH
    at process.kill (internal/process/per_thread.js:198:13)
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/hosted/node/hosted-plugin-process.js:140:25
    at Array.forEach (<anonymous>)
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/hosted/node/hosted-plugin-process.js:139:28
    at /Users/akos.kitta/path/to/my/project/node_modules/ps-tree/index.js:87:7
    at Stream.a.end (/Users/akos.kitta/path/to/my/project/node_modules/event-stream/index.js:87:5)
    at Stream.onend (internal/streams/legacy.js:42:10)
    at Stream.emit (events.js:194:15)
    at end (/Users/akos.kitta/path/to/my/project/node_modules/map-stream/index.js:116:39)
    at Stream.stream.end (/Users/akos.kitta/path/to/my/project/node_modules/map-stream/index.js:122:5)
root ERROR [hosted-plugin: 23847] Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
root ERROR [hosted-plugin: 23847] With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
root ERROR [hosted-plugin: 23847] Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
root ERROR [hosted-plugin: 23847] Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
root INFO Detected keyboard layout from browser API: US (Mac)
root WARN Collided keybinding is ignored;  {"command":"editor.action.startFindReplaceAction","keybinding":"meta+alt+f","when":null}  collided with  {"command":"core.replace","keybinding":"ctrlcmd+alt+f"}
root WARN Could not register keybinding:
```

### Reproduction Steps

I do not have the exact steps for the issue, but it seems, we try to kill a process or process-group with a `PID` that does not exist.

**OS and Theia version:**

**Diagnostics:**

### LINKED ISSUE #7176: Error: `Unknown actor YourServiceName` when refreshing the browser window
### Description
 

Happened when verifying https://github.com/eclipse-theia/theia/pull/5167.
I can see a lot of `Unknown actor ServiceName` error in the console after refreshing the browser.

Steps to reproduce:
 - Build and start Theia from the source, open Theia in your workspace. I used this commit 00c1747c9.
 - Open `.node_modules/@theia/api-tests/src/browser-utils.spec.js` in an editor. Note, it's from `node_modules`.
 - I see the first error:
```
root ERROR [hosted-plugin: 92909] Error: Possible Emitter memory leak detected. 31 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:253:26)
    at PreferenceRegistryExtImpl._event.Object.assign.maxListeners [as onDidChangeConfiguration] (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:221:27)
    at Object.onDidChangeConfiguration (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/plugin/plugin-context.js:387:46)
    at b.hookConfigurationChanged (/Users/akos.kitta/git/theia/plugins/vscode-eslint/extension/client/out/extension.js:1:65825)
    at e.initialize.then.t (/Users/akos.kitta/git/theia/plugins/vscode-eslint/extension/client/out/extension.js:1:60594)
root ERROR [hosted-plugin: 92909] Error: Possible Emitter memory leak detected. 32 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:253:26)
    at PreferenceRegistryExtImpl._event.Object.assign.maxListeners [as onDidChangeConfiguration] (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:221:27)
    at Object.onDidChangeConfiguration (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/plugin/plugin-context.js:387:46)
    at V.register (/Users/akos.kitta/git/theia/plugins/vscode-eslint/extension/client/out/extension.js:1:48061)
    at Promise (/Users/akos.kitta/git/theia/plugins/vscode-eslint/extension/client/out/extension.js:1:68963)
    at new Promise (<anonymous>)
    at b.handleRegistrationRequest (/Users/akos.kitta/git/theia/plugins/vscode-eslint/extension/client/out/extension.js:1:68621)
    at e.onRequest.e (/Users/akos.kitta/git/theia/plugins/vscode-eslint/extension/client/out/extension.js:1:60165)
    at /Users/akos.kitta/git/theia/plugins/vscode-eslint/extension/client/out/extension.js:1:7804
    at /Users/akos.kitta/git/theia/plugins/vscode-eslint/extension/client/out/extension.js:1:8842
root ERROR [hosted-plugin: 92909] Promise rejection not handled in one second: TypeError: r.languages.registerSelectionRangeProvider is not a function , reason: TypeError: r.languages.registerSelectionRangeProvider is not a function
root ERROR [hosted-plugin: 92909] With stack trace: TypeError: r.languages.registerSelectionRangeProvider is not a function
    at s.VersionDependentRegistration [as _doRegister] (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:165417)
    at s.update (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:12072)
    at t.VersionDependentRegistration.update (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:12541)
    at new t.VersionDependentRegistration (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:12340)
    at Object.t.register (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:165351)
    at Promise.all.Promise.resolve.then.then.t (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:122930)
    at process._tickCallback (internal/process/next_tick.js:68:7)
root ERROR [hosted-plugin: 92909] Promise rejection not handled in one second: TypeError: r.languages.registerSelectionRangeProvider is not a function , reason: TypeError: r.languages.registerSelectionRangeProvider is not a function
With stack trace: TypeError: r.languages.registerSelectionRangeProvider is not a function
    at s.VersionDependentRegistration [as _doRegister] (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:165417)
    at s.update (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:12072)
    at t.VersionDependentRegistration.update (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:12541)
    at new t.VersionDependentRegistration (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:12340)
    at Object.t.register (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:165351)
    at Promise.all.Promise.resolve.then.then.t (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:122930)
    at process._tickCallback (internal/process/next_tick.js:68:7)
root ERROR [hosted-plugin: 92909] Promise rejection not handled in one second: undefined , reason: undefine
```

Close the editor and refresh the browser window:
```
Promise rejection not
root ERROR [hosted-plugin: 92812] handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor StatusBarMessageRegistryMain , reason: Error: Unknown actor StatusBarMessageRegistryMain
With stack trace: Error: Unknown actor StatusBarMessageRegistryMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plu
root ERROR [hosted-plugin: 92812] gin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor WorkspaceMain , reason: Error: Unknown actor WorkspaceMain
With stack trace: Error: Unknown actor WorkspaceMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor CommandRegistryMain , reason: Error: Unknown actor CommandRegistryMain
With stack trace: Error: Unknown actor CommandRegistryMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor CommandRegistryMain , reason: Error: Unknown actor CommandRegistryMain
With stack trace: Error: Unknown actor CommandRegistryMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
root ERROR [hosted-plugin: 92812] at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor TasksMain , reason: Error: Unknown actor TasksMain
With stack trace: Error: Unknown actor TasksMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor TasksMain , reason: Error: Unknown actor TasksMain
With stack trace: Error: Unknown actor TasksMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor TasksMain , reason: Error: Unknown actor TasksMain
With stack trace: Error: Unknown actor TasksMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
```

Note, I have truncated the stack trace 👆, it was more than 2k lines. I can consistently reproduce it.

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

fix #7176, fix #5019, fix #5839, fix #6677, fix #7113

The issue arises when there are pending requests in the plugin host process and the main side is already gone (which is basically always on reload). For some reasons we create a new RPC protocol which is not capable of handling such pending requests to stop plugins.

Instead of creating new protocol this PR adds new control messages:
- terminate to ask the plugin host process to shutdown rpc connection and deactivate all plugins as much as possible
- terminated to get notified when the host process is done to kill it and its children
- all other communications are prohibited during termination, since there is nobody to talk to and it will for sure fail

It fixes the issue with massive amount of error logging produced on each reload, around 2K lines.
For instance, I checked Gitpod logs for last 7 days and first 3 of 5 most frequent errors are incarnation of this issue.

It as well improves stopping of plugins, since deactivation of VS Code extension can happen asynchronous, but we were not handling it.
In addition, now the plugin host process has a chance to kill child processes on its own (by disposing RPCProtocol) without relying on Theia backend.

#### How to test

- Reload the page while causing extensive communication with the plugin host process, i.e. debug something, use language features causing many diagnostics and so on.
- Check that backend logs don't have any errors about unknown actors or closed connections from the plugin host process. There can be some errors from concrete plugins though, but they should be rare.
- Check that the plugin host process is shutdown and all its children, i.e. if you debug something, you should debug it again on reload, ports should not be occupied. Use system tools to explore process trees, i.e. `ps -auxf` on linux.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
@kittaakos Could you check please whether you can reproduce #7113 with it?

File: packages/plugin-ext/src/hosted/node/plugin-host-rpc.ts [hunk 1]
```diff
@@ -76,6 +76,10 @@ export class PluginHostRPC {
         );
     }
 
+    async terminate(): Promise<void> {
```
Comment (benoitf) [inline packages/plugin-ext/src/hosted/node/plugin-host-rpc.ts]: Hello is it needed ?
as plugin-manager is available in the RPC ?

File: packages/plugin-ext/src/hosted/node/plugin-host.ts [hunk 2]
```diff
@@ -67,19 +71,37 @@ process.on('rejectionHandled', (promise: Promise<any>) => {
...
+        return;
+    }
     try {
-        emitter.fire(JSON.parse(message));
+        const msg = JSON.parse(message);
+        if ('type' in msg && msg.type === MessageType.Terminate) {
+            terminating = true;
+            emitter.dispose();
+            await Promise.race([
+                pluginHostRPC.terminate(),
```
Comment (benoitf) [inline packages/plugin-ext/src/hosted/node/plugin-host.ts]: Could we send order directly to pluginManager through RPC  getProxy(`MAIN_RPC_CONTEXT.HOSTED_PLUGIN_MANAGER_EXT`) ?

Comment (akosyakov) [reply packages/plugin-ext/src/hosted/node/plugin-host.ts]: I thought it makes sense from lifecycle perspective to handle inside `PluginHostRPC`, since it is responsible to create the manager, it should be responsible to terminate it.

File: packages/plugin-ext/src/hosted/node/plugin-host-rpc.ts (hunk 1 above)
Comment (akosyakov) [reply packages/plugin-ext/src/hosted/node/plugin-host-rpc.ts]: yes, but it is created by this class

File: packages/plugin-ext/src/hosted/node/plugin-host.ts [hunk 3]
```diff
@@ -67,19 +71,37 @@ process.on('rejectionHandled', (promise: Promise<any>) => {
...
+                new Promise(resolve => setTimeout(resolve, 4 * 1000))
```
Comment (benoitf) [inline packages/plugin-ext/src/hosted/node/plugin-host.ts]: could we make this delays configurable ?

File: packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts [hunk 4]
```diff
@@ -93,34 +92,42 @@ export class HostedPluginProcess implements ServerPluginRunner {
...
+                waitForTerminated.resolve();
             }
         });
-        const hostedPluginManager = rpc.getProxy(MAIN_RPC_CONTEXT.HOSTED_PLUGIN_MANAGER_EXT);
-        hostedPluginManager.$stop().then(() => {
-            emitter.dispose();
-            this.killProcessTree(cp.pid);
-        });
+        cp.send(JSON.stringify({ type: MessageType.Terminate }));
+        // give 10 seconds to terminate gracefully and then kill the process
```
Comment (benoitf) [inline packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts]: probably allow to be configurable

Comment (akosyakov) [reply packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts]: Should it be possible to disable timeout with 0?

File: packages/plugin-ext/src/plugin/plugin-manager.ts [hunk 5]
```diff
@@ -119,28 +126,58 @@ export class PluginManagerExtImpl implements PluginManagerExt, PluginManager {
...
-    protected stopPlugin(plugin: ActivatedPlugin): void {
+    protected async stopPlugin(id: string, plugin: ActivatedPlugin, options: StopOptions = { terminating: false }): Promise<void> {
+        let result;
         if (plugin.stopFn) {
-            plugin.stopFn();
+            try {
+                result = plugin.stopFn();
+            } catch (e) {
+                if (!options.terminating) {
+                    console.error(`[${id}]: failed to stop:`, e);
```
Comment (benoitf) [inline packages/plugin-ext/src/plugin/plugin-manager.ts]: there is a logger in that class, probably better to use it.

File: packages/plugin-ext/src/hosted/node/plugin-host.ts (hunk 2 above)
Comment (benoitf) [reply packages/plugin-ext/src/hosted/node/plugin-host.ts]: yes make sense

File: packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts (hunk 4 above)
Comment (benoitf) [reply packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts]: yes, might be interesting 👍

File: packages/plugin-ext/src/plugin/plugin-manager.ts (hunk 5 above)
Comment (akosyakov) [reply packages/plugin-ext/src/plugin/plugin-manager.ts]: I don't think the plugin host process has access to the logger. But maybe i'm overlooking something.

File: packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts [hunk 6]
```diff
@@ -93,34 +92,42 @@ export class HostedPluginProcess implements ServerPluginRunner {
...
     }
 
+    protected killProcess(pid: number): void {
+        try {
+            process.kill(pid);
+        } catch (e) {
+            if (e && 'code' in e && e.code === 'ESRCH') {
+                return;
+            }
+            console.error(`[${pid}] failed to kill`, e);
```
Comment (benoitf) [inline packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts]: sorry, it was there for logger instead of console.error

File: packages/plugin-ext/src/plugin/plugin-manager.ts (hunk 5 above)
Comment (benoitf) [reply packages/plugin-ext/src/plugin/plugin-manager.ts]: I make comment on the wrong console.error line

File: packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts (hunk 6 above)
Comment (akosyakov) [reply packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts]: ok, will use here

File: packages/plugin-ext/src/plugin/plugin-manager.ts (hunk 5 above)
Comment (akosyakov) [reply packages/plugin-ext/src/plugin/plugin-manager.ts]: acknowledged :)

**Comment by benoitf** [comment]
looks very nice 👍

**Comment by akosyakov** [comment]
@benoitf thanks! I will update the PR and ping you again

**Comment by akosyakov** [comment]
@benoitf About configurable timeouts, env variables should work? i.e. users for them are adopters, not end users. It is not feasible to configure it via preferences since the user session is not always available (i.e. during page reload we cannot read them) and I'm not sure that it is desirable to give control over them to end users.

**Comment by benoitf** [comment]
@akosyakov yes sure I was more thinking a setting of the product (not user preferences)

**Comment by akosyakov** [comment]
@benoitf I've pushed again:
- logger is used now
- there are new ENV variables and cli options to control plugin host termination timeout as well as timeout of stopping plugin host services

**Comment by akosyakov** [comment]
@benoitf I will merge on Monday
