### PR TITLE
preferences: Fix search term on open via menu

### LINKED ISSUE #9931: Opening the preferences menu via menu automatically sets a search term
### Bug Description:

When opening the preferences menu via the menu action like this, Theia automatically places `[object Object]` into the search bar, resulting in no preferences being found. This was probably introduced by #9785.

### Steps to Reproduce:

1. Open the preferences menu via the menu action: 
grafik
2. Observe the opened preferences view:
grafik

### Additional Information

- Operating System: Windows
- Theia Version: a6422c3

### PR DESCRIPTION
**Pull request by msujew**
#### What it does
Closes #9931 

Fixes the issue by simply checking for the string type before passing the argument into the search term.

#### How to test

1. Open the preferences menu via the settings menu in the bottom left.
2. Observe an empty search bar

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/core/src/browser/context-menu-renderer.ts [hunk 1]
```diff
@@ -94,15 +94,14 @@ export interface RenderContextMenuOptions {
...
+        let args: any[] | undefined;
         if (Array.isArray(menuPathOrOptions)) {
             menuPath = menuPathOrOptions;
-            args = [anchor!];
         } else {
             menuPath = menuPathOrOptions.menuPath;
             anchor = menuPathOrOptions.anchor;
             onHide = menuPathOrOptions.onHide;
-            args = menuPathOrOptions.args ? [...menuPathOrOptions.args, anchor] : [anchor];
+            args = menuPathOrOptions.args;
```
Comment (colin-grant-work) [inline packages/core/src/browser/context-menu-renderer.ts:104]: I think this change is correct, but I happen to know that I've relied on the existing behavior downstream to distinguish command activations from different sources, and I may not be alone in that. A more limited fix to the specific problem might be to check whether the type of the arg is string before setting it in the search bar of the preferences view.

Comment (msujew) [reply packages/core/src/browser/context-menu-renderer.ts:104]: That was my first thought as well, but that sounds like a workaround, as this issue will repeat itself for any command with a single optional argument. But I guess I can change it that way, if you rely on it. Maybe there's a cleaner solution for that problem?

Comment (colin-grant-work) [reply packages/core/src/browser/context-menu-renderer.ts:104]: I'm OK with removing it - I know where I've relied on it and how to fix it - but it would definitely be a breaking change worth highlighting in the changelog, and I'm not sure that there aren't legitimate uses for it that we'd be cutting off. It's worth being cautious about, because it isn't something that people may realize was questionable behavior, and they won't get much help from TypeScript about it, because command handlers are supposed to expect `any[]`, so changes in what will _actually_ be passed in aren't detected by the type system.

**Review by vince-fugnitto — COMMENTED** [review]
@msujew I confirmed that it fixes the issue with the `preferences`, however I believe it introduces a regression in the following use-case:

_pull-request_:

https://user-images.githubusercontent.com/40359487/130087610-5074c5fe-6b45-46df-854c-93f5c5c4f0da.mp4

_master_:

https://user-images.githubusercontent.com/40359487/130087778-cd10ccee-42e3-4eab-8a5a-dc5c746eb375.mp4

**Comment by colin-grant-work** [comment]
> @msujew I confirmed that it fixes the issue with the `preferences`, however I believe it introduces a regression in the following use-case:

Very timely: there's the legitimate use case for it (maybe - I'm not sure that's how the menu should work...).

**Comment by msujew** [comment]
> however I believe it introduces a regression

Ah, as I thought we rely somewhere on that undocumented behavior. :/

Alright, I'll look for a more localized fix for this issue.

**Review by colin-grant-work — APPROVED** [review]
This solves the problem nicely, and definitely looks like a safer approach. 👍

**Review by vince-fugnitto — APPROVED** [review]
I confirmed that the change fixes the issue on `master` :+1: 
It is also self-contained and does not cause any regressions.
