### PR TITLE
Basic ssh_config support

### LINKED ISSUE #14102: Unable to connect via SSH with keyfile
### Bug Description:

I have a lot of hosts entries in `~/.ssh/config` like this one:
```
Host pc
    Hostname 192.168.100.11
    Port 22
    User shdwchn10
    Compression yes
    IdentityFile ~/.ssh/pc
```

And I'm unable to connect to any of them via Theia (Linux, Appimage). ssh in terminal works fine.

### Steps to Reproduce:

1. Have some systems with `Host` entry in  `~/.ssh/config` file (each system in this file doesn't allow password login)
2. Try to connect to any of them with `username@ip`
3. Error: `Could not open SSH connection to remote. All configured authentication methods failed`
4. Or try to connect with the host name (from `~/.ssh/config`): `pc` and enter username in the second prompt
5. Error: `Could not open SSH connection to remote. getaddrinfo ENOTFOUND pc`
6. If I try to enter just the host name without username in the second prompt (like it works in ssh cli: `ssh pc`) I get this error: `Please enter a user name.`

image
`username@ip` connection error. Error from logs:
```
2024-09-01T16:30:34.013Z root INFO Ended remote connection to host 'shdwchn10@192.168.100.11'
```

image
`pc` connection error (logs are empty)

image
`pc` without username error (logs are empty)

### Additional Information

- Operating System: Fedora Linux 40.20240828.0 (Silverblue)
- Theia Version: 1.52.0

### PR DESCRIPTION
**Pull request by KnowZero**
#### What it does

Very basic support for ssh_config files and quick access to ssh_config hosts.

Currently only Host, Hostname, Port, User, and IdentityFile is supported. With Host allowing some wildcards which can be accessed through %h

## Step 1: 

Create an sh file with the following and run it, it will generate  a ssh_config file and docker files and ssh keys to test with:

```
#!/bin/bash

# create docker-compose file
cat > ./docker-compose.yml << EOF
version: '3.8'
services:
    theia_ssh1:
        build:
            context: .
            args:
                SSH_PORT: "2221"
        ports:
            - 2221:2221
EOF

# create docker file with ssh server
cat > ./Dockerfile << \EOF
FROM ubuntu:latest
ARG SSH_PORT
RUN  mkdir ~/.ssh && apt-get update && apt-get install -y openssh-server xz-utils


COPY ./id_rsa.pub /root/.ssh/authorized_keys
RUN mkdir /var/run/sshd
RUN echo 'root:password' | chpasswd


RUN echo "PORT=${SSH_PORT}" \
    && sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config \
    && sed -i "s/#Port 22/Port ${SSH_PORT}/" /etc/ssh/sshd_config

    
CMD ["/usr/sbin/sshd", "-D"]
EOF

# create ssh_config file file
cat > ./ssh_config << EOF
Host localhost
    Port 2221
    User root
Host test1
    Hostname 127.0.0.1
    Port 2221
Host test2_*
    Hostname %h.0.0.1
    Port 2221
Host test3_?
    Hostname 127.0.0.%h
    User root
    Compression yes
    Port 2221
Host test4
    Hostname 127.0.0.1
    Port 2221
    IdentityFile ${PWD}/id_rsa 

EOF

#generate key
ssh-keygen -t rsa -f "${PWD}/id_rsa" -q -P ""
```
## Step 2:

set `remote.ssh.configFile` setting to point to config file generated

## Step 3:

docker-compuse up

## Step 4:

When connecting to remote host, you can either access them via typing like `test1` or pick it in the quick access menu(Connect Current Window to Host in Config File). You can also do things like `root@test1`, default password is `password`. You can also test wildcard via `root@test2_127` ,  `test3_1` shows single character wildcard and `test4` is key login without password 

#### Follow-ups

Partly fixes #14102 and #14289

@jonah-iden 

#### Breaking changes

- [ ] This PR introduces breaking changes and requires careful review. If yes, the breaking changes section in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) has been updated.

#### Review checklist

- [ ] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/remote/src/electron-node/ssh/remote-ssh-connection-provider.ts [hunk 1]
```diff
@@ -53,14 +55,69 @@ export class RemoteSSHConnectionProviderImpl implements RemoteSSHConnectionProvi
     protected passwordRetryCount = 3;
     protected passphraseRetryCount = 3;
 
+    async matchSSHConfigHost(host: string, user?: string, customConfigFile?: string): Promise<Record<string, string[]> | undefined> {
+        const sshConfig = await this.getSSHConfig(customConfigFile);
+
+        for (const record of sshConfig) {
+            if (record.host) {
+                const checkHost = new RegExp('^' + (record.host[0])
```
Comment (jonah-iden) [inline packages/remote/src/electron-node/ssh/remote-ssh-connection-provider.ts:63]: could you maybe add a comment here to explain what this does. Its quite hard to grasp just by reading

File: packages/remote/src/electron-node/ssh/remote-ssh-connection-provider.ts [hunk 2]
```diff
@@ -53,14 +55,69 @@ export class RemoteSSHConnectionProviderImpl implements RemoteSSHConnectionProvi
...
+            }
+        }
+    }
+
+    async getSSHConfig(customConfigFile?: string): Promise<Array<Record<string, string[]>>> {
+        const sshConfigFilePath = customConfigFile || path.join(os.homedir(), '.ssh', 'config');
+        const buff: Buffer = await fs.promises.readFile(sshConfigFilePath);
+
+        let record: Record<string, string[]> = {};
+        const records: Record<string, string[]>[] = [];
```
Comment (jonah-iden) [inline packages/remote/src/electron-node/ssh/remote-ssh-connection-provider.ts:84]: why not use something like [ssh-config](https://www.npmjs.com/package/ssh-config) to do the parsing? That would make it easier on our side to maintain

File: packages/remote/src/electron-browser/remote-preferences.ts [hunk 3]
```diff
@@ -41,11 +41,20 @@ export const RemotePreferenceSchema: PreferenceSchema = {
                 'Controls the template used to download the node.js binaries for the remote backend. Points to the official node.js website by default. Uses multiple placeholders:'
             ) + '\n- ' + nodeDownloadTemplateParts.join('\n- ')
         },
+        'remote.ssh.configFile': {
+            type: 'string',
+            default: '',
```
Comment (jonah-iden) [inline packages/remote/src/electron-browser/remote-preferences.ts:46]: wouldn't a default value be nice either here or when reading this preference. Like userdir/.ssh/ssh_config

Comment (jonah-iden) [reply packages/remote/src/electron-browser/remote-preferences.ts:46]: this would of course need to be os dependent. You could use the variables from theia-core `os.ts` for this

**Comment by jonah-iden** [comment]
Hi, thanks for the contribution. It works great. I left a few suggestions.
Also it seems you havn't [signed the eca](https://accounts.eclipse.org/user/eca) yet. Would be great if you could do that otherwise we can not merge this for legal reasons

File: packages/remote/src/electron-node/ssh/remote-ssh-connection-provider.ts (hunk 2 above)
Comment (KnowZero) [reply packages/remote/src/electron-node/ssh/remote-ssh-connection-provider.ts:84]: I didn't know what the procedure was for adding an additional library be it licensing or code review of the library so I played it safe. If it is fine, I can use it.

**Comment by KnowZero** [comment]
> Hi, thanks for the contribution. It works great. I left a few suggestions. Also it seems you havn't [signed the eca](https://accounts.eclipse.org/user/eca) yet. Would be great if you could do that otherwise we can not merge this for legal reasons

I definitely signed it, same way I signed it before. It's weird/ Clicking it, it seems the sign verification is down?

File: packages/remote/src/electron-node/ssh/remote-ssh-connection-provider.ts (hunk 2 above)
Comment (jonah-iden) [reply packages/remote/src/electron-node/ssh/remote-ssh-connection-provider.ts:84]: makes sense. As long as its not some tiny obscure library we normally don't do any code review of the library itself. 
Regarding licences there is te 3pp licence check action which checks the license. Should it not be able to determine the licence by itself we would need to make a request to eclipse legal team https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues. I would take care of that. There was a way to create this automaticly. And since its MIT that issue should also be resolved relatively quick and automaticly by them

**Comment by jonah-iden** [comment]
> I definitely signed it, same way I signed it before. It's weird/ Clicking it, it seems the sign verification is down?

I was also under the asumption you did. 
Doesn't seem to be down. I revalidated it and still seems to fail. 
When you look at https://api.eclipse.org/git/eca/status/gh/eclipse-theia/theia/15499 ther are some troubleshooting steps, could you check those

**Comment by KnowZero** [comment]
> > Doesn't seem to be down. I revalidated it and still seems to fail.
> 
> sorry i take that back. There actually seems to be a problem at eclipse right now with the eca validation

Validation seems to be fixed so I revalidated it

File: packages/remote/src/electron-node/ssh/remote-ssh-connection-provider.ts (hunk 2 above)
Comment (KnowZero) [reply packages/remote/src/electron-node/ssh/remote-ssh-connection-provider.ts:84]: So I should switch to the ssh-config library?

Comment (jonah-iden) [reply packages/remote/src/electron-node/ssh/remote-ssh-connection-provider.ts:84]: yeah i think that would be good

**Comment by KnowZero** [comment]
@ jonah-iden Okay, I implemented ssh-config

File: packages/remote/src/electron-browser/remote-preferences.ts (hunk 3 above)
Comment (KnowZero) [reply packages/remote/src/electron-browser/remote-preferences.ts]: I went with:
```
OS.backend.isWindows ? '${env:USERPROFILE}\\.ssh\\config' : '${env:HOME}/.ssh/config'
```
This also allows env variables to be used in the path.

**Review by jonah-iden — APPROVED** [review]
I did a few smaller improvements for the usage of SSH config. Hope that was ok. But this looks good to me now.
