### PR TITLE
11442: Use named pipes for inter-process RPC communication

### LINKED ISSUE #11390: Can't watch file change when start without --no-cluster flag
### Bug Description:
Can't watch file change

### Steps to Reproduce:
1. yarn browser start
2. Enable verbose file watching logs.
image
3. modify test.txt
4. no log output
change-file-demo-1
5. yarn browser start --no-cluster
6. modify test.txt
7. log output
change-file-demo-2

### Additional Information

- Operating System: win10
- Theia Version: master, commit 97ce5f89eccf866fdd2058c20b50a8271204790f
- Node：14.19.1

### LINKED ISSUE #11442: File watching broken on Windows
### Steps to Reproduce:

1. Open application with `theia` as workspace and open Navigator.
2. Observe that `.git` is not displayed in the navigator.
3. Open preferences, search for `files.exclude`, click `Edit in JSON` link.
4. Set the value for the `"**/.git"` field to `false`.
5. Observe that the `.git` folder doesn't immediately appear.
6. Reload the application.
7. Observe the `.git` folder does appear in the Navigator.

### Additional Information

- Operating System: Windows 10, Firefox
- Theia Version: 78b7f9558bc35c2f0283e098191f1b24af2721e3

### PR DESCRIPTION
**Pull request by tortmayr**
#### What it does

Refactors `IPCChannel` to use named pipe communication via sockets. Previously we used an extra process pipe on top of the standard pipes (stdin,stdout,sdterr,ipc) which does not work reliably under windows. Switching to named pipe communication ensures that inter process RPC communication works reliably on all platforms.

Fixes #11442
Fixes #11390

Contributed on behalf of STMicroelectronics

#### How to test

Check that the bugs descriped in https://github.com/eclipse-theia/theia/issues/11390 and  https://github.com/eclipse-theia/theia/issues/11442#issue-1309856089  no longer occur .
**Important**: In order to launch the file watcher in a separate process the Theia application needs to be started without the `--no-cluster` flag . 

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/core/src/node/messaging/ipc-channel.ts [hunk 1]
```diff
@@ -49,12 +48,13 @@ export class IPCChannel implements Channel {
...
     protected ipcErrorListener: (error: Error) => void = error => this.onErrorEmitter.fire(error);
 
-    constructor(childProcess?: cp.ChildProcess) {
+    constructor(socket: Socket, childProcess?: cp.ChildProcess) {
         if (childProcess) {
             this.setupChildProcess(childProcess);
         } else {
             this.setupProcess();
         }
+        this.messagePipe = new BinaryMessagePipe(socket);
```
Comment (paul-marechal) [inline packages/core/src/node/messaging/ipc-channel.ts:57]: Do we really need a `Socket`, or is `Duplex` enough here?

```suggestion
    constructor(connection: Duplex, childProcess?: cp.ChildProcess) {
        if (childProcess) {
            this.setupChildProcess(childProcess);
        } else {
            this.setupProcess();
        }
        this.messagePipe = new BinaryMessagePipe(connection);
```

File: packages/core/src/node/messaging/ipc-bootstrap.ts [hunk 2]
```diff
@@ -22,6 +24,10 @@ import { checkParentAlive, IPCEntryPoint } from './ipc-protocol';
 checkParentAlive();
 
 const entryPoint = IPCEntryPoint.getScriptFromEnv();
+const ipcServer = process.argv[process.argv.length - 1];
```
Comment (paul-marechal) [inline packages/core/src/node/messaging/ipc-bootstrap.ts:27]: I don't know if my concern is valid, but I'd prefer erasing information about that pipe from the spawned processes somehow:

```suggestion
const ipcServer = process.argv.pop();
```

Also `argv` might not be the best mechanism to transfer the IPC server path? I know this is what I used for the plugin host in a different change but it was only because we had total control over said `argv`.

Here it might be better to use environment variables:

```suggestion
const ipcServer = process.env.THEIA_IPC_SERVER;
delete process.env.THEIA_IPC_SERVER;
```

File: packages/core/src/node/messaging/ipc-channel.ts (hunk 1 above)
Comment (tortmayr) [reply packages/core/src/node/messaging/ipc-channel.ts]: Duplex should be enough

**Review by paul-marechal — APPROVED** [review]
File watching works again on Windows with this change, thanks!

**Comment by colin-grant-work** [comment]
I suspect that this issue was also closed by this PR: https://github.com/eclipse-theia/theia/issues/11308
