### PR TITLE
Tasks: Ensure workspace delegate and scope defined

### LINKED ISSUE #10575: Error Logged by Task System if No Workspace
### Steps to Reproduce:

1. Open the application without a workspace
2. Check the logs for an error to the effect that one Cannot read property 'toString' of undefined emitted by the TaskConfigurations.getKeyFromScope method.

### Additional Information

- Operating System: RHEL 7
- Theia Version: 1.21.0

### PR DESCRIPTION
**Pull request by colin-grant-work**
#### What it does

Fixes #10575 by ensuring that both the scope of workspace delegate and the delegate itself are defined in the `TaskConfigurationManager`.

Closes #10497

#### How to test

1. Open the application with no workspace.
2. In the frontend logs, see no message about inabililty to read property `scope` of `undefined`.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/task/src/browser/task-configuration-manager.ts [hunk 1]
```diff
@@ -225,8 +225,9 @@ export class TaskConfigurationManager {
 
     protected readonly toDisposeOnDelegateChange = new DisposableCollection();
     protected updateWorkspaceModel(): void {
-        const newDelegate = this.workspaceService.saved ? this.workspacePreferences : this.folderPreferences;
-        const effectiveScope = this.workspaceService.saved ? TaskScope.Workspace : this.workspaceService.tryGetRoots()[0]?.resource.toString();
+        const isFolderWorkspace = this.workspaceService.opened && !this.workspaceService.saved;
```
Comment (vince-fugnitto) [inline packages/task/src/browser/task-configuration-manager.ts:228]: The notion of `saved` vs `unsaved` workspaces wasn't clear at first to describe workspace folders versus multi-workspace files. I'm wondering if it is worth documenting better from `WorkspaceService` itself.

**Review by vince-fugnitto — APPROVED** [review]
The changes look good to me, I confirmed that on `master` the following error exists while this pull-request resolves the issue:

```
logger-protocol.ts:112 root ERROR TypeError: Cannot read properties of undefined (reading 'toString')
    at TaskConfigurations.getKeyFromScope (http://localhost:3000/packages_task_lib_browser_quick-open-task_js.bundle.js:1744:22)
    at TaskConfigurations.readTasks (http://localhost:3000/packages_task_lib_browser_quick-open-task_js.bundle.js:1570:26)
    at TaskConfigurations.refreshTasks (http://localhost:3000/packages_task_lib_browser_quick-open-task_js.bundle.js:1562:20)
    at TaskConfigurations.onDidTaskFileChange (http://localhost:3000/packages_task_lib_browser_quick-open-task_js.bundle.js:1554:28)
    at http://localhost:3000/packages_task_lib_browser_quick-open-task_js.bundle.js:1401:28
    at http://localhost:3000/bundle.js:141256:69
    at CallbackList.invoke (http://localhost:3000/bundle.js:141262:26)
    at Emitter.fire (http://localhost:3000/bundle.js:141374:29)
    at TaskConfigurationManager.updateWorkspaceModel (http://localhost:3000/packages_task_lib_browser_quick-open-task_js.bundle.js:1152:47)
    at TaskConfigurationManager.<anonymous> (http://localhost:3000/packages_task_lib_browser_quick-open-task_js.bundle.js:1013:18)
```

File: packages/task/src/browser/task-configuration-manager.ts (hunk 1 above)
Comment (colin-grant-work) [reply packages/task/src/browser/task-configuration-manager.ts:228]: 👍  I've added a JSDoc explaining the conditions under which the `.saved` field is true or false.
