### PR TITLE
ui/ux: fix flickering icons when resizing explorer

### LINKED ISSUE #12615: navigator: flickering toolbar icons when resizing
### Bug Description:
Resizing the navigator in the explorer view when it is not in focus causes the toolbar icons to flicker. 

Bug Demo: 
Bug Demo

Correct Behavior: 
Correct Behavior

### Steps to Reproduce:

1. Open Theia application
2. Go in the `Explorer` view and open a folder if none are open (`File` -> `Open Folder`)
3. Click somewhere outside the `Explorer` view to make sure that it is not focused
4. Resize the view and notice the toolbar icons flickering

### Additional Information

- Operating System: Windows
- Theia Version: 1.38

### PR DESCRIPTION
**Pull request by vladarama**
#### What it does

This PR closes #12615 by fixing the flickering of the toolbar icons when resizing the navigator. The issue was resolved by adding a new method called `noPointerOnHover`. This method temporarily disables pointer events on the explorer view when the mouse enters it which prevents the flickering behavior and leads to a better user experience.

Demo:
Fix Demo

#### How to test

1. Open Theia application
2. Go in the `Explorer` view and open a folder if none are open (`File` -> `Open Folder`)
3. Click somewhere outside the `Explorer` view to make sure that it is not focused
4. Resize the view and notice that the toolbar icons stay hidden until you stop resizing the view

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/core/src/browser/view-container.ts [hunk 1]
```diff
@@ -1234,7 +1236,19 @@ export class ViewContainerPart extends BaseWidget {
         };
     }
 
+    protected handleResize(): void {
+        const handleMouseEnter = () => {
+            this.node?.classList.add('no-pointer-events');
+            setTimeout(() => {
+                this.node?.classList.remove('no-pointer-events');
+                this.node?.removeEventListener('mouseenter', handleMouseEnter);
+            }, 1000);
```
Comment (msujew) [inline packages/core/src/browser/view-container.ts:1245]: I feel like one second is a very long time until the icons appear again. Something like `100` ms is probably more appropriate and should prevent the flickering as well.

Comment (vladarama) [reply packages/core/src/browser/view-container.ts]: Good point, one second is indeed way too long. I changed it to `100ms` and it seems to work well.

**Review by msujew — APPROVED** [review]
Thanks, looks good to me 👍
