### PR TITLE
Use withServices to detect early Monaco initialization

### LINKED ISSUE #17245: Monaco new console error
### Bug Description:
Hi,
In the latest Theia, I see a new error in the console log:

```
StandaloneServices was already initialized and the following services were already instantiated before MonacoInit.init() 
could apply Theia overrides: codeEditorService, configurationService, themeService, contextService, layoutService. 
These services are using the default Monaco implementations instead of Theia's. This may cause unexpected behavior.
Investigate which code triggers premature service resolution.
  init @ monaco-init.ts:237
  (anonymous) @ index.js:158
  await in (anonymous)
  ./src-gen/frontend/index.js @ index.js:172
  __webpack_require__ @ bootstrap:25
  (anonymous) @ startup:4
  (anonymous) @ startup:4
```

### Steps to Reproduce:

1. Open the browser sample app
2. Check the console log

### Additional Information

- Operating System: Mac
- Theia Version: 1.70

### PR DESCRIPTION
**Pull request by colin-grant-work**
#### What it does

Fixes #17245 by using a targeted check to detect whether Monaco services had been initialized before our call to `StandaloneServices.initialize`

#### How to test

1. In the normal case, you should not see the log reported in #17245
2. If you put a breakpoint after our call to `StandaloneServices.initialize`, you should see that `isInitialized` is `true` and `servicesInitializedBeforeOverrides` is `false`, since we have then initialized the services, but they hadn't been initialized before our call.

#### Breaking changes

- [ ] This PR introduces breaking changes and requires careful review. If yes, the breaking changes section in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) has been updated.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)
- [x] User-facing text is internationalized using the `nls` service (for details, please see the [Internationalization/Localization section](https://github.com/theia-ide/theia/blob/master/doc/coding-guidelines.md#internationalizationlocalization) in the Coding Guidelines)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/monaco/src/browser/monaco-init.ts [hunk 1]
```diff
@@ -199,53 +200,79 @@ export namespace MonacoInit {
...
         // in case no Monaco editor was constructed before and items with keybindings are shown. See #15042.
         setBaseLayerHoverDelegate(StandaloneServices.get(IHoverService));
     }
 }
+
+function patchServices(overrides: Record<string, SyncDescriptor<unknown>>): void {
+    // eslint-disable-next-line @typescript-eslint/no-explicit-any
+    const instantiationService = StandaloneServices.get(IInstantiationService) as any;
+    const serviceCollection: ServiceCollection | undefined = instantiationService?._services;
+    if (serviceCollection) {
```
Comment (cdamus) [inline packages/monaco/src/browser/monaco-init.ts]: nit: If for whatever reason the private `_services` changes in a future release then `serviceCollection` may end up falsy. If we think we need to patch services but we don't get the collection we expect, then we silently fail to do anything. We should probably check that we got a `ServicesCollection` of the correct shape and log if not.

**Review by cdamus — APPROVED** [review]
Does the job! I do have a nit for you to consider if you're keen.

File: packages/monaco/src/browser/monaco-init.ts (hunk 1 above)
Comment (colin-grant-work) [reply packages/monaco/src/browser/monaco-init.ts]: Old code, but we should actually be able to reach into the Monaco sources and say exactly what kind of object we expect, and even have a test that confirms that we get what we expect so CI can tell us if we're wrong quickly.

**Review by cdamus — APPROVED** [review]
Now _that_ slams the door shut! 😀
