### PR TITLE
Remove global shortcuts from Electron, use WindowService for reload

### LINKED ISSUE #10701: Ctrl+R in bash terminal does not activate 'reverse-i-search'
### Bug Description:
When using a bash terminal in Theia, the keybinding sequence `ctrl+r` does not activate the 'reverse-i-search' functionality. This can be inconvenient for users who heavily rely on this bash functionality.

### Steps to Reproduce:

1. Open a terminal bash terminal on your machine outside Theia and press `ctrl+r` to activate reverse-i-search
2. Do the same thing in Theia and observe that it doesn't seem to work

### Additional Information

- Operating System:
- Linux
- Theia Version:
- Master

### PR DESCRIPTION
**Pull request by colin-grant-work**
#### What it does

Fixes #10701 by removing the registration of `globalShortcuts` from the `ElectronMainApplication`. There is already a command available internally to reload the window, which can be rebound or unbound and is context-sensitive, so the global shortcut is not necessary.

#### How to test

1. Run the Electron application
2. Open a `bash` terminal
3. Use the `ctrl+r` shortcut to access 'reverse-i-search'
4. Put focus on some element other than the terminal.
5. Use the ctrl+r shortcut to refresh the window - it should refresh
6. Dirty an editor and use the ctrl+r shortcut - you should be prompted to confirm the refresh
7. If you'd like, rebind the Refresh Window command to some other keybinding and confirm that it behaves correctly.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/core/src/electron-main/electron-main-application.ts [hunk 1]
```diff
@@ -445,26 +444,6 @@ export class ElectronMainApplication {
...
     }
 
-    /**
-     * Catch certain keybindings to prevent reloading the window using keyboard shortcuts.
-     */
-    protected attachGlobalShortcuts(electronWindow: BrowserWindow): void {
-        const handler = this.config.electron?.disallowReloadKeybinding
-            ? () => { }
-            : () => this.reload(electronWindow);
-        const accelerators = ['CmdOrCtrl+R', 'F5'];
```
Comment (vince-fugnitto) [inline packages/core/src/electron-main/electron-main-application.ts:455]: In order to have the same feature parity as we had with these changes, I'd try and bring <kbd>F5</kbd> back as an possible alternative to <kbd>ctrlcmd</kbd>+<kbd>r</kbd>.

**Review by vince-fugnitto — COMMENTED** [review]
I confirmed that the changes fix https://github.com/eclipse-theia/theia/issues/10701, and when a file is dirty the reload will prevent the app from restarting unless prompted.

File: packages/core/src/electron-main/electron-main-application.ts (hunk 1 above)
Comment (vince-fugnitto) [reply packages/core/src/electron-main/electron-main-application.ts:455]: On second thought <kbd>F5</kbd> is used to start a debug session (similarly to vscode) so we can probably exclude it as a possibility to reload.

**Review by vince-fugnitto — APPROVED** [review]
LGTM! :+1:

**Comment by orange-pig** [comment]
Sorry, I find the remove funciton 'attachGlobalShortcuts', like being refactored to `theia-electron-window.ts` in #10600 before time.

They are all removal operations, and there is no conflict when merging.

The problem still exists.

**Comment by kittaakos** [comment]
Did you deprecate `disallowReloadKeybinding`? It's not used anymore, just in tests. Thanks!
