### PR TITLE
Fix breakpoint context menu behaviour

### LINKED ISSUE #6237: [debug] Unstable behaviour with breakpoint context menu
### Description

More often than not, the context menu in code files acts in an unpredictable manner when managing breakpoints.
It's also different depending whether the file is in preview mode or fully opened for editing.

Observations:

- Setting and removing breakpoints using the mouse works as expected

- When setting a breakpoint via the context menu, the breakpoint either doesn't appear (preview mode) or appears on a different line (open mode).

- Removing a breakpoint (created with the mouse) doesn't work using the context menu. In preview mode, the option doesn't appear in the context menu as if the breakpoint isn't there. In open mode, it doesn't remove the breakpoint.

There may be other weirdness, but I think those are the main issues.

### Reproduction Steps

File open in preview mode (single-click on file tree):

preview

File open in open mode (double-click on file tree):

open

**OS and Theia version:**
OS: MacOS 10.14.5
Theia: 0.10.0, master (24f77b) - electron flavour

cc @eclipse-theia/debug-extension

### PR DESCRIPTION
**Pull request by thegecko**
Signed-off-by: thegecko <rob.moran@arm.com>

#### What it does
This PR fixes #6237 by ensuring the editor window is correctly focussed and the current position is stored while managing breakpoints via the context menu.

Specifically:
- `focus` the current editor widget before showing the context menu. This ensures the `current` and `active` editor is correctly set in the shell for when the context menu is shown.
- Remove the `onhide` behaviour of the context menu which resets the current position. This was causing a race condition where the position was trying to be read by breakpoint management functions and it was no longer set (causing the breakpoint to appear on the first or last line).
@akosyakov Was there any reason for the position to be reset when closing the menu? I didn't see any effects with stopping this.

- BONUS: I noticed the `onhide` event for the electron menus was being fired immediately, This is now fired when the menu is closed as expected. 

#### How to test
Please refer to issue #6237 for reproduction steps.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by thegecko** [comment]
> it does not add a new breakpoint, but remove the breakpoint added via the context menu

Hmm, in electron this works as expected and I don't see this behaviour

**Comment by thegecko** [comment]
@akosyakov It works fine because toggling the breakpoint without the context menu explicitly sets the position:

https://github.com/eclipse-theia/theia/blob/master/packages/debug/src/browser/editor/debug-editor-model.ts#L293

All other uses of toggle are via the context-menu and require the position to be set. I'll update the PR to tidy this slightly.

**Comment by akosyakov** [comment]
sorry, I don't get it, I meant this method returns the bogus position after closing the context menu: https://github.com/eclipse-theia/theia/blob/aa36ae62e9b45c8ffcdbb96789da0ff8a8469780/packages/debug/src/browser/editor/debug-editor-model.ts#L243-L246

testing now again

**Comment by akosyakov** [comment]
It does not work for me, please see the screencast:
breakpoint

Toggle is using the wrong line after using the context menu.

**Comment by thegecko** [comment]
Thanks for the update, I wasn't aware toggle appeared in the main menu.

I assume you can recreate the original problem?

**Comment by thegecko** [comment]
Thanks for your feedback @akosyakov 

PR has been updated to only use the position of the context menu for commands in the context menu. This fixes the original issue and ensures the debug commands also continue to work as expected.

**Comment by akosyakov** [comment]
I'm probably missing something: Why do we need to change APIs, won't it be enough to clean up the context position when the menu is closed as it was before: https://github.com/eclipse-theia/theia/blob/57be198635ced9325aaad0ada885b60e02154128/packages/debug/src/browser/editor/debug-editor-model.ts#L290

File: packages/debug/src/browser/editor/debug-editor-service.ts [hunk 1]
```diff
@@ -112,10 +115,17 @@ export class DebugEditorService {
...
         }
     }
+    toggleContextBreakpoint(): void {
+        const { model } = this;
+        if (model) {
+            model.toggleContextBreakpoint();
+        }
+    }
+
     setBreakpointEnabled(enabled: boolean): void {
```
Comment (akosyakov) [inline packages/debug/src/browser/editor/debug-editor-service.ts]: it looks fragile, if someone calls it programmatically when the last context position will be enabled, not a breakpoint for the current line

**Comment by akosyakov** [comment]
I wonder whether we can pass the current position as an arg to the context menu instead of remembering it: https://github.com/ARMmbed/theia/blob/9cb7a32db69f10e2d15810e0ce27248f96f2171a/packages/core/src/browser/context-menu-renderer.ts#L37

Editor context menu commands when can use it, but it will remove a need to keep the context position which is potentially can lead to bugs as https://github.com/eclipse-theia/theia/pull/6480#discussion_r342966798

**Comment by thegecko** [comment]
I'll take a look, I was struggling to fix this in a clean way

**Comment by thegecko** [comment]
Thanks @akosyakov . The PR has been updated to use the args sent to the context menu render.
This creates a much neater solution, please take a look.

File: packages/debug/src/browser/editor/debug-editor-service.ts [hunk 2]
```diff
@@ -84,38 +84,47 @@ export class DebugEditorService {
...
-    get logpointEnabled(): boolean | undefined {
-        const { logpoint } = this;
+    getContextLogpointEnabled(position?: monaco.Position): boolean | undefined {
+        const logpoint = this.getContextLogpoint(position);
         return logpoint && logpoint.enabled;
     }
 
-    get breakpoint(): DebugBreakpoint | undefined {
-        const breakpoint = this.anyBreakpoint;
+    getContextBreakpoint(position?: monaco.Position): DebugBreakpoint | undefined {
```
Comment (akosyakov) [inline packages/debug/src/browser/editor/debug-editor-service.ts]: I don't think we need `Context` marker. This method can be used programmatically to get a breakpoint at some position from other context.

Also if does not do anything for `undefined` value it is strange to have a signature allowing to call this method without any argument. Would not it better to move check that a position is defined to context editor command handlers? i.e. `isEnabled: position => monaco.Position.is(position) && !!this.getBreakpoint(position)`

The same for others methods.

Comment (thegecko) [reply packages/debug/src/browser/editor/debug-editor-service.ts]: The `context` name was specifically because it was only used in the context menus. I can rename.

> Would not it better to move check that a position is defined to context editor command handlers and make the position argument mandatory?

Personally I think this is a lot harder to read, there are many functions which return if the optional arguments are undefined.

However, happy to make changes to get this PR merged ASAP

Comment (akosyakov) [reply packages/debug/src/browser/editor/debug-editor-service.ts]: ok, let's go with it, I hope nobody relies on removed APIs

Comment (thegecko) [reply packages/debug/src/browser/editor/debug-editor-service.ts]: Unfortunately there is no `monaco.Position.is(position)` and it's in typefox code :(

**Comment by thegecko** [comment]
@akosyakov Updated to reflect your change requests. Have used a local `isPosition()` function in lieu of one available on `monaco.Position`.

Happy to merge?

**Comment by akosyakov** [comment]
@thegecko yes, i was happy to merge before as well :)
