### PR TITLE
Automatically reconnect on offline event

### LINKED ISSUE #9298: Websocket does not reconnect when changing WIFI networks on Linux distributions
### Bug Description:

When using Theia in a chromium based browser on Linux distributions, changing WIFI networks leads to a permanent offline mode. The websocket connection is never re-established. Reloading the page fixes the issue, although losing all unsaved changes in the process.

This seems to be a Chromium issue as indicated in [this bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=706002).

### Steps to Reproduce:

1. Start Theia in a chromium based browser on a Linux distribution.
2. Change to another WIFI network.
3. Theia shows the offline mode banner and never reconnects.

### Additional Information

- Operating System: Ubuntu
- Browser: Chromium/Chrome
- Theia Version: 1.11

### PR DESCRIPTION
**Pull request by Darkgaja**
#### What it does

Fixes #9298.

As the [bug report over at chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=706002) indicates, listening to the `offline` event of the browser enables us to manually tell the socket to reconnect. This event is usually fired during a change of network.

I tested this behavior on an Ubuntu 20.04 machine. Running a VM on Windows 10 didn't allow me to reproduce the network issue. I also looked for any regression issues under Firefox and Windows, but everything seems to work normally even with the fix in place.

#### How to test

1. Start Theia in a chromium based browser on a Linux distribution.
2. Change to another Wifi network.
3. The websocket connection will be re-established, indicated by the banner changing from online to offline and finally back to online.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/core/src/browser/messaging/ws-connection-provider.ts [hunk 1]
```diff
@@ -64,6 +64,7 @@ export class WebSocketConnectionProvider extends AbstractConnectionProvider<WebS
             this.handleIncomingRawMessage(data);
         };
         this.socket = socket;
+        window.addEventListener('offline', () => this.socket.reconnect());
```
Comment (marechal-p) [inline packages/core/src/browser/messaging/ws-connection-provider.ts:67]: I like this change, but according to the documentation, this is not 100% reliable. Is it fine to be slightly more paranoid and also attach to `online` and only trigger `this.socket.reconnect()` if `this.socket.readyState` is neither `CONNECTING` nor `OPEN`? In an attempt to make it more reliable.

Comment (Darkgaja) [reply packages/core/src/browser/messaging/ws-connection-provider.ts]: I like that idea and implemented it like that. However, it doesn't make much sense to check for `OPEN` as the state can actually be `OPEN` while no network connection is established, which is actually the main reason behind this PR.

**Review by marechal-p — APPROVED** [review]
Code LGTM. Although I wasn't able to reproduce the issue on master using Linux and Chrome. It is working for me with and without this change.

**Comment by vince-fugnitto** [comment]
> Code LGTM. Although I wasn't able to reproduce the issue on master using Linux and Chrome. It is working for me with and without this change.

I was unable to reproduce the issue as well on both _master_ and this _pull-request_.

**Comment by marechal-p** [comment]
@Darkgaja can you confirm that you have the issue as of master and that this PR fixes it for you? I don't see any regression, so if it fixes it for you I'll merge.

**Comment by Darkgaja** [comment]
@marechal-p @vince-fugnitto Just tested it on the master and the issue still persists:

https://user-images.githubusercontent.com/4377073/114525711-9c5e4680-9c46-11eb-8934-0b6a86692960.mp4

(Saving doesn't work, git synchronisation as well. Waiting doesn't help)

My changes seem to fix these issues.

**Review by vince-fugnitto — APPROVED** [review]
@Darkgaja thank you for providing the screenshares, they helped me reproduce the issue on _master_ and I confirmed that the _pull-request_ addresses the issue nicely :+1:
