### PR TITLE
[plugin] allow to override built-in commands

### LINKED ISSUE #7587: VSCODE VIM plugin not working
### Description
After #7539 merge to master, VSCODE VIM plugin basic commands like 'hjkl' stop working. CTRL + F for 'PageDown' is working. When you press 'j', instead of moving down one line letter 'j' appear in text (it looks like always in insert mode &lt;ESC> is not working)

### Reproduction Steps
git clone https://github.com/eclipse-theia/theia.git
cd theia/
yarn
cd examples/browser/
cp ~/Downloads/vscodevim.vim-1.13.1.vsix ../../plugins/
yarn run start
Open http://localhost:3000 in browser
Open some file
Press CTRL+F -> it's working
Press j, letter 'j' appear in text instead of moving one line down

**OS and Theia version:**
Linux xxx 5.4.0-4-amd64 #1 SMP Debian 5.4.19-1 (2020-02-13) x86_64 GNU/Linux
e2dfc1adf of master branch

**Diagnostics:** 
Errors in console after yarn run start:
root ERROR [hosted-plugin: 4054265] Promise rejection not handled in one second: TypeError: r.languages.registerSelectionRangeProvider is not a function , reason: TypeError: r.languages.registerSelectionRangeProvider is not a function                                                                                                                  
root ERROR [hosted-plugin: 4054265] With stack trace: TypeError: r.languages.registerSelectionRangeProvider is not a function                                                 
    at s.VersionDependentRegistration [as _doRegister] (/home/tavoda/opt/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:165355)      
    at s.update (/home/tavoda/opt/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:12010)                                              
    at t.VersionDependentRegistration.update (/home/tavoda/opt/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:12479)                 
    at new t.VersionDependentRegistration (/home/tavoda/opt/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:12278)                    
    at Object.t.register (/home/tavoda/opt/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:165289)                                    
    at Promise.all.Promise.resolve.then.then.t (/home/tavoda/opt/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:122868)              
    at process._tickCallback (internal/process/next_tick.js:68:7)                                                                                                             
root ERROR [hosted-plugin: 4054265] Promise rejection not handled in one second: TypeError: r.languages.registerSelectionRangeProvider is not a function , reason: TypeError: r.languages.registerSelectionRangeProvider is not a function                                                                                                                  
With stack trace: TypeError: r.languages.registerSelectionRangeProvider is not a function                                                                                     
    at s.VersionDependentRegistration [as _doRegister] (/home/tavoda/opt/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:165355)      
    at s.update (/home/tavoda/opt/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:12010)                                              
    at t.VersionDependentRegistration.update (/home/tavoda/opt/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:12479)                 
    at new t.VersionDependentRegistration (/home/tavoda/opt/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:12278)                    
    at Object.t.register (/home/tavoda/opt/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:165289)                                    
    at Promise.all.Promise.resolve.then.then.t (/home/tavoda/opt/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:122868)              
    at process._tickCallback (internal/process/next_tick.js:68:7)

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

- fix #7587: allow to override built-in commands to support VS Code Vim extension, 

#### How to test

- Follow https://github.com/eclipse-theia/theia/issues/7587#issue-600503510

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
@tavoda Could you try this PR please?

File: packages/plugin-ext-vscode/src/browser/plugin-vscode-commands-contribution.ts [hunk 1]
```diff
@@ -165,14 +160,6 @@ export class PluginVscodeCommandsContribution implements CommandContribution {
             }
         });
 
-        commands.registerCommand(VscodeCommands.SET_CONTEXT, {
-            isVisible: () => false,
```
Comment (RomanNikitenko) [inline packages/plugin-ext-vscode/src/browser/plugin-vscode-commands-contribution.ts:169]: @akosyakov 
I guess the the command was registered for https://github.com/eclipse-theia/theia/issues/4053

How it can be handled after removing this part?
Do you mean it's registered on VS Code side?

Sorry, if I missed something...

Comment (akosyakov) [reply packages/plugin-ext-vscode/src/browser/plugin-vscode-commands-contribution.ts:169]: It is already registered by Monaco. On master you can see a warning that this registration is ignored.

Comment (RomanNikitenko) [reply packages/plugin-ext-vscode/src/browser/plugin-vscode-commands-contribution.ts:169]: thanks!
