### PR TITLE
Filter versions for target platform in Extensions view

### LINKED ISSUE #17025: Install specific version in Extensions view does not filter versions for target platform
### Bug Description:

For extensions that publish platform specific versions, clicking `Install Specific Version...` shows all the versions available. In the UI, this looks like extension version is duplicated. See the attached screenshot for Claude Code extension.
We should try to filter the extensions by target platform or by universal type.

Image

### Steps to Reproduce:

1. Search for Claude Code in the extensions view. 
2. Click the Gear icon for Claude Code extension and select `Install Specific Version...`.
3. The quick pick menu shows multiple entries for each version.

### PR DESCRIPTION
**Pull request by udit-329**
#### What it does

Filter the extensions versions by target platform or by universal whenever available. Without this fix, going to extensions view -> Claude Code -> Gear icon -> Install Specific Version... would show each version multiple times. 
This would be the case for all extensions that publish separate versions of the extension for each target platform.

Fixes #17025 

#### How to test

-> Go to extensions view.
-> Search for Claude Code.
-> Click on the Gear icon.
-> Select `Install Specific Version...`.
-> Verify that the quick pick menu only shows each version once.

#### Breaking changes

- [ ] This PR introduces breaking changes and requires careful review. If yes, the breaking changes section in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) has been updated.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)
- [x] User-facing text is internationalized using the `nls` service (for details, please see the [Internationalization/Localization section](https://github.com/theia-ide/theia/blob/master/doc/coding-guidelines.md#internationalizationlocalization) in the Coding Guidelines)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/vsx-registry/src/browser/vsx-extensions-contribution.ts
Comment (ndoschek) [inline packages/vsx-registry/src/browser/vsx-extensions-contribution.ts:285]:
```ts
const { extensions } = await client.query({ extensionId, includeAllVersions: true, targetPlatform });
```

Comment (udit-329) [reply packages/vsx-registry/src/browser/vsx-extensions-contribution.ts:285]: I initially tried that approach, but the issue with that is the `query` API does not default to `universal` if the target platform filter returns empty. So for extensions that do not publish a version for our current target platform the list would be empty.
It is possible to make a second `query` request passing `universal` as the target platform, but we would still have to do grouping/filtering/merging of lists since it is possible not every version of the extension is published for every target platform.

Comment (ndoschek) [reply packages/vsx-registry/src/browser/vsx-extensions-contribution.ts:285]: That's a good point, thanks for explaining!
In that case, the client-side filtering makes total sense, then let's keep it this way.

File: packages/vsx-registry/src/browser/vsx-extensions-contribution.ts [hunk 1]
```diff
@@ -293,7 +293,42 @@ export class VSXExtensionsContribution extends AbstractViewContribution<VSXExten
...
+        for (const ext of compatibleExtensions) {
+            if (!extensionsByVersion.has(ext.version)) {
+                extensionsByVersion.set(ext.version, []);
+            }
+            extensionsByVersion.get(ext.version)!.push(ext);
+        }
+
+        // Filter extensions to one per version, preferring the current platform or universal
+        const filteredExtensions: VSXExtensionRaw[] = [];
+        for (const [_, exts] of extensionsByVersion.entries()) {
```
Comment (ndoschek) [inline packages/vsx-registry/src/browser/vsx-extensions-contribution.ts]: One final, small suggestion: we could simplify the loop by iterating over values directly since the version key isn't used inside the loop body:

```ts
for (const exts of extensionsByVersion.values()) {
```

Otherwise this looks good to me 👍

Comment (udit-329) [reply packages/vsx-registry/src/browser/vsx-extensions-contribution.ts]: Done!
