### PR TITLE
fix: use partial JSON extraction to prevent tool call label flicker

### LINKED ISSUE #17216: Improve partial arg rendering in tool rendering
### Bug Description:
While a tool call is in progress we do not show the nice shorthand for the parameters. This only happens once the tool call is completed

Image

Image

Image

As a consequence fast running tool calls with parameters appear to "flicker" as the parameters are shortly rendered in "full", followed by the nicer shorthand.

The cause is that the parameters are not finished streaming yet and therefore don't parse as valid JSON.

In the ShellExecutionRenderer this is streamlined a bit by being able to handle partial/invalid JSON. Something like this is needed for the other tools too. 

### Additional Information

- Operating System:
- Theia Version:

### PR DESCRIPTION
**Pull request by eneufeld**
#### What it does

Introduce extractJsonStringField utility that tries JSON.parse first, then falls back to regex extraction for incomplete/streaming JSON. Refactor parseShellExecutionInput to use the new utility. Update getArgumentsShortLabel implementations
(createPathShortLabel, FileContentFunction, FindFilesByPattern) to fall back to partial extraction when JSON.parse fails.
Update DelegationToolRenderer to show agentId and
prompt from partial JSON during streaming.

Fixes #17216

#### How to test

See the original issue.

Ask Coder to update some file.

#### Breaking changes

- [ ] This PR introduces breaking changes and requires careful review. If yes, the breaking changes section in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) has been updated.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)
- [x] User-facing text is internationalized using the `nls` service (for details, please see the [Internationalization/Localization section](https://github.com/theia-ide/theia/blob/master/doc/coding-guidelines.md#internationalizationlocalization) in the Coding Guidelines)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/ai-ide/src/browser/file-changeset-functions.ts [hunk 1]
```diff
@@ -43,7 +44,10 @@ function createPathShortLabel(args: string, hasMore: boolean): { label: string;
             return { label: String(parsed.path), hasMore };
         }
     } catch {
-        // ignore parse errors
+        const path = extractJsonStringField(args, 'path');
```
Comment (CamilleLetavernier) [inline packages/ai-ide/src/browser/file-changeset-functions.ts]: Since extraJsonStringField already includes JSON.parse, should we replace the entire try/catch block with a single call to extractJsonStringField?

**Review by CamilleLetavernier — APPROVED** [review]
Thanks, changes look good to me :+1: I only have one minor comment inline

File: packages/ai-ide/src/browser/file-changeset-functions.ts (hunk 1 above)
Comment (eneufeld) [reply packages/ai-ide/src/browser/file-changeset-functions.ts]: good point, i will check

**Review by CamilleLetavernier — APPROVED** [review]
Thanks, looks good to me 👍
