### PR TITLE
fix: do not set anthropic tool choice without tools

### LINKED ISSUE #15327: Anthropic invocations without tools fail
### Bug Description:

Using agents without tools in the prompt fails for Anthropic models

Image

### Steps to Reproduce:

1. Select an Anthropic model for Universal
2. Send a message to `@Universal`

### Additional Information

- Operating System: Ubuntu 24.04
- Theia Version: latest master [2a2c0ba](https://github.com/eclipsesource/theia/commit/2a2c0bab5bfc907cb0b58611a4e190fcc37408a7)

### PR DESCRIPTION
**Pull request by sdirix**
#### What it does

Makes sure to not hand over the 'tool_choice' parameter to the anthropic SDK if there are no tools to choose from. The SDK will throw an error otherwise.

fixes #15327
#### How to test

1. Configure an anthropic LLM for Universal, e.g. sonnet-3.7
2. Invoke Universal, e.g `@Universal Hi there`
3. Observe that no errors are thrown and the request is handled as usually
4. Also invoke another agent with tools, e.g. `@Coder`, there should be no regressions

#### Breaking changes

- [ ] This PR introduces breaking changes and requires careful review. If yes, the breaking changes section in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) has been updated.

#### Review checklist

- [X] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/ai-anthropic/src/node/anthropic-language-model.ts [hunk 1]
```diff
@@ -266,6 +266,9 @@ export class AnthropicModel implements LanguageModel {
     }
 
     private createTools(request: LanguageModelRequest): Anthropic.Messages.Tool[] | undefined {
+        if (request.tools?.length === 0) {
```
Comment (eneufeld) [inline packages/ai-anthropic/src/node/anthropic-language-model.ts:269]: i don't think this is needed, the existing code should return undefined already

**Review by eneufeld — APPROVED** [review]
