### PR TITLE
don't block web socket with many plugins

### LINKED ISSUE #6228: plugin system does not scale over JSON-RPC
With many plugins, a lot of metadata gets send to the frontend and then back to the server (plugin host process) on each deployment. It happens in big chunks of plugins leading to massive ws messages which deprive all other ws channels from possibility to communicate.

Other ideas? cc @eclipse-theia/plugin-system @svenefftinge @AlexTugarev 

In order to reproduce install about 50 vscode extensions:
- install all vscode built-int language extensions
- install different language extensions
- install debug extensions for different runtimes

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

- fix #6228: 
  - use permessage-deflate to compress any ws message greater than 256kb
  - remove raw package data from plugin metadata
    - frontend plugins don't have access to it anymore
    - backend plugins recover it from the disk
  - only fetch not yet loaded plugins to the frontend
  - install contributions info only to process
metadata in the frontend
  - install dependencies info only to process metadata on the backend
  - initialize debugger contributions from metadata, instead of sending it first to the plugin host and then back to the frontend
- closes #6233 - superseded
- [x] update the changelog with a breaking change
- [x] checked license compatibility of new dependencies

#### How to test

- remove native extension from the browse example and rebuild:
  - textmate grammar
  - debug-nodejs
  - java
  - java-debug
- install 57 VS Code extensions in `plugins` folder:
https://drive.google.com/file/d/1tuOsorMVOKi_twL9oAuZxgrD7-VUwNsj/view?usp=sharing
  - could not come up with a command to pull it from the gdrive in the terminal, if someone knows how to, please share
- use system proxy to emulate slow connection, e.g. Charles proxy
  - you cannot do it in Chrome, since it cannot throttle web sockets
- measure how long does it takes to activate all plugins before and after
- observe whether you get yellow status bar and ws frames hangs for 20-30 seconds after and before
- play with unstable connections to confirm that plugins get reloaded/unloaded on the reconnection

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/plugin-ext/src/common/plugin-api-rpc.ts [hunk 1]
```diff
@@ -162,12 +152,35 @@ export const emptyPlugin: Plugin = {
...
+    configStorage: ConfigStorage
+    activationEvents: string[]
+}
+
 export interface PluginManagerExt {
-    $stop(pluginId?: string): PromiseLike<void>;
 
-    $init(pluginInit: PluginInitData, configStorage: ConfigStorage): PromiseLike<void>;
+    /** initialize the manager, should be called only once */
+    $initiliaze(params: PluginManagerInitializeParams): Promise<void>;
```
Comment (svenefftinge) [inline packages/plugin-ext/src/common/plugin-api-rpc.ts]: initialize

File: packages/plugin-ext/src/hosted/browser/hosted-plugin.ts [hunk 2]
```diff
@@ -248,89 +284,122 @@ export class HostedPluginSupport {
...
+                    }
+                } catch (e) {
+                    console.error(`Failed to start plugins for '${host}' host`, e);
+                }
+            })());
         }
-        return toDisconnect;
+        await Promise.all(thenable);
+
+        const pluginCount = `${started} plugin${started === 1 ? '' : 's'}`;
```
Comment (benoitf) [inline packages/plugin-ext/src/hosted/browser/hosted-plugin.ts]: FYI there is https://www.npmjs.com/package/pluralize

File: packages/plugin-ext/src/hosted/browser/worker/worker-main.ts [hunk 3]
```diff
@@ -102,10 +116,10 @@ const pluginManager = new PluginManagerExtImpl({
             } else {
                 foreign.push({
                     pluginPath: pluginModel.entryPoint.backend!,
-                    pluginFolder: plg.source.packagePath,
+                    pluginFolder: pluginModel.packagePath,
                     model: pluginModel,
                     lifecycle: pluginLifecycle,
-                    rawModel: plg.source
+                    rawModel: stubPluginPackage(pluginModel)
```
Comment (benoitf) [inline packages/plugin-ext/src/hosted/browser/worker/worker-main.ts]: do we still need this rawModel ?

File: packages/plugin-ext/src/hosted/node/hosted-plugin-deployer-handler.ts [hunk 4]
```diff
@@ -32,12 +32,12 @@ export class HostedPluginDeployerHandler implements PluginDeployerHandler {
     /**
      * Managed plugin metadata backend entries.
      */
-    private currentBackendPluginsMetadata: PluginMetadata[] = [];
+    private readonly currentBackendPluginsMetadata = new Map<string, PluginMetadata>();
```
Comment (benoitf) [inline packages/plugin-ext/src/hosted/node/hosted-plugin-deployer-handler.ts]: I don't see why we moved from arrays to map and change method names in that file ?
to use a cache ?

File: packages/plugin-ext/src/hosted/node/plugin-host-rpc.ts [hunk 5]
```diff
@@ -128,40 +129,46 @@ export class PluginHostRPC {
                     console.error(e);
                 }
             },
-            init(raw: PluginMetadata[]): [Plugin[], Plugin[]] {
+            async init(raw: PluginMetadata[]): Promise<[Plugin[], Plugin[]]> {
```
Comment (benoitf) [inline packages/plugin-ext/src/hosted/node/plugin-host-rpc.ts]: are we forced to move from sync to async there ?
From what I see it's to read package.json files but can't it be delayed later as well and only used for frontends not backend yet.

**Comment by akosyakov** [comment]
In order to reproduce on the master state:
- install Charles proxy and configure it to throttle with 3G for localhost
- apply these patch to collect how long does it take to fetch metadata and start plugins: 
[measure_before.txt](https://github.com/eclipse-theia/theia/files/3645749/measure_before.txt)

My results on 3G
- before:
  - yellow status bar
  - unresponsive UI
  - fetching metadata: `getDeployedMetadata took 16066.520000109449 ms`
  - sending metadata to the plugin host and staring plugins: `startPlugins took 48116.30499991588 ms`
- after:
  - no yellow status bar
  - responsive UI
  - fetching metadata: `Sync of 57 plugins took: 2785.3900000918657 ms`
  - staring plugins: `Start of 57 plugins took: 1804.2249998543411 ms`

I also measured on my normal connection. In this case results are not so different than on 3G.

File: packages/plugin-ext/src/common/plugin-api-rpc.ts [hunk 6]
```diff
@@ -162,12 +152,35 @@ export const emptyPlugin: Plugin = {
     }
 };
 
+export interface PluginManagerInitializeParams {
```
Comment (benoitf) [inline packages/plugin-ext/src/common/plugin-api-rpc.ts]: I don't see why there is a rename from PluginInitData to PluginManagerInitializeParams. I mean it's already a lot of changes so mixing some opinionated cleanup and changes is something that I dislike as I already commented in a lot of PRs

File: packages/core/src/node/messaging/messaging-contribution.ts [hunk 7]
```diff
@@ -84,7 +84,10 @@ export class MessagingContribution implements BackendApplicationContribution, Me
     onStart(server: http.Server | https.Server): void {
         const wss = new ws.Server({
             server,
-            perMessageDeflate: false
+            perMessageDeflate: {
+                // don't compress if a message is less than 256kb
+                threshold: 256 * 1024
```
[the remark this answers is not in the document]
Comment (akosyakov) [reply packages/core/src/node/messaging/messaging-contribution.ts]: No, we've never done it before. I did not want to install very aggressive threshold, just enough to handle the current issue.

WS docs also have many warning about using it: https://github.com/websockets/ws#websocket-compression

Let's file an issue to investigate whether we can lower threshold? We can make it even configurable that each product can play with it.

File: packages/plugin-ext/src/hosted/browser/hosted-plugin.ts (hunk 2 above)
Comment (akosyakov) [reply packages/plugin-ext/src/hosted/browser/hosted-plugin.ts]: Do we need 500 lines of an external package to replace one liner?

**Comment by benoitf** [comment]
Great improvement.

FYI on macOS there is Apple Network Link Conditioner utility

File: packages/plugin-ext/src/hosted/node/hosted-plugin-deployer-handler.ts (hunk 4 above)
Comment (akosyakov) [reply packages/plugin-ext/src/hosted/node/hosted-plugin-deployer-handler.ts]: for fast access in `getDeployedPluginMetadata `

File: packages/plugin-ext/src/hosted/node/plugin-host-rpc.ts (hunk 5 above)
Comment (akosyakov) [reply packages/plugin-ext/src/hosted/node/plugin-host-rpc.ts]: Only if we replace with fs sync read since `rawModel` is always used synchronously. But using sync fs operations is discouraged for perf reasons.

File: packages/plugin-ext/src/hosted/browser/hosted-plugin.ts (hunk 2 above)
Comment (benoitf) [reply packages/plugin-ext/src/hosted/browser/hosted-plugin.ts]: it's just that I see it 3 times only in that file

File: packages/plugin-ext/src/common/plugin-api-rpc.ts (hunk 6 above)
Comment (akosyakov) [reply packages/plugin-ext/src/common/plugin-api-rpc.ts]: We used to send data to initialize manager each time when we start a plugin, i.e. all preferences. I've changed it to send them only once when the manager is created, so we don't need to push them again and again on each deployment.

File: packages/plugin-ext/src/hosted/browser/worker/worker-main.ts (hunk 3 above)
Comment (akosyakov) [reply packages/plugin-ext/src/hosted/browser/worker/worker-main.ts]: It will be bigger refactoring to make it optional. There are different clients in the plugin host, assuming that it is always present, i.e. debug ext and vscode backend init script.

File: packages/plugin-ext/src/common/plugin-api-rpc.ts (hunk 6 above)
Comment (benoitf) [reply packages/plugin-ext/src/common/plugin-api-rpc.ts]: but I mean, you could just change params.

It's like renaming init to initialize... why ?

File: packages/plugin-ext/src/hosted/browser/worker/worker-main.ts (hunk 3 above)
Comment (benoitf) [reply packages/plugin-ext/src/hosted/browser/worker/worker-main.ts]: it can be done in a follow-up but it's like there is a big hack by faking the raw stuff and let think it is still there.

File: packages/plugin-ext/src/hosted/browser/hosted-plugin.ts (hunk 2 above)
Comment (akosyakov) [reply packages/plugin-ext/src/hosted/browser/hosted-plugin.ts]: will remove duplication

File: packages/plugin-ext/src/hosted/node/hosted-plugin-deployer-handler.ts (hunk 4 above)
Comment (benoitf) [reply packages/plugin-ext/src/hosted/node/hosted-plugin-deployer-handler.ts]: map entries are never removed ?

File: packages/plugin-ext/src/common/plugin-api-rpc.ts (hunk 6 above)
Comment (akosyakov) [reply packages/plugin-ext/src/common/plugin-api-rpc.ts]: ok, just to check that I understand correctly:
- we keep `$init` but we call it only once without options to start plugins
- we add `$start` method to actually start plugins

Comment (benoitf) [reply packages/plugin-ext/src/common/plugin-api-rpc.ts]: I mean it's a global thing: please separate cleanup/code refactoring from enhancement. Here we have both mixed

cleanup, code refactoring is good but for me mixing it with enhancements is producing nightmare and unexpected results in downstream as well

File: packages/plugin-ext/src/hosted/node/hosted-plugin-deployer-handler.ts (hunk 4 above)
Comment (akosyakov) [reply packages/plugin-ext/src/hosted/node/hosted-plugin-deployer-handler.ts]: It's possible to uninstall plugins in Gitpod, entries are removed as consequence as well. I can add the context menu to the plugin view to uninstall plugins from the vanilla Theia as well. Would it be fine to add as another PR?

Comment (benoitf) [reply packages/plugin-ext/src/hosted/node/hosted-plugin-deployer-handler.ts]: well I would say that if we populate map with entries, it should have ways to clean it up upstream yes

File: packages/plugin-ext/src/hosted/node/plugin-host-rpc.ts (hunk 5 above)
Comment (benoitf) [reply packages/plugin-ext/src/hosted/node/plugin-host-rpc.ts]: I was thinking on more lazy loading with later asynchronous operations, not during init phase, not using sync read.

Comment (akosyakov) [reply packages/plugin-ext/src/hosted/node/plugin-host-rpc.ts]: I will try to move it just before calling plugin initialization script.

File: packages/plugin-ext/src/hosted/browser/hosted-plugin.ts [hunk 8]
```diff
@@ -167,38 +170,32 @@ export class HostedPluginSupport {
...
-                    this.pluginServer.getAllStorageValues({ workspace: this.workspaceService.workspace, roots })
-                ]);
-                await this.doLoad({ plugins, logPath, storagePath, pluginAPIs, globalStates, workspaceStates, roots }, this.container);
-            });
+            await this.progressService.withProgress('', PluginProgressLocation, () => this.doLoad());
         } catch (e) {
             console.error('Failed to load plugins:', e);
         }
-    }
+    }), 50, { trailing: true });
```
Comment (akosyakov) [inline packages/plugin-ext/src/hosted/browser/hosted-plugin.ts]: should be `leading`

File: packages/core/src/node/messaging/messaging-contribution.ts (hunk 7 above)
[the remark this answers is not in the document]
Comment (akosyakov) [reply packages/core/src/node/messaging/messaging-contribution.ts]: a follow-up issue: https://github.com/eclipse-theia/theia/issues/6253

File: packages/plugin-ext/src/common/plugin-protocol.ts [hunk 9]
```diff
@@ -378,12 +385,21 @@ export interface PluginModel {
...
+    activationEvents?: string[];
+    // frontend contributions info -- end
+
+    // backend dependencies info -- start
     /**
      * The deployable form of extensionDependencies from package.json,
      * i.e. not `publisher.name`, but `vscode:extension/publisher.name`.
      */
     extensionDependencies?: string[];
+    rawExtensionDependencies?: string[];
```
[the remark this answers is not in the document]
Comment (akosyakov) [reply packages/plugin-ext/src/common/plugin-protocol.ts]: update docs

File: packages/plugin-ext/src/hosted/browser/hosted-plugin.ts (hunk 2 above)
Comment (akosyakov) [reply packages/plugin-ext/src/hosted/browser/hosted-plugin.ts]: extracted `logMeasurement` method

File: packages/plugin-ext/src/hosted/browser/worker/worker-main.ts (hunk 3 above)
Comment (akosyakov) [reply packages/plugin-ext/src/hosted/browser/worker/worker-main.ts]: I can also do `rawModel: undefined!`, so if frontend plugins try to access it they will get `undefined`. Would it work?

File: packages/plugin-ext/src/hosted/node/plugin-host-rpc.ts (hunk 5 above)
Comment (akosyakov) [reply packages/plugin-ext/src/hosted/node/plugin-host-rpc.ts]: I cannot move it because we call `self.initContext(backendInitPath, plugin);` in this method and raw model should be already there for plugin-vscode-init: https://github.com/theia-ide/theia/blob/dd1d2a0c9c4f9e0326771ab2b4027b8ba28c4181/packages/plugin-ext-vscode/src/node/plugin-vscode-init.ts#L47-L49

File: yarn.lock [hunk 10]
```diff
@@ -1584,6 +1584,11 @@ async-each@^1.0.0:
   version "1.0.1"
   resolved "https://registry.yarnpkg.com/async-each/-/async-each-1.0.1.tgz#19d386a1d9edc6e7c1c85d388aedbcc56d33602d"
 
+async-limiter@^1.0.0:
```
Comment (akosyakov) [inline yarn.lock]: I've checked that all new deps are MIT cc @eclipse-theia/ip-help

File: packages/plugin-ext/src/hosted/node/hosted-plugin-deployer-handler.ts (hunk 4 above)
Comment (akosyakov) [reply packages/plugin-ext/src/hosted/node/hosted-plugin-deployer-handler.ts]: ok, will cover it as part of https://github.com/eclipse-theia/theia/issues/5507

File: packages/plugin-ext/src/common/plugin-api-rpc.ts (hunk 1 above)
Comment (akosyakov) [reply packages/plugin-ext/src/common/plugin-api-rpc.ts]: renamed back to `$init`

**Comment by akosyakov** [comment]
@benoitf please have a look again, I've addressed what I could.

File: yarn.lock (hunk 10 above)
Comment (marcdumais-work) [reply yarn.lock]: I did the recursive check of NPM production dependencies and everything looks good.

Comment (akosyakov) [reply yarn.lock]: @marcdumais-work thank you!

File: packages/plugin-ext/src/common/plugin-api-rpc.ts (hunk 6 above)
Comment (svenefftinge) [reply packages/plugin-ext/src/common/plugin-api-rpc.ts]: > I mean it's a global thing: please separate cleanup/code refactoring from enhancement. Here we have both mixed

@benoitf I agree that we should avoid doing "opinionated" improvements, i.e. changes based on taste or generally without a clear benefit. But generally improving the code is a good thing, no? I don't see why improvements should not go together with bugfixes and enhancements. I'd actually like to encourage everyone to strive for improving the code they touch. Maybe I don't understand your concern and we can discuss in next dev meeting?

Comment (benoitf) [reply packages/plugin-ext/src/common/plugin-api-rpc.ts]: @svenefftinge my remark is just to separate commits from what is feature and what is cleanup/refactoring and not do enhancement, and everything as well in the same time

I usually see ppl changing code formatting, renaming methods, etc as part of a new feature commit and I dislike it personally as from reviewer, you want to see if the change is really for the feature or not

Comment (benoitf) [reply packages/plugin-ext/src/common/plugin-api-rpc.ts]: in short, small commits, small PRs, merge fast

Comment (benoitf) [reply packages/plugin-ext/src/common/plugin-api-rpc.ts]: this PR is doing code cleanup, introduce breaking changes, remove partially the raw model with hack,  enable perMessage deflate compression, change the way metadata are kept, etc. but I would say almost all of them could be separated and merged in independent way. break less, easy to track, easy to revert

Comment (akosyakov) [reply packages/plugin-ext/src/common/plugin-api-rpc.ts]: commit history is rewritten with a commit for each improvement, is there something else have to be done? Please have a look at other comments whether they are resolved that we can proceed.

File: packages/plugin-ext/src/hosted/node/hosted-plugin-deployer-handler.ts [hunk 11]
```diff
@@ -47,14 +47,22 @@ export class HostedPluginDeployerHandler implements PluginDeployerHandler {
...
     async getDeployedBackendMetadata(): Promise<PluginMetadata[]> {
         // await first deploy
         await this.backendPluginsMetadataDeferred.promise;
         // fetch the last deployed state
-        return this.currentBackendPluginsMetadata;
+        return [...this.currentBackendPluginsMetadata.values()];
+    }
+
+    getDeployedPluginMetadata(pluginId: string): PluginMetadata | undefined {
+        const metadata = this.currentBackendPluginsMetadata.get(pluginId);
```
Comment (benoitf) [inline packages/plugin-ext/src/hosted/node/hosted-plugin-deployer-handler.ts]: I have a couple of questions.

we cache the model with its id (publisher + name)

- what is happening for development mode where we might change package.json without changing publisher/name
- what is happening if we bump to a new plug-in version

Comment (akosyakov) [reply packages/plugin-ext/src/hosted/node/hosted-plugin-deployer-handler.ts]: It would the same as before. This PR does not change it, caching was there before to avoid deploying duplicate plugins.

> what is happening for development mode where we might change package.json without changing publisher/name

Seems to be a bug, should be the same on master.

> what is happening if we bump to a new plug-in version

So far the plugin system did not apply semver to decide which plugin to deploy and pick the first one. It should be an enhancement request.

**Comment by akosyakov** [comment]
I'm going to rebase and merge it if the CI is green and no one has questions to changes of this PR. Current state is quite broken and works for couple plugins, leading to bad UX whenever a bit more is installed.

**Comment by akosyakov** [comment]
@benoitf What is your suggestions how to handle it?

**Comment by benoitf** [comment]
remove 2 commits from PR and merge it (but it won't solve the blocking)
or solve the metadata/model.

I'm not saying there are no global issues on deploying a lot of plug-ins, but it's not because we have a PR that fix an issue and that CI test is green that we should merge something that is leading to more complex codebase with dirty hacks.

**Comment by akosyakov** [comment]
> or solve the metadata/model.

I meant what is you suggestion about it? And:

> for the first one, it seems we're in the middle of something.
We have metadata with model, etc but in fact they're not the same as for some you will have contribution/dependencies and for some case you won't. So when you're manipulating metadata you don't know quickly if you're in a mode where you have access or not to it.

how do you suggest to solve it?

**Comment by akosyakov** [comment]
> for the first one, it seems we're in the middle of something.
We have metadata with model, etc but in fact they're not the same as for some you will have contribution/dependencies and for some case you won't. So when you're manipulating metadata you don't know quickly if you're in a mode where you have access or not to it.

I don't see how it can happen: if the plugin was deleted it will be unloaded by next deployment form the frontend and the plugin host process.

> about the last one, which is very related to the previous one, it's still a hack

For the hack for frontend plugins, I'm still not sure what your expectations. Should we install undefined? Should we throw on access on packageJSON?

File: packages/plugin-ext/src/common/plugin-protocol.ts [hunk 12]
```diff
@@ -378,12 +385,25 @@ export interface PluginModel {
...
+    // frontend contributions info -- end
+
+    // backend dependencies info -- start
     /**
-     * The deployable form of extensionDependencies from package.json,
-     * i.e. not `publisher.name`, but `vscode:extension/publisher.name`.
+     * The deployable form of `rawExtensionDependencies`,
+     * e.g. not `publisher.name`, but `vscode:extension/publisher.name`.
      */
     extensionDependencies?: string[];
```
Comment (benoitf) [inline packages/plugin-ext/src/common/plugin-protocol.ts]: also rawExtensionDependencies / extensionDependencies (extension) is VS Code name. It looks odd inside plug-in model to have extensions which may let thing it could be Theia extensions

Comment (akosyakov) [reply packages/plugin-ext/src/common/plugin-protocol.ts]: so it should be `extensionDependencies` and `rawPluginDependencies`? or we should break nor? this comment is probably very related to the scope of this PR

Comment (benoitf) [reply packages/plugin-ext/src/common/plugin-protocol.ts]: yes, it's something that I've missed long time ago

**Comment by benoitf** [comment]
>> for the first one, it seems we're in the middle of something.
>> We have metadata with model, etc but in fact they're not the same as for some you will have
>> contribution/dependencies and for some case you won't. So when you're manipulating metadata >> you don't know quickly if you're in a mode where you have access or not to it.

>I don't see how it can happen: if the plugin was deleted it will be unloaded by next deployment 
> from the frontend and the plugin host process. ...It can happen if one somehow manually 
> manipulates with the file disk, but when it can happen at any time when the plugin system reads
> package.json. Don't think we should expect it.

I'm not talking about the cache or reloading. I mean, when you see a metadata object you might call metadata.model.contributes on it but sometimes it will be there and sometimes no. (even if it's the package.json) because some options are on or off and then you'll have to go to see which option as been given in upper calls, etc.

as I said, by looking in the code, we're giving options parameter without contributes:true just to know if it's a backend or a frontend. overkill.

>> about the last one, which is very related to the previous one, it's still a hack

> For the hack for frontend plugins, I'm still not sure what your expectations. Should we install undefined? Should we throw on access of packageJSON?

the hack is on stubbing and broken raw model

**Comment by svenefftinge** [comment]
> We have metadata with model, etc but in fact they're not the same as for some you will have contribution/dependencies and for some case you won't. So when you're manipulating metadata you don't know quickly if you're in a mode where you have access or not to it.

I don't see how this is a hack or bad code. It is a classic optimization based on fetch profiles and gladly we have a type system that tells us if something can be `undefined`.

**Comment by akosyakov** [comment]
> I'm not talking about the cache or reloading. I mean, when you see a metadata object you might call metadata.model.contributes on it but sometimes it will be there and sometimes no. (even if it's the package.json) because some options are on or off and then you'll have to go to see which option as been given in upper calls, etc.

Would it be fine to have different interface for the frontend which contain `contributes` and remove it from `PluginMetadata`?

> as I said, by looking in the code, we're giving options parameter without contributes:true just to know if it's a backend or a frontend. overkill.

in this place, yes

**Comment by akosyakov** [comment]
> the hack is on stubbing and broken raw model

Understood, but what should we do instead? Would `undefined` work?

**Comment by svenefftinge** [comment]
@benoitf Also, you keep saying that Anton's proposed solutions are hacks, without suggesting an alternative. It feels like you are blocking and it is wasting his time. This is already the second non-trivial attempt on guessing what kind of solution you might be able to accept. This is not cool especially when the current state is as broken as it is. So please help us fixing this problem.

**Comment by benoitf** [comment]
@svenefftinge you're saying that this is broken but it seems it's the case since the beginning and in a couple of days it is becoming a blocker. I'm just saying that we still have time to do proper fixes.
A breaking change PR was merged last friday without pinging at least one Red Hat committer. 
So, please excuse me if I do a correct review.

I am not blocking for fun, just to ensure consistency.

> @benoitf Also, you keep saying that Anton's proposed solutions are hacks, without suggesting an alternative.

I've said that stubbing is not the way to go and that adding a new parameter to every methods for not storing contributes/extensions is overkill. I doubt I have to say what to write, I'm pretty sure that Anton knows when it's becoming like a hack for a specific case or if it's well integrated.

To me it's feeling like I receive pressure to get something merged but I don't see immediate urgency on upstream.

**Comment by svenefftinge** [comment]
>  I doubt I have to say what to write, I'm pretty sure that Anton knows when it's becoming like a hack for a specific case or if it's well integrated.

Anton asked several times what alternative approach you would suggest. So, yes, it doesn't seem to be so obvious. Please be more specific in critism and provide alternative suggestions. Calling other people's work a 'hack' is not helpful either. I don't think anyone intentionally proposes bad code changes, especially not Anton.

**Comment by akosyakov** [comment]
@benoitf I don't know about expectations of frontend plugins developers or if there are any frontend plugins using `theia.Plugin.packageJSON`. I understood that you are not happy that they receive incomplete model, but what should be expected instead?

Ideally I would just remove an API and say that it is the limitation, or replace it with the async version. But i don't think we have separate typings for frontend and backend plugins. Alternatively we can make it async always and implement `vscode.Extension.packageJSON` differently.

**Comment by akosyakov** [comment]
> A breaking change PR was merged last friday without pinging at least one Red Hat committer.

Nobody was trying to hide from you breaking changes. PR was opened for 2 week with an intention that committers can have a look. It is true that we've overlooked that teams are not notified anymore, but Theia committers should stay active as well. Your input is always treated seriously and welcomed on other matters, not only on the plugin system. Also there is always way to correct things afterward given that committers are active and ready to handle it, raising an issue would be enough.

> So, please excuse me if I do a correct review.

One thing is check user visible issues (including extension developers), another asking to rewrite the code which solves user issues and used only in Theia repo. I agree about the issue with `vscode.Extension.packageJSON`, but restructuring of the plugin model to remove some properties could be done later or not if t is turned out to be not so important afterwards.

> To me it's feeling like I receive pressure to get something merged but I don't see immediate urgency on upstream.

There are many people in the community relying that the plugin system works reliably, scales, handles reconnections, supports all VS Code APIs and so on. It is strange that Theia community should wait when a particular product stumbles on some particular issue and only when it will be addressed. Issues should be first fixed in Theia and then products can check up, handle breaking changes and so on, not another way around.

File: packages/plugin-ext/src/hosted/node/plugin-service.ts [hunk 13]
```diff
@@ -82,22 +82,25 @@ export class HostedPluginServerImpl implements HostedPluginServer {
...
-                    for (const metadata of await this.hostedPlugin.getExtraPluginMetadata()) {
-                        extraPluginMetadata.set(metadata.model.id, metadata);
+                    for (const extraMetadata of await this.hostedPlugin.getExtraPluginMetadata()) {
+                        extraPluginMetadata.set(extraMetadata.model.id, extraMetadata);
                     }
                 }
-                plugin = extraPluginMetadata.get(pluginId);
+                const metadata = extraPluginMetadata.get(pluginId);
+                if (metadata) {
+                    plugin = { metadata };
```
Comment (akosyakov) [inline packages/plugin-ext/src/hosted/node/plugin-service.ts]: @benoitf not sure whether extra plugin metadata suppose to have any contributes

It would be good to setup the example app using these APIs or remove and move them to Che, no one except Che developers can reason about them right now. cc @svenefftinge

**Comment by akosyakov** [comment]
@benoitf @svenefftinge I've refactored last 2 commits:
- metadata does not have anymore contributions and dependencies, clients should read these info when it is required using `PluginReader`
- for frontend plugins i throw unsupported error if someone tries to access `theia.Plugin.packageJSON`

**Comment by akosyakov** [comment]
> as I said, by looking in the code, we're giving options parameter without contributes:true just to know if it's a backend or a frontend. overkill.

@benoitf it is turned out to be not true, it is used in plugin-dev frontend, for example here: https://github.com/theia-ide/theia/blob/b95ac56d6381285fbb25d38fbde26d477509e259/packages/plugin-dev/src/browser/hosted-plugin-informer.ts#L60-L77

File: packages/plugin-ext/src/common/plugin-protocol.ts (hunk 12 above)
Comment (akosyakov) [reply packages/plugin-ext/src/common/plugin-protocol.ts]: renamed

**Comment by akosyakov** [comment]
I've noticed that with an opened editor loading contributions takes around 15s. It turned out because we try to detect a language for plaintext editors for each extension, more extension we have longer it takes. I will schedule auto detection for another tick that we can start plugins earlier.

Another issue is that we register languages before grammars, but grammars are activated when a language is activated. So if a language is activated before the grammar is registered then a grammar is never activated. And it happens if you have an opened editor. We don't see it with textmate-grammars native extension, because everything always registered before any Monaco model is created, in this PR it gets very apparent. I will inverse the registration order to fix it.

**Comment by akosyakov** [comment]
@svenefftinge addressed https://github.com/eclipse-theia/theia/pull/6252#issuecomment-535367097 with https://github.com/eclipse-theia/theia/pull/6252/commits/70e51c4af479ca9ae3fffdb4353aa7d40fe662e5

**Comment by akosyakov** [comment]
All commits except cleaning up plugin model are extracted to https://github.com/eclipse-theia/theia/pull/6267

File: packages/plugin-ext/src/hosted/node/plugin-service.ts (hunk 13 above)
Comment (benoitf) [reply packages/plugin-ext/src/hosted/node/plugin-service.ts]: @akosyakov until now examples are not examples but just assemblies of theia extensions from built-in `packages`

Comment (akosyakov) [reply packages/plugin-ext/src/hosted/node/plugin-service.ts]: > not sure whether extra plugin metadata suppose to have any contributes 

What about apis? Should extra plugin metadata be changed to provide something else as well?

Comment (akosyakov) [reply packages/plugin-ext/src/hosted/node/plugin-service.ts]: > until now examples are not examples but just assemblies of theia extensions from built-in packages

My point is that there should be a criteria to decide what should be a contribution point or what should be just overloaded via DI in a concrete product. Till now, in the rest of Theia, the criteria was to have at least one 2-3 stable internal clients to the contribution point.  It was done to make sure that:
- anyone can judge about usefulness of such APIs, not guess or wait for someone
- don't have complexity of individual solutions in the framework, gain experience before abstracting something
- don't have unused contribution points

In the plugin system I see information passed around and contribution points which are never used. For a Theia committer who is not aware of Che, it looks confusing and unnecessary. Why should plugin host have an ID of an individual plugin when it runs many? Why do we have host always when we have one? What is extra metadata? and so on.

>  until now examples are not examples but just assemblies of theia extensions from built-in packages

We always treated it as an example. Although it should be aligned with there we are going, i.e. use VS Code extension as you mentioned. If the plugin system has support of remote running, adding some simple example would help with reasoning about unused data and contribution points as well.

**Comment by akosyakov** [comment]
@benoitf I will update the changelog.

@marcdumais-work the release is today right?

**Comment by marcdumais-work** [comment]
Hi @akosyakov , @benoitf 

It's the plan to do the release today, yes. I see there was a lot of recent action about plugins, and that the situation is perhaps not completely resolved. So I defer to you about whether we should go ahead now or wait a bit for a more satisfactory resolution. Doing a 0.11.1 release in e.g. a week is also an option.

Please advise.

**Comment by akosyakov** [comment]
@marcdumais-work we are going to land it only afterwards, please processes with the release

**Comment by akosyakov** [comment]
@benoitf @svenefftinge  the changelog is updated, the release is done

> From what I see with the breaking changes, it will be a total breakage of Eclipse Che and remote plug-ins.

I've looked at Che on usage of renamed/replaced APIs and found:
 - https://github.com/eclipse/che-theia/blob/b3c9138bb25e191e0c4b9cef682edb04ebdfa265/extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-frontend-service.ts which can be replaced with get plugin ids and then for each get metadata as frontend does it now in Theia
- https://github.com/eclipse/che-theia/blob/69ae14f116c189a2561e2d45007fb4d7b47b365f/extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-init.ts probably not going to break, since `PluginReader` still has `getPluginMetadata`.

> APIs were renamed, some sync methods are now async and new lifecycle method is added.

`PluginHost.init` still supports sync version, it is maybe promise, not a promise. I could not find that lifecycle method `PluginManagerExt.$init` is used in Che.

I've looked at https://github.com/eclipse/che-theia.

Again such work should be done on the product level when it is about to migrate, not a framework level. JS provides access to anything at runtime, even to private stuff via index access, and DI allow to override and inject whatever product wants. I don't think there is a way to break completely.

**Comment by svenefftinge** [comment]
Awesome work, Anton! 
@benoitf I assume we can merge this now?

**Comment by benoitf** [comment]
@akosyakov thx for the heads up on che-theia repository. 
Well it's not because we have access to private components that the product is extensible. Also DI is not completely there.
BTW thx for the latest improvements, it's a more clean solution. 

@svenefftinge yes
