### PR TITLE
monaco: parseSnippet RangeError handling

### LINKED ISSUE #12434: RangeError: Maximum call stack size exceeded with recent `vscode.html` builtin extension
### Bug Description:
Since recently, vscode builtin "vscode.html" contributes a `snippet`, which trips Theia's snippet parser, throwing it into infinite recursion. The snippet appeared after v1.70.2, and we are noticing it for the first time with unreleased v1.72.2. This extension is tiny, contributing only a Textmate  grammar and a snippet.

Here is the parser that goes into recursive loop when dealing with the contributed snippet:
https://github.com/eclipse-theia/theia/blob/83b726eaf4ceb14e6d2f64ddbf63665a11baf552/packages/monaco/src/browser/monaco-snippet-suggest-provider.ts#L194-L202

``` log
2023-04-19T16:39:20.368Z root INFO Changed application state from 'attached_shell' to 'initialized_layout'.
2023-04-19T16:39:20.440Z root INFO [a237a147-9f5a-4f0f-99d3-b1ff74376554] Sync of 2 plugins: 127.0 ms [Finished 2.093 s after frontend start]
2023-04-19T16:39:20.440Z root INFO [a237a147-9f5a-4f0f-99d3-b1ff74376554] Loading plugin contributions
2023-04-19T16:39:20.440Z root INFO [a237a147-9f5a-4f0f-99d3-b1ff74376554] Load contributions of 2 plugins: 21.0 ms [Finished 2.114 s after frontend start]
2023-04-19T16:39:20.481Z root WARN [a237a147-9f5a-4f0f-99d3-b1ff74376554][vscode.html]: Language for 'source.css' not found.
2023-04-19T16:39:20.482Z root WARN [a237a147-9f5a-4f0f-99d3-b1ff74376554][vscode.html]: Language for 'source.js' not found.
2023-04-19T16:39:20.482Z root WARN [a237a147-9f5a-4f0f-99d3-b1ff74376554][vscode.html]: Language for 'source.python' not found.
2023-04-19T16:39:20.482Z root WARN [a237a147-9f5a-4f0f-99d3-b1ff74376554][vscode.html]: Language for 'source.smarty' not found.
2023-04-19T16:39:20.526Z root ERROR RangeError: Maximum call stack size exceeded
    at Array.values (<anonymous>)
    at MonacoSnippetSuggestProvider.parseSnippets (http://localhost:3000/packages_monaco_lib_browser_monaco-frontend-module_js.js:3122:54)
    at MonacoSnippetSuggestProvider.parseSnippets (http://localhost:3000/packages_monaco_lib_browser_monaco-frontend-module_js.js:3127:22)
    at MonacoSnippetSuggestProvider.parseSnippets (http://localhost:3000/packages_monaco_lib_browser_monaco-frontend-module_js.js:3127:22)
    at MonacoSnippetSuggestProvider.parseSnippets (http://localhost:3000/packages_monaco_lib_browser_monaco-frontend-module_js.js:3127:22)
    at MonacoSnippetSuggestProvider.parseSnippets (http://localhost:3000/packages_monaco_lib_browser_monaco-frontend-module_js.js:3127:22)
    at MonacoSnippetSuggestProvider.parseSnippets (http://localhost:3000/packages_monaco_lib_browser_monaco-frontend-module_js.js:3127:22)
    at MonacoSnippetSuggestProvider.parseSnippets (http://localhost:3000/packages_monaco_lib_browser_monaco-frontend-module_js.js:3127:22)
    at MonacoSnippetSuggestProvider.parseSnippets (http://localhost:3000/packages_monaco_lib_browser_monaco-frontend-module_js.js:3127:22)
    at MonacoSnippetSuggestProvider.parseSnippets (http://localhost:3000/packages_monaco_lib_browser_monaco-frontend-module_js.js:3127:22)

```

### Steps to Reproduce:

1. Build the example application, browser or Electron, from the master branch
2. Delete all extensions from folder `./plugins/`. Unzip `html-1.72.1.zip` into it: 
[html-1.72.1.zip](https://github.com/eclipse-theia/theia/files/11275450/html-1.72.1.zip)
3. Start example app. You should see a similar as above "_RangeError: Maximum call stack size exceeded_" exception

### Additional Information

- Operating System:
- Theia Version:

### PR DESCRIPTION
**Pull request by FernandoAscencio**
#### What it does
Closes #12434

- Changes `parseSnippets` from recursive function to nested for-loops.
- Eliminates 'prefix' requirement for `JsonSerializedSnippet.is()` as it is in VS Code.
- Changes handling to account for missing 'prefix' parameter.
- Add `isFileTemplate` param to Snippet to bring it in line with VSCode.

##### Notes
As discussed [here](https://github.com/FernandoAscencio/theia/pull/24) there are three parameters in VS Code `Snippet` that are not present in Theia's: `snippetSource`, `snippetIdentifier`, and `extensionId`. Their inclusion or exclusion seems to be out of this PR's scope.

When adding a prefix to the error causing snippet as seen [here](https://github.com/FernandoAscencio/theia/pull/24#issuecomment-1521973356) it does not follow VS Code's display as seen [here](https://github.com/FernandoAscencio/theia/pull/24#issuecomment-1522288708).

#### How to test
Follow the steps in #12434.
1. Build the example application, browser or Electron, from the master branch
2. Delete all extensions from folder ./plugins/. Unzip html-1.72.1.zip into it: [html-1.72.1.zip](https://github.com/eclipse-theia/theia/files/11275450/html-1.72.1.zip)
3. Start example app. The error should not appear when loading.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/monaco/src/browser/monaco-snippet-suggest-provider.ts [hunk 1]
```diff
@@ -240,18 +244,20 @@ export interface JsonSerializedSnippets {
     [name: string]: JsonSerializedSnippet | { [name: string]: JsonSerializedSnippet };
 }
 export interface JsonSerializedSnippet {
+    isFileTemplate?: boolean;
     body: string | string[];
-    scope: string;
-    prefix: string | string[];
+    scope?: string;
+    prefix: string | string[] | undefined;
```
Comment (paul-marechal) [inline packages/monaco/src/browser/monaco-snippet-suggest-provider.ts:250]: Nitpick but makes the changes more consistent:

```suggestion
    scope?: string;
    prefix?: string | string[];
```

File: packages/monaco/src/browser/monaco-snippet-suggest-provider.ts [hunk 2]
```diff
@@ -196,7 +197,10 @@ export class MonacoSnippetSuggestProvider implements monaco.languages.Completion
             if (JsonSerializedSnippet.is(scopeOrTemplate)) {
                 accept(name, scopeOrTemplate);
             } else {
-                this.parseSnippets(scopeOrTemplate, accept);
+                // eslint-disable-next-line @typescript-eslint/no-shadow
+                for (const [name, template] of Object.entries(scopeOrTemplate)) {
+                    accept(name, template);
+                }
```
Comment (paul-marechal) [inline packages/monaco/src/browser/monaco-snippet-suggest-provider.ts:203]: This change means you eliminated the recursion, which means `parseSnippet` will ever only dig 2 levels deep within snippets objects (first for-loop on entries, followed by second identical for-loop.)

I'm not familiar with snippets, are there potentially deeper snippets to find? If not then I guess this is OK.

Comment (FernandoAscencio) [reply packages/monaco/src/browser/monaco-snippet-suggest-provider.ts:203]: What I found was that both in VS Code and Theia, `JsonSerializedSnippets` is defined as either a single snippet `JsonSerializedSnippet` or and array `JsonSerializedSnippet[]`. [Here](https://github.com/eclipse-theia/theia/pull/12463/files/a6a9825dabe199a01190e7c6c74371a360084400#:~:text=%7D-,export%20interface%20JsonSerializedSnippets%20%7B,%7D,-export%20interface%20JsonSerializedSnippet)

I don't think it will go deeper than 2 levels. This part is also an almost exact replica of VS Code, so hopefully we will be forewarned if there are relevant changes.

File: packages/monaco/src/browser/monaco-snippet-suggest-provider.ts (hunk 1 above)
Comment (FernandoAscencio) [reply packages/monaco/src/browser/monaco-snippet-suggest-provider.ts]: Makes sense.

**Review by paul-marechal — APPROVED** [review]
I don't see the "maximum stack depth reached" error anymore, LGTM
