### PR TITLE
set focus to terminal that the attached task is running from

### LINKED ISSUE #7407: attaching the same task repeatedly should not open multiple terminals
### Description

Same task can be attached over and over again, producing multiple terminal widgets.
Since we disallow running identical tasks in parallel (https://github.com/eclipse-theia/theia/issues/5269), we should not open more than one terminal widget when the same task is attached for a second time.

### Reproduction Steps

1. Open workspace, start a long running task
2. open a another tab pointing to the same workspace.
3. While the task started in Step 1 is still running, do `Terminal -> Attach Task` from the browser opened in Step 2.
4. Repeat Step 3 multiple times. Theia creates a new terminal widget every time.

Peek 2020-03-23 16-52

**OS and Theia version:**

Ubuntu 18.04. Chrome, example browser.
version 9d59a4e0c51712cb260d29d98061dec0c5f5884c

### PR DESCRIPTION
**Pull request by elaihau**
- Same task can be attached over and over again, producing multiple terminal widgets. With this change, Theia sets focus to the teminal widget that the to-be-attached task is running from. If such terminal widget is not found, Theia creates a new terminal widget for the attached task.

- fixes #7407

Signed-off-by: Liang Huang <lhuang4@ualberta.ca>

#### How to test

1. Start a long running task in a workspace
2. Open the same workspace in a different browser (or browser tab).
3. Attach the long running task in the browser opened in Step 2
4. Repeat Step 3.
Expected: Theia does not open new terminals in Step 4.

Peek 2020-03-30 15-14

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

### CODE REVIEW

File: packages/task/src/browser/task-service.ts [hunk 1]
```diff
@@ -1008,10 +1015,14 @@ export class TaskService implements TaskConfigurationClient {
...
-        widget.start(processId);
+        widget.start(terminalId);
     }
 
     private getTerminalWidgetId(terminalId: number): string {
+        const terminalWidget = this.terminalService.getByTerminalId(terminalId);
+        if (terminalWidget) {
+            return terminalWidget.id;
+        }
         return `${TERMINAL_WIDGET_FACTORY_ID}-${terminalId}`;
```
Comment (akosyakov) [inline packages/task/src/browser/task-service.ts]: it looks like broken abstraction, only the terminal widget factory should know how ids are created, clients should not assume it, otherwise they will be broken if the factory is changed. Should not we return `undefined` rather here? And remove references to `TERMINAL_WIDGET_FACTORY_ID`.

Comment (elaihau) [reply packages/task/src/browser/task-service.ts]: You are right. I removed the line that has the factory id, and re-tested.

File: packages/task/src/browser/task-service.ts [hunk 2]
```diff
@@ -1008,11 +1018,14 @@ export class TaskService implements TaskConfigurationClient {
                 taskConfig: taskInfo ? taskInfo.config : undefined
             }
         );
-        widget.start(processId);
+        widget.start(terminalId);
     }
 
-    private getTerminalWidgetId(terminalId: number): string {
-        return `${TERMINAL_WIDGET_FACTORY_ID}-${terminalId}`;
+    private getTerminalWidgetId(terminalId: number): string | undefined {
```
Comment (RomanNikitenko) [inline packages/task/src/browser/task-service.ts:1024]: could you change the modifier `private` to `protected`

Comment (elaihau) [reply packages/task/src/browser/task-service.ts]: yep, updated the code as suggested in the latest patch. Thank you for the feedback !

File: packages/task/src/browser/task-service.ts [hunk 3]
```diff
@@ -700,12 +700,15 @@ export class TaskService implements TaskConfigurationClient {
...
             if (terminalId) {
-                const terminal = this.terminalService.getById(this.getTerminalWidgetId(terminalId));
-                if (terminal && task.presentation) {
-                    if (task.presentation.focus) { // assign focus to the terminal if presentation.focus is true
-                        this.terminalService.open(terminal, { mode: 'activate' });
-                    } else if (task.presentation.reveal === RevealKind.Always) { // show the terminal but not assign focus
-                        this.terminalService.open(terminal, { mode: 'reveal' });
+                const widgetId = this.getTerminalWidgetId(terminalId);
+                if (widgetId) {
+                    const terminal = this.terminalService.getById(widgetId);
```
Comment (RomanNikitenko) [inline packages/task/src/browser/task-service.ts:705]: could you clarify for me why `getById()` is used here.
I mean you use:
- `getByTerminalId` when `onTaskExit`
- `getByTerminalId` when `onOutputProcessed`

but 
- `this.getTerminalWidgetId(terminalId)` and then `getById()` when task is running

I see you have `terminalId` at this step, but another way is used to get a corresponding terminal.

thanks in advance!

File: packages/task/src/browser/task-service.ts (hunk 2 above)
Comment (RomanNikitenko) [reply packages/task/src/browser/task-service.ts]: thanks!

File: packages/terminal/src/browser/base/terminal-service.ts [hunk 4]
```diff
@@ -46,6 +46,12 @@ export interface TerminalService {
      */
     getById(id: string): TerminalWidget | undefined;
 
+    /**
+     * @param id - the terminal id (NOT the terminal widget id!)
+     * @return the widget
+     */
+    getByTerminalId(terminalId: number): TerminalWidget | undefined;
```
Comment (RomanNikitenko) [inline packages/terminal/src/browser/base/terminal-service.ts:53]: I think adding a new method to interface should be mentioned as `breaking changes` in `changelog`

Comment (akosyakov) [reply packages/terminal/src/browser/base/terminal-service.ts:53]: we can, but I don't think anyone implements it. This interface should be removed and clients should use `TerminalFrontendContribution` directly.

It is unnecessary boilerplate and we don't encourage it: https://github.com/eclipse-theia/theia/wiki/Coding-Guidelines#classes-over-interfaces

Also we don't require a breaking change notice only if there is a sufficient adoption for experimental API:  https://github.com/eclipse-theia/theia/blob/master/doc/api-management.md#experimental I believe there is only one implementation `TerminalFrontendContribution`.

Comment (akosyakov) [reply packages/terminal/src/browser/base/terminal-service.ts:53]: @elaihau Could you file an issue to remove `TheiaWidget` and `TheiaService` interfaces and rename `TerminalWidgetImpl` to `TerminalWidget`. We could do it via deprecation for clients accessing it, i.e. existing interfaces can extend `TerminalWidget` and `TerminalFrontendContribution` and tell to use them instead.

Comment (RomanNikitenko) [reply packages/terminal/src/browser/base/terminal-service.ts:53]: @akosyakov 
> we can, but I don't think anyone implements it.

I don't know if anyone implements it...

> It is unnecessary boilerplate and we don't encourage it

I totally agree with you, but at the moment there is an interface and, as I mentioned above, I don't know if anyone implements it. I pointed out that, but at your discretion...

> Also we don't require a breaking change notice only if there is a sufficient adoption for experimental API

thanks for the explanation!

File: packages/task/src/browser/task-service.ts (hunk 3 above)
Comment (RomanNikitenko) [reply packages/task/src/browser/task-service.ts:705]: moreover, `getTerminalWidgetId()` uses `getByTerminalId()` inside.

`this.getTerminalWidgetId(terminalId)` ->
`this.terminalService.getByTerminalId(terminalId)`->  you have terminal at this step ->
`terminalWidget.id` -> 
`this.terminalService.getById(widgetId)`

Looks strange for me...

Comment (elaihau) [reply packages/task/src/browser/task-service.ts:705]: Yes you are right. With the new function `terminalService.getByTerminalId()` added I can get the terminal instance directly from all places.

File: packages/terminal/src/browser/base/terminal-service.ts (hunk 4 above)
Comment (elaihau) [reply packages/terminal/src/browser/base/terminal-service.ts:53]: > @elaihau Could you file an issue to remove `TheiaWidget` and `TheiaService` interfaces 

@akosyakov 
Just want to confirm with you: you meant `TerminalWidget` and `TerminalService`, did you?

Comment (akosyakov) [reply packages/terminal/src/browser/base/terminal-service.ts:53]: yes, sorry 🤦‍♂
