### PR TITLE
[quick-open] Do not validate input on start

### LINKED ISSUE #6245: [quick open] Quick input validation handler fires on widget start
### Description
 
Quick input validation handler begins to validate when the widget just started. If the validation is set up to show an error on empty string, the error will be shown right after the input is called without any text. 
### Reproduction Steps

1. Clone and compile the [test plugin](https://github.com/vinokurig/Test.git)
2. Start the plugin as a Hosted Plugin
3. `F1` => `Hello World`

**WRONG** The validation  error appears.
Expected: The validation **must not** be called on the start. If the input is accepted without any text the validation **must** be called before the acceptation.
**OS and Theia version:**

**Diagnostics:**

### PR DESCRIPTION
**Pull request by vinokurig**
#### What it does

Check if the `onType` handler is fired at first time, ignore validating the input. As `QuickInputService` wraps `QuickOpenServece`:
https://github.com/eclipse-theia/theia/blob/5e50106058fd05d76e8e18010aff3ec398c48e45/packages/core/src/browser/quick-open/quick-input-service.ts#L123
 such workaround can resolve the problem.
fixes #6245 
#### How to test

1. Clone and compile the [test plugin](https://github.com/vinokurig/Test.git)
2. Start the plugin as a Hosted Plugin
3. `F1` => `Hello World`

**See**: The validation is not called on the start.
#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
@vinokurig Does it close any issues? Could you reference them please?

**Comment by vinokurig** [comment]
@akosyakov 
> Does it close any issues? Could you reference them please?

Updated description.

File: packages/core/src/browser/quick-open/quick-input-service.ts [hunk 1]
```diff
@@ -119,11 +119,17 @@ export class QuickInputService {
         let label = prompt;
         let currentText = '';
         const validateInput = options && options.validateInput;
+        let initial: boolean = true;
```
Comment (akosyakov) [inline packages/core/src/browser/quick-open/quick-input-service.ts]: Should it be reset to `false` when a quick input is closed?
