### PR TITLE
#6308: Close websocket channel when a language server connection is closed

### LINKED ISSUE #6308: Client is not notified when language server process terminates
### Description
I have a language server that terminates with an exit code in certain situations due to a fatal error. That's bad, but what's even worse is that the Theia frontend doesn't know about it and so it does not trigger a restart. Even an explicit restart through the respective command does not create a new language server process.

### Reproduction Steps
Create a LanguageServerContribution that spawns a terminating command like this:
```typescript
const serverConnection = await this.createProcessStreamConnectionAsync(command, args);
this.forward(clientConnection, serverConnection);
```

**OS and Theia version:**
macOS 10.14.6, Theia 0.11.0-next.fbd63c5d

**Diagnostics:** 
This workaround helps:
```typescript
serverConnection.onClose(() => (clientConnection as any).reader.socket.close());
```

### PR DESCRIPTION
**Pull request by spoenemann**
#### What it does
Fixes #6308.

#### How to test
Add the following line to `json-starter.ts`
```typescript
setTimeout(() => process.exit(1), 5000);
```
Without this fix, the JSON language server stops working after 5 seconds. With the fix, the server is restarted every 5 seconds.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/core/src/node/messaging/messaging-service.ts [hunk 1]
```diff
@@ -54,3 +54,18 @@ export namespace MessagingService {
         configure(service: MessagingService): void;
     }
 }
+
+export interface WebSocketConnection extends IConnection {
```
Comment (spoenemann) [inline packages/core/src/node/messaging/messaging-service.ts]: This might be moved to `vscode-ws-jsonrpc` later.

File: packages/core/src/common/messaging/web-socket-channel.ts [hunk 2]
```diff
@@ -93,6 +93,20 @@ export class WebSocketChannel implements IWebSocket {
         this.fireClose(code, reason);
     }
 
+    tryClose(code: number = 1000, reason: string = ''): void {
```
Comment (marechal-p) [inline packages/core/src/common/messaging/web-socket-channel.ts]: The only difference with `close` is that this one doesn't throw. Is it really required?

We could make `close` not throw anymore? No internal client is actually wrapping it in a throw/catch clause either...

I am fine with the current change, but I am curious.

File: packages/core/src/node/messaging/messaging-service.ts [hunk 3]
```diff
@@ -54,3 +54,18 @@ export namespace MessagingService {
...
+    channel: WebSocketChannel;
+}
+export namespace WebSocketConnection {
+    export function is(connection: IConnection): connection is WebSocketConnection {
+        return (connection as WebSocketConnection).channel instanceof WebSocketChannel;
+    }
+
+    export function create(connection: IConnection, channel: WebSocketChannel): WebSocketConnection {
+        const result = connection as WebSocketConnection;
+        result.channel = channel;
```
Comment (marechal-p) [inline packages/core/src/node/messaging/messaging-service.ts]: Conceptually speaking, is this not slightly bogus? Technically, there is supposed to be `n` channels for 1 given connection, so should you rather convert this `channel` property into a `channels` list, pushing new channels into it, and closing them all on close?

File: packages/core/src/common/messaging/web-socket-channel.ts (hunk 2 above)
Comment (spoenemann) [reply packages/core/src/common/messaging/web-socket-channel.ts]: If I use `close` instead of `tryClose` in BaseLanguageServerContribution, an "already disposed" error is thrown occasionally on page reload.

I think it's fine for `close` to throw on disposed because it's expected to send a message to the other endpoint. We could also add another optional parameter instead of a separate method, though.

File: packages/core/src/node/messaging/messaging-service.ts (hunk 3 above)
Comment (spoenemann) [reply packages/core/src/node/messaging/messaging-service.ts]: No, every `IConnection` that is established through a WebSocketChannel has exactly one associated channel. `IConnection` is not the raw WebSocket connection, but rather a wrapper around a reader and a writer for a single channel.

We should eliminate this helper method by moving the new `WebSocketConnection` interface to `vscode-ws-jsonrpc`, but IMO that could be done after merging this.

Comment (marechal-p) [reply packages/core/src/node/messaging/messaging-service.ts]: Ok, got confused by the name. Can you rename it `WebSocketChannelConnection`?
