### PR TITLE
Fix breakpoint expression resizing

### LINKED ISSUE #9526: Breakpoint expression input field does not auto resize
### Bug Description:
When trying to add a conditional breakpoint or logpoint to an editor, the input field does not automatically resize. This can make reading the placeholder message or the input expression quite difficult.

bad-resizing

### Steps to Reproduce:

1. Open a source code file (or a file in which you can set a breakpoint)
2. Make the window size fairly narrow
3. Right click in editor's the left gutter to "Add Conditional Breakpoint" or "Add Logpoint"
4. Maximize the window and observe that the input field does not resize

### Additional Information

- Operating System: Linux
- Theia Version: Master (Electron and Browser)

### PR DESCRIPTION
**Pull request by kenneth-marut-work**
#### What it does

Fixes #9526 by adding a resize handler to the debug-breakpoint-widget's input editor. It also adds a resize emitter on the MonacoEditor so that resize events from a parent Widget can be forwarded when necessary.

#### How to test

Follow the steps outlined in #9526, and observe that the expression input field *does* resize when the the window is maximized

good-resizing

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/debug/src/browser/editor/debug-breakpoint-widget.tsx [hunk 1]
```diff
@@ -82,18 +90,17 @@ export class DebugBreakpointWidget implements Disposable {
         const inputNode = document.createElement('div');
         inputNode.classList.add('theia-debug-breakpoint-input');
         this.zone.containerNode.appendChild(inputNode);
-
-        const input = this._input = await this.createInput(inputNode);
+        this.expressionInput = this._input = await this.createInput(inputNode);
```
Comment (colin-grant-work) [inline packages/debug/src/browser/editor/debug-breakpoint-widget.tsx:93]: This seems a bit odd. Why the two fields, `this.expressionInput` and `this._input`?

File: packages/monaco/src/browser/monaco-editor.ts [hunk 2]
```diff
@@ -357,6 +360,7 @@ export class MonacoEditor extends MonacoEditorServices implements TextEditor {
         if (this.node) {
             const layoutSize = this.computeLayoutSize(this.node, dimension);
             this.editor.layout(layoutSize);
+            this.onResizeEmitter.fire(undefined);
```
Comment (colin-grant-work) [inline packages/monaco/src/browser/monaco-editor.ts:363]: Why fire this event here if it's always going to be `undefined`?

File: packages/debug/src/browser/editor/debug-breakpoint-widget.tsx (hunk 1 above)
Comment (kenneth-marut-work) [reply packages/debug/src/browser/editor/debug-breakpoint-widget.tsx]: Thanks for catching this, I had renamed the input field without seeing this member variable to const reassignment. I've reverted this change and kept the original name to avoid any breakage.

File: packages/monaco/src/browser/monaco-editor.ts (hunk 2 above)
Comment (kenneth-marut-work) [reply packages/monaco/src/browser/monaco-editor.ts]: Another good catch, I had intended for the `undefined` case to be handled by forwarding the request to the editor's `resizeToFit` method but hadn't handled it properly in the setter. This should be fixed now.

File: packages/monaco/src/browser/monaco-editor.ts [hunk 3]
```diff
@@ -84,6 +84,9 @@ export class MonacoEditor extends MonacoEditorServices implements TextEditor {
     readonly onLanguageChanged = this.onLanguageChangedEmitter.event;
     protected readonly onScrollChangedEmitter = new Emitter<void>();
     readonly onEncodingChanged = this.document.onDidChangeEncoding;
+    // eslint-disable-next-line no-null/no-null
+    protected readonly onResizeEmitter = new Emitter<Dimension | null>();
+    readonly onResized = this.onResizeEmitter.event;
```
Comment (colin-grant-work) [inline packages/monaco/src/browser/monaco-editor.ts:89]: I think [the guidelines](https://github.com/eclipse-theia/theia/wiki/Coding-Guidelines#event_names) would likely prefer `onDidResize` unless there's a conflict with that name?

**Review by colin-grant-work — APPROVED** [review]
I confirm that this change allows the breakpoint widget to resize with the editor widget.

File: packages/monaco/src/browser/monaco-editor.ts (hunk 3 above)
Comment (kenneth-marut-work) [reply packages/monaco/src/browser/monaco-editor.ts]: No problem, I've renamed this value and squashed the commits
