### PR TITLE
Fix inline breakpoints

### LINKED ISSUE #6910: [debug][ui] Inline breakpoint markers on 0 column
### Description
image

### Reproduction Steps
 1. Set breakpoints in test
 1. Run test case with mocha and `--inspect-brk`
 1. Connect via `Debug` -> `Attach to Process`, continue to breakpoint
 1. Reload frontend
Observe: Sometimes, _some_ of the breakpoints (?) are now in column 0.

**OS and Theia version:**
 - OS: Linux Mint 19.3
 - Theia: `next.df9c87b2`

**Diagnostics:** 
none

### PR DESCRIPTION
**Pull request by justinang1**
Issue: #7114 

#### What it does

- Fixes breakpoints that are rendered on the first column, as they become inline. 
- May also resolve #6910.

#### How to test

- Open sample file and create a breakpoint without any indentation (on the first column). Run command "Copy Line Down" from Selection Tab or through Find Command. 
- New line should retain breakpoint marker but it will no longer be inline. 
- Breakpoints created with indentation will still have indented breakpoint marker when copied. 

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
@tom-shan Could you try please?

File: packages/debug/src/browser/editor/debug-editor-model.ts [hunk 1]
```diff
@@ -222,7 +222,7 @@ export class DebugEditorModel implements Disposable {
                 glyphMarginClassName: className,
                 glyphMarginHoverMessage: message.map(value => ({ value })),
                 stickiness: DebugEditorModel.STICKINESS,
-                beforeContentClassName: typeof column === 'number' ? `theia-debug-breakpoint-column ${className}-column` : undefined
+                beforeContentClassName: typeof column === 'number' ? (column > 1 ? `theia-debug-breakpoint-column ${className}-column` : undefined) : undefined
```
Comment (akosyakov) [inline packages/debug/src/browser/editor/debug-editor-model.ts]: please align with https://github.com/microsoft/vscode/blob/355eea22ea9a98a5d0517ffeae5bd176e96bb185/src/vs/workbench/contrib/debug/browser/breakpointEditorContribution.ts#L95

it is the complete solution

Comment (justinang1) [reply packages/debug/src/browser/editor/debug-editor-model.ts]: I've changed the code to mirror the vscode logic. However, I did not find a getLineFirstNonWhitespaceColumn function in the breakpoint class, so instead I assigned a constant and made a comparison against that constant. 

Should I look to implement the getLineFirstNonWhitespaceColumn function instead?

Comment (tom-shan) [reply packages/debug/src/browser/editor/debug-editor-model.ts]: this function exists refer to https://github.com/TypeFox/vscode/blob/monaco/0.18.0/src/vs/editor/common/model/textModel.ts#L798 so just use it

File: packages/debug/src/browser/editor/debug-editor-model.ts [hunk 2]
```diff
@@ -216,13 +216,15 @@ export class DebugEditorModel implements Disposable {
         const column = breakpoint.column;
         const range = typeof column === 'number' ? new monaco.Range(lineNumber, column, lineNumber, column + 1) : new monaco.Range(lineNumber, 1, lineNumber, 1);
         const { className, message } = breakpoint.getDecoration();
+        const firstNonWhitespaceColumn = 1;
```
Comment (akosyakov) [inline packages/debug/src/browser/editor/debug-editor-model.ts]: but it should no be no 1, but computed as in link which I sent yesterday, i.e. first non whitespace character

File: packages/debug/src/browser/editor/debug-editor-model.ts (hunk 1 above)
Comment (akosyakov) [reply packages/debug/src/browser/editor/debug-editor-model.ts]: `this.editor.getControl().getModel()!.getLineFirstNonWhitespaceColumn()`

**Comment by justinang1** [comment]
> thank you! merging if build is green

Sure, let me know if there's any issues.

Sorry for having to loop you in so many times.

**Comment by akosyakov** [comment]
> Sorry for having to loop you in so many times.

it is fine, usually I'm the one who sorry to keep others iterating on PRs 😆
