### PR TITLE
[theming] fix hardcoded search result overview ruler color

### LINKED ISSUE #6819: [theming] search result's color in overview ruler is hardcoded
**Description**

The search result decoration in the `overviewRuler` is currently hardcoded, and at the moment it looks like there are either errors in the file, or there are deletions:

https://github.com/eclipse-theia/theia/blob/ec2a8663ee51a0bcb67c93db918cd2932b4bfc3e/packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx#L761-L763

Screen Shot 2020-01-03 at 4 19 19 PM

The correct way would be to allow themes to update the value.

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

Fixes #6819

- fixes the hardcoded value for the `overviewRuler` to instead use theme color when a search result is present.
- aligns the `overviewRuler` decoration position with VS Code.

| Before | After |
|:---:|:---:|
| Screen Shot 2020-01-03 at 4 19 19 PM | Screen Shot 2020-01-03 at 4 22 29 PM |

#### How to test

1. verify with multiple themes
2. perform a search through the `search-in-workspace` widget, the decoration should be fixed

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
@akosyakov please let me know if this is the correct approach, and or if it can be simplified further.

File: packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx [hunk 1]
```diff
@@ -759,8 +764,8 @@ export class SearchInWorkspaceResultTreeWidget extends TreeWidget {
                     },
                     options: {
                         overviewRuler: {
-                            color: 'rgba(230, 0, 0, 1)',
```
Comment (akosyakov) [inline packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx]: have you tried 'var(--theia-editor-findMatchHighlightBackground)'? coding guidelines explain how css variable name is derived from variable name: https://github.com/eclipse-theia/theia/wiki/Coding-Guidelines#theming-no-css-color-values

**Comment by akosyakov** [comment]
It also would be good to look at VS Code codebase and see which variable do they use.

File: packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx (hunk 1 above)
Comment (vince-fugnitto) [reply packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx]: Yes, unfortunately, it does not work to use:
```ts
'var(--theia-editor-findMatchHighlightBackground)'
```

**Comment by vince-fugnitto** [comment]
> It also would be good to look at VS Code codebase and see which variable do they use.

I based it off the following from the VS Code sources:
https://github.com/microsoft/vscode/blob/ee8eb463a26aed6b728db81bcd85c21cf68beec5/src/vs/workbench/contrib/search/common/searchModel.ts#L155-L180

File: packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx [hunk 2]
```diff
@@ -744,6 +746,9 @@ export class SearchInWorkspaceResultTreeWidget extends TreeWidget {
 
     protected createEditorDecorations(resultNode: SearchInWorkspaceFileNode | undefined): EditorDecoration[] {
         const decorations: EditorDecoration[] = [];
+        const findMatchHighlightBackground = typeof this.colorRegistry.getCurrentColor('editor.findMatchHighlightBackground') !== undefined
```
Comment (akosyakov) [inline packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx]: why to query twice and not simply use a result of `this.colorRegistry.getCurrentColor('editor.findMatchHighlightBackground')`?

File: packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx (hunk 1 above)
Comment (akosyakov) [reply packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx]: ok

File: packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx (hunk 2 above)
Comment (vince-fugnitto) [reply packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx]: Thank you for your feedback, I've updated the code to only query once :)
