### PR TITLE
VS Code like theming (colors and icons)

### LINKED ISSUE #1486: fine-grained CSS variables
We use CSS variables for theming. Right now most of the variables are generic and changing them can break some parts of UI. It would be nice to introduce semantic specific CSS variables to have more fine-grained control.

### LINKED ISSUE #4831: support vscode theming
See https://code.visualstudio.com/api/extension-capabilities/theming

### LINKED ISSUE #6300: [vscode] vscode-icons extension doesn't work
### Description
It seems that the [vscode-icons](https://github.com/vscode-icons/vscode-icons/releases) extension doesn't work in Theia:

> When installing the extension vsicons the icons don't change and this shows up in preferences
> image

(from the original issue https://github.com/gitpod-io/gitpod/issues/818)

### Reproduction Steps

1. Install https://github.com/vscode-icons/vscode-icons/releases in Theia
2. The icons don't change. Also, this error shows up in user preferences:

```
Property workbench.iconTheme is not allowed
```

**OS and Theia version:** `master`

**Diagnostics:**

### LINKED ISSUE #6747: [Filesystem] When a file tree node is cached, it's not possible to overwrite its name and icon
### Description
 

When a file tree node is cached (especially after a move operation), it's not possible to overwrite its name and icon.

### Reproduction Steps

Reproducing the issue is not really straightforward.

My situation was a contribution for a new icon for files with some specific extension.

When a file with that extension is moved, the new icon might get lost and substituted by the default one.

**OS and Theia version:**

Ubuntu 18.04, Theia master branch

**Diagnostics:**

### LINKED ISSUE #6776: file-icons vscode extension does not work
https://marketplace.visualstudio.com/items?itemName=file-icons.file-icons doesn't work

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

fix #4831, fix #1486, fix #6300, fix #6747, fix #6776

- [x] (core) allow to register and use colors
  - Theia extensions can register new colors.
  - All colors are translated into css variables with `.` replaced by `-` and `--theia` prefix
  - Theia extensions can use registered colors via css or programatically from `ColorRegistrsy.getCurrentColor`
- [x] (plugin) hook [themes contribution point](https://code.visualstudio.com/api/references/contribution-points#contributes.themes) @akosyakov 
  - [x] json files
  - [x] tmTheme files
  - [x] Theia extensions should use `MonacoThemingService.register` to contribute new themes
- [x] (plugin) hook [colors contribution point](https://code.visualstudio.com/api/references/contribution-points#contributes.colors) @akosyakov 
- [x] (monaco) preserve themes between user sessions and reconnections @akosyakov 
- [x] register missing [VS Code colors](https://code.visualstudio.com/api/references/theme-color) from corresponding Theia extension, see https://github.com/eclipse-theia/theia/pull/6722
  - Base colors are reused from Monaco, one has to check what is missing by inspecting them.
  - restyle Theia extensions
  - remove existing css variables
- [x] define color theming coding guidelines
  - [x] make sure that colors are not defined in css anymore, i.e. `--theia-ui-font-color` and `--theia-layout-color` are not used
- [x] update CHANGELOG with breaking changes
- [x] (core) allow to register and select icon themes
  - [x] register existing theme
  - [x] register None theme to disable icon themes
  - [x] deprecate `name`, `description` and `icon` for tree nodes, use `LabelProvider` instead to avoid storing them in the local storage and compute synchronously only demand only for visible UI nodes
- [x] (plugin) hook [icon theme contribution point](https://code.visualstudio.com/api/extension-guides/icon-theme)
  - [x] icon definitions from paths
  - [x] preserve current icon theme between reloads
  - [x] icon definitions based on font definitions
  - [x] icon associations
  - [x] overriding icon associations for different color themes
- [x] (core) align theming commands and preferences with VS Code 
- [x] a CQ for copied code: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21223
- [x] fix tests
- [x] review places where `FOLDER_ICON`  and `FILE_ICON` are used
- [x] local storage runs out of memory sometimes -> theme data are stored in indexeddb instead
- [x] debug console tab does not have icon
- [x] in offline mode for One Dark Pro theme status bar elements are bogusly highlighted while hovering over them
- [x] status bar coloring while debugging a program
- [x] custom default dark/light Theia themes, in light theme activity bar should be light as well
- [x] outline show duplicate elements

#### How to test

- uninstall `@theia/git` theia extension in the browser app
- install following VS Code extensions under `plugins` folder:
  - https://registry.npmjs.org/@theia/vscode-builtin-theme-defaults/-/vscode-builtin-theme-defaults-0.2.1.tgz to test default themes
  - https://registry.npmjs.org/@theia/vscode-builtin-vscode-theme-seti/-/vscode-builtin-vscode-theme-seti-0.3.0-next.2111655b67.tgz to test default VS Code icon theme
  - https://registry.npmjs.org/@theia/vscode-builtin-theme-red/-/vscode-builtin-theme-red-0.2.1.tgz and https://registry.npmjs.org/@theia/vscode-builtin-theme-tomorrow-night-blue/-/vscode-builtin-theme-tomorrow-night-blue-0.2.1.tgz to test custom themes (red and night)
  - https://registry.npmjs.org/@theia/vscode-builtin-git/-/vscode-builtin-git-0.2.1.tgz to test custom colors for git decorations in the navigator and scm views
  - https://github.com/microsoft/vscode-extension-samples/tree/master/theme-sample to test loading of color themes from tsTheme files
- check whether following UI respect icon theme switch:
  - [x] `@theia/editor`
    - [x] Quick Pick Editor Language
    - [x] Editor Quick Open
    - [x] Editor Title
      - [x] side areas
      - [x] main/bottom areas
    - [x] Diff Editor Title
  - [x] `@theia/filesystem`
    - [x] Quick File Open
    - [x] Open/Save File Dialog
  - [x] `@theia/navigator` - Navigator View
  - [x] `@theia/markers` - Problems View
  - [x] `@theia/git`
    - [x] SCM View
    - [x] Git Diff
    - [x] Git Commit Detail
    - [x] Git History
  - [x] `@theia/plugin-ext`
    - [x] SCM widget with git vscode built-in extension
    - [x] Tree Views
  - [x] `@theia/search-in-workspace` - Search View
  - [x] `@theia/workspace` - Quick Open Workspace
- https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme to test hides `hidesExplorerArrows`

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
It's a temporary PR against the webview PR, don't merge it!

@jbicker please see `What it does`, it explains what is your part. We can discuss it next Tuesday face to face.

I'm going to hook VS Code contribution points that you can also test against VS Code extensions and then go back to the webview PR.

**Comment by akosyakov** [comment]
I've hooked up theme contribution from VS Code extensions for JSON files.

@jbicker You can install download following themes and put them under `plugins` folder to install for testing:
- https://registry.npmjs.org/@theia/vscode-builtin-theme-red/-/vscode-builtin-theme-red-0.2.1.tgz
- https://registry.npmjs.org/@theia/vscode-builtin-theme-tomorrow-night-blue/-/vscode-builtin-theme-tomorrow-night-blue-0.2.1.tgz

Right now theming is only applied to editors and webviews:
theming

File: packages/monaco/src/typings/monaco/index.d.ts [hunk 1]
```diff
@@ -537,8 +537,15 @@ declare module monaco.color {
     export interface ColorContribution {
         readonly id: string;
     }
+    export interface ColorDefaults {
+        ligh?: string;
```
Comment (svenefftinge) [inline packages/monaco/src/typings/monaco/index.d.ts]: typo -> `light`

**Comment by akosyakov** [comment]
@jbicker I've finished my part, all VS Code extension contribution points are respected, please see `How to test` section.

**Comment by akosyakov** [comment]
Instant switching between the default theme and no icon files theme:
none_theme

File: examples/api-samples/src/browser/sample-dynamic-label-provider-contribution.ts [hunk 2]
```diff
@@ -58,7 +58,7 @@ export class SampleDynamicLabelProviderContribution extends DefaultUriLabelProvi
         return new URI(element.toString());
     }
 
-    async getIcon(element: URI): Promise<string> {
+    getIcon(element: URI): string {
```
Comment (akosyakov) [inline examples/api-samples/src/browser/sample-dynamic-label-provider-contribution.ts]: - [ ] (breaking) document that `LabelProviderContribution.getIcon` should be fast and async to avoid blocking rendering and remove icon caching from (tree) nodes

File: packages/core/src/browser/label-provider.ts [hunk 3]
```diff
@@ -38,25 +38,31 @@ export interface LabelProviderContribution {
     /**
      * returns an icon class for the given element.
      */
-    getIcon?(element: object): MaybePromise<string>;
+    getIcon?(element: object): string | undefined;
```
Comment (akosyakov) [inline packages/core/src/browser/label-provider.ts]: - [ ] document that `undefined` means try next

File: packages/core/src/browser/label-provider.ts [hunk 4]
```diff
@@ -38,25 +38,31 @@ export interface LabelProviderContribution {
...
      */
     readonly onDidChange?: Event<DidChangeLabelEvent>;
 
-    readonly getConstituentUris?: (compositeElement: object) => URI[];
+    /**
+     * Check whether the given element is affected by the given change event.
+     * Contributions delegating to the label provider can use this hook
+     * to perfrom a recursive check.
+     */
+    affects?(element: object, event: DidChangeLabelEvent): boolean;
```
Comment (akosyakov) [inline packages/core/src/browser/label-provider.ts]: @westbury I've removed dependencies to `URI` with such method

File: packages/core/src/browser/label-provider.ts [hunk 5]
```diff
@@ -73,7 +79,7 @@ export class DefaultUriLabelProviderContribution implements LabelProviderContrib
         return 0;
     }
 
-    getIcon(uri: URI): MaybePromise<string> {
+    getIcon(uri: URI): string {
```
Comment (akosyakov) [inline packages/core/src/browser/label-provider.ts]: the same as https://github.com/eclipse-theia/theia/pull/6475/commits/2795c7ecf6644c2e0d823562fe59a70af522781b#r350290387

File: packages/core/src/browser/tree/tree.ts [hunk 6]
```diff
@@ -65,14 +65,20 @@ export interface TreeNode {
     readonly id: string;
     /**
      * A human-readable name of this tree node.
+     *
+     * @deprecated use `LabelProvider.getName` instead or move this property to your tree node type
```
Comment (akosyakov) [inline packages/core/src/browser/tree/tree.ts]: - [ ] document how `LabelProviderContribution` should be used to customize appearance of the tree node across the application

**Comment by akosyakov** [comment]
Getting closer :)
minimal_theme

File: packages/core/src/browser/label-provider.ts (hunk 4 above)
Comment (westbury) [reply packages/core/src/browser/label-provider.ts]: That almost solves it.  However consider two URLs A and B combined into a diff {A,B} .  Now take a diff between that diff file and a third file C, so we have {{A,B},C}.  I know we should not get such a URI but as far as the label providers are concerned, this is supported.  Pass in the URI for {{A,B},C} together with an event that affects A only.  The implementation in DiffUris.affects will pass the URIs for {A,B} and C directly to the event and will not detect the change.

**Comment by akosyakov** [comment]
Complete support of icon theming in the explorer:
material

File: packages/core/src/browser/label-provider.ts [hunk 7]
```diff
@@ -114,52 +120,24 @@ export class LabelProvider implements FrontendApplicationContribution {
...
-                        }
-                    }
-                }
+    protected affects(element: object, event: DidChangeLabelEvent): boolean {
+        if (event.affects(element)) {
+            return true;
+        }
+        for (const contribution of this.findContribution(element)) {
+            if (contribution.affects && contribution.affects(element, event)) {
+                return true;
```
[the remark this answers is not in the document]
Comment (akosyakov) [reply packages/core/src/browser/label-provider.ts]: I don't think that the code before was correct, i.e an order given by `canHandle` should be used. We should not sort to get some other order. Also I don't get how it is possible to not fire an event from second contribution, for some elements it can return a value for other not. It should be guarded by `canHandle` and did change event implementations. If a client then calls `affects` it can decide to skip refreshing itself or can always do it if it is cheap.

File: packages/core/src/browser/label-provider.ts [hunk 8]
```diff
@@ -169,31 +147,40 @@ export class LabelProvider implements FrontendApplicationContribution {
...
-        if (!contrib) {
-            return '';
+    getIcon(element: object): string {
+        const contributions = this.findContribution(element);
+        for (const contribution of contributions) {
+            const value = contribution.getIcon && contribution.getIcon(element);
+            if (value === undefined) {
+                continue;
+            }
+            return value;
```
[the remark this answers is not in the document]
Comment (akosyakov) [reply packages/core/src/browser/label-provider.ts]: One can install a marker property on the passed element and call `LabelProvider` again. If a a marker property is installed `canHandle` should then return `false`. It won't require any API breaking. btw what is the concrete use case for it? While working of icon theming switches I could not find any need. The pattern is that a new contribution are introduced on the top to provide more specialited logic, i.e. see:
- https://github.com/eclipse-theia/theia/blob/0fdf16575106ef7bc2b895309accb35711dac672/packages/filesystem/src/browser/file-tree/file-tree-label-provider.ts#L23
- https://github.com/eclipse-theia/theia/blob/0fdf16575106ef7bc2b895309accb35711dac672/packages/plugin-ext/src/main/browser/plugin-icon-theme-service.ts#L553
- https://github.com/eclipse-theia/theia/blob/0fdf16575106ef7bc2b895309accb35711dac672/packages/plugin-ext/src/main/browser/view/plugin-tree-view-node-label-provider.ts#L35

File: packages/core/src/browser/label-provider.ts (hunk 4 above)
Comment (akosyakov) [reply packages/core/src/browser/label-provider.ts]: Is there a real case? I can solve it by passing affects fn which does recursive check, but it introduces all kind of complexity, like what if `C` can be broke down to A and B again. How do stop recursion? I would prefer to avoid make it complex trying to solve imaginary issues.

**Comment by akosyakov** [comment]
most popular VS Code theme applied to Theia
Screen Shot 2019-12-12 at 11 09 49

File: yarn.lock [hunk 9]
```diff
@@ -6450,6 +6455,11 @@ icss-utils@^2.1.0:
   dependencies:
     postcss "^6.0.1"
 
+idb@^4.0.5:
```
Comment (akosyakov) [inline yarn.lock]: @marcdumais is `ISC` fine? i hope it is using indexeddb api otherwise is very tedious :(

**Comment by akosyakov** [comment]
@eclipse-theia/ecd-theia-committers that's ready for testing, I still have to update CHANGELOG and write down coding guidelines for theming, but rather than that one should be able to test default Theia themes, install VS Code extensions contributing file icon and color themes

File: yarn.lock (hunk 9 above)
Comment (marcdumais-work) [reply yarn.lock]: yes, `ISC` is an Eclipse Foundation approved license

**Comment by vince-fugnitto** [comment]
I noticed that the divider in the default light theme looks a bit too dark (if it is intended please ignore my comment). The menu also looks off as in the alignment:

image

image

**Comment by akosyakov** [comment]
@vince-fugnitto thanks for testing! Please don't hesitate if something looks weird. The thing is that base colors should be derived from VS Code colors, that their themes look the same, but then we have Theia themes and there we can change values as we want, e.g. for example in Theia light theme the activity bar is light gray as before, not dark as in VS Code light.

File: CHANGELOG.md [hunk 10]
```diff
@@ -13,6 +13,60 @@ Breaking changes:
 - [debug] renamed getter method `multiSesssion` to `multiSession` [#6698](https://github.com/eclipse-theia/theia/pull/6698)
 - [task] changed the data structure of `ProvidedTaskConfigurations.tasksMap` [#6718](https://github.com/eclipse-theia/theia/pull/6718)
 - [task] added `taskDefinitionRegistry` and `taskSourceResolver` to the constructor of `TaskRunQuickOpenItem` and `ConfigureBuildOrTestTaskQuickOpenItem` [#6718](https://github.com/eclipse-theia/theia/pull/6718)
+- Support VS Code icon and color theming. [#6475](https://github.com/eclipse-theia/theia/pull/6475)
```
Comment (akosyakov) [inline CHANGELOG.md]: @eclipse-theia/ecd-theia-committers Here is a list of breaking changes. Is it clear what should be done to deal with them?

We plan it to land after 0.14 release that it was in for the entire next month and released as a part of 0.15.

**Comment by akosyakov** [comment]
vscode-icons works generally nicely, but `Apply Icons Customizations` break folder icons, it is because we mutate the schema configuration from the plugin metadata, see https://github.com/eclipse-theia/theia/pull/4070#discussion_r360339722 Unfortunately from https://github.com/eclipse-theia/theia/pull/4070 it is not clear how to reproduce the original issue. I'm going to revert mutation of plugin configurations and we will need to fix the original issue (whatever it was) differently. cc @tolusha @benoitf

**Comment by akosyakov** [comment]
> I noticed that the tab editor label becomes dark even though the editor is still visible. This is a different behavior than that of VS Code.

@vince-fugnitto It is like in VS Code:
Screen Shot 2019-12-20 at 16 06 58

The issue is in the definition of focused and last editor. In Theia only one shell widget can be focused according to `document.activeElement`. In VS Code though they treat last editor as focused. You can see in the image above that with many editor groups, the editor also becomes gray even though it is still visible in the first group.

**Comment by akosyakov** [comment]
@vince-fugnitto I've removed shadowing over focused menu item that a context menu looks a bit more aligned with it. Regarding the separator, yes it is expected in VS Code themes. For Theia light theme we can change it to a bit brighter if you like. I suggest that such fine tuning of our theme can be done with separate PRs, not necessary by me.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I've removed shadowing over focused menu item that a context menu looks a bit more aligned with it. Regarding the separator, yes it is expected in VS Code themes. For Theia light theme we can change it to a bit brighter if you like. I suggest that such fine tuning of our theme can be done with separate PRs, not necessary by me.

Okay sounds good! I wasn't sure so I made the comment but we can definitely improve our own default themes in the future iteratively and not in this pull request.

**Comment by vince-fugnitto** [comment]
> > @vince-fugnitto I've removed shadowing over focused menu item that a context menu looks a bit more aligned with it. Regarding the separator, yes it is expected in VS Code themes. For Theia light theme we can change it to a bit brighter if you like. I suggest that such fine tuning of our theme can be done with separate PRs, not necessary by me.
> 
> Okay sounds good! I wasn't sure so I made the comment but we can definitely improve our own default themes in the future iteratively and not in this pull request.

We might need to refine the CSS present in the file dialog, the following occurs (even for the default VS Code themes):

<div align='center'>

Screen Shot 2019-12-20 at 11 28 53 AM

</div>

**Comment by akosyakov** [comment]
> We might need to refine the CSS present in the file dialog, the following occurs (even for the default VS Code themes):

@vince-fugnitto I'm not sure what is wrong on the screenshot. Could you elaborate please?

**Comment by vince-fugnitto** [comment]
> > We might need to refine the CSS present in the file dialog, the following occurs (even for the default VS Code themes):
> 
> @vince-fugnitto I'm not sure what is wrong on the screenshot. Could you elaborate please?

With the change, the background color present for the nodes in the dialog is quite different.
We may need to more finely tune the background color.

For reference, master looks like:

Screen Shot 2019-12-20 at 11 40 06 AM

**Comment by vince-fugnitto** [comment]
By the way, great work in the pull request! I absolutely love how we are both able to change the theme and icon pack ❤️ 

Screen Shot 2019-12-20 at 11 43 01 AM

One potential improvement in the future is update the decorations for the editor (minimap included) to not make search results looks like deletions or errors).

**Comment by akosyakov** [comment]
@vince-fugnitto let's start opening follow-up issues, ok? I don't mind improvements, but it is good time to land the PR now just after the release and have a window of one month for such improvements. We have also other PRs like the terminal find widget, advance debugging and the extension view dependent on it.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto let's start opening follow-up issues, ok? I don't mind improvements, but it is good time to land the PR now just after the release and have a window of one month for such improvements. We have also other PRs like the terminal find widget, advance debugging and the extension view dependent on it.

I like that idea :) My intention was to track some follow up issues/improvements for the pull request.

**Comment by akosyakov** [comment]
> I like that idea :) My intention was to track some follow up issues/improvements for the pull request.

I think new issues would be better, that they can be handled independently and not necessary by us. Also after merging we probably get more feedback from the community on new styles and theming approach.

**Comment by vince-fugnitto** [comment]
> > I like that idea :) My intention was to track some follow up issues/improvements for the pull request.
> 
> I think new issues would be better, that they can be handled independently and not necessary by us. Also after merging we probably get more feedback from the community on new styles and theming approach.

Sure, I'll go ahead and open them. Should we assign some special type of label?

**Comment by akosyakov** [comment]
@vince-fugnitto I've tackled all issues except https://github.com/eclipse-theia/theia/issues/6786. I don't think it is very critical. Please let me know what else should be done for the approval.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I've tackled all issues except #6786. I don't think it is very critical. Please let me know what else should be done for the approval.

I verified my existing issues and they look to be resolved 👍 
I did notice a couple of issues however:

1. it looks like we might add `git` decorations twice?

Screen Shot 2019-12-26 at 1 28 25 PM

2. certain light themes have incorrect colors for the sidebar (activity bar)

_@theia/vscode-builtin-quietlight_

Screen Shot 2019-12-26 at 1 40 31 PM

_VS Code Horizon Bright Theme_

Screen Shot 2019-12-26 at 1 40 42 PM

3. the `LICENSE` icon still seems to be incorrect when using `minimal icon theme` (it seems to be treated as a folder)

Screen Shot 2019-12-26 at 1 44 43 PM

**Comment by akosyakov** [comment]
> it looks like we might add git decorations twice?

@vince-fugnitto Are you sure that you did not have git support installed from Theia  and VS Code extensions at the same time?

**Comment by akosyakov** [comment]
@vince-fugnitto I'have addressed everything in https://github.com/eclipse-theia/theia/pull/6475#issuecomment-569113332. Except double git decorators, I suspect you have git support from Theia and VS Code extensions at the same time. Maybe you have not rebuilt the browser example after changing package.json. Please have a look again.

**Comment by akosyakov** [comment]
> Sorry if I am a bit late reviewing the changes at each iteration, I'm not officially back to work until the 2nd of January but did not want to hold you back 😄

@vince-fugnitto that's alright, have nice holidays!

**Comment by akosyakov** [comment]
I'm going to merge it. Please open new issues if something is wrong or to ask for help on how to migrate.
