### PR TITLE
TreeWidget: Ensure globalSelection is correctly set when opening context menu

### LINKED ISSUE #12937: Navigator shows wrong context menu entries when the application is started with open file(s)
### Bug Description:
When an editor is already open (and thus restored) when Theia is started and you perform a right click in the file that belongs to that editor the context menu is almost empty, all entries that are file specific are missing. When you switch the editor or select a different file it works afterwards.

### Steps to Reproduce:

1. Open a file (I used Blueprint to ensure it is not a issue in my application)
2. Click in the Navigator to give it focus
3. Reload the window
4. Open the context menu for the already preselected file in the navigator widget

### Additional Information

- Operating System: Windows 10, Chrome
- Theia Version: 1.41.0 (Current Blueprint)

Debugging showed SelectionService.selection is not set.

### PR DESCRIPTION
**Pull request by jonah-iden**
#### What it does

Closes #12937

This ensures the globalSelection is set correctly when focusing a tree widget. There are cases where when restoring the layout the global selection is not set because the widget is not yet active and when opening the context menu there is no selection changed event so the global selection stays at the old value. See the linked issue

#### How to test

Taken from the linked issue

   1. Open a file 
   2. Click in the Navigator to give it focus (this is actually optional as long as the navigator is open)
   3. Reload the window
   4. Open the context menu for the already preselected file in the navigator widget

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/core/src/browser/tree/tree-widget.tsx [hunk 1]
```diff
@@ -1579,6 +1585,7 @@ export namespace TreeWidget {
                 height={height}
                 // This is a pixel value, it will scan 200px to the top and bottom of the current view
                 overscan={500}
+                foc
```
Comment (msujew) [inline packages/core/src/browser/tree/tree-widget.tsx:1588]: Question: Is this supposed to be `focusin`?

**Review by msujew — APPROVED** [review]
LGTM 👍
