### PR TITLE
fix: prevent duplicate VSIX installations by using package.json ident…

### LINKED ISSUE #16845: Same VSIX can be installed multiple times by renaming the VSIX file
### Bug Description:

Same VSIX can be installed multiple times by renaming the VSIX file. This creates a new directory in `deployedPlugins`, but the IDE does not include contributions coming from the later installed VSIX

### Steps to Reproduce:

1. Generate a VSIX from https://github.com/microsoft/vscode-extension-samples/tree/main/helloworld-sample
2. Move the VSIX file out of this project
3. Rename the hello world command contribution to make it unique from the one generated in Step 1
4. Generate VSIX again (keep name, version etc. info same)
5. Now generate VSIX again, rename it to make the name different from the previous VSIX.
7. Install the VSIX from Step 1
8. Check Hello World command in the IDE, it should be available
9. Install the VSIX from Step 5, it will also install successfully
10. IDE list of installed extensions will only show the one installed first
11. Check `deployedPlugins`, it will have directories for both extensions
12. Check Hello World 2nd command (from the change made in Step 3), it is not available in the IDE

### Result

Both extensions were installed and IDE shows only one in the installed list and command contributions are also only from the first installed extension.

Image

Image

### Suggested Solution

Probably the IDE should validate name inside the `package.json` of the VSIX instead of the VSIX filename. Because the extension name is depending on the name defined in `package.json`. If this is done, the above steps should give an error at installing the renamed VSIX file.

### Additional Information

This example does not affect the IDE rather hides contributions of the later installed VSIX, but if there is some application which reads some data from the installed extension's directory, that would start looking from two locations in this scenario whereas the IDE would show only one extension as installed. In such scenarios, this behavior can cause confusing and unexpected behaviors

- Operating System: Windows 
- Theia Version: 1.67.0

### PR DESCRIPTION
**Pull request by rajj28**
#### What it does

Fixes #16845 - Prevents duplicate VSIX extension installations when the same extension is installed from VSIX files with different filenames.

**Problem:** Extensions installed via "Install from VSIX..." were identified by their **filename** rather than the actual extension identity from `package.json`. This allowed the same extension to be installed multiple times by simply renaming the VSIX file, resulting in:
- Multiple directories under `deployedPlugins`
- Only the first installed extension appearing in the IDE
- Contributions (commands) from later-installed VSIX files being silently ignored

**Solution:** Extract the true extension identity (`publisher.name@version`) from the VSIX's embedded `extension/package.json` instead of deriving it from the filename.

**Changes:**
- Added `extractExtensionIdentityFromVsix()` function in `plugin-vscode-utils.ts` that reads publisher, name, and version from the VSIX's package.json
- Modified `LocalVSIXFilePluginDeployerResolver.resolveFromLocalPath()` to:
  - Use package.json-based identity instead of filename for deployment directory naming
  - Check `getDeployedPluginsById()` to block duplicate installations of the same extension
  - Graceful fallback to filename-based ID if package.json cannot be read

#### How to test

1. Build a sample VSIX extension (e.g., Hello World sample)
2. Install it via `Extensions: Install from VSIX...`
3. Rename the VSIX file (e.g., `hello-0.0.1.vsix` → `hello-renamed.vsix`)
4. Attempt to install the renamed VSIX via `Extensions: Install from VSIX...`
5. **Expected:** Installation is blocked with a console message indicating the extension is already installed
6. **Before fix:** Both VSIX files would be installed, creating duplicate directories in `deployedPlugins`

#### Follow-ups

- Consider adding user-facing notification when duplicate installation is blocked (currently only logs to console)
- Potential enhancement: Allow version upgrades/downgrades via VSIX when different versions are detected

#### Breaking changes

- [ ] This PR introduces breaking changes and requires careful review. If yes, the breaking changes section in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) has been updated.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)
- [x] User-facing text is internationalized using the `nls` service (for details, please see the [Internationalization/Localization section](https://github.com/theia-ide/theia/blob/master/doc/coding-guidelines.md#internationalizationlocalization) in the Coding Guidelines)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/plugin-ext-vscode/src/node/plugin-vscode-utils.ts [hunk 1]
```diff
@@ -20,6 +20,75 @@ import * as filenamify from 'filenamify';
...
+    publisher?: string;
+    /** The name of the extension */
+    name: string;
+    /** The version of the extension */
+    version: string;
+    /** The unversioned ID in the format `publisher.name` */
+    unversionedId: PluginIdentifiers.UnversionedId;
+    /** The versioned ID in the format `publisher.name@version` */
+    versionedId: PluginIdentifiers.VersionedId;
+}
```
Comment (ndoschek) [inline packages/plugin-ext-vscode/src/node/plugin-vscode-utils.ts]: We should reuse `PluginIdentifiers.Components` instead of introducing a new type it has the same shape (`publisher?`, `name`, `version`) and the versioned/unversioned IDs can be derived at the call site with `componentsToUnversionedId()`/`componentsToVersionedId()`.

Comment (rajj28) [reply packages/plugin-ext-vscode/src/node/plugin-vscode-utils.ts]: thankyou for your review @ndoschek  and i have check and modified my pr .

1. The custom ExtensionIdentity type has been removed.
2. The function extractExtensionIdentityFromVsix now returns PluginIdentifiers.Components (with publisher?, name, version)
3. The versioned and unversioned IDs are derived at the call site using PluginIdentifiers.componentsToUnversionedId(components) and PluginIdentifiers.componentsToVersionedId(components)

**Comment by ndoschek** [comment]
Thank you for the update @rajj28!
Could you please take a quick look at the compile issue? From what I can tell, it seems to be just a missing import.

Also, the message from the thrown error is not yet surfaced in the notification popup. We should include `e.message` in the user-facing notification. This can be adjusted in `packages/vsx-registry/src/browser/vsx-extensions-contribution.ts`, in `installVsixFile`.

**Comment by rajj28** [comment]
@ndoschek thankyou so much for updating this and now i have implemented the feeback , you can have a look

File: packages/plugin-ext-vscode/src/node/plugin-vscode-utils.ts [hunk 2]
```diff
@@ -20,6 +20,57 @@ import * as filenamify from 'filenamify';
...
+ * VSIX files are ZIP archives with the extension content in an `extension/` subdirectory.
+ * This function extracts only the `extension/package.json` file to read the extension metadata.
+ *
+ * @param vsixPath Path to the VSIX file
+ * @returns The extension identity, or undefined if the package.json cannot be read or is invalid
+ */
+/**
+ * Extracts extension identity from a VSIX file by reading its package.json.
+ * Returns PluginIdentifiers.Components (publisher?, name, version).
+ */
```
Comment (ndoschek) [inline packages/plugin-ext-vscode/src/node/plugin-vscode-utils.ts:33]: Minor: There are two JSDoc blocks stacked on top of each other here. Please merge them into one single comment.

File: packages/plugin-ext-vscode/src/node/plugin-vscode-utils.ts [hunk 3]
```diff
@@ -20,6 +20,57 @@ import * as filenamify from 'filenamify';
...
+        }
+
+        // Use UNPUBLISHED as the default publisher for extensions without one
+        const publisher = packageJson.publisher ?? PluginIdentifiers.UNPUBLISHED;
+
+        const components: PluginIdentifiers.Components = {
+            publisher,
+            name: packageJson.name,
+            version: packageJson.version
+        };
```
Comment (ndoschek) [inline packages/plugin-ext-vscode/src/node/plugin-vscode-utils.ts]: Setting the publisher to UNPUBLISHED here is premature, `Components.publisher` is already optional, and the `UNPUBLISHED` fallback is already handled inside.
By setting it explicitly here, callers can no longer distinguish "no publisher in the VSIX" from "publisher is literally UNPUBLISHED".
So I suggest to omit the fallback like this:

```suggestion
        const components: PluginIdentifiers.Components = {
            publisher: packageJson.publisher,
            name: packageJson.name,
            version: packageJson.version
        };
```

File: packages/plugin-ext-vscode/src/node/local-vsix-file-plugin-deployer-resolver.ts [hunk 4]
```diff
@@ -16,18 +16,20 @@
 
 import * as path from 'path';
 import { inject, injectable } from '@theia/core/shared/inversify';
-import { PluginDeployerResolverContext } from '@theia/plugin-ext';
+import { PluginDeployerResolverContext, PluginDeployerHandler } from '@theia/plugin-ext/lib/common/plugin-protocol';
```
Comment (ndoschek) [inline packages/plugin-ext-vscode/src/node/local-vsix-file-plugin-deployer-resolver.ts]: We should use the public re-exports for consistency instead of changing to those deep lib imports in this line and in line 24:
```ts
import { PluginDeployerResolverContext, PluginDeployerHandler, PluginIdentifiers } from '@theia/plugin-ext';
```

File: packages/plugin-ext-vscode/src/node/local-vsix-file-plugin-deployer-resolver.ts [hunk 5]
```diff
@@ -38,14 +40,48 @@ export class LocalVSIXFilePluginDeployerResolver extends LocalPluginDeployerReso
...
+        const versionedId = PluginIdentifiers.componentsToVersionedId(components);
+
+        // Check if an extension with this identity is already deployed in memory
+        const existingPlugins = this.pluginDeployerHandler.getDeployedPluginsById(unversionedId);
+        if (existingPlugins.length > 0) {
+            const existingVersions = existingPlugins.map(p => p.metadata.model.version);
+            // Throw an error with a user-facing message
+            throw new Error(
+                'Extension ' + unversionedId + ' (version(s): ' + existingVersions.join(', ') + ') is already installed.\n' +
+                'Uninstall the existing extension before installing a new version from VSIX.'
```
Comment (ndoschek) [inline packages/plugin-ext-vscode/src/node/local-vsix-file-plugin-deployer-resolver.ts]: Since this is user facing, it should use `nls.localize`

File: packages/plugin-ext-vscode/src/node/local-vsix-file-plugin-deployer-resolver.ts [hunk 6]
```diff
@@ -38,14 +40,48 @@ export class LocalVSIXFilePluginDeployerResolver extends LocalPluginDeployerReso
...
+            );
```
Comment (ndoschek) [inline packages/plugin-ext-vscode/src/node/local-vsix-file-plugin-deployer-resolver.ts]: On a closer look, I noticed my previous assumption does not hold, this error gets swallowed by `resolvePlugins()` and will not reach the user in the notification popup. I suggest to revert that back to a `console.log` for now.

```ts
console.log(
    'Extension ' + unversionedId + ' (version(s): ' + existingVersions.join(', ') + ') is already installed.\n' +
    'Uninstall the existing extension before installing a new version from VSIX.'
);
return;
```

We can then handle in a follow up another approach to show a confirmation dialog to the user for example, which would allow the user to replace an existing one, but this is out of scope for this PR

**Comment by rajj28** [comment]
Hi @ndoschek ,

Thank you for the detailed feedback! I've addressed all your comments:

1. Merged the duplicate JSDoc comments
2. Removed the premature UNPUBLISHED fallback - now letting componentsToUnversionedId() handle it
3. Changed to use public re-exports from @theia/plugin-ext
4. Reverted to console.log + return instead of throwing error (as you correctly noted, it gets swallowed)
5. Reverted the vsx-extensions-contribution.ts changes since they're no longer needed
The duplicate detection now logs a clear message to the console. As you suggested, we can enhance the UX with a confirmation dialog in a follow-up PR.

All changes are in the latest commit. Please let me know if there's anything else to adjust!

**Comment by safisa** [comment]
Hi @rajj28, @ndoschek,
I tested this fix in my environment, and it works as expected. This is the solution I was waiting for, so thank you!

In my case, it prevented the installation of a VSIX file for an already installed extension, whether it's the same version or a different one. This was the issue I wanted to address, and this PR resolved it. For example:
- If I install extension version 1.0.0 (either from Open VSX or from a file),
- and then try to install the same extension with the same version from a VSIX file, it should fail.
- If I try to install the same extension with a different version from a VSIX file, it should also fail.

Is it possible to provide users with a more detailed explanation of the reason for the failure (rather than just a message in the console), like a notification message?

Thanks

**Comment by rajj28** [comment]
@ndoschek thankyou for your feedbacks , i would love to work on followup for this pr
