### PR TITLE
Fix context-keys ScmProvider update, add submenu plugin contribution

### LINKED ISSUE #8724: Add VS Code API to contribute submenus
# Feature Description: 
VS Code recently added support to contribute sub menus in the context explorer as part of https://github.com/microsoft/vscode/issues/100172

Could this be ported to Theia?

Syntax
```
{
  "contributes": {
    "menus": {
      "scm/title": [
        {
          "command": "git.commit",
          "group": "navigation"
        },
        {
          "submenu": "git.stage",
          "group": "navigation"
        }
      ],
      "git.stage": [
        {
          "command": "git.stageAll",
          "group": "navigation"
        },
        {
          "command": "git.stageUntracked",
          "group": "navigation"
        }
      ]
    },
    "submenus": [
      {
        "id": "git.stage",
        "label": "Stage",
        "icon": "$(something)"
      }
    ]
  }
}

```
image

Implementation https://github.com/microsoft/vscode/pull/102784
Some updates https://github.com/microsoft/vscode/commit/130aa96b42113e4ff008ed53ce0e396891bd4090 & https://github.com/microsoft/vscode/commit/98262ef05017cc79ab33be09a2de921c4141ada4

### PR DESCRIPTION
**Pull request by vinokurig**
Signed-off-by: Igor Vinokur <ivinokur@redhat.com>

#### What it does

Fixes #8724

* Update the `ScmProvider` context-keys on SCM widget start to handle properly the `when` condition of the related menu items.
* Apply [submenu plugin contribution](https://code.visualstudio.com/updates/v1_48#_submenus) to be able to render submenus in the `SCM` view.
#### How to test

1. Remove `"@theia/git": "^1.9.0"` from `examples/browser/package.json` file.
2. Download [vscode-git-1.49.3](https://open-vsx.org/api/vscode/git/1.49.3/file/vscode.git-1.49.3.vsix) and copy it to the `plugins` folder.
3. Open a workspace with a git project and open the SCM panel
4. Try the `...` drop-down menu.
See:
screenshot-localhost_3000-2021 01 27-16_51_48

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/core/src/browser/shell/tab-bar-toolbar.tsx [hunk 1]
```diff
@@ -153,7 +153,12 @@ export class TabBarToolbar extends ReactWidget {
         const menuPath = ['TAB_BAR_TOOLBAR_CONTEXT_MENU'];
         const toDisposeOnHide = new DisposableCollection();
         for (const [, item] of this.more) {
-            toDisposeOnHide.push(this.menus.registerMenuAction([...menuPath, item.group!], {
+            if (item.group!.indexOf('/') > -1) {
+                const split = item.group!.split('/');
+                split.splice(2);
```
Comment (vince-fugnitto) [inline packages/core/src/browser/shell/tab-bar-toolbar.tsx:158]: In the case that the split has `2` elements, the result of the `splice(2)` would be empty.
Do we need extra handling to determine that the `split` operation has a length of 3 (subgroup)?

For instance, is there a case that it would not follow the pattern `group/submenu/subgroup`?

**Review by vince-fugnitto — COMMENTED** [review]
I verified that the submenus present in the `scm` view with the builtin git extensions (both `git` and `git-ui`) are now populated :+1:

File: packages/core/src/browser/shell/tab-bar-toolbar.tsx [hunk 2]
```diff
@@ -153,7 +153,12 @@ export class TabBarToolbar extends ReactWidget {
         const menuPath = ['TAB_BAR_TOOLBAR_CONTEXT_MENU'];
         const toDisposeOnHide = new DisposableCollection();
         for (const [, item] of this.more) {
-            toDisposeOnHide.push(this.menus.registerMenuAction([...menuPath, item.group!], {
+            if (item.group!.indexOf('/') > -1) {
```
[the remark this answers is not in the document]
Comment (vinokurig) [reply packages/core/src/browser/shell/tab-bar-toolbar.tsx]: Done, added a comment

**Comment by vinokurig** [comment]
@vince-fugnitto I've reworked this PR to hanle multiple nestance level of the submenus. To test it you should add such submenu contribution to the `package.json` of any theia plugin:
```
"contributes": {
    "menus": {
      "scm/title": [
        {
          "submenu": "git.custosubmenu1",
          "group": "2_main@3",
          "when": "scmProvider == git"
        },
        {
          "command": "git.clone",
          "group": "1_header@3",
          "when": "scmProvider == git"
        }
      ],
      "git.custosubmenu1": [
        {
          "submenu": "git.custosubmenu2",
          "group": "1_sync"
        },
        {
          "command": "git.sync",
          "group": "1_sync"
        }
      ],
      "git.custosubmenu2": [
        {
          "command": "git.sync",
          "group": "1_custom"
        }
      ]
    },
    "submenus": [
      {
        "id": "git.custosubmenu1",
        "label": "Custom Submenu 1"
      },
      {
        "id": "git.custosubmenu2",
        "label": "Custom Submenu 2"
      }
    ]
  }
```
And it will look like:
screenshot-localhost_3000-2021 02 02-14_21_05

File: packages/core/src/browser/shell/tab-bar-toolbar.tsx (hunk 1 above)
Comment (vinokurig) [reply packages/core/src/browser/shell/tab-bar-toolbar.tsx]: Reworked it in the latest fixup.

**Comment by vince-fugnitto** [comment]
@vinokurig thank you, I'll take a look at the changes shortly 👍 
I believe it fixes the following issue if you'd like to track it: https://github.com/eclipse-theia/theia/issues/8724.

**Review by vince-fugnitto — APPROVED** [review]
@vinokurig I confirmed that the pull-request works well with:
- the `vscode-builtin-git` extension now successfully contributing submenus
- the nested submenu example you provided https://github.com/eclipse-theia/theia/pull/8996#issuecomment-771598256

I'm not sure if you want others to review the changes as well.
