### PR TITLE
Fix Highlighting in SCM Tree

### LINKED ISSUE #8581: scm: tree-search should highlight matched nodes
### Bug Description:

The `tree-search` for `scm` should properly highlight matched nodes like in other areas (ex: `explorer`).
At the moment, nodes are not highlighted which is both confusing and inconsistent with the rest of the framework.

<div align='center'>

</div>

### Steps to Reproduce:

1. start the application, perform changes and open the `scm` view
2. type to start the `tree-search` 
3. notice how no highlights are present

### PR DESCRIPTION
**Pull request by colin-grant-work**
#### What it does

This PR fixes #8581 by adjusting the `ScmTreeLabelProvider` class to provide labels for all of the `ScmTreeWidget` node types and then using the `searchHighlights` map to produce a highlighted caption. This introduces adjustments to the interfaces of the various `ScmTreeWidget` node types, but those could be made non-breaking by adding `| ReactNode` to the previous specifications, if that is desirable.

image

#### How to test

1. start the application in a source-controlled workspace
2. perform changes and open the scm view
1. type to start the tree-search
1. notice that highlights are present

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/core/src/browser/tree/tree-widget.tsx [hunk 1]
```diff
@@ -608,10 +608,10 @@ export class TreeWidget extends ReactWidget implements StatefulWidget {
                 backgroundColor: highlight.backgroundColor
             };
         }
-        const createChildren = (fragment: TreeDecoration.CaptionHighlight.Fragment) => {
+        const createChildren = (fragment: TreeDecoration.CaptionHighlight.Fragment, index: number) => {
```
Comment (colin-grant-work) [inline packages/core/src/browser/tree/tree-widget.tsx:611]: Before I changed this, I received React errors about array children without keys. I'm not certain why that error doesn't occur in other trees, but if anyone knows how to get away with it in the SCM too, I'm happy to use that rather than changing this function. That said, I don't anticipate that this should cause problems.

File: packages/scm/src/browser/scm-tree-widget.tsx [hunk 2]
```diff
@@ -661,15 +665,14 @@ export class ScmResourceGroupElement extends ScmElement<ScmResourceGroupComponen
 export namespace ScmResourceGroupComponent {
     export interface Props extends ScmElement.Props {
         treeNode: ScmFileChangeGroupNode;
-        groupLabel: string;
```
Comment (vince-fugnitto) [inline packages/scm/src/browser/scm-tree-widget.tsx:664]: I believe we should document this as a breaking change.

File: packages/scm/src/browser/scm-tree-widget.tsx [hunk 3]
```diff
@@ -718,7 +721,6 @@ export namespace ScmResourceFolderElement {
     export interface Props extends ScmElement.Props {
         treeNode: ScmFileChangeFolderNode;
         sourceUri: string;
-        path: string;
```
Comment (vince-fugnitto) [inline packages/scm/src/browser/scm-tree-widget.tsx:721]: Similarly to `ScmResourceGroupComponent.Props`, I believe we should document it as a breaking change.

**Review by vince-fugnitto — COMMENTED** [review]
@colin-grant-work the changes now highlight the matches in the tree based on the search query. I'll need to confirm it still works correctly using the `git` built-in extensions.

I did notice the following issues that I'm not sure should be handled by the pull-request:


When no nodes are present, we still highlight the tree (which looks incorrect).

scm-changes

`Changes` is highlighted even though it is not part of the changeset but just a category (it is also highlighted in a different color):

scm-2

File: packages/scm/src/browser/scm-tree-widget.tsx (hunk 2 above)
Comment (colin-grant-work) [reply packages/scm/src/browser/scm-tree-widget.tsx:664]: Happy to do so. As I mentioned in my description, I could also leave these fields untouched and just add `caption`, if that's preferable?

**Comment by colin-grant-work** [comment]
> @colin-grant-work the changes now highlight the matches in the tree based on the search query. I'll need to confirm it still works correctly using the `git` built-in extensions.
>
> When no nodes are present, we still highlight the tree (which looks incorrect).

I'm happy to handle these in the current PR, though I'm not sure what behavior is most desirable. Arguably, if there are no changes, there's no need to render the top-level node at all (similar to how the Navigator doesn't render the top workspace node if it isn't a directory) so we could:

1. Not render a `ChangeGroupNode` if it has no children (make it invisible).
2. Not highlight the `ChangeGroupNode` even if it matches the search (either unconditionally or on the condition that is has no children)
3. Just remove whatever style code is making it a different color so that the highlight at least looks like the highlighting of other nodes.

I'm inclined to opt for 1 and 3. Don't render the node if it isn't informative, and if it is rendered, highlight the same as any other node. Does that sound reasonable?

**Comment by vince-fugnitto** [comment]
> > @colin-grant-work the changes now highlight the matches in the tree based on the search query. I'll need to confirm it still works correctly using the `git` built-in extensions.
> > When no nodes are present, we still highlight the tree (which looks incorrect).
> 
> I'm happy to handle these in the current PR, though I'm not sure what behavior is most desirable. Arguably, if there are no changes, there's no need to render the top-level node at all (similar to how the Navigator doesn't render the top workspace node if it isn't a directory) so we could:
> 
> 1. Not render a `ChangeGroupNode` if it has no children (make it invisible).
> 2. Not highlight the `ChangeGroupNode` even if it matches the search (either unconditionally or on the condition that is has no children)
> 3. Just remove whatever style code is making it a different color so that the highlight at least looks like the highlighting of other nodes.
> 
> I'm inclined to opt for 1 and 3. Don't render the node if it isn't informative, and if it is rendered, highlight the same as any other node. Does that sound reasonable?

I know that it is done this way since it aligns with vscode, they display the `changes` top-level node despite no actual children (changes):

image

I think we should be consistent with the behavior present in vscode for the moment, and fix the highlighting of this node (removing the highlighting versus fixing the color).

**Comment by colin-grant-work** [comment]
@vince-fugnitto, I've pushed up a version that documents the breaking (and non-breaking) changes in the `CHANGELOG.md` and restricts highlights to non-group nodes.

**Review by vince-fugnitto — APPROVED** [review]
The changes work well for me, I now see that highlighting works well for `scm`.
I also verified the changes using the `git` built-in extensions instead of `@theia/git`:

```json
"vscode-builtin-git": "https://open-vsx.org/api/vscode/git/1.39.1/file/vscode.git-1.39.1.vsix",
"vscode-builtin-git-ui": "https://open-vsx.org/api/vscode/git-ui/1.39.1/file/vscode.git-ui-1.39.1.vsix"

```
