### PR TITLE
Return undefined instead of throwing when getting non-existent menu

### LINKED ISSUE #15664: Toolbar console errors
### Bug Description:

During regular usage of Theia, the console is flooded with errors like this

```
2025-05-28T05:30:27.061Z root ERROR Error: not a compound menu node: ["plugin_editor/title"]
    at MenuModelRegistry.getMenu (http://localhost:3000/bundle.js:409298:19)
    at TabBarToolbarRegistry.visibleItems (http://localhost:3000/bundle.js:391756:48)
    at TabBarToolbar.updateTarget (http://localhost:3000/bundle.js:392020:62)
    at ToolbarAwareTabBar.updateToolbar (http://localhost:3000/bundle.js:393271:22)
    at ToolbarAwareTabBar.onUpdateRequest (http://localhost:3000/bundle.js:393263:14)
    at ToolbarAwareTabBar.processMessage (http://localhost:3000/bundle.js:11962:22)
    at invokeHandler (http://localhost:3000/bundle.js:9067:21)
    at sendMessage (http://localhost:3000/bundle.js:8821:13)
    at runMessageLoop (http://localhost:3000/bundle.js:9118:17)
    at http://localhost:3000/bundle.js:8795:42
```

After 5 minutes of usage I had 20+ of these entries in the Console

### Steps to Reproduce:

1. Build the Browser example application (I did not even download the vsx extensions)
2. Use the tool a bit, switching between tabs is sufficient to trigger this for me

I have the toolbar visible.

This is my toolbar config, in case it's relevant

```
{
    "items": {
        "left": [
            [
                {
                    "id": "textEditor.commands.go.back",
                    "command": "textEditor.commands.go.back",
                    "icon": "codicon codicon-arrow-left"
                },
                {
                    "id": "textEditor.commands.go.forward",
                    "command": "textEditor.commands.go.forward",
                    "icon": "codicon codicon-arrow-right"
                }
            ],
            [
                {
                    "id": "workbench.action.splitEditorRight",
                    "command": "workbench.action.splitEditor",
                    "icon": "codicon codicon-split-horizontal"
                }
            ]
        ],
        "center": [
            [
                {
                    "id": "theia-sample-toolbar-contribution",
                    "group": "contributed"
                }
            ]
        ],
        "right": [
            [
                {
                    "id": "workbench.action.showCommands",
                    "command": "workbench.action.showCommands",
                    "icon": "codicon codicon-terminal",
                    "tooltip": "Command Palette"
                },
                {
                    "id": "ai-terminal:open",
                    "command": "ai-terminal:open",
                    "icon": "codicon codicon-microscope"
                }
            ]
        ]
    }
}
```

### Additional Information

- Operating System: Ubuntu 24.04
- Theia Version: latest master, i.e. [9b2d680](https://github.com/eclipse-theia/theia/commit/9b2d6806bf0367aebb7a68bb140b4cb868853f7a)

### PR DESCRIPTION
**Pull request by tsmaeder**
#### What it does
This PR makes `MenuModelRegistry.getMenu()` return undefined instead of throwing for non-existent menus. 

Fixes #15664

#### How to test
Make sure menus work in all the affected cases in this change. Also, there should be no more console messages at startup.
Make sure the dirty-diff widget appears and can be used. 

#### Follow-ups
https://github.com/eclipse-theia/theia/issues/15793

#### Breaking changes

- [ ] This PR introduces breaking changes and requires careful review. If yes, the breaking changes section in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) has been updated.

#### Attribution

Contributed on behalf of STMicroelectronics

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by tsmaeder** [comment]
@cdamus

**Review by sdirix — APPROVED** [review]

File: packages/test/src/browser/view/test-tree-widget.tsx [hunk 1]
```diff
@@ -299,7 +299,7 @@ export class TestTreeWidget extends TreeWidget {
         if (TestItemNode.is(node)) {
             const testItem = node.testItem;
             return this.contextKeys.with({ view: this.id, controllerId: node.controller.id, testId: testItem.id, testItemHasUri: !!testItem.uri }, () => {
-                const menu = this.menus.getMenu(TEST_VIEW_INLINE_MENU);
+                const menu = this.menus.getMenu(TEST_VIEW_INLINE_MENU)!; // we register items into this men, so we know it exists
```
Comment (sdirix) [inline packages/test/src/browser/view/test-tree-widget.tsx]:
```suggestion
                const menu = this.menus.getMenu(TEST_VIEW_INLINE_MENU)!; // we register items into this menu, so we know it exists
```

**Comment by Greglar4** [comment]
I think it is necessary to alter line 141 of tab-bar-toolbar-registry.ts, because if getMenu can return undefined, there will be an error when menu.children is attempted to be accessed in the for of loop. This was one of the causes of the issue #15601 for me.

**Comment by tsmaeder** [comment]
Hey, @Greglar4, thanks for catching that case.

**Review by rschnekenbu — APPROVED** [review]
LGTM!
