### PR TITLE
Fix some API inconsistencies related to web views

### LINKED ISSUE #12087: Fix some inconsistencies in webview VS Code API
### Feature Description:
There are some inconsistencies in our webview API implementation that show up as "partial" implementations in the compatibility report, namely:

* `WebViewOptions.enableCommandUris` can be an array of strings as well as a boolean
* `window.createWebViewPanel(...) uses an ad-hoc type instead of WebviewPanelShowOptions

### PR DESCRIPTION
**Pull request by tsmaeder**
#### What it does
Fixes a typing difference in `createWebViewPanel` as well as support for filtering command links via an array of command id's passed to `enableCommandUris`.

Fixes #12087

Contributed on behalf of STMicroelectronics

#### How to test
The attached extension opens three web views at startup: one where the `openFolder` link works, but `openFile` is disabled, one where command links are generally enabled and one where they are generally turned off.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by tsmaeder** [comment]
Here's the extension:

[commanduritest-0.0.1.zip](https://github.com/eclipsesource/theia/files/10458325/commanduritest-0.0.1.zip)

And here's the source:

[commanduritest.zip](https://github.com/eclipsesource/theia/files/10458371/commanduritest.zip)

File: packages/plugin-ext/src/main/browser/webview/webview.ts [hunk 1]
```diff
@@ -450,8 +450,12 @@ export class WebviewWidget extends BaseWidget implements StatefulWidget, Extract
...
             return link;
         }
-        if (!!this.contentOptions.enableCommandUris && link.scheme === Schemes.command) {
-            return link;
+        if (link.scheme === Schemes.command) {
+            if (Array.isArray(this.contentOptions.enableCommandUris) && this.contentOptions.enableCommandUris.some(value => value === link.path.toString())) {
+                return link;
+            } else if (this.contentOptions.enableCommandUris === true) {
+                return link;
+            }
```
Comment (msujew) [inline packages/plugin-ext/src/main/browser/webview/webview.ts:458]: Suggestion: Just because it seems weird to me to have two branches returning the same value.
```suggestion
            if (this.contentOptions.enableCommandUris === true || Array.isArray(this.contentOptions.enableCommandUris) && this.contentOptions.enableCommandUris.some(value => value === link.path.toString())) {
                return link;
            }
```

**Review by msujew — APPROVED** [review]
Looks good to me 👍

File: packages/plugin-ext/src/main/browser/webview/webview.ts (hunk 1 above)
Comment (paul-marechal) [reply packages/plugin-ext/src/main/browser/webview/webview.ts:458]: It breaks the max line length ESLint rule, and even when I tried adding some line returns to make it look nice it didn't really look any nicer than what is written in this PR...

Let's leave it as is :)
