### PR TITLE
Prevent illegal array size when constructing menu bar

### LINKED ISSUE #17352: Toggle menu bar fails to render menu on second iteration.
### Bug Description:
Toggling top menu back and forth renders menu inoperable.

### Steps to Reproduce:

Image

1.  Just menu -> view -> appearance -> toggle menu bar (several times)

### Additional Information
Also toggling menu bar back and forth fails if default is set to "compact"
`newValue` received in the following code is  `undefined` when swithcing to "compact"
@theia/core/src/browser/common-frontend-contribution.ts
```typescript
 protected handlePreferenceChange
...
  case 'window.menuBarVisibility': {
    const { newValue } = e;
    const mainMenuId = 'main-menu';
    if (newValue === 'compact') {
        this.shell.leftPanelHandler.addTopMenu({
            id: mainMenuId,
            iconClass: `theia-compact-menu ${codicon('menu')}`,
            title: nls.localizeByDefault('Application Menu'),
            menuPath: MAIN_MENU_BAR,
            order: 0,
        });
    } else {
        app.shell.leftPanelHandler.removeTopMenu(mainMenuId);
    }
    break;
  }
```

### PR DESCRIPTION
**Pull request by colin-grant-work**
#### What it does

Fixes #17352 by disabling Lumino's overflow menu feature for the main menu bar. The overflow feature has a bug where `onUpdateRequest` consumes a stale `_overflowIndex` (only recomputed at the end of the method), which causes a `RangeError` when the menu bar is rendered at zero width — exactly what happens when toggling the menu bar visibility. Additionally, Theia's CSS does not constrain the menu bar's `offsetWidth` to the available space, so the overflow detection never triggers in practice.

The fix passes `{ overflowMenuOptions: { isVisible: false } }` to the `MenuBarWidget` constructor to disable the feature entirely.

Also restricts the "Toggle Menu Bar" command to non-macOS or non-Electron contexts (it was previously hidden on all macOS, but it should be available in the browser on macOS).

See also: https://github.com/jupyterlab/lumino/issues/811

#### How to test

1. In the browser... (or, probably, in Electron on Windows or Linux)
2. Use the View > Appearance > Toggle Menu Bar command two or more times
3. The menu bar should not be broken at any point.

#### Breaking changes

- [x] This PR introduces breaking changes and requires careful review. If yes, the breaking changes section in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) has been updated.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)
- [x] User-facing text is internationalized using the `nls` service (for details, please see the [Internationalization/Localization section](https://github.com/theia-ide/theia/blob/master/doc/coding-guidelines.md#internationalizationlocalization) in the Coding Guidelines)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/core/src/browser/menu/browser-menu-plugin.ts [hunk 1]
```diff
@@ -163,6 +163,22 @@ export class DynamicMenuBarWidget extends MenuBarWidget {
         };
     }
 
+    /**
+     * Workaround for a Lumino bug: {@link MenuBar.clearMenus clearMenus} does not reset the
```
Comment (cdamus) [inline packages/core/src/browser/menu/browser-menu-plugin.ts]: nit: Do we have a Lumino bug URL that we can track to remove this work-around when an eventual fix is adopted? Only concerned because we are using undocumented internals of the superclass here. Also, is it necessary to empty out `_menuItemSizes`? because that isn't mentioned in this doc comment.

Perhaps, at a minimum, we should have an `@lumino-uplift` tag in this comment to signal a reassessment on the next upgrade, similar to the `@monaco-uplift` tag specified in the coding guidelines.

**Review by cdamus — APPROVED** [review]
Looks good to me! I do have a nit to offer.

**Review by cdamus — APPROVED** [review]
Works just as well and looks more tasty. Thanks for the update!

**Review by cdamus — APPROVED** [review]
