### PR TITLE
[core] Fixed race condition on contribution initialization

### LINKED ISSUE #6807: [core] there seems to be a potential race condition on contribution initialization
### Description
 

When creating a new `FrontendApplicationContribution` there seems to be a chance to create some race condition if the `configure` method takes too long.

### Reproduction Steps

To reproduce the error, just create a `FrontendApplicationContribution` that in the `configure` method waits for 1 second. An error in the console appears:

> Error: A command with id 'workspace:removeFolder' does not exist.

**OS and Theia version:**
Theia version: 0.12
OS: Ubuntu 18.04

**Diagnostics:** 

Full error stack trace:

> menu.ts:266 Uncaught (in promise) Error: A command with id 'workspace:removeFolder' does not exist.
    at ActionMenuNode.get [as label] (menu.ts:266)
    at ActionMenuNode.get [as sortString] (menu.ts:280)
    at menu.ts:202
    at Array.sort (.../lib/native)
    at CompositeMenuNode.../../theia/packages/core/lib/common/menu.js.CompositeMenuNode.addNode (menu.ts:194)
    at MenuModelRegistry.../../theia/packages/core/lib/common/menu.js.MenuModelRegistry.registerMenuAction (menu.ts:79)
    at FileNavigatorContribution.push.../../theia/packages/navigator/lib/browser/navigator-contribution.js.FileNavigatorContribution.updateAddRemoveFolderActions (navigator-contribution.ts:491)
    at FileNavigatorContribution.<anonymous> (navigator-contribution.ts:164)
    at step (navigator-contribution.ts:15)
    at Object.next (navigator-contribution.ts:15)

### PR DESCRIPTION
**Pull request by federicobozzini**
#### What it does

It fixes #6807 by delayin the registration of menu actions for the folder operations.

#### How to test

See #6807.

#### Review checklist

- [X] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/navigator/src/browser/navigator-contribution.ts [hunk 1]
```diff
@@ -161,6 +161,10 @@ export class FileNavigatorContribution extends AbstractViewContribution<FileNavi
         };
         updateFocusContextKeys();
         this.shell.activeChanged.connect(updateFocusContextKeys);
+    }
+
+    async onStart(app: FrontendApplication): Promise<void> {
+        await this.workspacePreferences.ready;
```
Comment (vince-fugnitto) [inline packages/navigator/src/browser/navigator-contribution.ts]: @federicobozzini should we instead opt for a non-blocking asynchronous call?

Example:

```ts

@inject(FrontendApplicationStateService)
protected readonly stateService: FrontendApplicationStateService;

async onStart(app: FrontendApplication): Promise<void> { 
    this.stateService.reachedState('ready').then(
         () => this.updateAddRemoveFolderActions(this.menuRegistry);
    );
}
```

Comment (akosyakov) [reply packages/navigator/src/browser/navigator-contribution.ts]: please don't use `FrontendApplicationStateService`, `FrontendApplicationContribution` provides already with sufficient lifecycle hooks

Comment (federicobozzini) [reply packages/navigator/src/browser/navigator-contribution.ts]: @vince-fugnitto  I've made it non-blocking.

Comment (vince-fugnitto) [reply packages/navigator/src/browser/navigator-contribution.ts]: @federicobozzini with this change I no longer see the toolbar menu item for `Add Folder to Workspace`, something which is added by:

```ts
this.updateAddRemoveFolderActions(this.menuRegistry);
```

In order for the item to return, one must right-click the empty area in the navigator for the command to exist. This is a regression from master and we may need to adjust.

Comment (federicobozzini) [reply packages/navigator/src/browser/navigator-contribution.ts]: @vince-fugnitto Can you please be more specific about where that item should be? On master I see it only in the "Explorer" menu (just above the file navigator) and on the context menu opened on right-click in the navigator. I see the item in the same two places on this branch.

This is on the electron version.

Comment (vince-fugnitto) [reply packages/navigator/src/browser/navigator-contribution.ts]: I performed additional testing and it does not look to be related to your changes.

---

For future reference, I was referencing the `...` (more toolbar item) from the Explorer widget which contains a menu item for `Add Folder to Workspace`:

<div align='center'>

image

</div>

**Comment by akosyakov** [comment]
@vince-fugnitto please merge if it is good
