### PR TITLE
[ls] implement multiple workspace folders in MonacoWorkspace

### LINKED ISSUE #6108: [multi-workspace][ls] Support `workspace/didChangeWorkspaceFolders`
### Description
 

As an extension developer, I want my LS to be notified when a folder is added/removed to/from my Theia workspace. VS Code sends the `DidChangeWorkspaceFoldersParams` to the LS when the workspace has changed.

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

### PR DESCRIPTION
**Pull request by JanKoehnlein**
Fixes #6108

Signed-off-by: Jan Koehnlein <jan.koehnlein@typefox.io>

#### What it does
This PR adds support of multiple workspace root folders to Monaco workspace. 
Language servers will be notified with a `didChangeWorkspaceFolders` notification whenever the user adds or removes a workspace folder.

#### How to test
Add/remove workspace folders in Theia and watch extensions with language servers get notified.

- [X] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by kittaakos** [comment]
I do not understand this explicit `vscode` dependency. I can see [`monaco-languageclient`](https://github.com/TypeFox/monaco-languageclient/blob/bc8b38c669fdcfa2fd3f60301ef03c4882f28f7f/client/src/services.ts#L254-L255) also imports them.

File: packages/monaco/src/browser/monaco-workspace.ts [hunk 1]
```diff
@@ -175,14 +179,25 @@ export class MonacoWorkspace implements lang.Workspace {
...
     @postConstruct()
     protected init(): void {
         this.workspaceService.roots.then(roots => {
-            const rootStat = roots[0];
-            if (rootStat) {
-                this._rootUri = rootStat.uri;
-                this.resolveReady();
-            }
+            this._workspaceFolders = roots.map((dir, index) => this.toWorkspaceFolder(dir.uri, index));
+            this.resolveReady();
```
Comment (kittaakos) [inline packages/monaco/src/browser/monaco-workspace.ts]: Looks like you have changed the behavior. The original code does not resolve if no roots are available. Expected?

**Comment by kittaakos** [comment]
> I do not understand this explicit `vscode` dependency.

I see. They're from here: https://github.com/microsoft/vscode/blob/master/src/vs/vscode.d.ts#L8432-L8452.

File: packages/monaco/src/browser/monaco-workspace.ts [hunk 2]
```diff
@@ -534,5 +556,4 @@ export class MonacoWorkspace implements lang.Workspace {
         // eslint-disable-next-line @typescript-eslint/no-explicit-any
         return 'resource' in edit && (edit as any).resource instanceof monaco.Uri;
     }
-
```
Comment (kittaakos) [inline packages/monaco/src/browser/monaco-workspace.ts]: Please revert.

File: packages/monaco/src/browser/monaco-workspace.ts (hunk 1 above)
Comment (JanKoehnlein) [reply packages/monaco/src/browser/monaco-workspace.ts]: Good catch. We should also turn `ready` to unresolved when all workspace folders have been removed. I'll prepare that.

**Comment by JanKoehnlein** [comment]
Sorry for the sloppy initial commit. I've changed the `ready` resolution and added the missing dev dependency on `@types/vscode`.

File: packages/monaco/src/browser/monaco-workspace.ts [hunk 3]
```diff
@@ -175,14 +182,34 @@ export class MonacoWorkspace implements lang.Workspace {
...
+        });
+
+        this.workspaceService.onWorkspaceChanged(async newRootDirs => {
+            const oldWorkspaceUris = this.workspaceFolders.map(folder => folder.uri.toString());
+            const newWorkspaceUris = newRootDirs.map(folder => folder.uri);
+            const added = newWorkspaceUris.filter(uri => oldWorkspaceUris.indexOf(uri) < 0).map((dir, index) => this.toWorkspaceFolder(dir, index));
+            const removed = oldWorkspaceUris.filter(uri => newWorkspaceUris.indexOf(uri) < 0).map((dir, index) => this.toWorkspaceFolder(dir, index));
+            this._workspaceFolders = newWorkspaceUris.map(this.toWorkspaceFolder);
+            if (this._workspaceFolders.length === 0) {
+                this._ready = new Promise<void>(resolve => {
```
Comment (akosyakov) [inline packages/monaco/src/browser/monaco-workspace.ts]: i don't think it is necessary. `roots` is a promised which resolved when a workspace is changed first time

File: packages/monaco/src/browser/monaco-workspace.ts [hunk 4]
```diff
@@ -175,14 +182,34 @@ export class MonacoWorkspace implements lang.Workspace {
...
-            const rootStat = roots[0];
-            if (rootStat) {
-                this._rootUri = rootStat.uri;
+            this._workspaceFolders = roots.map((dir, index) => this.toWorkspaceFolder(dir.uri, index));
+            if (this._workspaceFolders.length !== 0) {
+                this.resolveReady();
+            }
+        });
+
+        this.workspaceService.onWorkspaceChanged(async newRootDirs => {
```
Comment (akosyakov) [inline packages/monaco/src/browser/monaco-workspace.ts]: should be sync?

File: packages/monaco/src/browser/monaco-workspace.ts [hunk 5]
```diff
@@ -175,14 +182,34 @@ export class MonacoWorkspace implements lang.Workspace {
...
         this.workspaceService.roots.then(roots => {
-            const rootStat = roots[0];
-            if (rootStat) {
-                this._rootUri = rootStat.uri;
+            this._workspaceFolders = roots.map((dir, index) => this.toWorkspaceFolder(dir.uri, index));
+            if (this._workspaceFolders.length !== 0) {
+                this.resolveReady();
+            }
+        });
+
```
Comment (akosyakov) [inline packages/monaco/src/browser/monaco-workspace.ts]: I think the control flow should be:
- (1) listen for `ready`
- (2) compute _workspaceFolders and fire first event (should be synchronous)
- (3) start listening for `onWorkspaceChanged` event, perform (2) for each event

File: packages/monaco/src/browser/monaco-workspace.ts (hunk 3 above)
Comment (akosyakov) [reply packages/monaco/src/browser/monaco-workspace.ts]: Ah, ok, so it is because of the race condition, between ready and `onWorkspaceChanged` event. I think if we construct code like in https://github.com/eclipse-theia/theia/pull/7182/files#r381844782 then it should not be necessary

File: packages/monaco/src/browser/monaco-workspace.ts [hunk 6]
```diff
@@ -175,14 +182,34 @@ export class MonacoWorkspace implements lang.Workspace {
...
+    }
+
     @postConstruct()
     protected init(): void {
         this.workspaceService.roots.then(roots => {
-            const rootStat = roots[0];
-            if (rootStat) {
-                this._rootUri = rootStat.uri;
+            this._workspaceFolders = roots.map((dir, index) => this.toWorkspaceFolder(dir.uri, index));
+            if (this._workspaceFolders.length !== 0) {
```
Comment (akosyakov) [inline packages/monaco/src/browser/monaco-workspace.ts]: Honestly i'm not sure that this predicate is correct, if open a Theia without a workspace, then `WorkspaceService` should be still ready. Wonder why we have it.

**Comment by JanKoehnlein** [comment]
I addressed your comments and re-implemented the workspaceFolder init/updated

**Comment by akosyakov** [comment]
@JanKoehnlein the build is failing, for some reasons it cannot find monaco namespace anymore

**Comment by JanKoehnlein** [comment]
I had this sporadically here, too. I guess we should not add a dependency to `@types/vscode` but define the `WorkspaceFolder` and `WorkspaceFolderChangeEvent` interfaces ourselves

File: packages/monaco/src/browser/monaco-workspace.ts [hunk 7]
```diff
@@ -175,14 +179,20 @@ export class MonacoWorkspace implements lang.Workspace {
...
     @postConstruct()
-    protected init(): void {
-        this.workspaceService.roots.then(roots => {
-            const rootStat = roots[0];
-            if (rootStat) {
-                this._rootUri = rootStat.uri;
-                this.resolveReady();
-            }
+    protected async init(): Promise<void> {
+        await this.workspaceService.roots.then(roots => {
```
Comment (kittaakos) [inline packages/monaco/src/browser/monaco-workspace.ts]: Does the `await` look good with the `then` here?

File: packages/monaco/src/browser/monaco-workspace.ts [hunk 8]
```diff
@@ -175,14 +179,20 @@ export class MonacoWorkspace implements lang.Workspace {
...
+            this.updateWorkspaceFolders(roots);
+            this.resolveReady();
+        });
+
+        this.workspaceService.onWorkspaceChanged(async newRootDirs => {
```
Comment (kittaakos) [inline packages/monaco/src/browser/monaco-workspace.ts]: Why `async`?

File: packages/monaco/src/browser/monaco-workspace.ts [hunk 9]
```diff
@@ -191,13 +201,29 @@ export class MonacoWorkspace implements lang.Workspace {
...
+        const added = newWorkspaceUris.filter(uri => oldWorkspaceUris.indexOf(uri) < 0).map((dir, index) => this.toWorkspaceFolder(dir, index));
+        const removed = oldWorkspaceUris.filter(uri => newWorkspaceUris.indexOf(uri) < 0).map((dir, index) => this.toWorkspaceFolder(dir, index));
+        this._workspaceFolders = newWorkspaceUris.map(this.toWorkspaceFolder);
+        this.onDidChangeWorkspaceFoldersEmitter.fire({ added, removed });
+    }
+
+    protected toWorkspaceFolder(uriString: string, index: number): WorkspaceFolder {
+        return {
+            uri: Uri.parse(uriString),
+            name: uriString.substring(uriString.lastIndexOf('/')) || uriString,
```
Comment (kittaakos) [inline packages/monaco/src/browser/monaco-workspace.ts]: If you have an encoded URI string here, and you have a file somewhere at `path/to/Foo Bar Folder`, then you will have a URI `file:///path/to/Foo%20Bar%20Folder`. After the `substring` the folder name will be still `Foo%20Bar%20Folder` instead of the desired `Foo Bar Folder`. Please correct me if I am wrong.

File: packages/monaco/src/browser/monaco-workspace.ts [hunk 10]
```diff
@@ -191,13 +201,29 @@ export class MonacoWorkspace implements lang.Workspace {
...
+            index
+        };
+    }
+
     get rootUri(): string | null {
-        return this._rootUri;
+        return this._workspaceFolders[0] && this._workspaceFolders[0].uri.toString();
```
Comment (kittaakos) [inline packages/monaco/src/browser/monaco-workspace.ts]: I think this incorrect, same for `rootPath`. This will never ever return with `null` but `undefined` silently. Am  I overlooking something?

```ts
const array = [];
function toUpper(): string | null {
    return array[0] && array[0].toLocaleLowerCase();
}
console.log(undefined === toUpper()); // true
console.log(null === toUpper()); // false
```
(You can try it with `ts-node` quickly.)

File: packages/monaco/src/browser/monaco-workspace.ts (hunk 9 above)
Comment (kittaakos) [reply packages/monaco/src/browser/monaco-workspace.ts]: Probably, something like this would be safer:
```ts
protected toWorkspaceFolder(uriString: string, index: number): WorkspaceFolder {
    const uri = Uri.parse(uriString);
    return {
        uri,
        name: uri.toString(true).substring(uri.toString(true).lastIndexOf('/')) || uri.toString(true),
        index
    };
}
```

File: packages/monaco/src/browser/monaco-workspace.ts (hunk 7 above)
Comment (akosyakov) [reply packages/monaco/src/browser/monaco-workspace.ts]: i think so, we should not listen to events till the initial state is computed

File: packages/monaco/src/browser/monaco-workspace.ts (hunk 9 above)
Comment (akosyakov) [reply packages/monaco/src/browser/monaco-workspace.ts]: we have Path api, here it should be base name: `uri.path.base`

Comment (kittaakos) [reply packages/monaco/src/browser/monaco-workspace.ts]: It's a `vscode` URI here, `uri.path` is a `string`. Did you mean, parse it to a Theia URI and then `path.base`?

File: packages/monaco/src/browser/monaco-workspace.ts (hunk 7 above)
Comment (JanKoehnlein) [reply packages/monaco/src/browser/monaco-workspace.ts]: Fixed

File: packages/monaco/src/browser/monaco-workspace.ts (hunk 8 above)
Comment (JanKoehnlein) [reply packages/monaco/src/browser/monaco-workspace.ts]: Fixed.

File: packages/monaco/src/browser/monaco-workspace.ts (hunk 10 above)
Comment (JanKoehnlein) [reply packages/monaco/src/browser/monaco-workspace.ts]: Replaced

File: packages/monaco/src/browser/monaco-workspace.ts (hunk 9 above)
Comment (JanKoehnlein) [reply packages/monaco/src/browser/monaco-workspace.ts]: I did a mixture :-)

**Comment by kittaakos** [comment]
Thanks for the updates, @JanKoehnlein. Once the build is green I am going to verify it with one or two VS Code LS extensions.

**Comment by kittaakos** [comment]
It throws an error at startup:
```
monaco-workspace.ts:214 Uncaught (in promise) TypeError: Cannot read property 'map' of undefined
    at MonacoWorkspace.push.../../packages/monaco/lib/browser/monaco-workspace.js.MonacoWorkspace.updateWorkspaceFolders (monaco-workspace.ts:214)
    at MonacoWorkspace.<anonymous> (monaco-workspace.ts:200)
    at step (monaco-workspace.ts:15)
    at Object.next (monaco-workspace.ts:15)
    at fulfilled (monaco-workspace.ts:15)
```
You get the value before you set it:
_Get_:
https://github.com/eclipse-theia/theia/blob/ecedb651a53e715b97d9bb05907922896f1c2f9f/packages/monaco/src/browser/monaco-workspace.ts#L214
_Set_:
https://github.com/eclipse-theia/theia/blob/ecedb651a53e715b97d9bb05907922896f1c2f9f/packages/monaco/src/browser/monaco-workspace.ts#L218

**Comment by JanKoehnlein** [comment]
Wow. Looks like I should get more sleep. Initialization of the property with an empty array way missing.

**Comment by kittaakos** [comment]
From the LSP [specs](https://microsoft.github.io/language-server-protocol/specification.html#workspace_workspaceFolders):

> The `workspace/workspaceFolders` request is sent from the server to the client to fetch the current open list of workspace folders. Returns `null` in the response if only a single file is open in the tool. Returns an empty array if a workspace is open but no folders are configured.

If I open Theia without a workspace and then open a single file (e.g.: `main.go`),  the `monaco-workspace` returns with an empty array instead of `null`. Note, the LS works.

**Comment by akosyakov** [comment]
@kittaakos `MonacoWorkspace` confirms to VS Code API, not to LSP, transformation from VS Code api to LSP happens here: https://github.com/microsoft/vscode-languageserver-node/blob/50ffd38681b3fc8dde75a70accfa3c29db1889f3/client/src/workspaceFolders.ts#L45-L53

**Comment by JanKoehnlein** [comment]
Thanks a lot for the reviews!
