### PR TITLE
GH-8350: Fixed bogus app config defaults.

### LINKED ISSUE #8350: FrontendApplicationConfigProvider.get returns a configuration without the application name
It happens in the case if `frontend.config` section in package.json does not contain application name property. It breaks VS Code extensions like python.

We should inject the default application name if it was not set in package.json or throw an exception in FrontendApplicationConfigProvider.get

### PR DESCRIPTION
**Pull request by kittaakos**
Closes #8350

Signed-off-by: Akos Kitta <kittaakos@typefox.io>

#### What it does

Fixes the bogus default handling for application props.

#### How to test

 - Delete the `applicationName` from `examples/browser/package.json`,
 - `yarn --cwd ./examples/browser build`,
 - Verify that the `applicationName` is `Eclipse Theia` in the generated `examples/browser/src-gen/frontend/index.js`.

Or verify it with a VS Code extension. See [here](https://github.com/eclipse-theia/theia/issues/8350#issuecomment-672154559).

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: dev-packages/application-package/src/application-package.ts [hunk 1]
```diff
@@ -87,7 +88,7 @@ export class ApplicationPackage {
             theia.target = defaultTarget;
         }
 
-        return this._props = { ...ApplicationProps.DEFAULT, ...theia };
+        return this._props = merge(ApplicationProps.DEFAULT, theia);
```
Comment (akosyakov) [inline dev-packages/application-package/src/application-package.ts:91]: Does it mutate and return `ApplicationProps.DEFAULT`? Or it creates a new instance and merge defaults into it?

File: dev-packages/application-package/src/application-package.ts [hunk 2]
```diff
@@ -20,6 +20,7 @@ import { NpmRegistry, NodePackage, PublishedNodePackage, sortByKey } from './npm
 import { Extension, ExtensionPackage, RawExtensionPackage } from './extension-package';
 import { ExtensionPackageCollector } from './extension-package-collector';
 import { ApplicationProps } from './application-props';
+const merge = require('deepmerge');
```
Comment (akosyakov) [inline dev-packages/application-package/src/application-package.ts:23]: it does not seem to be type safe

File: dev-packages/application-package/src/application-package.ts (hunk 1 above)
Comment (kittaakos) [reply dev-packages/application-package/src/application-package.ts:91]: It creates a new object. Check the [docs](https://www.npmjs.com/package/deepmerge#mergex-y-options):

> Merging creates a new object, so that neither x or y is modified.
