### PR TITLE
Do not copy preferences that are valid in folder scope

### LINKED ISSUE #16613: New workspace file unexpectedly populated with settings
### Bug Description:

I recently created a new multi-root workspace using the 'Add Folder to Workspace' command, and when I then opened the newly created workspace file, it contained about 200 lines of settings, including a copy of all of Theia's `launch` configs.

### Steps to Reproduce:

1. Open one folder as a single-folder workspace (I started with this repo)
2. Use the 'Add folder to workspace' command to add another folder.
3. There will be a prompt to save your new workspace as a workspace file.
4. Say yes and save the file.
5. Open the file. (e.g. by going to preferences, selecting workspace scope, then opening the JSON)
6. Observe that it contains a `settings` field.

> [!NOTE]
> This deviates from my expectations in two ways. Most significantly in that the file contains more than a specification of the folders contained in the workspace - on creation, it shouldn't specify any settings. Secondly, that at (3) there is a prompt to save the workspace file. I'd expect to be left alone with an untitled workspace until closing the application or changing workspaces, at which point the save prompt would appear. That's a matter of UX judgment, but the current arrangement does differ from VSCode's behavior and, I think, the behavior of earlier versions of Theia.

### Additional Information

- Operating System: MacOS Tahoe
- Theia Version: 9b2e07fb7d4d8937fdc11da2903931098907145c

### PR DESCRIPTION
**Pull request by colin-grant-work**
#### What it does

Closes #16613

Credit to @sdirix for identifying the change.

#### How to test

1. Open one folder as a single-folder workspace (I started with this repo)
2. Use the 'Add folder to workspace' command to add another folder.
3. There will be a prompt to save your new workspace as a workspace file.
4. Say yes and save the file.
5. Open the file. (e.g. by going to preferences, selecting workspace scope, then opening the JSON)
6. Observe that if it contains a `settings` field, those settings are only those from the original folder that are declared not to be valid in `folder` scope.

#### Breaking changes

- [ ] This PR introduces breaking changes and requires careful review. If yes, the breaking changes section in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) has been updated.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)
- [x] User-facing text is internationalized using the `nls` service (for details, please see the [Internationalization/Localization section](https://github.com/theia-ide/theia/blob/master/doc/coding-guidelines.md#internationalizationlocalization) in the Coding Guidelines)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/workspace/src/browser/workspace-service.ts [hunk 1]
```diff
@@ -596,6 +596,9 @@ export class WorkspaceService implements FrontendApplicationContribution, Worksp
         const workspaceData: WorkspaceData = { folders: [], settings: {} };
         if (!this.saved) {
             for (const p of Object.keys(this.schemaService.getJSONSchema(PreferenceScope.Workspace).properties!)) {
+                if (this.schemaService.isValidInScope(p, PreferenceScope.Folder)) {
+                    continue;
+                }
```
Comment (sdirix) [inline packages/workspace/src/browser/workspace-service.ts:603]: We should add a comment on why this is necessary to help future readers of the code

**Review by sdirix — APPROVED** [review]
Works for me. Thanks!
