### PR TITLE
Fix problems related with menu bar updates on focus change.

### LINKED ISSUE #14002: Menu bar does not open on first click when certain sidebar elements have focus
### Bug Description:
When certain sidebar elements have focus, clicking on the menu bar does not open the selected menu group, but appears to 'weaken' the focus on the element, thus another click will open the menu group.

Clicking again on the menu group to close it returns focus to the original element and so the bug will repeat if attempting to reopen the menu.

For an example of 'weakening focus': when the search input box has focus, the first click on the menu bar will remove the "(up/down for history)" text from the input box, but the insertion caret will still be flashing.

### Steps to Reproduce:

1. Click inside an affected sidebar panel or on it's icon in the side panel selector
2. Click on the menu bar

Here is the results of my experimentation on whether different sidebar elements exhibit the bug behaviour (Yes means affected):
Explorer
- Explorer heading: No
- Open Editors sub-heading: No
- Open Editors box: No
- Project Folder sub-heading: No
- Project Folder box: Yes
Search
- Search heading: No
- Search input box: Yes (and each toggle box - Match case, etc)
- Toggle replace button: Yes
- Replace input box: Yes
- Search results box: Yes
Source Control
- Source Control heading: No
- Rest of box: Yes
- (Note that due to https://github.com/eclipse-theia/theia/issues/14001 I cannot install any SCM extensions, thus I cannot try any other elements)
Debug
- No elements appear to be affected
Extensions
- Extensions heading: No
- Search input box: Yes
- Recommended sub-heading: No
- Recommended box: Yes
- Installed sub-heading: No
- Installed box: Yes
Testing
- Testing heading: No
- Test explorer sub-heading: No
- Test explorer box: Yes
- Test runs sub-heading: No
- Test runs box : No

### Additional Information

- Operating System: Windows 10 (Build 19045.4651)
- Theia Version: 1.51.0

### PR DESCRIPTION
**Pull request by tsmaeder**
#### What it does
This PR introduces an event object describing changes to the menu registry more precisely. The code that manages the menu bar then only rebuilds itself when the change actually concerns the main menu bar. This prevents the menu bar from being replaced when the keyboard focus changes.

Fixes #14002

#### How to test
Make sure you set the "title bar style" setting to "custom" (This issue does not affect the native menus). Observe that the Sample menu appears dynamically and is correctly displayed and works. Make sure the scenario from the linked issue is fixed. Test electron and browser cases. 

#### Follow-ups
This is a workaround that fixes the problem at hand. To attack the root problem, we would have to solve https://github.com/eclipse-theia/theia/issues/14879

#### Breaking changes

- [ ] This PR introduces breaking changes and requires careful review. If yes, the breaking changes section in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) has been updated.

#### Attribution
Contributed on behalf of STMicroelectronics

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/core/src/browser/menu/browser-menu-plugin.ts [hunk 1]
```diff
@@ -156,6 +160,10 @@ export class BrowserMainMenuFactory implements MenuWidgetFactory {
 
 }
 
+export function isMenuElement(element: HTMLElement | null): boolean {
+    return !!element && element.className.includes('lm-Menu');
+}
```
Comment (msujew) [inline packages/core/src/browser/menu/browser-menu-plugin.ts:165]: Question: Is this required? It does not seem to be in use and also uses Lumino stuff.

**Review by msujew — APPROVED** [review]
Looks good to me 👍

File: packages/core/src/browser/menu/browser-menu-plugin.ts (hunk 1 above)
Comment (tsmaeder) [reply packages/core/src/browser/menu/browser-menu-plugin.ts:165]: Good catch, I ported this commit from the lumino-PR.
