### PR TITLE
[#7173] Prevent error on disabled performance API

### LINKED ISSUE #7173: Plugin loading breaks when resistFingerprinting is enabled
### Description
When Firefox is hardened against fingerprinting by enabling `privacy.resistFingerprinting` loading of plugins breaks with an error to the console. This for example breaks language-support-plugins.

### Reproduction Steps
- Fetch `theiaide/theia:next` docker image and start it (`:latest` shows same behavior)
- Get a recent Firefox
- Access `about:config` and enable `privacy.resistFingerprinting`
- Try to load the application
- See error:

```
root ERROR Failed to load plugins: U</e.prototype.createMeasurement/<@https://***HOST***/bundle.js:8:376112
U</e.prototype.logMeasurement@https://***HOST***/bundle.js:8:376368
U</e.prototype.syncPlugins/</<@https://***HOST***/bundle.js:8:366859
s/</<@https://***HOST***/bundle.js:8:360880
s/<@https://***HOST***/bundle.js:8:360985
a@https://***HOST***/bundle.js:8:359728
```

**OS and Theia version:**
- Theia: `@theia/core 0.16.0-next.00c1747c`
- OS: Archlinux, Firefox 73.0

**Diagnostics:** 
- [Firefox Bug 1369303](https://bugzilla.mozilla.org/show_bug.cgi?id=1369303)
- [Firefox Bug 1511941](https://bugzilla.mozilla.org/show_bug.cgi?id=1511941) (Possible fix)
- Relevant code: https://github.com/eclipse-theia/theia/blob/00c1747c98aefe946d2f2c6b7db5b8e356183abf/packages/plugin-ext/src/hosted/browser/hosted-plugin.ts#L577-L594
- Failing code: https://github.com/eclipse-theia/theia/blob/00c1747c98aefe946d2f2c6b7db5b8e356183abf/packages/plugin-ext/src/hosted/browser/hosted-plugin.ts#L588

**Example (tested in dev-console):**
```
21:27:49.736 performance.mark('foo-start')
21:27:49.756 undefined
21:28:08.117 performance.mark('foo-end')
21:28:08.178 undefined
21:28:32.134 performance.measure('foo-name', 'foo-start', 'foo-end')
21:28:32.152 undefined
21:28:42.935 performance.getEntriesByName('foo-name')
21:28:42.982 Array []
21:28:46.752 performance.getEntriesByName('foo-name')[0]
21:28:46.763 undefined
21:28:51.444 performance.getEntriesByName('foo-name')[0].duration
21:28:51.487 TypeError: performance.getEntriesByName(...)[0] is undefined
```

refs / obsoletes https://github.com/theia-ide/theia-apps/issues/306

### PR DESCRIPTION
**Pull request by Luzifer**
#### What it does

When performance API is disabled through `privacy.resistFingerprinting` setting in recent Firefox all API calls are possible though `getEntriesByName` will return an empty Array.

This change checks the length of the returned array before using the first element in order not to cause a call to `undefined.duration` which breaks plugin architecture.

closes #7173 

#### How to test

In short: Enable `resistFingerprinting` in Firefox, ensure plugins are still loaded.

Please see description of #7173 for further information.

#### Review checklist

- [ ] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/plugin-ext/src/hosted/browser/hosted-plugin.ts [hunk 1]
```diff
@@ -585,7 +585,10 @@ export class HostedPluginSupport {
         return () => {
             performance.mark(endMarker);
             performance.measure(name, startMarker, endMarker);
-            const duration = performance.getEntriesByName(name)[0].duration;
+
+            const entries = performance.getEntriesByName(name);
+            const duration = entries.length > 0 ? entries[0].duration : 0;
```
Comment (akosyakov) [inline packages/plugin-ext/src/hosted/browser/hosted-plugin.ts]: reporting 0 will be bogus

Comment (Luzifer) [reply packages/plugin-ext/src/hosted/browser/hosted-plugin.ts]: When a number is expected reporting `NaN` would have side-effects. Followed the [example Vimeo used](https://bugzilla.mozilla.org/show_bug.cgi?id=1511941#c2) and used a value which is a valid number and also below 100 (the check inside `core` for the `performance` API)…

I'm not sure about the implications of returning `NaN`. From my experience that creates more issues than it solves…

Comment (Luzifer) [reply packages/plugin-ext/src/hosted/browser/hosted-plugin.ts]: Hm interestingly it looks like the number is only used in log entries and for some reason `Number.NaN.toFixed(1)` indeed works and reports `NaN`…

Well. I can change that if you want…

The difference would be:
```
[${this.clientId}] ${prefix} of ${pluginCount} took: NaN ms
vs.
[${this.clientId}] ${prefix} of ${pluginCount} took: 0 ms
```

Comment (akosyakov) [reply packages/plugin-ext/src/hosted/browser/hosted-plugin.ts]: > [${this.clientId}] ${prefix} of ${pluginCount} took: 0 ms

Would be confusing? Maybe we can avoid logging all together if a value is NaN?

Comment (Luzifer) [reply packages/plugin-ext/src/hosted/browser/hosted-plugin.ts]: We certainly can… :slightly_smiling_face:
