### PR TITLE
Align addOrReattachWidget behavior with VSCode

### LINKED ISSUE #9617: Webview opening with ViewColumn.Beside is inconsistent
### Bug Description:
When creating a VSCode plugin that uses `createWebviewPanel` and passes `vscode.ViewColumn.Beside` as its `showOptions`, it doesn't always work as expected, especially when the the currently active widget is not one of the main area editors. We have noticed this issue when trying to spawn a webview using a file-explorer context menu custom command, and the view does not show up as a split-pane view.

This is best described through the example below

### Steps to Reproduce:

- Build the latest version of Theia
- Clone this example [extension](https://github.com/kenneth-marut-work/vscode-webview-sample/tree/webview-main-bottom-example), and copy `cat-coding-0.0.1.vsix` into your `theia/plugins` directory.

**Good Behavior (VSCode):**
1. Open VSCode to the sample repo linked above, and run the extension from `Run -> Run Without Debugging`
1. In the Extension Host, close all editors and tabs, then run the command `Start Cat Coding session from the Main Panel` using the keyboard shortcut `ctrl+shift+p`
    - [ ] observe that a new webview opens
1. Without clicking anywhere, run the command again
    - [ ] observe another webview opens in a split view
1. Close one of the two editors so that you are left with a single 'Cat Coding' editor
1. Click somewhere in the file navigator (to apply focus to the navigator widget), then run the command again using `ctrl+shift+p`
    - [ ] Observe another window opens in split view again, this is correct.

**Bad Behavior:** 
1. Run Theia with the `vsix` file mentioned above copied into your `theia/plugins` directory.
2. Run through steps 1-5, but observe that step 5 causes the window to open in the same tabbar as the original editor. 
---
The correct general behavior for `vscode.ViewColumn.Besides` should be as follows:
- If no editors are open, a webview should be placed in the main area tabbar
- If one editor is open, the new webview should open *to the right* as a split view
- If multiple split views are open:
  - If an editor tab is *active*, the webview should open in the panel *to the right* of the active tab
     - If there is already a panel to the right, the webview is added to that tabbar
     - If there is no panel to the right, a new panel is created
  - If an editor is *not active* (or any other widget is active, i.e. the navigator), the webview should open in a *new split panel* all the way to the right

### Additional Information

- Operating System: Linux
- Theia Version: master

### PR DESCRIPTION
**Pull request by kenneth-marut-work**
Signed-off-by: Kenneth Marut <kenneth.marut@ericsson.com>

#### What it does

Fixes #9617 by aligning webview placement during creation with VSCode. It determines if the webview should be open in a new split panel, or appended to a previously created panel by adding the appropriate checks to align with VSCode's behavior. It also ensures that split pane webviews follow the same rules for 'bottom' panel (which is specific to Theia).

#### How to test

1. Build this branch, clone this example [extension](https://github.com/kenneth-marut-work/vscode-webview-sample/tree/webview-main-bottom-example), and copy `cat-coding-0.0.1.vsix` into your `theia/plugins` directory.
1. Start Theia, close all editors and tabs, then run the command `Start Cat Coding session from the Main Panel` using the keyboard shortcut `ctrl+shift+p`
    - [ ] observe that a new webview opens
1. Without clicking anywhere, run the command again
    - [ ] observe another webview opens in a split view
1. Close one of the two editors so that you are left with a single 'Cat Coding' editor
1. Click somewhere in the file navigator (to apply focus to the navigator widget), then run the command again using `ctrl+shift+p`
    - [ ] Observe another window opens in split view again, this is correct.

- Also try using the command `Start Cat Coding session from the Bottom Panel` to verify the behavior is identical for Webviews added to the bottom panel.

The correct general behavior for `vscode.ViewColumn.Besides` should be as follows:
- If no editors are open, a webview should be placed in the main area tabbar
- If one editor is open, the new webview should open *to the right* as a split view
- If multiple split views are open:
  - If an editor tab is *active*, the webview should open in the panel *to the right* of the active tab
     - If there is already a panel to the right, the webview is added to that tabbar
     - If there is no panel to the right, a new panel is created
  - If an editor is *not active* (or any other widget is active, i.e. the navigator), the webview should open in a *new split panel* all the way to the right

 
**Note: don't open up *too* many coding cats, you'll start to get some slow downs and a lot of toast spam 🙂**

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/plugin-ext/src/main/browser/webviews-main.ts [hunk 1]
```diff
@@ -89,12 +90,19 @@ export class WebviewsMainImpl implements WebviewsMain, Disposable {
...
-            const ref = this.shell.currentWidget;
-            if (ref && this.shell.getAreaFor(ref) === widgetOptions.area) {
+        // -2 corresponds to vscode.ViewColumn.Beside opening option
+        const canOpenBeside = showOptions.viewColumn === -2 && (area === WebviewPanelTargetArea.Main || area === WebviewPanelTargetArea.Bottom);
+        if (canOpenBeside) {
+            let activeOrRightmostTabbar = this.shell.getTabBarFor(area);
+            if (!activeOrRightmostTabbar) {
+                const areaTabBars = area === WebviewPanelTargetArea.Main ? this.shell.mainAreaTabBars : this.shell.bottomAreaTabBars;
+                activeOrRightmostTabbar = areaTabBars[areaTabBars.length - 1];
+            }
```
Comment (colin-grant-work) [inline packages/plugin-ext/src/main/browser/webviews-main.ts:103]: Are there conditions under which this second attempt to get a tabbar works after the first has failed? My impression of the code behind `getTabBarFor` is that if there *is* a tabbar, it should be returned, but there are some subtleties to the tracking of `_currentTitle` in `theia-dock-panel.ts` that I don't follow completely.

**Review by colin-grant-work — APPROVED** [review]
This is working well for me, and the code looks reasonable. I might put a link to the plugin repo and copy the test instructions over here to make it easier for others to test. Bouncing between the issue and the solution can be a bit bothersome.

File: packages/plugin-ext/src/main/browser/webviews-main.ts [hunk 2]
```diff
@@ -89,12 +90,19 @@ export class WebviewsMainImpl implements WebviewsMain, Disposable {
...
-        const widgetOptions: ApplicationShell.WidgetOptions = { area: showOptions.area ? showOptions.area : 'main' };
-
+        const area = showOptions.area ? showOptions.area : WebviewPanelTargetArea.Main;
+        const widgetOptions: ApplicationShell.WidgetOptions = { area };
         let mode = 'open-to-right';
-        if (showOptions.viewColumn === -2) {
-            const ref = this.shell.currentWidget;
-            if (ref && this.shell.getAreaFor(ref) === widgetOptions.area) {
+        // -2 corresponds to vscode.ViewColumn.Beside opening option
+        const canOpenBeside = showOptions.viewColumn === -2 && (area === WebviewPanelTargetArea.Main || area === WebviewPanelTargetArea.Bottom);
```
[the remark this answers is not in the document]
Comment (kenneth-marut-work) [reply packages/plugin-ext/src/main/browser/webviews-main.ts]: yes we can!

File: packages/plugin-ext/src/main/browser/webviews-main.ts (hunk 1 above)
Comment (kenneth-marut-work) [reply packages/plugin-ext/src/main/browser/webviews-main.ts]: Yeah that's a good catch. I thought I had been getting `undefined` previously when a tabbar wasn't active, but that doesn't seem to be the case. I've removed the redundant check
