### PR TITLE
Also watch non-existent template directories

### LINKED ISSUE #16172: [Theia AI] Custom Agent not showing up in the browser-app
### Bug Description:

I created a basic Theia application (see https://github.com/fipro78/vscode_theia_cookbook/tree/main/theia) and added the following AI packages to the browser-app:

```json
    "@theia/ai-chat-ui": "1.64.1",
    "@theia/ai-chat": "1.64.1",
    "@theia/ai-code-completion": "1.64.1",
    "@theia/ai-core": "1.64.1",
    "@theia/ai-ide": "1.64.1",
    "@theia/ai-mcp-ui": "1.64.1",
    "@theia/ai-mcp": "1.64.1",
    "@theia/ai-openai": "1.64.1",
    "@theia/ai-terminal": "1.64.1",
```

I built the browser-app and start it. I select a folder to open. Then I enable AI via the settings and configure access to my OpenAI model. I then open the _AI Configuration [Beta]_ and click on **Add Custom Agent**. After selecting the workspace location for the customAgents.yml, the file opens, but the agent does not show up in the list agents, not in the configuration and not available in the chat. If I refresh the browser window and let Theia reload, the agent appears. Further editing the file (e.g. adding another agent) now results in directly showing up in the user interface.

Maybe some listener is missing in case the file is created the first time?

### Additional Information

- Operating System: Windows (Ubuntu WSL, Node Typescript Dev Container)
- Theia Version: 1.64.1

### PR DESCRIPTION
**Pull request by JonasHelming**
fixed #16172

#### What it does

Adapt prompt customization service to also watch directories not yet existing.
fixed #16172

#### How to test

1. Make sure no .prompts directory is in the workspace
2. Click on "Add custom agent" in the agent overview (AI Configuration view)
3. Observe that the new agent appears in the list immediatly

#### Breaking changes

- [ ] This PR introduces breaking changes and requires careful review. If yes, the breaking changes section in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) has been updated.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/ai-core/src/browser/frontend-prompt-customization-service.ts [hunk 1]
```diff
@@ -486,59 +519,100 @@ export class DefaultPromptFragmentCustomizationService implements PromptFragment
...
         this.toDispose.push(this.fileService.watch(dirURI, { recursive: true, excludes: [] }));
         this.toDispose.push(this.fileService.onDidFilesChange(async (event: FileChangesEvent) => {
-            // Only watch for changes within provided dir
+            // Filter for changes within the watched directory
             if (!event.changes.some(change => change.resource.toString().startsWith(dirURI.toString()))) {
                 return;
             }
+
+            // Handle directory creation (when watching a previously non-existent directory)
+            if (event.getAdded().some(addedFile => addedFile.resource.toString() === dirURI.toString())) {
```
Comment (sdirix) [inline packages/ai-core/src/browser/frontend-prompt-customization-service.ts]: This works for the case that a template directory was added. However we should also update when a template directory was deleted.

**Review by sdirix — CHANGES_REQUESTED** [review]
Works for me! However I noticed that one use case is still not considered: When a template directory is removed, we should also update.

To reproduce rename the `.prompts` directory when it contains some customizations and observe that the UI does not react.
