### PR TITLE
fix: prevent Chat UI crash when tool call returns a primitive value

### LINKED ISSUE #17202: Chat UI crashes when tool calls return non-object, non-string values
### Bug Description:

When a tool call returns a non-object, non-string value, the Chat UI crashes with errors like this

```
Uncaught TypeError: Cannot use 'in' operator to search for 'content' in 3
    at m.renderResult (toolcall-part-renderer.tsx:82:13)
```

This happens because we call `in` without checking whether we actually have an object in hand, see https://github.com/eclipse-theia/theia/blob/8904818291384f71e6885604f7c3cedd16a25065/packages/ai-chat-ui/src/browser/chat-response-renderer/toolcall-part-renderer.tsx#L74-L82

### Steps to Reproduce:

1. Create a file whose content is just the number 3
2. Ask an agent in the chat view to retrieve the content of the file
3. The `getFileContent` just returns the content of the file, which, when parsed, is converted to the `number` 3
4. Observe that the chat ui disappears and errors like the one above are logged

### Additional Information

- Operating System: Ubuntu 24.04
- Theia Version: latest (8904818291384f71e6885604f7c3cedd16a25065)

### PR DESCRIPTION
**Pull request by sdirix**
#### What it does

Guard against non-object values (numbers, booleans, etc.) before using the `in` operator in `renderResult`, fixing a TypeError when a tool call result is parsed into a primitive by `JSON.parse`.

Fixes #17202

#### How to test

1. Create a file whose content is just the number 3
2. Ask an agent in the chat view to retrieve the content of the file
3. The getFileContent just returns the content of the file, which, when parsed, is converted to the number 3
4. Observe that the chat ui still works and no error is printed in the console

#### Follow-ups

No direct follow ups. We could consider adapting our tall calls to always return object results. However for defense-in-depth we need to be able to handle non-object results anyway.

#### Breaking changes

- [ ] This PR introduces breaking changes and requires careful review. If yes, the breaking changes section in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) has been updated.

#### Review checklist

- [X] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)
- [X] User-facing text is internationalized using the `nls` service (for details, please see the [Internationalization/Localization section](https://github.com/theia-ide/theia/blob/master/doc/coding-guidelines.md#internationalizationlocalization) in the Coding Guidelines)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/ai-chat-ui/src/browser/chat-response-renderer/toolcall-part-renderer.tsx [hunk 1]
```diff
@@ -76,8 +76,8 @@ export class ToolCallPartRenderer implements ChatResponsePartRenderer<ToolCallCh
         if (!result) {
             return undefined;
         }
-        if (typeof result === 'string') {
-            return <pre>{JSON.stringify(result, undefined, 2)}</pre>;
+        if (typeof result !== 'object' || result === null) {
+            return <pre>{String(result)}</pre>;
```
Comment (sdirix) [inline packages/ai-chat-ui/src/browser/chat-response-renderer/toolcall-part-renderer.tsx:81]: Technically this second line is not needed for the fix. I just added it as stringifying a string is not nice and the formatting is not necessary for primitive values.
