### PR TITLE
fixed "applyTo" property in problem matcher for task output

### LINKED ISSUE #7396: "applyTo" property in taskConfig.problemMatcher doesn't work properly
### Description

`applyTo` is a property that controls if a problem reported on a text document is applied only to open, closed or all documents. It is not working in Theia.

### Reproduction Steps

1. As the GIF shows, open a workspace and define a task that produces problem markers. In my workspace, I had 

```
        "type": "npm",
        "script": "lintAAB",
        "problemMatcher": [
            {
                "owner": "eslint97",
                "source": "eslint97",
                "applyTo": "openDocuments",
                "fileLocation": "absolute",
                "pattern": [
                {
                    "regexp": "^([^\\s].*)$",
                    "kind": "location",
                    "file": 1
                },
                {
                    "regexp": "^\\s+(\\d+):(\\d+)\\s+(error|warning|info)\\s+(.+?)(?:\\s\\s+(.*))?$",
                    "line": 1,
                    "column": 2,
                    "severity": 3,
                    "message": 4,
                    "code": 5,
                    "loop": true
                }
                ]
          }
        ]
    }
```
in the task config, and 
```
  "scripts": {
    "lintAAB": "eslint ."
  },
```
in my package.json

2. Run the task. The lint warnings / errors that are found by the task all show up in the problems view, which is WRONG, because `applyTo` is set "openDocuments", while the markers displayed in the problems view are found from not-opened files.

Peek 2020-03-22 22-31

**OS and Theia version:**

Ubuntu 18.04. Chrome, example browser.
version ae5591edb22b06f890b090e5c4eb36ddeed05122

### PR DESCRIPTION
**Pull request by elaihau**
- With this change, "applyTo" can be used as a property to control if a problem reported on a text document is applied only to open, closed or all documents.

- fixed #7396

Signed-off-by: Liang Huang <lhuang4@ualberta.ca>

#### How to test

1. Open a workspace, define a task that produces warnings / errors, and add a problem mactcher that parses the warnings / errors.
Mine is  
```
    {
        "type": "npm",
        "script": "lintAAB",
        "problemMatcher": [
            {
                "owner": "eslint97",
                "source": "eslint97",
                "applyTo": "closedDocuments",
                "fileLocation": "absolute",
                "pattern": [
                {
                    "regexp": "^([^\\s].*)$",
                    "kind": "location",
                    "file": 1
                },
                {
                    "regexp": "^\\s+(\\d+):(\\d+)\\s+(error|warning|info)\\s+(.+?)(?:\\s\\s+(.*))?$",
                    "line": 1,
                    "column": 2,
                    "severity": 3,
                    "message": 4,
                    "code": 5,
                    "loop": true
                }
                ]
          }
        ]
    }
```
and the npm lintAAB is defined in package.json as follows
```
  "scripts": {
    "lintAAB": "eslint ."
  }
```

2. Close all docuements, and run the task defined in Step 1. We should be able to see all warnings & errors are displayed in the problems view.

3. Open one document associated with the problem markers added in Step 2. Run the task again.  Once the task finishes, markers displayed in Step 2, **except for** those associated with the opened file, should persist. Markers associated with the opened file should not be displayed.

Please note, in this step, you could possibly still see markers associated with the opened file in the problem view, as other they could be added by other contributors.

4. Close all documents, update `applyTo` of the problem matcher to "openDocuments". Run the task again. Once the task finishes, markers displayed in Step 2 should not show up, because we only want errors & warnings from opened documents to be reported.

5. When `applyTo` is "allDocuments", all parsed warnings and errors markers should be displayed in the problems view.

Peek 2020-03-24 19-48

 
#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

### CODE REVIEW

File: packages/task/src/browser/task-service.ts [hunk 1]
```diff
@@ -94,6 +97,8 @@ export class TaskService implements TaskConfigurationClient {
         terminateSignal: Deferred<string | undefined>,
         isBackgroundTaskEnded: Deferred<boolean | undefined>
     }>();
+    // URIs of the opened documents
+    protected openedDocuments: Set<string> = new Set();
```
Comment (akosyakov) [inline packages/task/src/browser/task-service.ts]: please don't introduce caches, caches are evil because can cause race condition, memory leaks and so on

they are necessary sometimes for performance, like for replicate data structures between 2 processes

but even in this case they should be properly encapsulated and respective service should be used.

In our case `MonacoWorkspace` know about opened document and should be asked about the current state.

File: packages/task/src/browser/task-service.ts [hunk 2]
```diff
@@ -236,16 +239,21 @@ export class TaskService implements TaskConfigurationClient {
...
-                            const newData = [
-                                ...existingMarkers
-                                    .filter(marker => marker.uri === uri.toString())
-                                    .map(markerData => markerData.data),
-                                problem.marker
-                            ];
-                            this.problemManager.setMarkers(uri, problem.description.owner, newData);
-                        } else {
-                            this.problemManager.setMarkers(uri, problem.description.owner, [problem.marker]);
+                        if (problem.description.applyTo === ApplyToKind.openDocuments && this.openedDocuments.has(uri.toString()) ||
```
Comment (akosyakov) [inline packages/task/src/browser/task-service.ts]:
```ts
const document = this.monacoWorkspace.getTextDocument(uri.toString());
                        if ((problem.description.applyTo === ApplyToKind.openDocuments && !!document) ||
                            (problem.description.applyTo === ApplyToKind.closedDocuments && !document) ||
                            problem.description.applyTo === ApplyToKind.allDocuments
                        ) {
```

small and fast

File: packages/task/src/browser/task-service.ts [hunk 3]
```diff
@@ -94,6 +96,8 @@ export class TaskService implements TaskConfigurationClient {
         terminateSignal: Deferred<string | undefined>,
         isBackgroundTaskEnded: Deferred<boolean | undefined>
     }>();
+    // URIs of the opened documents
+    protected openedDocuments: Set<string> = new Set();
```
Comment (akosyakov) [inline packages/task/src/browser/task-service.ts]: left over?

Comment (elaihau) [reply packages/task/src/browser/task-service.ts]: oops

**Comment by akosyakov** [comment]
code changes looks good, could someone please test it?

**Comment by elaihau** [comment]
Thank you for your time @vince-fugnitto !
