### PR TITLE
GH-6598: Exposed all handlers for a command.

### LINKED ISSUE #6598: [commands] As an extension developer I want to access all handlers for a command
### Description
 
I can get the visible and the active handler for a command, but not all of the available handlers. Extend the `CommandRegistry` API.

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

### PR DESCRIPTION
**Pull request by kittaakos**
Closes #6598.

Signed-off-by: Akos Kitta <kittaakos@typefox.io>

#### What it does

Exposed all handlers for a particular command via the new API.

#### How to test

Check the CI and the new tests.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/core/src/common/command.ts [hunk 1]
```diff
@@ -348,6 +348,15 @@ export class CommandRegistry implements CommandService {
         return undefined;
     }
 
+    /**
+     * Returns with all handlers for the given command. If the command does have any handlers,
```
Comment (vince-fugnitto) [inline packages/core/src/common/command.ts]: I believe there is a typo? 
"If the command **does not** have any handlers..."

Comment (kittaakos) [reply packages/core/src/common/command.ts]: Eagle eye ;) Fixed it, thanks!
