### PR TITLE
fix user storage regressions

### LINKED ISSUE #8301: keymaps: 'Open Keyboard Shortcuts in JSON' command should create file if it does not exist
#### Bug Description:

The command `Open Keyboard Shortcuts in JSON` should create the `keymaps.json` file if it does not exist instead of throwing an error:

```
monaco-editor-provider.js:203 Uncaught (in promise) Error: 'user_storage:/keymaps.json' is invalid
    at MonacoEditorProvider.<anonymous> (monaco-editor-provider.js:203)
    at step (monaco-editor-provider.js:71)
    at Object.next (monaco-editor-provider.js:52)
    at fulfilled (monaco-editor-provider.js:43)
```

#### Steps to Reproduce:

1. make sure that the `keymaps.json` file does not exist (ex: `rm -rf ~/.theia`)
2. open the keyboard shortcuts view, and attempt to open the `keymaps.json` with the toolbar item (`{ }`)
3. the error is thrown

<div align='center'>

bug

</div>

### LINKED ISSUE #8302: bug: error thrown when changing themes without a 'settings.json'
#### Bug Description:

There is an error thrown when changing themes without a `settings.json` present (no home `.theia`):

```
logger-protocol.ts:112 root ERROR Error: Unable to write file '/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/evinfug/.theia/settings.json')
    at new FileOperationError (file:///home/evinfug/workspaces/theia/examples/electron/lib/0.bundle.js:3060:28)
    at FileService.push.../../packages/filesystem/lib/browser/file-service.js.FileService.asFileOperationError (file:///home/evinfug/workspaces/theia/examples/electron/lib/0.bundle.js:1413:34)
    at FileService.push.../../packages/filesystem/lib/browser/file-service.js.FileService.rethrowAsFileOperationError (file:///home/evinfug/workspaces/theia/examples/electron/lib/0.bundle.js:1410:20)
    at FileService.<anonymous> (file:///home/evinfug/workspaces/theia/examples/electron/lib/0.bundle.js:1253:30)
    at step (file:///home/evinfug/workspaces/theia/examples/electron/lib/0.bundle.js:518:23)
    at Object.throw (file:///home/evinfug/workspaces/theia/examples/electron/lib/0.bundle.js:499:53)
    at rejected (file:///home/evinfug/workspaces/theia/examples/electron/lib/0.bundle.js:491:65)
Caused by: Error: Request 'writeFile' failed
    at Proxy.<anonymous> (file:///home/evinfug/workspaces/theia/examples/electron/lib/bundle.js:137680:33)
    at RemoteFileSystemProvider.push.../../packages/filesystem/lib/common/remote-file-system-provider.js.RemoteFileSystemProvider.writeFile (file:///home/evinfug/workspaces/theia/examples/electron/lib/78.bundle.js:923:28)
    at DelegatingFileSystemProvider.push.../../packages/filesystem/lib/common/delegating-file-system-provider.js.DelegatingFileSystemProvider.writeFile (file:///home/evinfug/workspaces/theia/examples/electron/lib/0.bundle.js:2765:34)
    at FileService.<anonymous> (file:///home/evinfug/workspaces/theia/examples/electron/lib/0.bundle.js:2179:60)
    at step (file:///home/evinfug/workspaces/theia/examples/electron/lib/0.bundle.js:518:23)
    at Object.next (file:///home/evinfug/workspaces/theia/examples/electron/lib/0.bundle.js:499:53)
    at file:///home/evinfug/workspaces/theia/examples/electron/lib/0.bundle.js:493:71
    at new Promise (<anonymous>)
    at push.../../packages/filesystem/lib/browser/file-service.js.__awaiter (file:///home/evinfug/workspaces/theia/examples/electron/lib/0.bundle.js:489:12)
    at FileService.push.../../packages/filesystem/lib/browser/file-service.js.FileService.doWriteUnbufferedQueued (file:///home/evinfug/workspaces/theia/examples/electron/lib/0.bundle.js:2156:16)
Caused by: EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/evinfug/.theia/settings.json'
    at new FileSystemProviderError (/home/evinfug/workspaces/theia/packages/filesystem/lib/common/files.js:230:28)
    at Object.createFileSystemProviderError (/home/evinfug/workspaces/theia/packages/filesystem/lib/common/files.js:239:25)
    at DiskFileSystemProvider.toFileSystemProviderError (/home/evinfug/workspaces/theia/packages/filesystem/lib/node/disk-file-system-provider.js:1168:24)
    at DiskFileSystemProvider.<anonymous> (/home/evinfug/workspaces/theia/packages/filesystem/lib/node/disk-file-system-provider.js:448:36)
    at step (/home/evinfug/workspaces/theia/packages/filesystem/lib/node/disk-file-system-provider.js:73:23)
    at Object.throw (/home/evinfug/workspaces/theia/packages/filesystem/lib/node/disk-file-system-provider.js:54:53)
    at rejected (/home/evinfug/workspaces/theia/packages/filesystem/lib/node/disk-file-system-provider.js:46:65)
```
For such a case, should the preference service create the `settings.json` if we programatically attempt to set a preference?

#### Steps to Reproduce:

1. make sure that your home `.theia` folder does not exist (ex: `rm -rf ~/.theia`)
2. start the application
3. open devtools
4. change theme using the command palette
5. notice the thrown errors on the console

<div align='center'>

theme

</div>

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

- fix #8302: ensure that user storage URI has a top-level directory. Otherwise `FileService` fails to create the user directory.
- remove hardcoded constants from preferences UI. It is a secret of the preference service to know which config URI should be use for each scope in the context of the given resource.
- fix #8301: use monaco model to handle keymaps. It allows to check whether model is invalid before opening it, in addition keymaps are now updated with minimal edits and preserving user formatting and comments.

#### How to test

- Start theia app and remove .theia in user home. Try to open keymaps and user settings.
- Try to modify keymaps and check that changes are reflected.
- Try to open settings file for different scopes, i.e. user, workspace, folder as a workspace and workspace folder.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/core/src/browser/preferences/preference-provider.ts [hunk 1]
```diff
@@ -159,12 +159,17 @@ export abstract class PreferenceProvider implements Disposable {
...
     /**
-     * undefined if cannot be provided for the given resource uri
+     * Returns undefined if there is no valid config URI for the given resource URI.
      */
     getConfigUri(resourceUri?: string): URI | undefined {
         return undefined;
     }
 
+    /**
+     * Returns undefined if there is config URI at all for the given resource URI.
```
Comment (akosyakov) [inline packages/core/src/browser/preferences/preference-provider.ts:169]: there is *no*
