### PR TITLE
Ensure preference files only in problems view if open

### LINKED ISSUE #7154: json: markers reported on start for files not opened
**Description**

When `theia` is used as a workspace, I noticed that `json` warnings are outputted (`.theia`), despite any of the files being opened. Is this the intended behavior? When verifying the same use case in VS Code, no warnings are present in the `problems` view:

image

**Steps to Reproduce**
1. start the application (better to start with a fresh port and no local storage)
2. open `theia` as a workspace (no files should be opened)
3. the `problems view` outputs warnings for **json** files under `.theia`

### PR DESCRIPTION
**Pull request by colin-grant-work**
#### What it does

Fixes #7154 by disposing of the preference system's reference to the `MonacoEditorModel` when not in use. This is similar to [VSCode's approach](https://github.com/microsoft/vscode/blob/edbf56a72a0630649effa940940d0800d42753e2/src/vs/workbench/services/configuration/common/configurationEditingService.ts#L184) in which the model reference is disposed of at the end of the write.

#### How to test

1. Open the application
2. Open the problems view
3. Open a preference file
4. Ensure that the preference file has some problems (dangling commas, schema violations)
5. Close the file
6. Observe that the problems view does not continue to show the problems for the preference file when it is closed.
---
1. Do normal preference operations (set values in the UI, set values in the file)
2. Observe that the changes take effect as expected.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/preferences/src/browser/preference-transaction-manager.ts [hunk 1]
```diff
@@ -0,0 +1,203 @@
...
+export abstract class Transaction<Arguments extends unknown[], Result = unknown, Status = unknown> {
+    protected _open = true;
+    get open(): boolean {
+        return this._open;
+    }
+    protected _result = new Deferred<Result | false>();
+    get result(): Promise<Result | false> {
+        return this._result.promise;
+    }
+    protected readonly queue = new Mutex(new CancellationError);
```
Comment (msujew) [inline packages/preferences/src/browser/preference-transaction-manager.ts:42]: Nitpick: Missing parenthesis. We should probably activate the ESLint rule for that, I've seen that in some other PR reviews as well.

File: packages/preferences/src/browser/preference-transaction-manager.ts [hunk 2]
```diff
@@ -0,0 +1,203 @@
...
+import { MonacoTextModelService } from '@theia/monaco/lib/browser/monaco-text-model-service';
+import { MonacoJSONCEditor } from './monaco-jsonc-editor';
+import { EditorManager } from '@theia/editor/lib/browser/editor-manager';
+
+export interface OnWillConcludeEvent<T> extends WaitUntilEvent {
+    status: T | false;
+}
+
+@injectable()
+export abstract class Transaction<Arguments extends unknown[], Result = unknown, Status = unknown> {
```
Comment (msujew) [inline packages/preferences/src/browser/preference-transaction-manager.ts:33]: Suggestion: Add some documentation explaining which use cases the `Transaction` type covers.

**Review by msujew — COMMENTED** [review]
The changes look really good to me 👍

The editor reference seems to be disposed as expected, removing the associated problems. As a consequence, the problems view isn't polluted with any configuration related issues.

I'll let others review as well.

File: packages/preferences/src/browser/preference-transaction-manager.ts (hunk 1 above)
Comment (colin-grant-work) [reply packages/preferences/src/browser/preference-transaction-manager.ts]: The omission was deliberate but completely arbitrary. I've added the parentheses. 👍

File: packages/preferences/src/browser/preference-transaction-manager.ts (hunk 2 above)
Comment (colin-grant-work) [reply packages/preferences/src/browser/preference-transaction-manager.ts:36]: I've added JSDocs for the Transaction class and its methods and fields.

**Review by vince-fugnitto — APPROVED** [review]
The changes look good to me :+1: 

- [x] confirmed the markers in the `settings.json` file only appear if the file is opened (similarly to vscode) so there is no noise on startup in the problems-view
- [x] confirmed that markers in the `settings.json` file are properly populated (ex: dangling commas, invalid preferences)
- [x] confirmed that updating preferences take effect like today

---

I noticed https://github.com/eclipse-theia/theia/issues/10599 when testing but I confirmed that it also exists on master.

**Comment by colin-grant-work** [comment]
@vince-fugnitto, I couldn't come up with a better solution to flakiness of these tests than just extending the timeout, and that seems to have gotten it through CI, at least. If you're OK with that, I'll write up breaking changes from this PR and merge it this week.

**Comment by colin-grant-work** [comment]
@msujew, just want to confirm your (infomal) approval stands here?

**Review by msujew — APPROVED** [review]
@colin-grant-work Yep, still stands :)

I did a brief look over the changed code and performed another look at the App running with your changes. Everything is still looking good 👍

**Comment by Okon199** [comment]
Please help I'm working through alot
