### PR TITLE
fix #8106:fix open deleted file in git scm errors

### LINKED ISSUE #8106: Open deleted file in GIT SCM causes errors
### Bug Description:
Open deleted file in GIT SCM causes errors

### Steps to Reproduce:
1. delete any file
2. open it in scm

UnStaged Case
image

Staged Case
image

### VS Code Case 
UnStaged Case
image

Staged Case
image

### Additional Information

- Operating System: MacOS Mojave 10.14.6
- Theia Version: 1.3.0

### PR DESCRIPTION
**Pull request by datou0412**
Signed-off-by: 二凢 <dingyu.wdy@alibaba-inc.com>

#### What it does

Fixes: #8106

There is a bug when try to open deleted files in git scm, it causes errors and can not open anything.

For more detail, view the [ISSUE #8106](https://github.com/eclipse-theia/theia/issues/8106)

#### How to test

1. Delete any file
2. Open git scm view
3. Click the deleted file in CHANGES or STAGED CHANGES

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
@datou0412 Could you update the PR description please?

**Comment by lmcbout** [comment]
Open Deleted file from SCM tree in git is only available if I click on the file name to open. If I select the "Open File" button on the SCM entry, then the error is still present and the file do NOT open in the editor

ScmDeletedFileButton

**Comment by datou0412** [comment]
> Open Deleted file from SCM tree in git is only available if I click on the file name to open. If I select the "Open File" button on the SCM entry, then the error is still present and the file do NOT open in the editor
> 
> ScmDeletedFileButton

yep, its another bug. I will try to fix it

File: packages/git/src/browser/git-contribution.ts [hunk 1]
```diff
@@ -440,6 +441,19 @@ export class GitContribution implements CommandContribution, MenuContribution, T
         registry.registerCommand(GIT_COMMANDS.OPEN_CHANGED_FILE, {
             execute: (...arg: ScmResource[]) => {
                 for (const resource of arg) {
+                    const provider = this.repositoryProvider.selectedScmProvider;
+                    if (provider) {
+                        const gitStatus = provider.getStatus();
+                        if (gitStatus) {
+                            const deletedFile = gitStatus.changes.find(change =>
+                                change.status === GitFileStatus.Deleted && change.uri === resource.sourceUri.toString());
```
Comment (akosyakov) [inline packages/git/src/browser/git-contribution.ts:449]: I wonder whether we should fix `resource.sourceUri` in first place instead? cc @westbury

Comment (datou0412) [reply packages/git/src/browser/git-contribution.ts:449]: So, what's the conclusion?

File: packages/git/src/browser/git-contribution.ts [hunk 2]
```diff
@@ -440,6 +441,19 @@ export class GitContribution implements CommandContribution, MenuContribution, T
...
+                            if (deletedFile) {
+                                const deletedFileUri = new URI(deletedFile.uri).withScheme(GIT_RESOURCE_SCHEME).withQuery('HEAD');
+                                this.editorManager.open(deletedFileUri, { mode: 'reveal' });
+                                return;
+                            }
+                        }
+                    }
                     this.editorManager.open(resource.sourceUri, { mode: 'reveal' });
```
Comment (akosyakov) [inline packages/git/src/browser/git-contribution.ts:457]: could you try to call `resource.open` here instead and revert the rest

File: packages/git/src/browser/git-contribution.ts (hunk 1 above)
Comment (akosyakov) [reply packages/git/src/browser/git-contribution.ts:449]: please see https://github.com/eclipse-theia/theia/pull/8107#discussion_r448153652

File: packages/git/src/browser/git-contribution.ts (hunk 2 above)
Comment (datou0412) [reply packages/git/src/browser/git-contribution.ts:457]: `resource.open()` will open the diff editor in the `Modified` case

Comment (datou0412) [reply packages/git/src/browser/git-contribution.ts:457]: The key is how to filter the `Deleted` cases by `resource`. I know my current method is not that elegant. Any suggestions?

Comment (akosyakov) [reply packages/git/src/browser/git-contribution.ts:457]: let's go with it if it works

**Comment by akosyakov** [comment]
@lmcbout could you try again please

**Comment by westbury** [comment]
The 'Open File' action always opens the file as it exists in the working tree.  IMO, the bug is that the 'Open File' action should not be there for a deleted file, since it does not exist and cannot be opened.  So remove from both the context menu and the inline action.

Double-clicking (or single-clicking depending on preferences) opens the diff.  The diff for a deleted file should just show the contents that were deleted.  This is technically a diff, even though one just sees one version of the file.  The file contents should not be modifiable, and a diff URL should be used to open it, with (HEAD) or (Index) showing in the title.

VS-Code, interestingly enough, has exactly the same bug.  'Open File' is there both in the context menu and inline action but it does nothing.  Although we can't easily fix this when using the Git builtin (which I have not tested but I assume also does nothing), we can fix this in the Theia's git package.

File: packages/git/src/browser/git-scm-provider.ts [hunk 3]
```diff
@@ -195,6 +195,9 @@ export class GitScmProvider implements ScmProvider {
 
     getUriToOpen(change: GitFileChange): URI {
         const changeUri: URI = new URI(change.uri);
+        if (change.status === GitFileStatus.Deleted) {
+            return changeUri.withScheme(GIT_RESOURCE_SCHEME).withQuery('HEAD');
+        }
```
Comment (westbury) [inline packages/git/src/browser/git-scm-provider.ts:200]: I don't think this code is complete.  Consider what happens if you modify a file, stage the file, then delete the file.  You should see the file with 'M' status in the staged section and with a 'D' status in the unstaged section.  (If one actually tries this out then you will see an incorrect 'M' in the unstaged section.  That is because of this bug https://github.com/eclipse-theia/theia/issues/7789).  If you click anything in the unstaged section then you should see the diff between the staged and the unstaged.  That means if you click on the deleted file in the unstaged section then you should see the contents of the file in the index, not the contents of the file in HEAD.

Until https://github.com/eclipse-theia/theia/issues/7789 is fixed you won't be able to test all the cases here.  So on that basis I would be happy with the changes currently in git-scm-provider with a TODO that more work is needed when https://github.com/eclipse-theia/theia/issues/7789 is fixed.  I think the suggestion will be correct in all cases, but I can't test it without fixing 7789.

```suggestion
        if (change.status === GitFileStatus.Deleted) {
           if (change.staged) { 
               return changeUri.withScheme(GIT_RESOURCE_SCHEME).withQuery('HEAD');
           } else {    
               return changeUri.withScheme(GIT_RESOURCE_SCHEME);
            }
         }
```

**Comment by westbury** [comment]
> If I select the "Open File" button on the SCM entry, then the error is still present and the file do NOT open in the editor

@lmcbout @akosyakov  As I commented, I don't think we should be able to open a file that has been deleted.  "Open File" opens what is in the file system.  We should remove "Open File" for files that have been deleted but that is a different issue.  Are you okay if we leave the code in git-contribution unchanged in this PR?  So we just have the fix in git-scm-provider?

@datou0412 Thanks for making the code changes and adding the TODO.   There should be an explanation following the TODO, so others know that the TODO is to test the code.  However, on further thought, it is probably better just to update #7789 to make sure this gets tested.  So if you want to remove the TODO that is fine too.  I just didn't want the testing of this code to get missed.

**Comment by akosyakov** [comment]
@akosyakov it is fine with me

**Comment by lmcbout** [comment]
I also noticed than the "Open File" does nothing in VSCODE. It is fine with me as well. We can always "Discard Changes" for a deleted file to bring it back to the workspace. So this PR solves what it is supposed to do

**Comment by westbury** [comment]
@datou0412 so we can merge this if you 1) revert the changes in git-contribution and 2) either add a description after the TODO or perhaps better just remove the TODO.  Sorry, I know this takes the commit almost back to where you started.
