### PR TITLE
Handle deleted files in open editors widget

### LINKED ISSUE #10322: Open Editors causes error on deleted file
### Bug Description:

If the editor for a deleted file is open, the `OpenEditorTreeModel` causes an error when trying to update.

image

image

### Steps to Reproduce:

1. Set the preference for close editor on delete to false.
2. Open a file.
3. Delete that file, but keep the editor open
4. Open / close other files
5. Watch the console for errors

### Additional Information

- Operating System: RHEL7 Electron 
- Theia Version: 1.18.0

### PR DESCRIPTION
**Pull request by kenneth-marut-work**
image

#### What it does

Fixes #10322 by adding support for deleted editors in the Open Editors widget. Adds a strikethrough decoration when a deleted editor is detected.

#### How to test

- Build this branch and open a workspace with some files
- Ensure the `Close On File Delete` preference is set to false
- Open several files as editors (both regular and preview editor(s))
- Ensure the open editors widget is shown in the navigator
- In an external terminal delete the files you have opened using, observe that the deleted files are decorated with a strike-through
- Drag the deleted editors around to different tabbars and observe that the decorations persist
- Observe there are no errors in the terminal, and that you can continue to open/add new editors and the Open Editors tree is properly updated
- Restore the deleted files (with `git restore`) and observe the strikethrough is removed

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/editor-preview/src/browser/editor-preview-tree-decorator.ts [hunk 1]
```diff
@@ -49,6 +56,35 @@ export class EditorPreviewTreeDecorator implements TreeDecorator, FrontendApplic
...
         this.editorWidgets.forEach(widget => this.registerEditorListeners(widget));
+        this.fileService.onDidFilesChange(async (event: FileChangesEvent) => {
+            if (!this.corePreferences['workbench.editor.closeOnFileDelete']) {
+                await this.checkForEditorDeleted(event);
+                this.fireDidChangeDecorations((tree: Tree) => this.collectDecorators(tree));
+            }
+        });
+    }
+
+    protected async checkForEditorDeleted(event: FileChangesEvent): Promise<void[] | undefined> {
```
Comment (colin-grant-work) [inline packages/editor-preview/src/browser/editor-preview-tree-decorator.ts:67]: Perhaps `Promise<void>` and just `await Promise.all(fileExistPromises)` as the last line?

File: packages/editor-preview/src/browser/editor-preview-tree-decorator.ts [hunk 2]
```diff
@@ -93,13 +129,18 @@ export class EditorPreviewTreeDecorator implements TreeDecorator, FrontendApplic
...
-            if (OpenEditorNode.is(node)) {
+            if (OpenEditorNode.is(node) && NavigatableWidget.is(node.widget)) {
                 const { widget } = node;
                 const isPreviewWidget = widget instanceof EditorPreviewWidget && widget.isPreview;
-                const decorations: TreeDecoration.Data = {
-                    fontData: { style: isPreviewWidget ? 'italic' : undefined }
-                };
-                result.set(node.id, decorations);
+                const deleted = this.deletedEditorIds.has(widget.id);
+                const style: MaybeArray<TreeDecoration.FontStyle> = [];
```
Comment (colin-grant-work) [inline packages/editor-preview/src/browser/editor-preview-tree-decorator.ts:136]: Since you're initializing it as an array, do you need to type it `MaybeArray`?

File: packages/navigator/src/browser/open-editors-widget/navigator-open-editors-tree-model.ts [hunk 3]
```diff
@@ -84,7 +88,15 @@ export class OpenEditorsModel extends FileTreeModel {
                 this.selectNode(nodeToSelect);
             }
         }));
-        this.toDispose.push(this.applicationShell.onDidAddWidget(() => this.updateOpenWidgets()));
+        this.toDispose.push(this.applicationShell.onDidAddWidget(async () => {
+            await this.updateOpenWidgets();
+            const existingWidgetIds = this.editorWidgets.map(widget => widget.id);
```
Comment (colin-grant-work) [inline packages/navigator/src/browser/open-editors-widget/navigator-open-editors-tree-model.ts:93]: Maybe make this a `Set` so that it's easier to check for membership?

Comment (kenneth-marut-work) [reply packages/navigator/src/browser/open-editors-widget/navigator-open-editors-tree-model.ts]: Nice idea

File: packages/editor-preview/src/browser/editor-preview-tree-decorator.ts (hunk 2 above)
Comment (kenneth-marut-work) [reply packages/editor-preview/src/browser/editor-preview-tree-decorator.ts]: 👍

File: packages/editor-preview/src/browser/editor-preview-tree-decorator.ts (hunk 1 above)
Comment (kenneth-marut-work) [reply packages/editor-preview/src/browser/editor-preview-tree-decorator.ts]: 👍

**Review by vince-fugnitto — COMMENTED** [review]
I confirmed the following behavior :+1: 

- [x] confirmed that the strike-through decoration is applied when the resource is deleted
- [x] confirmed that the decoration persists if the deleted editor is moved (different groups)
- [x] confirmed that restoring the file removes the decoration (from outside the application)
- [x] confirmed that restoring the file removes the decoration through git 
- [x] confirmed when deleted that the decoration is removed if the file is re-created manually in the app

**Comment by colin-grant-work** [comment]
An earlier version of this PR implemented the strikethrough decoration in the `editor-preview` package; the current version piggy-backs off of the git decorator's work. The downside of the current approach is that it doesn't work for untracked files or in workspaces that aren't source controlled.

The previous approach required a fair bit of code to track which editors corresponded to deleted files; the current approach is a fair bit simpler. It might be possible to achieve almost the same simplicity by implementing a decorator (perhaps a decorator service, rather than a tree decorator) in the `monaco` package, which knows whether its models are `valid` or not.

**Comment by vince-fugnitto** [comment]
Along with what @colin-grant-work mentioned, I also thought about not having the deleted decoration as part of `scm` as well (due to the same concerns about being under version control), and instead having it under `filesystem` (which knows about deleted files).

At the moment `@theia/filesystem` applies a `(deleted)` suffix to widgets that have their resources deleted such as an editor:

https://github.com/eclipse-theia/theia/blob/f09fc1a41c66635cd4ebc30a3737d1c237474383/packages/filesystem/src/browser/filesystem-frontend-contribution.ts#L267

Perhaps we can generalize the behavior to decorate from that extension.

**Comment by kenneth-marut-work** [comment]
@vince-fugnitto @colin-grant-work 
I've pushed a change that hooks into the filesystem's mechanism that adds the `(deleted)` "decorations" to the editor tabs. Since Navigator has a dependency on Filesystem, I've implemented the decorator inside the navigator package. Let me know if this is what you had in mind, thanks!

File: packages/filesystem/src/browser/filesystem-frontend-contribution.ts [hunk 4]
```diff
@@ -301,13 +304,15 @@ export class FileSystemFrontendContribution implements FrontendApplicationContri
             }
             if (!deleted) {
                 widget.title.label += this.deletedSuffix;
+                this.editorFileWasChangedEmitter.fire({ editor: widget, type: FileChangeType.DELETED });
```
[the remark this answers is not in the document]
Comment (kenneth-marut-work) [reply packages/filesystem/src/browser/filesystem-frontend-contribution.ts:307]: Shouldn't be a problem to do so, though there might be a fair bit of code duplication since the `file-system-frontend-contribution` has a quite a bit of filtering/checks to match up the fileChangeEvents with the open NavigatableWidgets. I thought that adding an event would result in the fewer lines :)

Let me know what you think, happy to make the change either way

File: packages/filesystem/src/browser/filesystem-frontend-contribution.ts [hunk 5]
```diff
@@ -77,6 +77,9 @@ export class FileSystemFrontendContribution implements FrontendApplicationContri
     @inject(FileService)
     protected readonly fileService: FileService;
 
+    protected editorFileWasChangedEmitter = new Emitter<{ editor: NavigatableWidget, type: FileChangeType }>();
+    readonly onEditorFileChanged = this.editorFileWasChangedEmitter.event;
```
Comment (vince-fugnitto) [inline packages/filesystem/src/browser/filesystem-frontend-contribution.ts:81]: I'm fine with https://github.com/eclipse-theia/theia/pull/10361/files#r747644822 and keeping the events in the contribution, only comment would be if we have to update the naming of the events following the [coding guideline](https://github.com/eclipse-theia/theia/wiki/Coding-Guidelines#event_names) but I'll leave it to your discretion :+1:

File: packages/navigator/src/browser/open-editors-widget/navigator-deleted-editor-decorator.ts [hunk 6]
```diff
@@ -0,0 +1,75 @@
...
+import { DepthFirstTreeIterator, NavigatableWidget, Tree, TreeDecoration, TreeDecorator } from '@theia/core/lib/browser';
+import { FileSystemFrontendContribution } from '@theia/filesystem/lib/browser/filesystem-frontend-contribution';
+import { Emitter } from '@theia/core';
+import { OpenEditorNode } from './navigator-open-editors-tree-model';
+import { FileChangeType } from '@theia/filesystem/lib/browser';
+
+@injectable()
+export class NavigatorDeletedEditorDecorator implements TreeDecorator {
+    @inject(FileSystemFrontendContribution) protected readonly fileSystemContribution: FileSystemFrontendContribution;
+    readonly id = 'theia-deleted-editor-decorator';
```
Comment (vince-fugnitto) [inline packages/navigator/src/browser/open-editors-widget/navigator-deleted-editor-decorator.ts:27]: minor:

```suggestion
export class NavigatorDeletedEditorDecorator implements TreeDecorator {

    @inject(FileSystemFrontendContribution)
    protected readonly fileSystemContribution: FileSystemFrontendContribution;
    
    readonly id = 'theia-deleted-editor-decorator';
```

File: packages/navigator/src/browser/open-editors-widget/navigator-deleted-editor-decorator.ts [hunk 7]
```diff
@@ -0,0 +1,75 @@
...
+        this.fileSystemContribution.onEditorFileChanged(({ editor, type }) => {
+            if (type === FileChangeType.DELETED) {
+                this.deletedEditors.add(editor);
+            } else if (type === FileChangeType.ADDED) {
+                this.deletedEditors.delete(editor);
+            }
+            this.fireDidChangeDecorations((tree: Tree) => this.collectDecorators(tree));
+        });
+    }
+    decorations(tree: Tree): Map<string, TreeDecoration.Data> {
```
Comment (vince-fugnitto) [inline packages/navigator/src/browser/open-editors-widget/navigator-deleted-editor-decorator.ts:45]: minor: add a `newline`.

```suggestion
    }
    
    decorations(tree: Tree): Map<string, TreeDecoration.Data> {
```

**Review by vince-fugnitto — COMMENTED** [review]
I confirmed that the functionality works as intended :+1: 

- [x] deleting a file outside the app causes the `line-through` for open editors
- [x] restoring the file removes the decoration
- [x] the decoration persists when the file is moved to different editor groups
- [x] the decoration now works with workspaces outside of version control :+1: 
- [x] restoring the file in-app (by recreating it manually) removes the decoration

File: packages/filesystem/src/browser/filesystem-frontend-contribution.ts (hunk 5 above)
Comment (kenneth-marut-work) [reply packages/filesystem/src/browser/filesystem-frontend-contribution.ts]: Thanks for the feedback! I've pushed a change that addresses your comments

File: packages/filesystem/src/browser/filesystem-frontend-contribution.ts [hunk 8]
```diff
@@ -77,6 +77,9 @@ export class FileSystemFrontendContribution implements FrontendApplicationContri
     @inject(FileService)
     protected readonly fileService: FileService;
 
+    protected editorFileDidChangeEmitter = new Emitter<{ editor: NavigatableWidget, type: FileChangeType }>();
+    readonly onDidChangeEditorFile = this.editorFileDidChangeEmitter.event;
```
Comment (vince-fugnitto) [inline packages/filesystem/src/browser/filesystem-frontend-contribution.ts:81]: minor - generally the emitter and event have similar names:

```suggestion
    protected onDidChangeEditorFileEmitter = new Emitter<{ editor: NavigatableWidget, type: FileChangeType }>();
    readonly onDidChangeEditorFile = this.onDidChangeEditorFileEmitter.event;
```

File: packages/navigator/src/browser/open-editors-widget/navigator-deleted-editor-decorator.ts [hunk 9]
```diff
@@ -0,0 +1,77 @@
...
+
+@injectable()
+export class NavigatorDeletedEditorDecorator implements TreeDecorator {
+
+    @inject(FileSystemFrontendContribution)
+    protected readonly fileSystemContribution: FileSystemFrontendContribution;
+
+    readonly id = 'theia-deleted-editor-decorator';
+    protected readonly decorationsChangedEmitter = new Emitter();
+    readonly onDidChangeDecorations = this.decorationsChangedEmitter.event;
```
Comment (vince-fugnitto) [inline packages/navigator/src/browser/open-editors-widget/navigator-deleted-editor-decorator.ts:32]: minor - related to a previous comment:

```suggestion
    protected readonly onDidChangeDecorationsEmitter = new Emitter();
    readonly onDidChangeDecorations = this.decorationsChangedEmitter.event;
```

**Review by vince-fugnitto — APPROVED** [review]
The changes work well for me, I'll let @colin-grant-work take a look if he wants :+1:

File: packages/filesystem/src/browser/filesystem-frontend-contribution.ts (hunk 8 above)
Comment (kenneth-marut-work) [reply packages/filesystem/src/browser/filesystem-frontend-contribution.ts]: 👍

File: packages/navigator/src/browser/open-editors-widget/navigator-deleted-editor-decorator.ts (hunk 9 above)
Comment (kenneth-marut-work) [reply packages/navigator/src/browser/open-editors-widget/navigator-deleted-editor-decorator.ts]: 👍

**Comment by kenneth-marut-work** [comment]
> The changes work well for me, I'll let @colin-grant-work take a look if he wants 👍

Thanks Vince, he's out today but should be back tomorrow

File: packages/navigator/src/browser/open-editors-widget/navigator-deleted-editor-decorator.ts [hunk 10]
```diff
@@ -0,0 +1,77 @@
...
+                        fontData: {
+                            style: 'line-through',
+                        }
+                    };
+                    deletedEditorsCopy.delete(node.widget);
+                    result.set(node.id, deletedDecoration);
+                }
+            }
+        }
+        deletedEditorsCopy.forEach(remainingEditor => this.deletedEditors.delete(remainingEditor));
```
Comment (colin-grant-work) [inline packages/navigator/src/browser/open-editors-widget/navigator-deleted-editor-decorator.ts:70]: This code could behave incorrectly if this decorator were used in a (hypothetical) 'Open TypeScript Editors' widget. Then any deleted files that were not TypeScript would be removed from the deleted tracker when the decorator was applied to that tree and be unavailable to (non-hypothetical) general Open Editors widgets. It might be better to listen to editor closures and remove things from the tracking set then?

Comment (kenneth-marut-work) [reply packages/navigator/src/browser/open-editors-widget/navigator-deleted-editor-decorator.ts]: Good suggestion, I've updated the tracking system for the deleted editors to rebuild the `this.deletedEditors` in response to onDidAddWidget

File: packages/filesystem/src/browser/filesystem-frontend-contribution.ts [hunk 11]
```diff
@@ -17,7 +17,7 @@
 import { injectable, inject } from '@theia/core/shared/inversify';
 import URI from '@theia/core/lib/common/uri';
 import { environment } from '@theia/core/shared/@theia/application-package/lib/environment';
-import { MaybePromise, SelectionService, isCancelled } from '@theia/core/lib/common';
+import { MaybePromise, SelectionService, isCancelled, Emitter } from '@theia/core/lib/common';
 import { Command, CommandContribution, CommandRegistry } from '@theia/core/lib/common/command';
```
Comment (iamtangram) [inline packages/filesystem/src/browser/filesystem-frontend-contribution.ts:21]: sss

**Review by colin-grant-work — APPROVED** [review]
This is working well for me. 👍 Thanks for moving to a URI-tracking system rather than an editor-tracking system. I think it should be more robust and more (potentially) useful elsewhere.

**Comment by kenneth-marut-work** [comment]
Thanks for the review @colin-grant-work and @vince-fugnitto. Merging now 👍
