### PR TITLE
Set menu bar less often at startup

### LINKED ISSUE #14280: Calling `setMenu()` More than 400 Times at Startup
### Bug Description:
While debugging a problem, I noticed we invoke `ElectronAPI.setMenu()` over 400 times at startup. It would be good to reduce that.

### Steps to Reproduce:
Put a log statement in the core `preload.ts#setMenu()` implementation. 

### Additional Information

- Operating System: Windows
- Theia Version: 1.54.x master

### PR DESCRIPTION
**Pull request by tsmaeder**
#### What it does
Debugging some code, I found out we're setting the main menu bar about 400 times at startup. This change reduces the number to around 10.

Fixes #14280

Contributed on behalf of STMicroelectronics
#### How to test
Make sure the main menu bar is set correctly, including checkmarks (example "View->Toggle Minimap").
#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/core/src/electron-browser/menu/electron-main-menu-factory.ts [hunk 1]
```diff
@@ -74,57 +74,58 @@ export type ElectronMenuItemRole = ('undo' | 'redo' | 'cut' | 'copy' | 'paste' |
...
 
-    protected _menu?: MenuDto[];
-    protected _toggledCommands: Set<string> = new Set();
+    protected menu?: MenuDto[];
+    protected toggledCommands: Set<string> = new Set();
 
     @inject(PreferenceService)
     protected preferencesService: PreferenceService;
 
+    setMenuBar = debounce(() => this.doSetMenuBar());
```
Comment (msujew) [inline packages/core/src/electron-browser/menu/electron-main-menu-factory.ts:83]: Minor: Having an explicit delay value here would be good. I never know, what the default for this is.
```suggestion
    setMenuBar = debounce(() => this.doSetMenuBar(), 10);
```

**Review by msujew — APPROVED** [review]
Works great, thanks!

File: packages/core/src/electron-browser/menu/electron-main-menu-factory.ts (hunk 1 above)
Comment (tsmaeder) [reply packages/core/src/electron-browser/menu/electron-main-menu-factory.ts]: @msujew I upped the value to 100, since updating the main menu 100 times per second seems a bit excessive ;-)
