### PR TITLE
[task]: Update `TaskConfigurationManager` on Workspace Location Change

### LINKED ISSUE #9329: Workspace Model Not Updated `onWorkspaceLocationChanged`
### Bug Description:

The `TaskConfigurationManager` proxies requests for `TaskScope.Workspace` to either folder scope or the workspace file depending on workspace status. It currently listens to `onWorkspaceChanged` to detect changes to the roots, but does not listen `onWorkspaceLocationChanged` events to detect the saving a new workspace file.

### Steps to Reproduce:

1. Get the code from [this branch](https://github.com/colin-grant-work/theia/tree/reproduction/bad-workspace-handling) to add a command to log what the configuration service lists in workspace scope. (ctrl+p, search 'Check tasks listed in workspace scope.')
2. Build.
3. Open a single-root, unsaved workspace.
4. If there are no tasks in the root, add one, e.g.
```
{
  "version": "2.0.0",
  "tasks": [
    {"label": "Folder task", "type": "shell", "command": "htop"}
  ]
}
```
5. Run the command to log tasks in workspace scope.
6. See that the tasks in the folder scope are logged (since folder scope = workspace scope)
7. Run `File > Save Workspace as ...` and save the workspace wherever you'd like.
8. Run the command to log tasks in workspace scope.
9. See that the tasks in folder scope are still logged, even though folder scope != workspace scope after saving the workspace file.

### Additional Information

- Operating System: RHEL
- Theia Version: `master`

### PR DESCRIPTION
**Pull request by colin-grant-work**
Signed-off-by: Colin Grant <colin.grant@ericsson.com>

#### What it does

Fixes #9329 by adding a listener for `onLocationChanged` to the `TaskConfigurationManager` to ensure that it updates the target of its workspace proxy when a workspace file is created.

In addition, it fires a changed event when the workspace proxy is changed, parallel to the events fired when new folder-scope models are created.

#### How to test

1. Checkout this PR branch.
2. Cherry pick the commit from [this branch](https://github.com/colin-grant-work/theia/tree/reproduction/bad-workspace-handling) to add a command to log what the configuration service lists in workspace scope. (ctrl+p, search 'Check tasks listed in workspace scope.')
3. Open a single-root, unsaved workspace.
4. If there are no tasks in the root, add one, e.g.
```
{
  "version": "2.0.0",
  "tasks": [
    {"label": "Folder task", "type": "shell", "command": "htop"}
  ]
}
```
5. Run the command to log tasks in workspace scope.
6. See that the tasks in the folder scope are logged (since folder scope = workspace scope)
7. Run `File > Save Workspace as ...` and save the workspace wherever you'd like.
8. Run the command to log tasks in workspace scope.
9. See that the tasks in folder scope are **not** logged, since folder scope != workspace scope after saving the workspace file.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/task/src/browser/task-configurations.ts [hunk 1]
```diff
@@ -146,19 +146,16 @@ export class TaskConfigurations implements Disposable {
     }
 
     getRawTaskConfigurations(scope?: TaskConfigurationScope): (TaskCustomization | TaskConfiguration)[] {
-        if (!scope) {
+        if (scope === undefined) {
```
Comment (colin-grant-work) [inline packages/task/src/browser/task-configurations.ts:149]: Since the enum has the non-string scopes as `1` and `2`, this wasn't causing an issue, but it could have if a scope ended up with enum value `0`.

Comment (kenneth-marut-work) [reply packages/task/src/browser/task-configurations.ts:149]: Looks good 👍

**Review by kenneth-marut-work — APPROVED** [review]
Tested and working 👍
