### PR TITLE
fix(core): unbind all services in connection container on close

### LINKED ISSUE #17383: Singleton services in connection-scoped containers are never destroyed
### Bug Description:

A singleton-scoped service in an Inversify container can decorate a method with `@preDestroy()` to provide clean-up behaviour that will run when that service is unbound. This should be the preferred way to clean up singleton services because their lifecycle is owned by the container that created them[^fn1].

The problem is that singleton services bound in the backend in frontend-connection scope via contributions on the `ConnectionContainerModule` contribution point are never unbound, so their `@preDestroy()` hooks never run, and there often isn't any sensible alternative trigger to clean them up. At any rate there shouldn't have to be because Inversify gives us `@preDestroy()`.

[^fn1]: Transient services should not allocate resources that would need such clean-up because their ownership is undefined. Factory-created services should be `Disposable` if they allocate resources because their ownership is definitely the client's.

### Steps to Reproduce:

This problem is a matter of resource leaks in the backend when frontend connections are closed, so there aren't practical steps to reproduce in the Theia example apps. Instead I've [created a unit test][test] on [a branch][br] that demonstrates the problem by failing and would pass with a fixed messaging service implementation.

1. Check out the branch.
2. Build and run the `@theia/core` tests.
3. See the TDD test fail.

[br]: https://github.com/eclipse-theia/theia/tree/cdamus/message-container-cleanup
[test]: https://github.com/eclipse-theia/theia/blob/573cf5b68c73408ed387d29f2c4942ca162c35c9/packages/core/src/node/messaging/test/default-messaging-service.spec.ts#L31

### Additional Information

- Operating System: All
- Theia Version: latest main branch as of 21 April 2026 (1.70.x)

### PR DESCRIPTION
**Pull request by cdamus**
#### What it does

Unbinds all services in the connection container on close of the socket. This lets `@preDestroy` hooks run in any singletons to clean up resources that they may have allocated.

Note that this does not interfere in any way with the timer-based reconnection strategy for fault-tolerant RPC connections. The container is only unbound once the connection is definitively closed. If a connection recovers from a brief outage, then all of the backend services will still be there ready to serve it.

Fixes #17383

#### How to test

Besides the included new automated test, add an `@preDestroy` clean-up method to some service bound in the backend in a connection-scoped container and do what is best to observe that it runs that clean-up when a frontend disconnects.

#### Follow-ups

None.

#### Breaking changes

- [ ] This PR introduces breaking changes and requires careful review. If yes, the breaking changes section in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) has been updated.

#### Attribution

None.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)
- [x] User-facing text is internationalized using the `nls` service (for details, please see the [Internationalization/Localization section](https://github.com/theia-ide/theia/blob/master/doc/coding-guidelines.md#internationalizationlocalization) in the Coding Guidelines)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/core/src/node/messaging/default-messaging-service.ts [hunk 1]
```diff
@@ -71,6 +71,7 @@ export class DefaultMessagingService implements MessagingService, BackendApplica
     protected createMainChannelContainer(socket: Channel): Container {
         const connectionContainer: Container = this.container.createChild() as Container;
         connectionContainer.bind(MainChannel).toConstantValue(socket);
+        socket.onClose(() => connectionContainer.unbindAll());
```
Comment (cdamus) [inline packages/core/src/node/messaging/default-messaging-service.ts]: Possibly this should be `unbindAllAsync()` to allow asynchronous `@preDestroy()` methods in services. I'm not sure there's a good reason not to. Perhaps an Inversify expert on the project team can advise one way or the other?

**Review by colin-grant-work — APPROVED** [review]
I don't see any regressions, and I wouldn't expect any, given that Theia doesn't use Inversify lifecycle methods that trigger on unbinding widely (though I did find one `preDestroy` I hadn't seen before). Nevertheless, it might be worth adding a note in the changelog indicating this as a potentially breaking change, since we know that service aliases with the wrong combination of binding types and decorations could break a global service.

**Comment by cdamus** [comment]
Thanks for the suggestion @colin-grant-work . Commit a6049ebb4b73c607a83c99977650075b5ce77469 adds a blurb to the changelog explaining how latent footguns may go off.

**Review by colin-grant-work — APPROVED** [review]
