### PR TITLE
Align collapsable item behaviour with VSCode

### LINKED ISSUE #6359: VSCode.TreeItem impl.  > difference in behavior when collapsing/expanding
### Description
https://github.com/microsoft/vscode/issues/34130

Following the issue above, there was a PR making it so that when providing a `command` to a collapsible `TreeItem`, clicking on it's twisty will only make it collapse/expand, whilst clicking elsewhere in the TreeItem will trigger it's command.

At this moment, in Theia this is ignored. Clicking on a collapsible TreeItem will always expand/collapse, so I had to contribute a "view action" to trigger this same command in the Theia plugin counterpart.

### Reproduction Steps
When using a VSCode extension as Theia plugin that has a TreeView, with collapsible TreeItems  providing a `command`:

1- Click on the "twisty"
2- Collapse/expand functionality will work as expected on the TreeItem
3- Click anywhere else on the TreeItem
4- It will collapse/expand as if clicking on the twisty

Expected: when clicking outside the twist on the TreeItem, it should trigger the assigned command.

**OS and Theia version:**
OSX 10.14.6
0.12.0-next

### PR DESCRIPTION
**Pull request by xcariba**
Signed-off-by: Alexander Kozinko <xcariba@gmail.com>

#### What it does
It aligns tree view behavior with VSCode (now Theia does not ignore commands on expandable items and fixes #6359):
1. If TreeViewItem is collapsable and has command - do not ignore it.
2. If user clicks on collapse/expand icon - do not execute command.
3. If user clicks on expendable item that has no command - toggle expansion.
4. If user clicks on expendable item that has command - execute command.

Also I changed item padding properties so that expandable and regular items are aligned (as in VSCode)

#### How to test
1. Install extension [vscode-theia-test-extension-0.0.1.vsix](https://github.com/xcariba/vscode-theia-test-extension/raw/main/vscode-theia-test-extension-0.0.1.vsix)
2. Open Test Tree View
3. Click on `Collapsable Item Without Command` expansion icon - it will toggle state
4. Click on `Collapsable Item Without Command` item - it will toggle state
5. Click on `Collapsable Item With Command` expansion icon - it will toggle state
6. Click on `Collapsable Item With Command` item - it will execute command (it will show Hello message)
7. Double click on `Collapsable Item With Command` item - it will execute command (it will show Hello message) and toggle state

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/plugin-ext/src/main/browser/view/tree-view-widget.tsx [hunk 1]
```diff
@@ -384,22 +385,40 @@ export class TreeViewWidget extends TreeViewWelcomeWidget {
...
     handleClickEvent(node: TreeNode, event: React.MouseEvent<HTMLElement>): void {
         super.handleClickEvent(node, event);
-        this.tryExecuteCommand(node);
+        // If clicked on item (not collapsable icon) - execute command or toggle expansion if item has no command
+        if (!event.currentTarget.hasAttribute('data-node-id')) {
+            const commandMap = this.findCommands(node);
+            if (commandMap.size > 0) {
+                this.tryExecuteCommand(commandMap);
+            } else {
+                if (this.isExpandable(node) && !this.hasShiftMask(event) && !this.hasCtrlCmdMask(event)) {
```
Comment (msujew) [inline packages/plugin-ext/src/main/browser/view/tree-view-widget.tsx:399]: Suggestion: Please merge this `else` and `if` branch into one `else if`.

File: packages/plugin-ext/src/main/browser/view/tree-view-widget.tsx [hunk 2]
```diff
@@ -384,22 +385,40 @@ export class TreeViewWidget extends TreeViewWelcomeWidget {
...
+                    this.model.toggleNodeExpansion(node);
+                }
+            }
+        }
     }
 
-    // execute TreeItem.command if present
-    protected tryExecuteCommand(node?: TreeNode): void {
+    protected findCommands(node?: TreeNode): Map<string, unknown[]> {
+        const commandMap = new Map<string, unknown[]>();
```
Comment (msujew) [inline packages/plugin-ext/src/main/browser/view/tree-view-widget.tsx:407]: I imagine this is a breaking change. Should we try to keep the `tryExecuteCommand(node?: TreeNode): void` signature? It would probably just contain `this.tryExecuteCommandMap(this.findCommands(node));`. Alternatively, the breaking change needs to be documented in the changelog.

**Review by msujew — COMMENTED** [review]
Thank you @xcariba for your contribution. I can confirm that the changes work as expected: 

A tree view node with a command is only toggled, when clicking on its toggle icon. When clicking on its name, the associated command is executed. This change does not affect nodes without a command.

This change also aligns the behavior of Theia with vscode perfectly. Good job!

File: packages/plugin-ext/src/main/browser/view/tree-view-widget.tsx (hunk 1 above)
Comment (xcariba) [reply packages/plugin-ext/src/main/browser/view/tree-view-widget.tsx]: Thamks, fixed!

File: packages/plugin-ext/src/main/browser/view/tree-view-widget.tsx (hunk 2 above)
Comment (xcariba) [reply packages/plugin-ext/src/main/browser/view/tree-view-widget.tsx]: I restored original `tryExecuteCommand` as you suggested. I have not found any usages of `tryExecuteCommand` anywhere, but I agree, there is no point in breaking api for other extensions.

**Review by msujew — APPROVED** [review]
LGTM. See my [previous comment](https://github.com/eclipse-theia/theia/pull/9696#pullrequestreview-698972671) for additional info on how the changes affect the behavior of Theia.

File: packages/plugin-ext/src/main/browser/view/tree-view-widget.tsx [hunk 3]
```diff
@@ -389,17 +390,37 @@ export class TreeViewWidget extends TreeViewWelcomeWidget {
 
     handleClickEvent(node: TreeNode, event: React.MouseEvent<HTMLElement>): void {
         super.handleClickEvent(node, event);
-        this.tryExecuteCommand(node);
+        // If clicked on item (not collapsable icon) - execute command or toggle expansion if item has no command
+        if (!event.currentTarget.hasAttribute('data-node-id')) {
```
Comment (colin-grant-work) [inline packages/plugin-ext/src/main/browser/view/tree-view-widget.tsx:394]: Are you certain this check is necessary? As I read the code from TreeWidget that handles the toggle click
https://github.com/eclipse-theia/theia/blob/3bd43c98dc5c755de7ae23d3123a32e54096a4a1/packages/core/src/browser/tree/tree-widget.tsx#L536-L549

this method (`handleClickEvent`) should not be called on a click on the toggle once you set `expandOnlyOnExpansionToggleClick` to `true`. Did you find that it was being called anyway?

Comment (xcariba) [reply packages/plugin-ext/src/main/browser/view/tree-view-widget.tsx]: Yeah, you right, it is unnecessary, thanks! I removed this check and tested again - it still works as expected.

**Review by colin-grant-work — APPROVED** [review]
This looks good to me! Thanks for the contribution!

**Comment by colin-grant-work** [comment]
@xcariba, it looks like something here is putting off the CI machinery. Would you mind rebasing to make sure you're up to date with the recent work on Monaco?

**Comment by xcariba** [comment]
> @xcariba, it looks like something here is putting off the CI machinery. Would you mind rebasing to make sure you're up to date with the recent work on Monaco?

Seems that rebase indeed fixed issue
