### PR TITLE
GH-6530: Set the shutdown hook to `beforeunload`.

### LINKED ISSUE #6530: [electron] The 'unload' event listener on the window is never invoked inside electron
### Description
 
Try to add some logging, you can see, it works from the browser example, but not from the electron on. The `unload` listener is not invoked when I refresh the browser window with the electron example. I bet this is related to #6499.

Problematic code:
https://github.com/eclipse-theia/theia/blob/a8f750a3f244501431b7b380424a0e4efb071eda/packages/core/src/browser/frontend-application.ts#L164-L168

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

### PR DESCRIPTION
**Pull request by kittaakos**
- `unload` was not triggered in electron. (See: https://github.com/electron/electron/issues/7278#issuecomment-248524750)
 - Exposed `ShellLayoutRestorer` APIs.
 - Added logging.
 - Fixed typos.

Closes #6530.

Signed-off-by: Akos Kitta <kittaakos@typefox.io>

#### What it does

This PR moves the frontend application's shutdown hook from `unload` to `beforeunload` as it the `master` state does not work with the electron example.

#### How to test

 - Build the electron example from the source,
 - refresh the browser a few times, 
 - check the logs,
 - you can see the layout is stored. ✨

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
We need to test the browser example as well.

File: packages/core/src/browser/shell/shell-layout-restorer.ts [hunk 1]
```diff
@@ -109,16 +109,17 @@ export interface ApplicationShellLayoutMigration {
     onWillInflateWidget?(desc: WidgetDescription, context: ApplicationShellLayoutMigrationContext): MaybePromise<WidgetDescription | undefined>;
 }
 
-const resetLayoutCommand = {
+export const RESET_LAYOUT: Command = {
```
Comment (vince-fugnitto) [inline packages/core/src/browser/shell/shell-layout-restorer.ts]: [minor] do we need a `changelog` note about this command?

Comment (kittaakos) [reply packages/core/src/browser/shell/shell-layout-restorer.ts]: No, it is not a breaking API change.

Comment (kittaakos) [reply packages/core/src/browser/shell/shell-layout-restorer.ts]: But you are definitely right about the changelog in general; switching from `unload` to `beforeunload` is a breaking change. I do an update. Thanks for the reminder 👍

Comment (kittaakos) [reply packages/core/src/browser/shell/shell-layout-restorer.ts]: Here: https://github.com/eclipse-theia/theia/pull/6532/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR5

Comment (vince-fugnitto) [reply packages/core/src/browser/shell/shell-layout-restorer.ts]: @kittaakos thank you and no problem :)

**Comment by kittaakos** [comment]
I am going to merge this tomorrow, please object if you want.
