### PR TITLE
fix(types-impl): add toJSON function to Range and Position. fix #9573

### LINKED ISSUE #9573: merge-conflict extension throw error 'Unable to show comparison'
### Bug Description:

click `compare changes` will throw error

image
image

### Steps to Reproduce:

1. make a merge conflict in git
2. click compare changes

### Additional Information

- Operating System: macos 11.2.2
- Theia Version: commitid 2eb4319fb4 (use in che-theia)

### PR DESCRIPTION
**Pull request by zWingz**
#### What it does
add `toJSON` function to `Range` and `Position`, fix #9573 

#### How to test

- start the theia
- create a merge conflict in workspace
image
- click `Compare Changes`
image

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/plugin-ext/src/plugin/types-impl.ts [hunk 1]
```diff
@@ -388,6 +388,10 @@ export class Position {
         }
         return false;
     }
+
+    toJSON(): any {
+		return { line: this.line, character: this.character };
+	}
```
Comment (msujew) [inline packages/plugin-ext/src/plugin/types-impl.ts:394]: Please enable eslint (or run the linter defined in the `package.json` with `yarn lint`). You used `tab` characters here - instead of spaces - which are discouraged by our eslint config. The same also applies to the other change.

Comment (zWingz) [reply packages/plugin-ext/src/plugin/types-impl.ts]: fixed

**Review by vince-fugnitto — APPROVED** [review]
@zWingz thank you for your first contribution, from investigating to resolving the issue :+1: 

I confirmed that the changes work, and that `merge-conflict` diffs are now displayed:

image

The code is also consistent with vscode:
- [Position.toJSON](https://github.com/microsoft/vscode/blob/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/src/vs/workbench/api/common/extHostTypes.ts#L228-L230)
- [Range.toJSON](https://github.com/microsoft/vscode/blob/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/src/vs/workbench/api/common/extHostTypes.ts#L363-L365)

**Review by msujew — APPROVED** [review]
LGTM as well.
