### PR TITLE
electron: Fix path comparison for exit confirmation

### LINKED ISSUE #10596: Electron window does never confirm exit (Windows)
### Bug Description:

https://github.com/eclipse-theia/theia/pull/10379 introduces a check for the "main window" by comparing the current web content URL and the main html page:

https://github.com/eclipse-theia/theia/blob/17b419fdf0d1015f2269ffcb64a095b305a8ec2d/packages/core/src/electron-main/electron-main-application.ts#L490

However, this check fails on windows, since `getURL()` returns a URI path with forward slashes, while `THEIA_FRONTEND_HTML_PATH` uses backward slashes on windows.

### Steps to Reproduce:

1. Start the electron app on Windows
2. Set the `application.confirmExit` preference to `always`
3. Exit the app, no confirmation dialog is displayed

### Additional Information

- Operating System: Windows
- Theia Version: 1.21.0

### PR DESCRIPTION
**Pull request by msujew**
#### What it does

Closes #10596 

Before testing for `includes`, we replace all backwards slashes with forward slashes.

#### How to test

1. Start the electron App on Windows.
2. Set the `application.confirmExit` preference to `always`.
3. Exit the application and assert that a confirmation dialog appears.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/core/src/electron-main/electron-main-application.ts [hunk 1]
```diff
@@ -487,7 +487,8 @@ export class ElectronMainApplication {
 
     protected async handleStopRequest(electronWindow: BrowserWindow, onSafeCallback: () => unknown, reason: StopReason): Promise<void> {
         // Only confirm close to windows that have loaded our front end.
-        const safeToClose = !electronWindow.webContents.getURL().includes(this.globals.THEIA_FRONTEND_HTML_PATH) || await this.checkSafeToStop(electronWindow, reason);
+        const frontendPath = this.globals.THEIA_FRONTEND_HTML_PATH.replace(/\\/g, '/');
+        const safeToClose = !electronWindow.webContents.getURL().includes(frontendPath) || await this.checkSafeToStop(electronWindow, reason);
```
Comment (colin-grant-work) [inline packages/core/src/electron-main/electron-main-application.ts:491]: Should we perform the same normalization on the URL for safety's sake?

**Review by colin-grant-work — COMMENTED** [review]
Looks reasonable to me, but I'm temporarily without a Windows environment for testing. @vince-fugnitto, @paul-marechal, are you able to run in Windows?

File: packages/core/src/electron-main/electron-main-application.ts (hunk 1 above)
Comment (msujew) [reply packages/core/src/electron-main/electron-main-application.ts]: Sure, I don't see any harm in it 👍

File: packages/core/src/electron-main/electron-main-application.ts [hunk 2]
```diff
@@ -487,7 +487,10 @@ export class ElectronMainApplication {
 
     protected async handleStopRequest(electronWindow: BrowserWindow, onSafeCallback: () => unknown, reason: StopReason): Promise<void> {
         // Only confirm close to windows that have loaded our front end.
-        const safeToClose = !electronWindow.webContents.getURL().includes(this.globals.THEIA_FRONTEND_HTML_PATH) || await this.checkSafeToStop(electronWindow, reason);
+        // Since our resolved frontend HTML path might contain backward slashes (Windows), we normalize everything first.
+        const currentUrl = electronWindow.webContents.getURL().replace(/\\/g, '/');
+        const frontendUri = this.globals.THEIA_FRONTEND_HTML_PATH.replace(/\\/g, '/');
+        const safeToClose = !currentUrl.includes(frontendUri) || await this.checkSafeToStop(electronWindow, reason);
```
Comment (paul-marechal) [inline packages/core/src/electron-main/electron-main-application.ts:493]: Shouldn't we only replace the backslashes when on Windows?

Comment (msujew) [reply packages/core/src/electron-main/electron-main-application.ts:493]: Sure, but this code doesn't do anything on any non-Windows-OS anyway (since no backwards slashes appear). But I'll wrap it in a `isWindows` branch.

**Review by paul-marechal — APPROVED** [review]

File: packages/core/src/electron-main/electron-main-application.ts (hunk 2 above)
Comment (paul-marechal) [reply packages/core/src/electron-main/electron-main-application.ts]: It's weird but IIRC unix systems allow backslashes in filenames:

```
$ touch \\meh\\
$ ls
'\meh\'
$ node -p 'fs.readdirSync(".").forEach(console.log)'
\meh\ 0 [ '\\meh\\' ]
undefined 
```

We should keep this in mind when converting paths to forward slashes and/or back.
