### PR TITLE
Fix quickpick problems found in IDE testing

### LINKED ISSUE #13450: Cannot checkout branches via UI
### Bug Description:
With the current Theia IDE preview (1.47.0) i can no longer checkout branches via the UI. When clicking on the current branch in the bootom left the correct branches are shown to select (to checkout), but clicking on any branch does not do anything. Same applies when executing the command (`Checkout to...`) manually. 

Note: There seems to be a random empty entry in the overview of branches to checkout.

### Steps to Reproduce:

1. Click on the current branch in the bottom left (or run the `Checkout to...` command)
2. Click on any branch in the selection menu
3. Notice that the branch does not change in the UI
4. Double check in a terminal that the branch was not changed.

### Additional Information

- Operating System: Ubuntu 22.04
- Theia Version: Theia IDE 1.47.0 (preview)

### PR DESCRIPTION
**Pull request by tsmaeder**
#### What it does
Fixes #13450, #13449

We found two problems when testing the latest Theia IDE preview build:

1. Checking out branches via the git plugin toolbar item was broken. Turns out our conversion of quick pick items from plugins was broken.
2. The update of css rules for quick pick, etc. was broken in the update to monaco 1.83.1, leading to css variables of the form "vscode-variable-name" being used instead of "theia-variable-name". 

contributed on behalf of STMicroelectronics

#### How to test
* Make sure you can check out stuff by clicking on the git toolbar item
* Make sure the visual appearance of quick picks o correct, e.g. the above scenario, but also using tasks, commands, etc.
#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/monaco/src/browser/monaco-quick-input-service.ts [hunk 1]
```diff
@@ -230,34 +222,89 @@ export class MonacoQuickInputImplementation implements IQuickInputService {
...
+                buttonSeparator: this.colorRegistry.toCssVariableName('button.Separator'),
+                buttonSecondaryForeground: this.colorRegistry.toCssVariableName('button.secondaryForeground'),
+                buttonSecondaryBackground: this.colorRegistry.toCssVariableName('button.secondaryBackground'),
+                buttonSecondaryHoverBackground: this.colorRegistry.toCssVariableName('button.secondaryHoverBackground'),
+            },
+            progressBar: {
+                progressBarBackground: this.colorRegistry.toCssVariableName('progressBar.background')
+            },
+            keybindingLabel: {
+                keybindingLabelBackground: this.colorRegistry.toCssVariableName('keybindingLabe.background'),
```
Comment (rschnekenbu) [inline packages/monaco/src/browser/monaco-quick-input-service.ts:302]:
```suggestion
                keybindingLabelBackground: this.colorRegistry.toCssVariableName('keybindingLabel.background'),
```

Comment (rschnekenbu) [reply packages/monaco/src/browser/monaco-quick-input-service.ts:302]: Small typo here

**Review by rschnekenbu — CHANGES_REQUESTED** [review]
That looks good to me, except small typo. 

Checkout and other git actions work fine.
The look and feel of Command palette, task actions and other quick inputs I could tests are OK.  Tested both on electron and browser.

**Review by rschnekenbu — APPROVED** [review]
LGTM! Thanks
